### ISSUE TITLE
Move and Make Copy are giving an error message

### ISSUE THREAD

**Issue by srgloureiro** [Komodo/KomodoEdit#1071]
When  I right-click a file's tab and pick File actions to do Move or Make Copy, it appears a message 
[http://i.imgur.com/PUSmT0l.png](http://i.imgur.com/PUSmT0l.png)

Komodo Edit, version 9.3.2, build 16460, platform win32-x86.
Built on Thu Dec 10 22:21:38 2015.

**Comment by srgloureiro** [comment]
This also happens on Rename, but only after the user does OK an the dialog asking for the new file name.

**Comment by mitchell-as** [comment]
Are you working with remote files? Your error message seems to indicate a problem with file paths. Perhaps the current file's path is no longer available due to a disconnect?

**Comment by srgloureiro** [comment]
No. I am working with a file on root of the d: unit

**Comment by Naatan** [comment]
I'm not able to reproduce this.

Is there anything out of the ordinary about your source and target directories? (are they network mounts perhaps?).

**Comment by srgloureiro** [comment]
No. I do not have any network drives.

**Comment by Naatan** [comment]
Does the error occur before or after picking a save location?

**Comment by srgloureiro** [comment]
Got a different erro this time:
Unable to move file: TypeError: path is undefined

**Comment by srgloureiro** [comment]
Got the same error again:
Unable to move file: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsILocalFile.copyTo]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://komodo/content/morekomodo/common.js :: MoreKomodoCommon.moveFile :: line 257"  data: no]

**Comment by srgloureiro** [comment]
It seems the file must be at root of D:\ unit

**Comment by Naatan** [comment]
Meaning the error only happens when the source file is at the root of D:\ ?

**Comment by srgloureiro** [comment]
Or may be both source and target?

**Comment by srgloureiro** [comment]
Just reproduced it now:

![image](https://cloud.githubusercontent.com/assets/6369967/23173407/f632a208-f850-11e6-8455-ac993dcbc445.png)

**Comment by Naatan** [comment]
Note sure what went different this time, but I was able to reproduce it with just a.txt > b.txt. I hit new file, saved it as `~/Downloads/a.txt` and then moved it to `b.txt`.

Thanks @srgloureiro !

**Comment by srgloureiro** [comment]
Got it again on latest version.

Was doing a Move of a file among two different directories and the file indeed moved and the over-the-tab tooltip got updated with the new path. However, the "Path is undefined message" appeared again.

Error log (possibly) relevant part:

[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-03-20 11:56:17,674] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-03-20 11:56:17,677] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:306:17
    saveAsURI@vieweditor:1613:13
    saveAs@vieweditor:1527:20
    save@vieweditor:1368:1
    viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1841:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
    command_doCommand@chrome://komodo/content/library/commands.js:272:1
    command_doCommandAsync@chrome://komodo/content/library/commands.js:224:1
    @chrome://komodo/content/keybindings/keybindings.js line 2506 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2506:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2675:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2561:5
-- EXCEPTION END --
[2017-03-20 11:56:17,677] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:306:17
    saveAsURI@vieweditor:1613:13
    saveAs@vieweditor:1527:20
    save@vieweditor:1368:1
    viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1841:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
    command_doCommand@chrome://komodo/content/library/commands.js:272:1
    command_doCommandAsync@chrome://komodo/content/library/commands.js:224:1
    @chrome://komodo/content/keybindings/keybindings.js line 2506 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2506:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2675:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2561:5
-- EXCEPTION END --
[2017-03-20 11:56:17,677] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:306:17
    saveAsURI@vieweditor:1613:13
    saveAs@vieweditor:1527:20
    save@vieweditor:1368:1
    viewManager.prototype.do_cmd_save@chrome://komodo/content/views.js:1841:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
    command_doCommand@chrome://komodo/content/library/commands.js:272:1
    command_doCommandAsync@chrome://komodo/content/library/commands.js:224:1
    @chrome://komodo/content/keybindings/keybindings.js line 2506 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2506:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2675:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2561:5
-- EXCEPTION END --
[2017-03-20 11:56:17,680] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2017-03-20 11:56:49,163] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:306:17
    moreKomodo._updateViewsByCommand@chrome://komodo/content/morekomodo/overlay.js:91:25
    moreKomodo.observe@chrome://komodo/content/morekomodo/overlay.js:72:17
    MoreKomodoCommon.moveFile@chrome://komodo/content/morekomodo/common.js:272:9
    moreKomodo.onMoveFile@chrome://komodo/content/morekomodo/overlay.js:437:13
    moreKomodo.doCommand@chrome://komodo/content/morekomodo/overlay.js:422:17
    goDoCommand@chrome://global/content/globalOverlay.js:94:7
    oncommand@chrome://komodo/content/komodo.xul:1:1
-- EXCEPTION END --
[2017-03-20 11:56:49,163] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:306:17
    moreKomodo._updateViewsByCommand@chrome://komodo/content/morekomodo/overlay.js:91:25
    moreKomodo.observe@chrome://komodo/content/morekomodo/overlay.js:72:17
    MoreKomodoCommon.moveFile@chrome://komodo/content/morekomodo/common.js:272:9
    moreKomodo.onMoveFile@chrome://komodo/content/morekomodo/overlay.js:437:13
    moreKomodo.doCommand@chrome://komodo/content/morekomodo/overlay.js:422:17
    goDoCommand@chrome://global/content/globalOverlay.js:94:7
    oncommand@chrome://komodo/content/komodo.xul:1:1
-- EXCEPTION END --
[2017-03-20 11:56:49,163] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:306:17
    moreKomodo._updateViewsByCommand@chrome://komodo/content/morekomodo/overlay.js:91:25
    moreKomodo.observe@chrome://komodo/content/morekomodo/overlay.js:72:17
    MoreKomodoCommon.moveFile@chrome://komodo/content/morekomodo/common.js:272:9
    moreKomodo.onMoveFile@chrome://komodo/content/morekomodo/overlay.js:437:13
    moreKomodo.doCommand@chrome://komodo/content/morekomodo/overlay.js:422:17
    goDoCommand@chrome://global/content/globalOverlay.js:94:7
    oncommand@chrome://komodo/content/komodo.xul:1:1
-- EXCEPTION END --
[2017-03-20 12:00:02,868] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2017-03-20 12:00:06,056] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-03-20 12:00:53,934] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-03-20 12:06:24,388] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-03-20 12:06:24,388] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-03-20 12:06:24,388] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-03-20 12:06:24,388] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-03-20 12:06:24,388] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by Naatan** [comment]
Thank you @srgloureiro , but we don't need any more error reports seeing as we can reproduce the issue.

**Comment by cgchoffman** [comment]
I can't reproduce this: https://github.com/Komodo/KomodoEdit/issues/1071#issuecomment-281393129

**Comment by cgchoffman** [comment]
I tried this in Edit, IDE 11 on OSX and Windows
