### ISSUE TITLE
unable to install color sheme true preferences

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1083]
Wanted to install my dracula color sheme true the preferences menu ( preferences > color sheme ), but komodo isn't installing the color scheme.

My error log:
```
[2016-02-11 21:14:30,413] [INFO] Startup: Welcome to Komodo IDE 9.3.2 build 88191 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2016-02-11 21:14:30,413] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Thu Dec 10 11:38:17 2015
[2016-02-11 21:14:31,632] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-02-11 21:14:31,904] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-02-11 21:14:33,391] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:806
[2016-02-11 21:14:33,407] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
[2016-02-11 21:14:33,539] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-02-11 21:14:37,267] [INFO] komodospellchecker: Spell checker loaded.
[2016-02-11 21:14:37,267] [INFO] komodospellchecker: Using dictionary en-US
[2016-02-11 21:14:37,387] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-02-11 21:14:59,674] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-02-11 21:14:59,674] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-02-11 21:19:17,446] [WARNING] views: Inconsistent view count in view_closed event
[2016-02-11 21:19:17,615] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-02-11 21:19:17,693] [WARNING] views: Inconsistent view count in view_opened event
[2016-02-11 21:19:20,055] [ERROR] koPHPLinter: Error getting phpInfoEx.version.  Is a PHP interpreter defined?
[2016-02-11 21:19:50,520] [ERROR] console-logger: TypeError: path.startsWith is not a function (2) in resource://gre/modules/osfile/ospath_win.jsm:195
Traceback (most recent call last):
  File "resource://gre/modules/osfile/ospath_win.jsm", line 195, in 

[2016-02-11 21:20:23,171] [ERROR] console-logger: TypeError: invalid 'in' operand computed (2) in chrome://komodo/content/sdk/dom.js:803
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 803, in 

[2016-02-11 21:20:50,605] [ERROR] console-logger: TypeError: path.startsWith is not a function (2) in resource://gre/modules/osfile/ospath_win.jsm:195
Traceback (most recent call last):
  File "resource://gre/modules/osfile/ospath_win.jsm", line 195, in 

[2016-02-11 21:21:07,770] [ERROR] console-logger: TypeError: invalid 'in' operand computed (2) in chrome://komodo/content/sdk/dom.js:803
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 803, in 

[2016-02-11 21:21:57,339] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-02-11 21:21:57,339] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by Naatan** [comment]
There is no option to import color schemes from the preferences window. The fact that it tried it at all is an error.

**Comment by mitchell-as** [comment]
This is no longer an issue in master with the new color scheme dialog.
