### ISSUE TITLE
KO9 codeintel exception

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#109]
Caught an exception.
Current open active file was a ```zcml```, XML type.
```
[2015-04-02 13:23:27,376] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 305, in scoperef_from_pos
    blob = self.blob_from_lang[lang]
TypeError: 'NoneType' object has no attribute '__getitem__'
[2015-04-02 13:23:27,433] [ERROR] koCodeIntel: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/adi/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 305, in scoperef_from_pos
    blob = self.blob_from_lang[lang]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Naatan** [comment]
Please describe what you were doing, what you were expecting and what happened.

Error reports are always appreciated but they are almost useless without context.

**Comment by agroszer** [comment]
So, the ```zcml``` file was open, searched for some string with ```Find all```, double clicked in the bottom ```Find results``` pane on a hit.
The error came while opening the new file

**Comment by Naatan** [comment]
Ok, and just to clarify - did anything actually "break" or you just saw an error but everything seemed to work fine?

**Comment by agroszer** [comment]
Saw the error, seemingly nothing broke hard.

**Comment by Naatan** [comment]
Ok, closing this until there is some correlation. Codeintel can throw errors like this at times but it's not necessarily reason for alarm.
