### ISSUE TITLE
Komodo 9.x problem with file save (local and remote)

### ISSUE THREAD

**Issue by joho1968** [Komodo/KomodoEdit#1099]
I was told to open up a new issue for this since it wasn't related to the one Google found :)

I just started seeing this as well, remote directory SFTP. Running KomodoIDE 9.3 under Linux. Never seen this particular error before. My error is 0x80004005 (NS_ERROR_FAILURE). Location is "JS frame :: vieweditor :: _doSave :: line 1261, data:no" What is very odd is that I can save other files in the same (remote) directory.

I have tried decreasing the file size to see if that has any bearing, but so far, there's no pattern. This is a 50K+ PHP file.

**Could this be some sort of exception generated by character conversion issues (UTF8 vs ISO8859-1 or ISO8859-15)?**

[2016-02-22 15:42:13,308] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/joho/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2016-02-22 15:42:15,119] [INFO] komodospellchecker: Spell checker loaded.
[2016-02-22 15:42:15,119] [INFO] komodospellchecker: Using dictionary en-US
[2016-02-22 15:42:15,187] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-02-22 15:42:16,315] [ERROR] console-logger: TypeError: this.sessions[this.activeSession] is undefined (2) in chrome://komob/content/sessions.js:551
Traceback (most recent call last):
File "chrome://komob/content/sessions.js", line 551, in

[2016-02-22 15:42:24,478] [WARNING] views: Inconsistent view count in view_closed event
[2016-02-22 15:42:24,604] [WARNING] views: Inconsistent view count in view_opened event
[2016-02-22 15:42:25,677] [ERROR] koPHPLinter: Error getting phpInfoEx.version. Is a PHP interpreter defined?
[2016-02-22 15:42:28,136] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
/home/joho/Komodo-IDE-9/lib/python/lib/python2.7/difflib.py:416: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
for j in b2j.get(a[i], nothing):
/home/joho/Komodo-IDE-9/lib/python/lib/python2.7/difflib.py:433: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
a[besti-1] == b[bestj-1]:
/home/joho/Komodo-IDE-9/lib/python/lib/python2.7/difflib.py:437: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
a[besti+bestsize] == b[bestj+bestsize]:
ERROR:xpcom:Unhandled exception calling 'int8 \* save(in boolean);'
Traceback (most recent call last):
File "/home/joho/Komodo-IDE-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in CallMethod
return 0, func(params)
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1664, in save
self._clean(ensureFinalEOL, cleanLineEnds)
File "/home/joho/Komodo-IDE-9/lib/mozilla/python/xpcom/components.py", line 268, in wrapperFn
return fn(args, *kwargs)
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1428, in clean
wsLinesToStrip = self.getChangedLinesWithTrailingWhitespace()
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1386, in getChangedLinesWithTrailingWhitespace
diff_content = self.getUnsavedChanges()
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 2060, in getUnsavedChanges
return ''.join(difflines)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 30: invalid continuation byte
ERROR:xpcom:Unhandled exception calling 'int8 \* save(in boolean);'
Traceback (most recent call last):
File "/home/joho/Komodo-IDE-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod
return 0, func(params)
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1664, in save
self._clean(ensureFinalEOL, cleanLineEnds)
File "/home/joho/Komodo-IDE-9/lib/mozilla/python/xpcom/components.py", line 268, in wrapperFn
return fn(args, *kwargs)
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1428, in _clean
wsLinesToStrip = self.getChangedLinesWithTrailingWhitespace()
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1386, in getChangedLinesWithTrailingWhitespace
diff_content = self.getUnsavedChanges()
File "/home/joho/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 2060, in getUnsavedChanges
return ''.join(difflines)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 30: invalid continuation byte
[2016-02-22 15:43:34,034] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by joho1968** [comment]
Update: If I use Emacs and change the encoding of the file to UTF-8, and then load the file in KomodoIDE again, it can save the file OK at the next change.

If I then change the file encoding to ISO 8859-15 or ISO 8859-1 in KomodoIDE after successfully saving it once in UTF-8, it's still saved successfully. But oinly once. On the next save attempt, with Latin encoding, it fails with the same error message.

Once it has started acting up, I cannot get it to save in KomodoIDE, regardless of what I set the buffer character set to. I have to revert to using Emacs to change the character encoding to UTF-8 before I can manage the file using KomodoIDE again.

Expected behavior: The IDE should tell me what one or more of the characters cannot be successfully converted by it, and offer a solution of "Not saving", "Conversion with character replacement", etc. (IMHO).

**Comment by mitchell-as** [comment]
Can you save the file locally, performing the same set of steps, and reproduce the encoding error? That will help us determine if this issue is only caused when saving remote files as opposed to saving any file, local or remote.

**Comment by joho1968** [comment]
What is odd is that I seem to have removed the odd character (I'm suspecting a long hyphen from pasted text), so I got this working, until this very moment, when I instead get "There was an error attempting to save 'index.php': No such file". But the file is very much there (and open in KIDE) :)

**Comment by joho1968** [comment]
And, again, if I change the file to UTF-8 using Emacs from a shell, I can re-open the file, and save it, in KIDE. 

This does, however, also happen if I copy the file to my machine and edit it locally. So it seems this has nothing to do with the SSH/SSL/SCP/SFTP transport layer.

**Comment by joho1968** [comment]
I can repeat this for other files as well, that most likely has "weird" content as far as encoding goes. It would be interesting to find these characters that are causing it to go tits up when saving in Latin encoding.

**Comment by Naatan** [comment]
Can you share a file that reproduces the issue?

Also, any reason why you are using Emacs to switch encoding? As Komodo lets you do this natively.

**Comment by joho1968** [comment]
The problemis that once the file is in ISO8859-1 or ISO8859-15 encoding, KIDE exhibits this behavior.

I can try to find a suitable file.



-Joaquim

___
Sent from my mobile phone using Work2Go

-----Original Message-----
