### ISSUE TITLE
Commenting a text block cause exception, cursor disappears

### ISSUE THREAD

**Issue by earx** [Komodo/KomodoEdit#1122]
### Short Summary

Commenting text (ctrl-/) cause exception, cursor disappears. text being unselectable with mouse
Checked on php, js files

### Steps to Reproduce

1.  select some region
2.  press ctrl-/

### Expected results

block is commented out

### Actual results

text is commented out, expetions is displayed, cursor disappears

### Platform Information

Ubuntu 14.04
Komodo IDE 9.3.2 build 88216 (platform linux-x86_64, running on Linux 3.13.0-79-generic version #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016)

### Errors / Logs

```
ERROR:xpcom:Unhandled exception calling 'int8 * comment(in nsISomething);'
Traceback (most recent call last):
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/komodo/koUDLLanguageBase.py", line 582, in comment
    KoCommenterLanguageService.comment(self, scimoz)
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/komodo/koLanguageServiceBase.py", line 745, in comment
    self._determineMethodAndDispatch(scimoz, commenters, commenting=True)
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/komodo/koLanguageServiceBase.py", line 712, in _determineMethodAndDispatch
    workers["line"](scimoz, textStart, textEnd)
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/komodo/koLanguageServiceBase.py", line 309, in _commentLines
    scimoz.replaceTarget(replacementLines[i - startIndexLine].rstrip('\r\n'))
IndexError: list index out of range
ERROR:xpcom:Unhandled exception calling 'int8 * doCommand(in string);'
Traceback (most recent call last):
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/evg/Komodo-IDE-9/lib/mozilla/components/koLanguageCommandHandler.py", line 693, in doCommand
    meth()
  File "/home/evg/Komodo-IDE-9/lib/mozilla/components/koLanguageCommandHandler.py", line 1119, in _do_cmd_comment
    commenter.comment(view.scimoz)
  File "<XPCOMObject method 'comment'>", line 3, in comment
Exception: 2147500037 (NS_ERROR_FAILURE)
[2016-03-04 14:17:29,743] [ERROR] commands: An error occurred executing the cmd_comment command
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://xtk/content/controller.js :: ForwardingController_doCommand :: line 203"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://xtk/content/controller.js'
+ lineNumber (number) 203
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'ForwardingController_doCommand@chrome://xtk/content/controller.js:203:4
command_doCommand@chrome://k'...475 chars
+ location (object) JS frame :: chrome://xtk/content/controller.js :: ForwardingController_doCommand :: line 203
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://xtk/content/controller.js'
| + name (string) 'ForwardingController_doCommand'
| + lineNumber (number) 203
| + columnNumber (number) 4
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 230
| + formattedStack (string) 'ForwardingController_doCommand@chrome://xtk/content/controller.js:203:4
command_doCommand@chrome://k'...475 chars
| + stack
    ForwardingController_doCommand@chrome://xtk/content/controller.js:203:4
    command_doCommand@chrome://komodo/content/library/commands.js:230:0
    @chrome://komodo/content/keybindings/keybindings.js line 2544 > eval:1:0
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2544:22
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2715:16
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2599:4
-- EXCEPTION END --
[2016-03-04 14:17:29,806] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2016-03-04 14:17:30,580] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-03-04 14:17:31,436] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/evg/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
```

[pystderr.log.zip](https://github.com/Komodo/KomodoEdit/files/158574/pystderr.log.zip)

**Comment by Naatan** [comment]
Could you share a file on which this occurs? (the actual file, not just its contents).

**Comment by earx** [comment]
[summary.php.zip](https://github.com/Komodo/KomodoEdit/files/159013/summary.php.zip)

**Comment by earx** [comment]
in fact, it was happened on any php / js file I've tried

**Comment by earx** [comment]
tell me if I can help you by some way.. may be - share teamviewer session?

**Comment by mitchell-as** [comment]
Thanks, I've managed to reproduce this.
