### ISSUE TITLE
New Skin: Color schemes editor is empty

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1129]
### Short Summary

Open the color scheme editor and all the aspects of it are empty.

### Steps to Reproduce

open prefs > Color Scheme > click Open Color Scheme Editor...open it

### Expected results

Populated windows.

### Actual results

Blank portions of the window. See screenshot

### Platform Information

IDE, Edit
Windows 10

### Errors / Logs

```
[2016-03-04 11:40:24,624] [INFO] Startup: Welcome to Komodo IDE 9.30.0-devel build 88534 (platform win64-x64, running on Windows post2012Server version 6.3.9600)
[2016-03-04 11:40:24,634] [INFO] Startup: C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\komodo.exe built on Fri Dec 11 15:01:01 2015
JavaScript warning: resource://gre/modules/Preferences.jsm, line 381: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 167: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 333: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 342: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 353: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 583: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 605: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 618: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 669: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 765: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 778: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 796: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 876: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1020: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1079: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1208: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1232: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1254: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1296: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1328: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1354: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1357: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1375: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1395: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1451: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1478: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1496: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1506: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1509: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1523: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1538: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1550: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1551: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1552: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1595: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 1609: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 3630: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 3657: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 4096: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 4547: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 4550: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 4596: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 5: ReferenceError: assignment to undeclared variable less
JavaScript strict warning: chrome://komodo/content/contrib/less.js, line 2128: ReferenceError: reference to undefined property mathFunctions[i].unit
[2016-03-04 11:40:25,901] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-03-04 11:40:25,921] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/9.30/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2016-03-04 11:40:25,934] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/9.30/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/9.30/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2016-03-04 11:40:26,167] [WARNING] startupWizard: CGCH!!!  It's working.
[2016-03-04 11:40:31,732] [WARNING] startupWizard: CGCH!!! cancel
JavaScript strict warning: , line 0: TypeError: "Services" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "Services" is read-only
[2016-03-04 11:40:31,888] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "Services" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: resource://gre/modules/DownloadUtils.jsm, line 79: SyntaxError: applying the 'delete' operator to an unqualified name is deprecated
[2016-03-04 11:40:32,325] [WARNING] console-logger: SyntaxError: applying the 'delete' operator to an unqualified name is deprecated (5) in resource://gre/modules/DownloadUtils.jsm:79
JavaScript strict warning: chrome://breadcrumbs/content/bootstrap.js, line 1: TypeError: "require" is read-only
[2016-03-04 11:40:32,346] [WARNING] console-logger: TypeError: "require" is read-only (5) in chrome://breadcrumbs/content/bootstrap.js:1
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
[2016-03-04 11:40:33,082] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
JavaScript strict warning: , line 0: TypeError: "XPCOMUtils" is read-only
JavaScript warning: file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/components/koamAddonManager.js, line 138: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
[2016-03-04 11:40:35,003] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/components/koamAddonManager.js:138
[2016-03-04 11:40:37,158] [ERROR] koLintService: Unexpected error while linting
Traceback (most recent call last):
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\components\koLintService.py", line 562, in run
    results = request.linter.lint(request)
  File "<XPCOMObject method 'lint'>", line 3, in lint
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 7: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 46: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 49: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 50: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 59: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 64: ReferenceError: reference to undefined property Z.o[a]
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 46: ReferenceError: reference to undefined property a[ub]
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 4: ReferenceError: reference to undefined property this.values[(":" + a)]
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 13: ReferenceError: reference to undefined property a[e]
JavaScript strict warning: http://www.google-analytics.com/analytics_debug.js, line 1: ReferenceError: reference to undefined property a[Math.floor(...)]
[2016-03-04 11:40:37,559] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:37,686] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:37,792] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1150:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
JavaScript strict warning: chrome://global/content/bindings/tree.xml, line 50: ReferenceError: reference to undefined property this.treeBoxObject.columns
[2016-03-04 11:40:38,519] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-03-04 11:40:38,581] [INFO] komodospellchecker: Spell checker loaded.
[2016-03-04 11:40:38,585] [INFO] komodospellchecker: Using dictionary en-US
JavaScript error: chrome://gitbranchextension/content/gitbranch.js, line 16: TypeError: StatusbarText is null
JavaScript error: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js, line 98: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.append]
JavaScript strict warning: resource://gre/modules/notifications.js, line 226: ReferenceError: reference to undefined property this._nm
JavaScript strict warning: chrome://scope-shell-composer/content/sdk/composer.js, line 149: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-gem/content/sdk/gem.js, line 93: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-gem/content/sdk/gem.js, line 137: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-pip/content/sdk/pip.js, line 100: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-pip/content/sdk/pip.js, line 144: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-ppm/content/sdk/ppm.js, line 92: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-ppm/content/sdk/ppm.js, line 135: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-pypm/content/sdk/pypm.js, line 134: SyntaxError: test for equality (==) mistyped as assignment (=)?
JavaScript strict warning: chrome://scope-shell-pypm/content/sdk/pypm.js, line 178: SyntaxError: test for equality (==) mistyped as assignment (=)?
[2016-03-04 11:40:39,653] [ERROR] console-logger: TypeError: StatusbarText is null (2) in chrome://gitbranchextension/content/gitbranch.js:16
Traceback (most recent call last):
  File "chrome://gitbranchextension/content/gitbranch.js", line 16, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:39,674] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.append] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:98
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 98, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception

JavaScript strict warning: chrome://komob/content/socketio.js, line 407: TypeError: variable i redeclares argument
JavaScript strict warning: chrome://komob/content/socketio.js, line 1133: TypeError: variable data redeclares argument
[2016-03-04 11:40:41,042] [ERROR] console-logger: Commando: Exception while registering scope 'Shell - NPM' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-npm@activestate.com.xpi!/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-npm@activestate.com.xpi!/bootstrap.js", line 11, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:41,073] [ERROR] console-logger: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js :: MozFile :: line 31"  data: no] (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-npm@activestate.com.xpi!/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-npm@activestate.com.xpi!/bootstrap.js", line 12, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:41,131] [ERROR] console-logger: Commando: Exception while registering scope 'Shell - Grunt' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-grunt@activestate.com.xpi!/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-grunt@activestate.com.xpi!/bootstrap.js", line 11, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:41,186] [ERROR] console-logger: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js :: MozFile :: line 31"  data: no] (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-grunt@activestate.com.xpi!/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-grunt@activestate.com.xpi!/bootstrap.js", line 12, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:41,266] [ERROR] console-logger: Commando: Exception while registering scope 'Shell - Gulp' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-gulp@activestate.com.xpi!/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-gulp@activestate.com.xpi!/bootstrap.js", line 11, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:41,309] [ERROR] console-logger: [Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js :: MozFile :: line 31"  data: no] (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-gulp@activestate.com.xpi!/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///C:/mozbuilds/9.3/moz3500-ko9.30/mozilla/ko-rel/dist/bin/extensions/scope-shell-gulp@activestate.com.xpi!/bootstrap.js", line 12, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
JavaScript strict warning: chrome://komob/content/socketio.js, line 2167: ReferenceError: reference to undefined property packet.ack
[2016-03-04 11:40:44,203] [WARNING] console-logger: Key event not available on some keyboard layouts: key="p" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-03-04 11:40:44,211] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-03-04 11:40:44,223] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-03-04 11:40:52,546] [ERROR] koScintillaSchemeService: asked for style 'arrays', don't know what to do
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:40:52,581] [ERROR] koScintillaSchemeService: No key: self._commonStyles[fallbackstyle=None], style='arrays', attribute='fore'
Traceback (most recent call last):
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\components\koScintillaSchemeService.py", line 565, in _getAspectFromStyleBlocks
    styleBlock = self._commonStyles[fallbackstyle]
KeyError: None
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
ERROR:xpcom:Unhandled exception calling 'int8 * getFore(in string, in string, out retval string);'
Traceback (most recent call last):
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\components\koScintillaSchemeService.py", line 593, in getFore
    scincolor = self._getAspect(language, style, 'fore')
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\components\koScintillaSchemeService.py", line 588, in _getAspect
    return self._getAspectFromAppliedData(style, attribute)
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\components\koScintillaSchemeService.py", line 576, in _getAspectFromAppliedData
    aspect = self._getAspectFromStyleBlocks(style, attribute)
  File "C:\mozbuilds\9.3\moz3500-ko9.30\mozilla\ko-rel\dist\bin\components\koScintillaSchemeService.py", line 565, in _getAspectFromStyleBlocks
    styleBlock = self._commonStyles[fallbackstyle]
KeyError: None
JavaScript error: chrome://komodo/content/dialogs/colorscheme.js, line 812: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.getFore]
[2016-03-04 11:40:52,882] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.getFore] (2) in chrome://komodo/content/dialogs/colorscheme.js:812
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/colorscheme.js", line 812, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-03-04 11:41:22,375] [WARNING] console-logger: ReferenceError: reference to undefined property this._path (5) in resource://gre/modules/osfile/osfile_win_front.jsm:901

```

### Screenshots / Screencasts

![capture](https://cloud.githubusercontent.com/assets/655154/13538209/1225453e-e1fe-11e5-9634-86345f49b43c.PNG)

### Workaround

--- If you found any workarounds for your issue please provide them here ---

A clean profile fixed it

**Comment by Defman21** [comment]
This is working, isn't it? :P

**Comment by cgchoffman** [comment]
That's what happens when you don't milestone your bugs!
