### ISSUE TITLE
Code pane missing for specific file

### ISSUE THREAD

**Issue by jfritz3** [Komodo/KomodoEdit#1143]
### Short Summary
My primary project file will not generate a code pane (major pain), all other code panes are fine

### Steps to Reproduce
Click 'Locate Current Scope" icon briefly shows **'Could not find a node corresponding to the scope at
appxxx.lineyyy in the Code Browser**' in the status line at bottom of window

Clicking any line in file displays "NoneType  object has no attribute 'get'"

### Expected results
Code tree

### Actual results
empty tree

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 8.5.4, build 86985
*Operating System (and version)?* Win7

### Additional Information
Program runs without error.  I cannot locate any inappropriate 'get' calls

 -- eg. Error logs, screenshots, workarounds --

**Comment by mitchell-as** [comment]
Hi, thanks for the report. There are a couple things that would help.

1. Would you please post the contents of your Help > Troubleshooting > View Log File when this error occurs?
2. If you could post the file or a file that demonstrates this problem along with some steps on how to reproduce it, that would help us immensely.

Thanks!

**Comment by jfritz3** [comment]
Debug Log:
[2016-03-10 07:20:01,878] [DEBUG] places_js: waiting for document complete
[2016-03-10 07:20:02,128] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2016-03-10 07:20:03,937] [ERROR] codeintel.oop.driver: traneupdater
Traceback (most recent call last):
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 518, in run
    handler.handleRequest(request, self)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 576, in handleRequest
    meth(request, driver)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 835, in do_get_sections
    sections = buf.get_sections()
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\buffer.py", line 411, in get_sections
    return self.cached_sections
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\citadel.py", line 198, in blob_from_lang
    self._load_buf_data_once()
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 808, in get_buf_data
    dbsubpath = join(dhash, dbfile_from_blobname[blobname])
KeyError: u'traneupdater'
[2016-03-10 07:20:05,739] [ERROR] codeintel.oop.driver: traneupdater
Traceback (most recent call last):
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 518, in run
    handler.handleRequest(request, self)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\components\codeBrowserOOP.py", line 25, in handleRequest
    return meth(request, driver)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\components\codeBrowserOOP.py", line 49, in do_get_buffer
    buf.scan()
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'traneupdater'
[2016-03-10 07:20:09,374] [ERROR] codeintel.oop.driver: traneupdater
Traceback (most recent call last):
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 518, in run
    handler.handleRequest(request, self)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\components\codeBrowserOOP.py", line 25, in handleRequest
    return meth(request, driver)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\components\codeBrowserOOP.py", line 49, in do_get_buffer
    buf.scan()
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'traneupdater'
[2016-03-10 07:20:09,374] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 518, in run
    handler.handleRequest(request, self)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 576, in handleRequest
    meth(request, driver)
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 835, in do_get_sections
    sections = buf.get_sections()
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\buffer.py", line 411, in get_sections
    return self.cached_sections
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "C:\Program Files\ActiveState Komodo IDE 8\lib\mozilla\python\komodo\codeintel2\citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by jfritz3** [comment]
The problem happens with only one large file. We can see about sending file if there is need.
