### ISSUE TITLE
APPCRASH: Customize Toolbars->click on a selection

### ISSUE THREAD

**Issue by code-read** [Komodo/KomodoEdit#1207]
### Short Summary
AppCrash: Customize Toolbars->click on a selection

### Steps to Reproduce
Edit existing Perl source code file.  Perform "Save As" to save to different file and preserve contents of original file.  Right click on toolbar, toggle various toolbars on/off to see which does what. 
Right click on toolbar, select Customize Toolbars, then click on a check next to a selection from the resulting popup menu.  The selection does not toggle, instead Komodo is hung and AppCrash results.

When I restart Komodo, it asks to restore context, but then restores the *unrenamed* source code file, unchanged.  So it did not "remember" that I had performed a "Save As".

The APPCRASH occurred twice in a row, when I elected "recover" from the popup menu Komodo presented at startup.  Not selecting "recover" from the popup menu resulted in Customize Toolbars operating as expected and not causing an APPCRASH.  So possibly the context Komodo restored, also restored whatever was causing it to crash.  Unfortunately I haven't since been able to reproduce this crash.

### Expected results
Customize Toolbars.

### Actual results
Crash.

### Platform Information

*Komodo Edit or IDE?* Komodo IDE
*Komodo Version?* see below
*Operating System (and version)?* Windows 7 Pro, see below

### Additional Information
Note that I have a high density display, (1440x2560) this causes some display problems with Toolbar elements.  For example, "Show Button Text" causes 

Windows crash report:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	komodo.exe
  Application Version:	9.3.2.0
  Application Timestamp:	5669d687
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.18869
  Fault Module Timestamp:	55636317
  Exception Code:	c0000005
  Exception Offset:	00039e33
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

============

pystderr.log:
[2016-04-01 09:37:31,313] [INFO] Startup: Welcome to Komodo IDE 9.3.2 build 88191 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2016-04-01 09:37:31,315] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Thu Dec 10 11:38:17 2015
[2016-04-01 09:37:32,058] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-04-01 09:37:32,127] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-04-01 09:37:32,740] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-04-01 09:37:32,926] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-04-01 09:37:33,528] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
[2016-04-01 09:37:49,108] [ERROR] CT::tracker.js: Scc error Error 128 running '[u'C:\\Program Files (x86)\\Git\\cmd\\git.exe', 'show', u'HEAD:./split-sentences2.pl']'
  in 'C:\Users\Carson\Perl': 
fatal: Path 'split-sentences2.pl' exists on disk, but not in 'HEAD'.
Traceback from ERROR in 'CT::tracker.js' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:337:27
    exports.ChangeTracker.prototype.onError@chrome://trackchanges/content/tracker.js:200:5

[2016-04-01 09:37:49,441] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2016-04-01 09:37:49,448] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2016-04-01 09:37:49,456] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1132:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2016-04-01 09:37:50,226] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-04-01 09:37:50,282] [INFO] komodospellchecker: Spell checker loaded.
[2016-04-01 09:37:50,282] [INFO] komodospellchecker: Using dictionary en-US

**Comment by Naatan** [comment]
Nice catch! This should be fixed in Komodo 10 because we replaced the customization dialog entirely, but I'll make sure that's the case (ie. it doesnt crash anymore).
