### ISSUE TITLE
My whole preferences, remote connections, projects disappear

### ISSUE THREAD

**Issue by csimpi** [Komodo/KomodoEdit#1220]
### Short Summary
I just close Komodo and restart my computer, and my datas from Komodo disappear.  When i try to open project files i get this message: "Unable to load project".

### Steps to Reproduce
Restart programs, restart computer again.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 9.3
*Operating System (and version)?* Windows 7

### Additional Information

[2016-04-06 20:04:07,497] [INFO] Startup: Welcome to Komodo IDE 9.3.2 build 88191 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2016-04-06 20:04:07,497] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Thu Dec 10 11:38:17 2015
[2016-04-06 20:04:08,020] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-04-06 20:04:08,056] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-04-06 20:04:08,447] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-04-06 20:04:08,558] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-04-06 20:04:11,230] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
[2016-04-06 20:04:12,578] [INFO] komodospellchecker: Spell checker loaded.
[2016-04-06 20:04:12,579] [INFO] komodospellchecker: Using dictionary en-US
[2016-04-06 20:04:12,619] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-04-06 20:04:14,318] [ERROR] console-logger: TypeError: this.sessions[this.activeSession] is undefined (2) in chrome://komob/content/sessions.js:551
Traceback (most recent call last):
  File "chrome://komob/content/sessions.js", line 551, in 

[2016-04-06 20:05:35,183] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-04-06 20:05:35,183] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
ERROR:xpcom:Unhandled exception calling 'int8 * load(in wstring);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koProject.py", line 1286, in load
    self._loadContents(contents, url, fname)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koProject.py", line 1272, in _loadContents
    self._parseStream(StringIO(contents), url, fname)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koProject.py", line 1310, in _parseStream
    for (event, node) in events:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\xml\dom\pulldom.py", line 232, in next
    rc = self.getEvent()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\xml\dom\pulldom.py", line 265, in getEvent
    self.parser.feed(buf)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\xml\sax\expatreader.py", line 214, in feed
    self._err_handler.fatalError(exc)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
SAXParseException: <unknown>:1:0: not well-formed (invalid token)
[2016-04-06 20:06:40,908] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-04-06 20:06:40,908] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
Is this reproducible?

**Comment by csimpi** [comment]
I think its not :( But its possible my windows too old and this is not Komodo's bug.

**Comment by cgchoffman** [comment]
Windows 7 is a supported platform.  Just for future reference, if you can't reproduce the issue, please open a thread in our forums for assistance: http://forum.komodoide.com/ as it's likely an isolated issue that isn't necessarily a Komodo bug.

Did something change in your system recently?  Do you have any oddities with your system configuration?  You Komodo profile should be `C:\Users\username\AppData\Local\ActiveState\KomodoIDE\version\`.  Is your profile there?

**Comment by tonyattwood** [comment]
Hey,

I could never imagine something like that! Just take a look <http://experience.serendipityinternational.org/e4hzkmc>


Yours sincerely, tony.attwood@ntlworld.com

**Comment by cgchoffman** [comment]
Turns out this was a bug in the Profile upgrade path.  It's been resolve for Komodo 10.1.

**Comment by cgchoffman** [comment]
oh woops, i thought it was already closed.  Thanks @Naatan
