### ISSUE TITLE
CodeIntel breaks in PHP if there is a variable with the same name as a function

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#123]
```
[2015-04-06 17:02:07,321] [ERROR] codeintel.tree: Unexpected error with evaluator: 'date' at codeintel_bug.php#56
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree.py", line 288, in eval
    calltips = self.eval_calltips()
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 321, in eval_calltips
    hit = self._hit_from_citdl(expr, start_scope)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 874, in _hit_from_citdl
    elem, scoperef = self._hit_from_variable_type_inference(elem, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1397, in _hit_from_variable_type_inference
    return self._hit_from_citdl(citdl, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 850, in _hit_from_citdl
    new_hit = self._hit_from_call(*hit)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1355, in _hit_from_call
    return self._hit_from_citdl(citdl, func_scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 819, in _hit_from_citdl
    hits, nconsumed = self._hits_from_first_part(tokens, scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 1096, in _hits_from_first_part
    elem = self._elem_from_scoperef(scoperef)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/tree_php.py", line 893, in _elem_from_scoperef
    elem, lpath = scoperef
TypeError: 'NoneType' object is not iterable
```

Thread on the forums: http://forum.komodoide.com/t/komodo-edit-8-x-function-arguments-calltips-not-working/1434
It doesn't work in Komodo IDE 9 too.

Snippet:

```
<?php
	
	//include 'all_include_empty_hub.php';
	
	// Ako ima IMPORT v status "in_progress", ni6to ne pravim
	$cron_jobs = new read_table_field_value('cron_job', array('import_export' => 'export', 'active' => '1'));
	if (!$cron_jobs->has_rows)
	{
		while (($row_cron_job = $cron_jobs->read_next_row()) !== FALSE)
		{
			//tuk da proverqvam dali tozi job ve4e ne e startiran
			//s dopylnitelni poleta v cron_job_instance !!!
			//1-vo pole za proverka: cron_job_id
			//2-ro (novo pole): started_at: s format: 2015_04_03_13_05
			
			$cron_job_id = $row_cron_job['id'];
			$minute_intervals = $row_cron_job['minute_intervals'];
			
			$query = 'SELECT export_name FROM automatic_export WHERE id = (SELECT cron_export_id FROM cron_job WHERE id = '.$cron_job_id.')';
			$select_name = new db_select($query);
			$export_name = '';
			if (($row_name = $select_name->read_1st_row()) !== FALSE)
			{
				$export_name = $row_name['export_name'];
			}
			
			
			
			$date 			= date("U");
			//$date_now 		= date("Y_m_d_H_i", $date);
			
			$arr_date 	= getdate($date);
			$year 		= $arr_date("year");
			$month 		= $arr_date("mon");
			$day 		= $arr_date("mday");
			$minute 	= $arr_date("minutes");
			$hour 		= $arr_date("hours");
			
			for ($i = 0; $i < 60; $i += $minute_intervals)
			{
				if ($minute >= $i && $minute < ($i + $minute_intervals))
				{
					$date_prev 		= mktime($hour, $i, 0, $month, $day, $year);
					$date_prev_Y 	= date("Y_m_d_H_i", $date_prev);
					$date_next 		= mktime($hour, ($i + $minute_intervals), 0, $month, $day, $year);
					$date_next_Y 	= date("Y_m_d_H_i", $date_next);
				}
			}
			
			// 1. Sravnqvane na teku6ata data s predi6noto i sledva6toto predpolagaemi vremena za start - s ot4itane na intervalite za 4asove i minuti
			
			
			
			// 1.1. Vzimane na predi6noto predpolagaemo vreme za start
			// Date of the previous expected start time
			$date_prev_U 	= date("Y_m_d_H_i");
			
			// 2. Ako predi6noto vreme za start e nali4no v tablica 'cron_job_instance' i teku6ata data e mejdu tqh - ni6to ne pravim
			
			$date_last = '';
			$instance_last = new read_cron_job_instance_last($cron_job_id);
			if (($row_last = $instance_last->read_1st_row()) !== FALSE)
			{
				$date_last = $row_last['started_at'];
			}
			
			// 3. Ako predi6noto vreme za start NE e nali4no v tablica 'cron_job_instance' - proverqvame poslednoto startirane:
			
			$date_last_started = '';
			$instance_last_started = new read_cron_job_instance_last_started($cron_job_id);
			if (($row_last_started = $instance_last_started->read_1st_row()) !== FALSE)
			{
				$date_last_started = $row_last_started['started_at'];
			}
			
			// 3.1 Ako nqma predi6no startirane - startirame cron-job-a
			// 3.2 Ako ima predi6no startirane, nova proverka:
			// 3.2.1 Proverqvame statusa mu:
			// 3.2.1.1 Ako e finish ili finish s gre6ki - startirame cron-job-a
			// 3.2.1.2 Ako e In Progress - syzdavame teku6tiqt red v 'cron_job_instance' sys status = 'not_started'
			
			$new_dv = getdate($control_value+0);
			if ($old_dv['year'] != $new_dv['year'] || $old_dv['mon'] != $new_dv['mon'] || $old_dv['mday'] != $new_dv['mday'])
			{
				$record_changed = TRUE;
			}
			
			// Uslovie za izpylnenieto na tozi cron_job
			if ($date_last_started == '')
			
			$query = 'SELECT export_name FROM automatic_export WHERE id = (SELECT cron_export_id FROM cron_job WHERE id = '.$cron_job_id.')';
			$select_name = new db_select($query);
			$export_name = '';
			if (($row_name = $select_name->read_1st_row()) !== FALSE)
			{
				$export_name = $row_name['export_name'];
			}
			
			$arr_cron_job_instance['import_export'] 		= 'Export';
			$arr_cron_job_instance['import_export_status'] 	= 'export_in_progress';
			$arr_cron_job_instance['cron_job_id'] 			= $cron_job_id;
			$arr_cron_job_instance['imp_exp_name'] 			= $export_name;
			
			$form_tbl_name 			= 'cron_job_instance';
			$SQL_Insert 			= cmn_::sql_insert_statement_construct($form_tbl_name, $arr_cron_job_instance);
			$indb 					= new db_insert($SQL_Insert);
			$cron_job_instance_id 	= $indb->insert_id;
			$query 					= 'UPDATE `'.$form_tbl_name.'` SET initial_id = '.$cron_job_instance_id.' WHERE id = '.$cron_job_instance_id.' LIMIT 1';
			$indb2 					= new db_update($query);
			
			exec('php /var/www/Hub/cron/test/test2.php 404 > /var/www/Hub/cron/test/4.log 2>&1');
			
		}
	}
?>
```

**Comment by Defman21** [comment]
Temporary workaround: changing the name of variable `$date`.

**Comment by Defman21** [comment]
So I've tested it with another variables, for example `$getdate = 1` also breaks a tooltip for getdate() function

**Comment by Naatan** [comment]
Could you please provide a snippet that's as small as possible?

**Comment by Defman21** [comment]
```php
$date = date("d");
date(|); //no tooltips, | - cursor
```

**Comment by Naatan** [comment]
Thanks, reproduced.
