### ISSUE TITLE
komodo 10 stops responding to keyboard in vi emulation mode

### ISSUE THREAD

**Issue by dch** [Komodo/KomodoEdit#1277]
### Short Summary

during normal editing, using split panes, komodo stops accepting any keyboard input.

### Steps to Reproduce

type away as normal. paste using ctrl-v.

### Expected results

text appears in active pane

### Actual results

nada. nichts. nothing.

### Platform Information

Komodo IDE, version 10.0.0-alpha1, build 88858, platform macosx.
Built on Fri Apr 15 01:43:18 2016.
el capitan 10.11.4 (15E65)

### Additional Information

pasting using mouse works.
cmd-Q to quit Komodo doesn't -- no keyboard entry at all works.

```
[2016-04-19 23:43:11,305] [ERROR] vimlog: 
-- EXCEPTION START --
TypeError: this.inputBufferLabel is null
+ stack
    VimController.prototype.inputBufferStart@chrome://komodo/content/keybindings/viKeyBinder.js:1125:13
    VimController.prototype.initSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:1413:1
    cmd_vim_enterSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:3835:5
    @chrome://komodo/content/keybindings/viKeyBinder.js line 2801 > eval:1:1
    vim_doCommand@chrome://komodo/content/keybindings/viKeyBinder.js:2801:25
    @chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:17
    VimController.prototype.handleKeypress@chrome://komodo/content/keybindings/viKeyBinder.js:1096:17
    onxblkeypress@chrome://komodo/content/bindings/views-editor.xml:2554:21
-- EXCEPTION END --
[2016-04-19 23:43:11,312] [ERROR] vimlog: 
-- EXCEPTION START --
TypeError: this.statusBarMode is null
+ stack
    VimController.prototype.updateStatusBarMode@chrome://komodo/content/keybindings/viKeyBinder.js:637:5
    @chrome://komodo/content/keybindings/viKeyBinder.js:719:9
    VimController.prototype.initSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:1415:9
    cmd_vim_enterSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:3835:5
    @chrome://komodo/content/keybindings/viKeyBinder.js line 2801 > eval:1:1
    vim_doCommand@chrome://komodo/content/keybindings/viKeyBinder.js:2801:25
    @chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:17
    VimController.prototype.handleKeypress@chrome://komodo/content/keybindings/viKeyBinder.js:1096:17
    onxblkeypress@chrome://komodo/content/bindings/views-editor.xml:2554:21
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
Does this also happen when you disable Vi mode?

**Comment by dch** [comment]
I ran yesterday without vi mode on (oh the pain) and had no issues, so I assume it's mode specific.

**Comment by dch** [comment]
So a bit more info, what actually happens is that you can no longer toggle vi mode with Escape key. The cursor stays in block mode, but you can press `i` and insert text, for example. The arrow keys won't work, but you can use vi motion successfully. movement between tabs (cmd-1 etc fails), but you can use the mouse to select tabs, save files from menu etc.

```
-- EXCEPTION START --
TypeError: this.inputBufferLabel is null
+ stack
    VimController.prototype.inputBufferStart@chrome://komodo/content/keybindings/viKeyBinder.js:1125:13
    VimController.prototype.initSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:1413:1
    cmd_vim_enterSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:3835:5
    @chrome://komodo/content/keybindings/viKeyBinder.js line 2801 > eval:1:1
    vim_doCommand@chrome://komodo/content/keybindings/viKeyBinder.js:2801:25
    @chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:17
    VimController.prototype.handleKeypress@chrome://komodo/content/keybindings/viKeyBinder.js:1096:17
    onxblkeypress@chrome://komodo/content/bindings/views-editor.xml:2554:21
-- EXCEPTION END --
[2016-04-21 14:55:05,301] [ERROR] vimlog: 
-- EXCEPTION START --
TypeError: this.statusBarMode is null
+ stack
    VimController.prototype.updateStatusBarMode@chrome://komodo/content/keybindings/viKeyBinder.js:637:5
    @chrome://komodo/content/keybindings/viKeyBinder.js:719:9
    VimController.prototype.initSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:1415:9
    cmd_vim_enterSearchForward@chrome://komodo/content/keybindings/viKeyBinder.js:3835:5
    @chrome://komodo/content/keybindings/viKeyBinder.js line 2801 > eval:1:1
    vim_doCommand@chrome://komodo/content/keybindings/viKeyBinder.js:2801:25
    @chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:17
    VimController.prototype.handleKeypress@chrome://komodo/content/keybindings/viKeyBinder.js:1096:17
    onxblkeypress@chrome://komodo/content/bindings/views-editor.xml:2554:21
-- EXCEPTION END --
[2016-04-21 14:57:30,773] [ERROR] console-logger: TypeError: this.statusBarMode is null (2) in chrome://komodo/content/keybindings/viKeyBinder.js:637
Traceback (most recent call last):
  File "chrome://komodo/content/keybindings/viKeyBinder.js", line 637, in 

[2016-04-21 14:57:32,613] [ERROR] console-logger: ReferenceError: root is not defined (2) in chrome://komodo/content/scc/commit.js:75
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 75, in 

[2016-04-21 14:58:00,784] [ERROR] console-logger: ReferenceError: root is not defined (2) in chrome://komodo/content/scc/commit.js:75
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 75, in 
```

**Comment by tonyattwood** [comment]
Hi,

Look at that, it's something really worthy, don't miss it. Here is the link   <http://follow.dulwichmassage.com/e4ckb>

Sincerely yours, tony.attwood@ntlworld.com

**Comment by tonyattwood** [comment]
Hey,

Have you  already tried that new Oliver's  recipe!  That's  something really delicious, give it a try <http://fast.mikevergato.com/e4hufplv>


Best wishes, tony.attwood@ntlworld.com
