### ISSUE TITLE
Rx Toolkit doesn't work with Ruby

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1337]
### Short Summary

I'm getting this error: (my regular expression is `[123]`)
```
There is an error in your regular expression: /home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- iconv (LoadError)
	from /home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/defman/Apps/Komodo/latest/lib/support/rxx/ruby/lib/json/common.rb:2:in `<top (required)>'
	from /home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/defman/Apps/Komodo/latest/lib/support/rxx/ruby/lib/json.rb:1:in `<top (required)>'
	from /home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/defman/Apps/Komodo/latest/lib/support/rxx/rxx_ruby.rb:13:in `rescue in <main>'
	from /home/defman/Apps/Komodo/latest/lib/support/rxx/rxx_ruby.rb:9:in `<main>'
```

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04

**Comment by Naatan** [comment]
Your Ruby setup is corrupt or not properly configured:

/home/defman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- iconv (LoadError)

**Comment by Defman21** [comment]
Installing iconv via gem solved the issue. Thanks Nathan!
