### ISSUE TITLE
Changing color scheme while Commando is opened breaks Commando

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1348]
### Short Summary

While I was creating my scheme I've opened Commando to see how my scheme looks for it and then I changed something related to Commando in the scheme and applied it. After waiting for applying changes, Commando dissipated and I was not able to open it again with hotkeys or with this big thing in the top center of Komodo window. 

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10
*Operating System (and version)?* Ubuntu 16.04 with Openbox

**Comment by mitchell-as** [comment]
I cannot reproduce this, but I your steps aren't clear. I opened the color scheme editor, then opened Commando, then went back to the color scheme editor, changed some interface colors, clicked "Apply", selected "UI" and "Widgets", then clicked OK (note Command was still open in Komodo). After waiting a bit for the scheme to apply, Commando closed, but I was able to reopen it via Ctrl+Shift+O and by clicking on it. Could you provide some more detailed steps? Thanks.

**Comment by Defman21** [comment]
Try to change something that related to Commando, probably its icon color. (`icons_special`)

**Comment by Defman21** [comment]
When I've changing this pref, Commando was not available until I pressed Ctrl+< (so not Ctrl+Shift+O or clicking on it)

**Comment by Naatan** [comment]
Please provide exact reproduction steps. Your error log would also be useful.

The steps you gave are way too vague for to reproduce.

**Comment by Defman21** [comment]
Open Color Scheme Editor.
Open Commando.
Change `Interface - icons_special` pref.
Press Apply.
Select everything in the popup, press OK.
Wait for applying changes.
Focus on main window, try to open Commando with Ctrl+Shift+O or clicking on the top thing that opens it.
Nothing should happen, but if you try to open it with specific scope via hotkey (Files for example, Ctrl+<) it will open.

Here's my log.
```
[2016-05-02 17:56:48,662] [WARNING] console-logger: Expected color but found '#'.  Error in parsing value for 'background-color'.  Declaration dropped. (1) in chrome://komodo/content/colorpicker/colorpicker.html:0
[2016-05-02 17:56:52,264] [WARNING] koLess: Reloading Skin
[2016-05-02 17:56:52,264] [WARNING] koLess: Clearing local and file cache
[2016-05-02 17:56:53,162] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in chrome://global/skin/global.css:179
[2016-05-02 17:56:53,703] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:54,428] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:54,500] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:54,573] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,090] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,158] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,307] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,376] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,674] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,746] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,818] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,888] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:55,956] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,027] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,099] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,168] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,236] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,306] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,376] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,445] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,515] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,584] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,654] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,723] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:56:56,792] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less?1462201012804:179
[2016-05-02 17:57:11,060] [WARNING] console-logger: Use of attributes' nodeValue attribute is deprecated. Use value instead. (1) in chrome://komodo/content/komodo.xul:0
[2016-05-02 17:57:30,056] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:57:57,978] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:57:58,621] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:57:58,638] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:00,894] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:01,490] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:01,507] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:01,524] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:03,395] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:03,787] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:03,811] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 17:58:03,823] [ERROR] console-logger: TypeError: aProperties is undefined (2) in chrome://inspector/content/viewers/styleRules/styleRules.js:586
Traceback (most recent call last):
  File "chrome://inspector/content/viewers/styleRules/styleRules.js", line 586, in 

[2016-05-02 18:11:31,751] [WARNING] console-logger: Error in parsing value for 'font-size'.  Declaration dropped. (1) in less://komodo/skin/global/global.less:179
[2016-05-02 18:11:32,014] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

**Comment by mitchell-as** [comment]
Thanks, reproduced by changing "Special" color while Commando is open.

**Comment by Naatan** [comment]
Thanks. Reproduced. Minor because it's easily worked around and not a likely thing to happen.
