### ISSUE TITLE
[10.0] crash when changing style preferences then can't launch

### ISSUE THREAD

**Issue by robclancy** [Komodo/KomodoEdit#1376]
### Short Summary
When setting colour scheme to solarized dark it crashes after appearing to attempt to apply it. Haven't tried with other colour schemes.

While trying to reproduce for this issue it happens to any scheme I choose but now it saves the settings still and restarting works fine. The first time

### Steps to Reproduce
- go to the interface preferences `preferences->appearance`
- click `use same color scheme for everything` if unchecked (this is what I did first time this happened, subsequent times it is already checked)
- change colour scheme to something else to force it all to reload
- apply or ok

### Expected results
Load for a while and change the scheme.

### Actual results
Loads for a while and code area starts to render again showing new scheme and then it crashes. Upon relaunch it shows new changes applied.

### Platform Information

Komodo IDE 10 
Arch Linux with i3

Komodo IDE, version 10.0.0-beta1, build 89060, platform linux-x86_64. Built on Tue May 3 02:35:35 2016.

### Additional Information

Terminal Output

> ~/Komodo-IDE-10/bin ⌚ 5:25:18
> $ ./komodo -v                           2.2.3
> komodo: debug: Komodo information:
> komodo: debug:   Version: Komodo IDE 10.0.0 Beta 1 nightly (Build 89060) linux-x86_64
> komodo: debug:   OS type: Linux release 4.5.1-1-ARCH on x86_64 (#1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016)
> komodo: debug: Komodo startup options:
> komodo: debug: 	nFiles: 0
> komodo: debug: mutex name: '/home/robbo/.komodoide/10.0/mutex.lock'
> komodo: debug: acquired mutex: fd=3
> komodo: debug: running lock name: '/home/robbo/.komodoide/10.0/running.lock'
> komodo: debug: No current running Komodo - Ok: fd=4
> komodo: debug: commandments file name: '/home/robbo/.komodoide/10.0/commandments.fifo'
> komodo: debug: first commandments file name: '/home/robbo/.komodoide/10.0/first-commandments.txt'
> komodo: debug: saving startup environment...
> komodo: debug: startup env name: '/home/robbo/.komodoide/10.0/startup-env.tmp'
> komodo: debug: writing out startup environment
> komodo: debug: setting up environment for XRE launch...
> komodo: debug: setting MOZ_NO_REMOTE=1
> komodo: debug: setting PYTHONHOME=/home/robbo/Komodo-IDE-10/lib/mozilla/../python
> komodo: debug: setting _KOMODO_VERUSERDATADIR=/home/robbo/.komodoide/10.0/
> komodo: debug: setting KOMODO_VERBOSE=1
> komodo: debug: setting XRE_PROFILE_PATH=/home/robbo/.komodoide/10.0/XRE
> komodo: debug: setting _XRE_USERAPPDATADIR=/home/robbo/.komodoide/10.0/XRE
> komodo: debug: unsetting MOZ_PLUGIN_PATH env var
> komodo: debug: startup argv for XRE:
> komodo: debug: 	argv[0] = './komodo'
> 
> (process:12306): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
> [2016-05-05 05:25:19,303] [INFO] Startup: Welcome to Komodo IDE 10.0.0-beta1 build 89060 (platform linux-x86_64, running on Linux 4.5.1-1-ARCH version #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016)
> [2016-05-05 05:25:19,303] [INFO] Startup: /usr/bin/python built on Tue May 3 02:35:35 2016
> [2016-05-05 05:25:19,335] [INFO] koInitService: Setting LC_CTYPE to utf-8
> [2016-05-05 05:25:19,631] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
> [2016-05-05 05:25:19,777] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
>     @chrome://komodo/content/komodo.js:15:1
> 
> [2016-05-05 05:25:20,544] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
> [2016-05-05 05:25:20,689] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/robbo/Komodo-IDE-10/lib/mozilla/components/koamAddonManager.js:138
> 
> [2016-05-05 05:25:23,850] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
> [2016-05-05 05:25:24,039] [ERROR] koScopeDocs-Py: Could not find cix for ext
> [2016-05-05 05:25:24,039] [ERROR] koScopeDocs-Py: Could not find cix for html5
> [2016-05-05 05:25:24,042] [INFO] elastic_tabstops: Elastic tabstops loaded.
> [2016-05-05 05:25:24,077] [INFO] komodospellchecker: Spell checker loaded.
> [2016-05-05 05:25:24,078] [INFO] komodospellchecker: Using dictionary en-US
> [2016-05-05 05:25:26,994] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
> [2016-05-05 05:25:26,995] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
> [2016-05-05 05:25:26,996] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
> [2016-05-05 05:26:28,921] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:26:28,921] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:26:28,921] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:26:28,922] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:26:28,922] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:31:46,940] [WARNING] prefs: The 'editor-scheme' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
> [2016-05-05 05:31:46,992] [WARNING] prefs: The 'interface-scheme' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
> [2016-05-05 05:31:46,994] [WARNING] prefs: The 'widget-scheme' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
> [2016-05-05 05:31:47,107] [WARNING] koLess: Reloading Skin
> [2016-05-05 05:31:47,107] [WARNING] koLess: Clearing local and file cache
> 
> 
> ^C
> 
>

**Comment by robclancy** [comment]
Also just tried to tweak the scheme, just changing the default font size and applying to all areas and I get the crash again but this time it breaks the profile again. Here is the python log I get when this happens ~~and then after that log is the log when I try launch again.~~ Okay now I can launch again. Sometimes I get a broken profile and sometimes not.

> ~/.komodoide/10.0 ⌚ 5:44:04
> $ cat pystderr.log                      2.2.3
> [2016-05-05 05:40:17,880] [INFO] Startup: Welcome to Komodo IDE 10.0.0-beta1 build 89060 (platform linux-x86_64, running on Linux 4.5.1-1-ARCH version #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016)
> [2016-05-05 05:40:17,880] [INFO] Startup: /usr/bin/python built on Tue May 3 02:35:35 2016
> [2016-05-05 05:40:17,910] [INFO] koInitService: Setting LC_CTYPE to utf-8
> [2016-05-05 05:40:18,157] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
> [2016-05-05 05:40:18,236] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
>     @chrome://komodo/content/komodo.js:15:1
> 
> [2016-05-05 05:40:18,698] [ERROR] console-logger: bad script XDR magic number (0) in :0
> Traceback (most recent call last):
>   File "", line 0, in 
> 
> [2016-05-05 05:40:18,864] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
> [2016-05-05 05:40:19,014] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/robbo/Komodo-IDE-10/lib/mozilla/components/koamAddonManager.js:138
> [2016-05-05 05:40:22,364] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
> [2016-05-05 05:40:22,518] [ERROR] koScopeDocs-Py: Could not find cix for ext
> [2016-05-05 05:40:22,518] [ERROR] koScopeDocs-Py: Could not find cix for html5
> [2016-05-05 05:40:22,521] [INFO] elastic_tabstops: Elastic tabstops loaded.
> [2016-05-05 05:40:22,554] [INFO] komodospellchecker: Spell checker loaded.
> [2016-05-05 05:40:22,554] [INFO] komodospellchecker: Using dictionary en-US
> [2016-05-05 05:40:22,887] [ERROR] console-logger: bad script XDR magic number (0) in :0
> Traceback (most recent call last):
>   File "", line 0, in 
> 
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/xpcom/server/policy.py", line 274, in _CallMethod_
>     ret = getattr(self._obj_, name) # Let attribute error go here!
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: sccType
> [2016-05-05 05:40:24,755] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:40:24,756] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:40:24,756] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:40:24,756] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:40:24,757] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
> [2016-05-05 05:40:24,870] [ERROR] koFileStatusService: unexpected error from koIFile.isDirectory
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 56, in sortFileStatus
>     if a[0].isDirectory and not b[0].isDirectory:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isDirectory
> [2016-05-05 05:40:24,874] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 466, in _process
>     if u.isLocal and not u.isNetworkFile:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isLocal
> [2016-05-05 05:40:24,874] [ERROR] koFileStatusService: Exception checking uri: None
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 621, in _process
>     reason):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/komodo/fileStatusUtils.py", line 250, in updateFileStatus
>     if koIFile.isLocal and not koIFile.isNetworkFile:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isLocal
> [2016-05-05 05:40:24,875] [ERROR] koFileStatusService: Exception detail: AttributeError('isLocal',)
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 621, in _process
>     reason):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/komodo/fileStatusUtils.py", line 250, in updateFileStatus
>     if koIFile.isLocal and not koIFile.isNetworkFile:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isLocal
> [2016-05-05 05:40:24,879] [ERROR] koFileStatusService: KoFileStatusService thread exception Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 590, in _process
>     reason):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/extensions/publishing@ActiveState.com/components/koPublishingStatus.py", line 164, in needsToReCheckFileStatus
>     uri_cache_key = self._norm_uri_cache_key(koFile.URI)
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/python/komodo/fileStatusUtils.py", line 107, in _norm_uri_cache_key
>     uri = unescapeURL(uri).strip("/")
>   File "/home/robbo/Komodo-IDE-10/lib/python/lib/python2.7/urllib.py", line 1223, in unquote
>     bits = s.split('%')
> AttributeError: 'NoneType' object has no attribute 'split'
> 
> [2016-05-05 05:40:25,319] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
> [2016-05-05 05:40:25,320] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
> [2016-05-05 05:40:25,321] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
> [2016-05-05 05:40:26,147] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 466, in _process
>     if u.isLocal and not u.isNetworkFile:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isLocal
> [2016-05-05 05:40:46,286] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 466, in _process
>     if u.isLocal and not u.isNetworkFile:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isLocal
> [2016-05-05 05:40:50,740] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
> Traceback (most recent call last):
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileStatusService.py", line 466, in _process
>     if u.isLocal and not u.isNetworkFile:
>   File "/home/robbo/Komodo-IDE-10/lib/mozilla/components/koFileEx.py", line 72, in __getattr__
>     raise AttributeError, attr
> AttributeError: isLocal
> [2016-05-05 05:40:53,690] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
> [2016-05-05 05:40:53,690] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
> [2016-05-05 05:40:53,690] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
> [2016-05-05 05:40:53,691] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
> [2016-05-05 05:40:53,691] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
> [2016-05-05 05:41:21,639] [WARNING] koLess: Reloading Skin
> [2016-05-05 05:41:21,639] [WARNING] koLess: Clearing local and file cache

**Comment by robclancy** [comment]
When I tweak the colour scheme with the color scheme editor and only change something for the editor (instead of for editor, interface and widgets) it works fine.
