### ISSUE TITLE
Can't load large 800MB csv document!

### ISSUE THREAD

**Issue by Tetramatrix** [Komodo/KomodoEdit#1390]
### Short Summary

Can't load a large 800MB csv document.
### Steps to Reproduce
1. Open file dialog
2. browse large 800MB csv document
3. Click ok
### Expected results

Document loaded and editable
### Actual results

Messagebox says can't load file. 
### Platform Information

Komodo IDE 10 alpha
Windows 10

**Comment by Defman21** [comment]
I'm not sure that Komodo is a good choice to open such a big data files. It's better to edit csv files in special programs like this: http://csved.sjfrancke.nl/

**Comment by Tetramatrix** [comment]
Isn't this a bug? I can be a text file, too?! I don't like to switch between hundreds of tools!

**Comment by Defman21** [comment]
Komodo IDE is not a Swiss knife. It's for creating different projects in programming languages, not for editing large data files. However I do not represent ActiveState or the Komodo development team so this is just my opinion. I'd suggest to wait for the response from one of the dev team :)

(btw you should not generate/create such big data files at all, in this case you could try to split this file into parts that Komodo could handle (I guess Komodo could candle 100MB file but I don't know really))

**Comment by Tetramatrix** [comment]
BTW. Swiss quality is overrated. I have a middle class swiss watch from TUSSI and after several years the date function sometimes shows a wrong date either a day late or early!

**Comment by Naatan** [comment]
@Defman21 is partly correct in that Komodo is not intended to open very large files, nor is it in fact a knife made by the Swiss. However we DO offer large file support to a degree.

That said, 800MB is stretching it. I would not be surprised to find that you ran into a hard limit. Could you tell me what the exact message is that you received?

**Comment by Tetramatrix** [comment]
It give me file open error:http://imgur.com/jpwGto2

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by Tetramatrix** [comment]
IMO there is no log entry. Just in case this is my log since installation:

[2016-05-08 17:40:25,637] [INFO] Startup: Welcome to Komodo IDE 10.0.0-beta1 build 89080 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2016-05-08 17:40:25,637] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10 nightly\lib\mozilla\komodo.exe built on Wed May 04 01:02:38 2016
[2016-05-08 17:40:26,275] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-05-08 17:40:26,325] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-05-08 17:40:27,165] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-08 17:40:27,414] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-05-08 17:40:33,125] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-08 17:40:33,384] [WARNING] koLanguageServiceBase: Found non-positive guess
[2016-05-08 17:40:34,048] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-08 17:40:34,269] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-08 17:40:34,641] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-08 17:40:35,757] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-05-08 17:40:36,051] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-05-08 17:40:36,089] [INFO] komodospellchecker: Spell checker loaded.
[2016-05-08 17:40:36,089] [INFO] komodospellchecker: Using dictionary en-US
[2016-05-08 17:40:36,220] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-05-08 17:40:36,220] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-05-08 17:40:37,066] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-08 17:40:40,036] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-05-08 17:40:40,039] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-05-08 17:40:40,049] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-05-08 17:40:40,065] [ERROR] commando-scope-packages: Unable to retrieve package listing for addons
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:40,069] [ERROR] commando-scope-packages: Unable to retrieve package listing for macros
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:40,072] [ERROR] commando-scope-packages: Unable to retrieve package listing for toolbox
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:40,076] [ERROR] commando-scope-packages: Unable to retrieve package listing for schemes
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:40,078] [ERROR] commando-scope-packages: Unable to retrieve package listing for languages
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:40,078] [ERROR] commando-scope-packages: Unable to retrieve package listing for skins
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:40,079] [ERROR] commando-scope-packages: Unable to retrieve package listing for keybinds
Traceback from ERROR in 'commando-scope-packages' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this._getAvailablePackagesByKind/<@chrome://scope-packages/content/packages.js:406:17
    this.request/req.onreadystatechange@chrome://komodo/content/sdk/ajax.js:66:17

[2016-05-08 17:40:41,496] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:31
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 31, in 

[2016-05-08 17:40:41,497] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:31
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 31, in 

[2016-05-08 17:40:41,499] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:31
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 31, in 

[2016-05-08 17:40:41,500] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:31
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 31, in 

[2016-05-08 17:40:41,503] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:31
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 31, in 

[2016-05-08 17:40:42,585] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010%20nightly/lib/mozilla/components/koamAddonManager.js:138

**Comment by Naatan** [comment]
Hmm nope, looks like you're right.

Any chance that file is available publicly somewhere?

**Comment by Tetramatrix** [comment]
Unfortunatley not. But I have good news. It give me this in error in log file:CodeIntelError: File too big. Size: 421022632 bytes, path: u'd:\\xxx\\xxx\\ip2location-lite-db11.csv\\ip2location-lite-db11.csv' when trying to load a 412MB file. You can download it at:http://http://lite.ip2location.com/database/ip-country-region-city-latitude-longitude-zipcode-timezone. It's the smaller and free version. BTW. when I try to load a pure binary file with 400MB data Komodo restarts and gives me this:http://imgur.com/LMQOEoh.
