### ISSUE TITLE
Ruby fails with CLI app debugging

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#1453]
### Short Summary

Title

### Steps to Reproduce

1. Clone https://github.com/laktek/todo somewhere
2. Install the dependencies with `gem install todo`
3. Change this line to lowercase: https://github.com/laktek/todo/blob/master/lib/todo/controller.rb#L3
4. Run bin/todo with the komodo debugger

### Expected results

See output

### Actual results

Get the following error:

```
no implicit conversion of Byebug::DBGP::OutputStream into String
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:703:in `open'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:703:in `open_logfile'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:635:in `initialize'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:353:in `new'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:353:in `initialize'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/logger.rb:5:in `new'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/logger.rb:5:in `new'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/program/class_methods.rb:19:in `block in <module:ClassMethods>'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/fattr-2.3.0/lib/fattr.rb:125:in `instance_eval'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/fattr-2.3.0/lib/fattr.rb:125:in `call'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/fattr-2.3.0/lib/fattr.rb:125:in `block (2 levels) in fattrs'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/fattr-2.3.0/lib/fattr.rb:174:in `block (3 levels) in fattrs'
(eval):4:in `logger'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/program/instance_methods.rb:73:in `setup_logging'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/program/instance_methods.rb:47:in `main_initialize'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/program/class_methods.rb:84:in `block in new'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/program/class_methods.rb:81:in `instance_eval'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/program/class_methods.rb:81:in `new'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/factories.rb:17:in `run'
/home/nathan/.rvm/gems/ruby-2.3.0/gems/main-6.2.0/lib/main/factories.rb:25:in `Main'
/home/nathan/Projects/Samples/ruby-todo/lib/todo/cli.rb:13:in `<top (required)>'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/nathan/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/nathan/Projects/Samples/ruby-todo/bin/todo:6:in `<top (required)>'
```

**Comment by mitchell-as** [comment]
Note to self: this seems to have always been present in our debugger since we hijack STDOUT to forward output to Komodo. The hijacked object needs to be able to be coerced into an IO object for use by loggers and such.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/416d49551cb4959177599ca2030bb46c9d006d0c.
