### ISSUE TITLE
Uncomment php block causes error

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1509]
### Short Summary
When you try to uncomment a php block, only the first line gets uncomment and the cursor dissapears. As discribed [here](http://forum.komodoide.com/t/code-commenting-in-php/2711).

### Steps to Reproduce
Open a php file and try to uncomment this:
```php
<?php
//echo "test";
//
//echo "test"
?>
```

### Platform Information
[2016-05-18 00:09:32,423] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform win32-x86, running on Windows post2012Server version 6.3.9600)

### Additional Information
```javascript
ERROR:xpcom:Unhandled exception calling 'int8 * uncomment(in nsISomething);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koUDLLanguageBase.py", line 591, in uncomment
    KoCommenterLanguageService.uncomment(self, scimoz)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koLanguageServiceBase.py", line 760, in uncomment
    self._determineMethodAndDispatch(scimoz, uncommenters, commenting=False)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koLanguageServiceBase.py", line 712, in _determineMethodAndDispatch
    workers["line"](scimoz, textStart, textEnd)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koLanguageServiceBase.py", line 510, in _uncommentLines
    scimoz.replaceTarget(replacementLines[i].rstrip('\r\n'))
  File "<XPCOMObject method 'replaceTarget'>", line 3, in replaceTarget
Exception: 2147942487 (NS_ERROR_ILLEGAL_VALUE)
ERROR:xpcom:Unhandled exception calling 'int8 * doCommand(in string);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koLanguageCommandHandler.py", line 694, in doCommand
    meth()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koLanguageCommandHandler.py", line 1013, in _do_cmd_uncomment
    commenter.uncomment(view.scimoz)
  File "<XPCOMObject method 'uncomment'>", line 3, in uncomment
Exception: 2147500037 (NS_ERROR_FAILURE)
[2016-05-18 00:09:52,016] [ERROR] commands: An error occurred executing the cmd_uncomment command
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://xtk/content/controller.js :: ForwardingController_doCommand :: line 203"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIController.doCommand]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://xtk/content/controller.js'
+ lineNumber (number) 203
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'ForwardingController_doCommand@chrome://xtk/content/controller.js:203:4
command_doCommand@chrome://k'...475 chars
+ location (object) JS frame :: chrome://xtk/content/controller.js :: ForwardingController_doCommand :: line 203
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://xtk/content/controller.js'
| + name (string) 'ForwardingController_doCommand'
| + lineNumber (number) 203
| + columnNumber (number) 4
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239
| + formattedStack (string) 'ForwardingController_doCommand@chrome://xtk/content/controller.js:203:4
command_doCommand@chrome://k'...475 chars
| + stack
    ForwardingController_doCommand@chrome://xtk/content/controller.js:203:4
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    @chrome://komodo/content/keybindings/keybindings.js line 2562 > eval:1:0
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2562:22
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2733:16
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2617:4
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
What are you doing to uncomment it?

**Comment by babobski** [comment]
Forgot to add the link, noticed a [issue](http://forum.komodoide.com/t/code-commenting-in-php/2711) on the forum. Tested it and got the same result.
You need to select the block first and than uncomment, got the same result using the keybinding as trough the menu.

**Comment by Naatan** [comment]
Reproduced using Code > Un-comment. Thanks!
