### ISSUE TITLE
Getting Started Splash Screen doesn't load properly.

### ISSUE THREAD

**Issue by Jake-Day-Williams** [Komodo/KomodoEdit#1538]
### Short Summary
On application launch the splash screen fails to load properly.

### Steps to Reproduce
Start Komodo IDE

### Expected results
A normal getting started page.

### Actual results
![error](https://cloud.githubusercontent.com/assets/17089983/15377364/6a80fe26-1d18-11e6-8c03-fe451b25f97a.PNG)

### Platform Information
*Komodo IDE* 
*10* 
*Windows 7*
 
### Additional Information
I've tried uninstalling and reinstalling. Got the same results.

**Comment by cgchoffman** [comment]
Can you open a CMD terminal, `cd` to where you've installed Komodo then run `ko -v` and paste the output here?

**Comment by Jake-Day-Williams** [comment]
komodo: debug:   Version: Komodo IDE 10.0.0 (Build 89159) win32-x86
komodo: debug:   OS type: Windows 7
komodo: debug: Komodo startup options:
komodo: debug:  nFiles: 0

**Comment by Jake-Day-Williams** [comment]
And here's the Terminal that pops up. It is returning some errors so I'm sharing it.


[2016-05-18 19:29:38,164] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 891
59 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2016-05-18 19:29:38,174] [INFO] Startup: C:\Program Files (x86)\ActiveState Kom
odo IDE 10\lib\mozilla\komodo.exe built on Wed May 11 15:04:59 2016
[2016-05-18 19:29:38,703] [WARNING] console-logger: mutating the [[Prototype]] o
f an object will cause your code to run very slowly; instead create the object w
ith the correct initial [[Prototype]] value using Object.create (1) in resource:
//gre/modules/Preferences.jsm:381
[2016-05-18 19:29:39,065] [ERROR] koProjectService: project_window_data:: getMos
tRecentWindow did not return a window
[2016-05-18 19:29:39,105] [ERROR] console-logger: bad script XDR magic number (0
) in :0
Traceback (most recent call last):
  File "", line 0, in

[2016-05-18 19:29:39,282] [ERROR] koScintillaSchemeService: Syntax Error loading
 scheme C:\Users\WilliamsTew\AppData\Local\ActiveState\KomodoIDE\10.0\schemes\ba
se16-brewer-dark.ksf:
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\
koScintillaSchemeService.py", line 88, in _execfile
    execfile(fname, namespace)
  File "C:\Users\WilliamsTew\AppData\Local\ActiveState\KomodoIDE\10.0\schemes\ba
se16-brewer-dark.ksf", line 2
SyntaxError: Non-ASCII character '\xc3' in file C:\Users\WilliamsTew\AppData\Loc
al\ActiveState\KomodoIDE\10.0\schemes\base16-brewer-dark.ksf on line 2, but no e
ncoding declared; see http://www.python.org/peps/pep-0263.html for details
[2016-05-18 19:29:39,332] [ERROR] SchemeBase: Unable to load Komodo color scheme
: {'userDefined': 1, 'filepath': u'C:\\Users\\WilliamsTew\\AppData\\Local\\Activ
eState\\KomodoIDE\\10.0\\schemes\\base16-brewer-dark.ksf'}
[2016-05-18 19:29:39,433] [ERROR] console-logger: TypeError: s is null (2) in ch
rome://komodo/content/startupWizard/startupWizard.js:214
Traceback (most recent call last):
  File "chrome://komodo/content/startupWizard/startupWizard.js", line 214, in

[2016-05-18 19:29:39,453] [ERROR] console-logger: TypeError: w is null (2) in ch
rome://komodo/content/bindings/windows.xml:319
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 319, in

**Comment by mitchell-as** [comment]
Hi, please make a backup of your "c:\users\...\AppData\Local\ActiveState\KomodoIDE\10.0" folder before deleting it and trying to run Komodo X again. If you still get the same error, please make a backup of the entire KomodoIDE folder before deleting and trying again. It appears Komodo X is either reading or importing an invalid file from your profile folder.

**Comment by cgchoffman** [comment]
@Naatan, color scheme imported when it shouldn't have been?  I'm not sure what the new profile import stuff does.  Are color schemes supposed to be migrated between versions?

**Comment by Naatan** [comment]
@cgchoffman they are but their setting should be changed to our new default.

I'll have to make the startup wizard more resilient against custom color schemes regardless. I'll make this bug about that.
