### ISSUE TITLE
Vi keybindings seem to break scintilla

### ISSUE THREAD

**Issue by blfgomes** [Komodo/KomodoEdit#1549]
### Short Summary
The up and down keyboard keys should be able to navigate past code folds, but the cursor goes inside it instead.

### Steps to Reproduce
Fold a code block and try to navigate it with the arrow keys.

### Expected results
The cursor should navigate past the fold, treating it as one line.

### Actual results
 The cursor goes inside the fold (not visible). For instance, if the fold has 4 lines, you have to press down 4 times to get past it.

### Platform Information
Komodo IDE 10.0 
Windows 7 Enterprise SP 1

**Comment by cgchoffman** [comment]
I'm not seeing this.  Win10, Komodo 10.  Could you restart Komodo, reproduce the issue then paste the output of *Help > Troubleshooting > View Log File* here?

**Comment by blfgomes** [comment]
Sure, here it is:

[2016-05-19 14:20:54,848] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2016-05-19 14:20:54,848] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\komodo.exe built on Wed May 11 15:04:59 2016
[2016-05-19 14:20:56,809] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-05-19 14:20:56,913] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-05-19 14:20:57,571] [ERROR] console-logger: TypeError: redeclaration of variable val (2) in chrome://analytics/content/analytics.js:204
Traceback (most recent call last):
  File "chrome://analytics/content/analytics.js", line 204, in 

[2016-05-19 14:20:57,898] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-19 14:20:58,296] [WARNING] keybindings: [Ctrl+F] was used for 'cmd_startIncrementalSearch', overriding to use 'cmd_startIncrementalSearch'
[2016-05-19 14:20:58,302] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-05-19 14:20:58,305] [WARNING] keybindings: [Ctrl+P] was used for 'cmd_scope-packages', overriding to use 'cmd_vim_linePrevious'
[2016-05-19 14:20:58,306] [WARNING] keybindings: [Ctrl+D] was used for 'cmd_addNextWordToCaretSet', overriding to use 'cmd_vim_scrollHalfPageDown'
[2016-05-19 14:20:58,306] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_runInLine', overriding to use 'cmd_vim_pageUp'
[2016-05-19 14:20:58,308] [WARNING] keybindings: [Ctrl+Y] was used for 'cmd_redo', overriding to use 'cmd_vim_lineScrollUp'
[2016-05-19 14:20:58,308] [WARNING] keybindings: [Ctrl+E] was used for 'cmd_endOfWord', overriding to use 'cmd_vim_lineScrollDown'
[2016-05-19 14:20:58,309] [WARNING] keybindings: [Ctrl+V] was used for 'cmd_paste', overriding to use 'cmd_vim_toggleVisualBlockMode'
[2016-05-19 14:20:58,311] [WARNING] keybindings: [Ctrl+[] was used for 'cmd_blockSelect', overriding to use 'cmd_vim_cancel'
[2016-05-19 14:20:58,312] [WARNING] keybindings: [Ctrl+R] was used for 'cmd_dbgRun', overriding to use 'cmd_vim_redo'
[2016-05-19 14:20:59,681] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-19 14:21:00,480] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138
[2016-05-19 14:21:03,358] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-05-19 14:21:03,996] [INFO] komodospellchecker: Spell checker loaded.
[2016-05-19 14:21:03,996] [INFO] komodospellchecker: Using dictionary en-US
[2016-05-19 14:21:04,045] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-05-19 14:21:04,507] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-05-19 14:21:04,509] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-05-19 14:21:08,785] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-05-19 14:21:08,789] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-05-19 14:21:08,819] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-05-19 14:21:15,171] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-19 14:21:15,174] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-19 14:21:15,174] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-19 14:21:15,174] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-19 14:21:15,176] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-19 14:21:16,769] [ERROR] scintilla: 
-- EXCEPTION START --
TypeError: xtk.ForwardingController is not a constructor
+ stack
    init@chrome://komodo/content/bindings/scintilla.xml:580:37
    initWithBuffer@viewbufferbase:637:13
    loadDiffResult@chrome://komodo/content/dialogs/diff.js:117:13
    scc_history_OnLoad@chrome://komodo/content/scc/history.js:264:13
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:157:5
-- EXCEPTION END --
[2016-05-19 14:21:16,776] [ERROR] scintilla: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.usePopUp is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1402}]'[JavaScript Error: "this.__scimoz.usePopUp is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1402}]' when calling method: [ISciMoz_Part2::usePopUp]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/bindings/scintilla.xml :: init :: line 607"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.usePopUp is undefined" {file: "file:///C:/Program%20Files%20(x86)/'...421 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/bindings/scintilla.xml'
+ lineNumber (number) 607
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/bindings/scintilla.xml :: init :: line 607
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/bindings/scintilla.xml'
| + name (string) 'init'
| + lineNumber (number) 607
| + columnNumber (number) 20
| + sourceLine (string) ''
| + caller (object) JS frame :: viewbufferbase :: initWithBuffer :: line 637
| + formattedStack (string) 'init@chrome://komodo/content/bindings/scintilla.xml:607:20
initWithBuffer@viewbufferbase:637:12
load'...285 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:16,779] [ERROR] view.diff: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.hookEvents is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1842}]'[JavaScript Error: "this.__scimoz.hookEvents is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1842}]' when calling method: [ISciMoz::hookEvents]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: viewbufferbase :: _hookSciMozEvents :: line 677"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.hookEvents is undefined" {file: "file:///C:/Program%20Files%20(x86'...421 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'viewbufferbase'
+ lineNumber (number) 677
+ columnNumber (number) 0
+ location (object) JS frame :: viewbufferbase :: _hookSciMozEvents :: line 677
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'viewbufferbase'
| + name (string) '_hookSciMozEvents'
| + lineNumber (number) 677
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: viewbufferbase :: initWithBuffer :: line 646
| + formattedStack (string) '_hookSciMozEvents@viewbufferbase:677:0
initWithBuffer@viewbufferbase:646:12
loadDiffResult@chrome://'...265 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:16,780] [ERROR] diff: error loading diff window dialog.
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.setMarginWidthN is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 2110}]'[JavaScript Error: "this.__scimoz.setMarginWidthN is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 2110}]' when calling method: [ISciMoz_Part0::setMarginWidthN]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/dialogs/diff.js :: loadDiffResult :: line 125"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.setMarginWidthN is undefined" {file: "file:///C:/Program%20Files%2'...442 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/dialogs/diff.js'
+ lineNumber (number) 125
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/dialogs/diff.js :: loadDiffResult :: line 125
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/diff.js'
| + name (string) 'loadDiffResult'
| + lineNumber (number) 125
| + columnNumber (number) 8
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/scc/history.js :: scc_history_OnLoad :: line 264
| + formattedStack (string) 'loadDiffResult@chrome://komodo/content/dialogs/diff.js:125:8
scc_history_OnLoad@chrome://komodo/content/scc/history.js:264:12
xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:157:4
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:19,891] [ERROR] diff: error loading diff window dialog.
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]'[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]' when calling method: [ISciMoz_Part1::emptyUndoBuffer]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: viewbufferbase :: setBufferText :: line 688"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%2'...442 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'viewbufferbase'
+ lineNumber (number) 688
+ columnNumber (number) 0
+ location (object) JS frame :: viewbufferbase :: setBufferText :: line 688
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'viewbufferbase'
| + name (string) 'setBufferText'
| + lineNumber (number) 688
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/diff.js :: loadDiffResult :: line 119
| + formattedStack (string) 'setBufferText@viewbufferbase:688:12
loadDiffResult@chrome://komodo/content/dialogs/diff.js:119:12
_scc_history_dialog.prototype.performDiff/<@chrome://komodo/content/scc/history.js:606:16
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:19,913] [ERROR] console-logger: TypeError: this.__scimoz.usePopUp is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:1402
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 1402, in 

[2016-05-19 14:21:19,921] [ERROR] console-logger: TypeError: this.__scimoz.hookEvents is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:1842
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 1842, in 

[2016-05-19 14:21:19,927] [ERROR] console-logger: TypeError: this.__scimoz.setMarginWidthN is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:2110
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 2110, in 

[2016-05-19 14:21:19,934] [ERROR] diff: error loading diff window dialog.
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]'[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]' when calling method: [ISciMoz_Part1::emptyUndoBuffer]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: viewbufferbase :: setBufferText :: line 688"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%2'...442 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'viewbufferbase'
+ lineNumber (number) 688
+ columnNumber (number) 0
+ location (object) JS frame :: viewbufferbase :: setBufferText :: line 688
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'viewbufferbase'
| + name (string) 'setBufferText'
| + lineNumber (number) 688
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/diff.js :: loadDiffResult :: line 119
| + formattedStack (string) 'setBufferText@viewbufferbase:688:12
loadDiffResult@chrome://komodo/content/dialogs/diff.js:119:12
_scc_history_dialog.prototype.performDiff/<@chrome://komodo/content/scc/history.js:606:16
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:20,197] [ERROR] diff: error loading diff window dialog.
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]'[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]' when calling method: [ISciMoz_Part1::emptyUndoBuffer]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: viewbufferbase :: setBufferText :: line 688"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%2'...442 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'viewbufferbase'
+ lineNumber (number) 688
+ columnNumber (number) 0
+ location (object) JS frame :: viewbufferbase :: setBufferText :: line 688
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'viewbufferbase'
| + name (string) 'setBufferText'
| + lineNumber (number) 688
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/diff.js :: loadDiffResult :: line 119
| + formattedStack (string) 'setBufferText@viewbufferbase:688:12
loadDiffResult@chrome://komodo/content/dialogs/diff.js:119:12
Di'...260 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:20,236] [ERROR] diff: error loading diff window dialog.
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]'[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js" line: 1978}]' when calling method: [ISciMoz_Part1::emptyUndoBuffer]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: viewbufferbase :: setBufferText :: line 688"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.__scimoz.emptyUndoBuffer is undefined" {file: "file:///C:/Program%20Files%2'...442 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'viewbufferbase'
+ lineNumber (number) 688
+ columnNumber (number) 0
+ location (object) JS frame :: viewbufferbase :: setBufferText :: line 688
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'viewbufferbase'
| + name (string) 'setBufferText'
| + lineNumber (number) 688
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/diff.js :: loadDiffResult :: line 119
| + formattedStack (string) 'setBufferText@viewbufferbase:688:12
loadDiffResult@chrome://komodo/content/dialogs/diff.js:119:12
sc'...214 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-05-19 14:21:20,923] [ERROR] console-logger: TypeError: this.__scimoz.emptyUndoBuffer is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:1978
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 1978, in 

[2016-05-19 14:21:20,944] [ERROR] console-logger: TypeError: this.__scimoz.emptyUndoBuffer is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:1978
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 1978, in 

[2016-05-19 14:21:20,967] [ERROR] console-logger: TypeError: this.__scimoz.emptyUndoBuffer is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:1978
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 1978, in 

[2016-05-19 14:21:20,979] [ERROR] console-logger: TypeError: this.__scimoz.emptyUndoBuffer is undefined (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js:1978
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/scimoz_wrapper.js", line 1978, in 

[2016-05-19 14:21:21,502] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-05-19 14:21:21,503] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-05-19 14:21:23,444] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-05-19 14:21:23,447] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-05-19 14:21:24,424] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-05-19 14:21:24,427] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-05-19 14:21:25,384] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-05-19 14:21:25,391] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366

**Comment by blfgomes** [comment]
I did a fresh install on a Windows 10 machine and I can't reproduce the issue either. It only happens on the Windows 7 machine.

**Comment by cgchoffman** [comment]
Did you try a fresh install on Windows 7 too?

**Comment by blfgomes** [comment]
I was able to reproduce on both machines now. It happens when the vi keybinding is in use.

**Comment by cgchoffman** [comment]
Makes sense with those errors.  Thanks for digging @blfgomes.  I've update the title for the bug.
