### ISSUE TITLE
Can't debug perl in Komodo 10. 

### ISSUE THREAD

**Issue by mgliana** [Komodo/KomodoEdit#1556]
### Short Summary

Upgraded from Komodo 9.2 to 10 and many of the code i wrote doesn't run/debug anymore. I am getting errors in the included standard modules, such as Moose, etc:

Undefined subroutine &Moose::is_class_loaded called at /usr/local/ActivePerl-5.20/lib/Moose.pm line 155.

Bareword "IS_WIN32" not allowed while "strict subs" in use at /Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/perllib/DB/DbgrURI.pm line 79.

Same code runs fine with Komodo 9.x
### Steps to Reproduce

Install Hash::Fold
Write a small scrip to use Hash::Fold
Debug
### Expected results

Successful execution. 
### Actual results

Bareword and undefined subroutine errors
### Platform Information

_Komodo Edit or IDE?_ 
IDE

_Komodo Version?_ 
10

_Operating System (and version)?_ 
OSX 10.11
### Additional Information
# !/usr/local/ActivePerl-5.20/bin/perl

use Hash::Fold;
print "hello\n";

 -- eg. Error logs, screenshots, workarounds --
Undefined subroutine &Moose::is_class_loaded called at /usr/local/ActivePerl-5.20/lib/Moose.pm line 155.
BEGIN failed--compilation aborted at /usr/local/ActivePerl-5.20/site/lib/Hash/Fold.pm line 4.
Compilation failed in require at Perl-1.pl line 3.
BEGIN failed--compilation aborted at Perl-1.pl line 3.

FAIL: 65280

**Comment by mitchell-as** [comment]
The perl debugger has not changed between Komodo 9 and Komodo X. It is likely that there is a configuration issue. I don't know enough Perl to figure out what is going wrong given the information you've provided. Have you confirmed that your Perl configuration/environment in Komodo 9 matches the one in Komodo X?

**Comment by mgliana** [comment]
Hi Mitchell,

Yes, i still have both komodo versions running on the same machine and using the same version of active perl (there is only one installed). Not sure what other configurations are there to configure (can you elaborate). If you create a new perl file with the above three lines, it should be enough to confirm or reject that it is environment/configuration related issue. 

Thanks and regards,

MG

**Comment by mitchell-as** [comment]
Hi, I've run `cpan install Hash::Fold` on my Linux machine, copied your 3-line script and debugged it without error. "hello" is output. Now I don't have "Moose" installed (not sure what that is), so I cannot comment on that part. I'm not a Perl developer, so maybe I should be doing something more complicated.

**Comment by cgchoffman** [comment]
Did you have any special configuration settings under *Prefs > Environment*, @mgliana?

**Comment by mgliana** [comment]
i compared the env settings of Komod 9.x and 10 and the only difference is 
xpc_service_name: com.activestate.KomodoIDE85152 vs com.activestate.KomodoIDE237792

**Comment by Naatan** [comment]
Does debugging work when you restart in Safe-mode? Help > Troubleshooting > Restart in Safe-mode.

**Comment by mgliana** [comment]
works in safe mode. Does this indicate that there is an extension that is
causing the issue?

**Comment by mgliana** [comment]
Tried to run it without plugins, but it didn't work. Tried to run it without tools and still didn't work. I reset all the configuration settings but no still no luck. The only way I can make it work is to run it in safe mode. There must be something that Komodo is using when not in safe mode. What could that be?

**Comment by mgliana** [comment]
i checked the logs and there is an exception:

[2016-05-26 11:56:21,946] [ERROR] debugSessionTab: 
-- EXCEPTION START --
TypeError: invocation is null
+ stack
    ko_dbg_invocation_doStart/onInvocationReady@chrome://komodo/content/debugger/debugger.js:2444:17
    ko_dbg_invocation_getInvocation/onSessionReady@chrome://komodo/content/debugger/debugger.js:2227:13
    ko_dbg_invocation_getInvocation@chrome://komodo/content/debugger/debugger.js:2231:13
    ko_dbg_invocation_doStart/onSessionReady@chrome://komodo/content/debugger/debugger.js:2431:1
    DBG_Manager_newSession/onTabMgrReady@chrome://komodo/content/debugger/debugger.js:382:13
    outputTabManager_getTabMgr@chrome://komodo/content/debugger/debugSessionTab.js:1082:21
    DBG_Manager_newSession@chrome://komodo/content/debugger/debugger.js:388:13
    ko_dbg_invocation_doStart@chrome://komodo/content/debugger/debugger.js:2537:17
    DBG_Manager.prototype.doStep@chrome://komodo/content/debugger/debugger.js:646:13
    doGo@chrome://komodo/content/debugger/debuggerController.js:195:9
    DebuggerItemsController.prototype.do_cmd_dbgGo@chrome://komodo/content/debugger/debuggerController.js:201:9
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:9
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    debugger_doCommand@chrome://komodo/content/debugger/debuggerController.js:31:16
    oncommand@chrome://komodo/content/komodo.xul:1:1
-- EXCEPTION END --

**Comment by cgchoffman** [comment]
> I reset all the configuration settings but no still no luck.

This is not working on OSX #1571.  Can you try performing that step manually? http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings#how-do-i-start-komodo-with-default-settings_completely-reset-your-settings

I suspect Prefs.xml/c in your profile given the testing you've done so far.  Remember, don't delete anything, rename then test please :D  We want the culprit alive :|

**Comment by mgliana** [comment]
completely removed the pref folders (including old versions) and restarted by got the same issue again. Must be something else that safe mode doesn't use. 

Ms-Mac-Pro:KomodoIDE mgliana$ pwd
/Users/mgliana/Library/Application Support/KomodoIDE
Ms-Mac-Pro:KomodoIDE mgliana$ ls -al
total 0
drwxr-xr-x   5 mgliana  staff   170  2 Jun 14:53 .
drwx------+ 48 mgliana  staff  1632  1 Jun 19:00 ..
drwxr-xr-x  28 mgliana  staff   952  2 Jun 15:01 10.0
drwxr-xr-x   2 mgliana  staff    68  2 Jun 14:51 10.0.bak
drwxr-xr-x   2 mgliana  staff    68  2 Jun 14:52 9.3.bak

**Comment by mitchell-as** [comment]
Just to be sure, can you rename your KomodoIDE folder to "KomodoIDE.bak" and try again? That way Komodo needs to create "KomodoIDE/10.0" from scratch with no chance of reading from any other folders in the directory.

Sorry for all the hoops you have to jump through :(

**Comment by tonyattwood** [comment]
Hello,


Just look at that new stuff, I was surprised so much,  you  have to take a look here  <http://favor.peruchitos.com/e4dtdcc>

Best wishes, tony.attwood@ntlworld.com

**Comment by kenybropwn99** [comment]
I'm having the same problem since upgrade from 9
Debugging any script causes the problem.  The debugger works but does not update the output panes - navigating away to somewhere (ie menu) else and back updates the debugging pane and it then works for a few steps then stops again.

Log below

[2016-09-07 10:42:29,678] [INFO] Startup: Welcome to Komodo IDE 10.1.1 build 89474 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2016-09-07 10:42:29,678] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\komodo.exe built on Thu Sep 01 14:27:01 2016
[2016-09-07 10:42:32,517] [WARNING] koLess: Clearing local and file cache
[2016-09-07 10:42:32,517] [WARNING] koLess: Cleaning up 1 old caches
[2016-09-07 10:42:33,048] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-09-07 10:42:34,203] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-09-07 10:42:37,167] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-09-07 10:42:37,930] [WARNING] ko-fileicons: Clearing icon cache
[2016-09-07 10:42:42,361] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-09-07 10:42:42,752] [INFO] komodospellchecker: Spell checker loaded.
[2016-09-07 10:42:42,752] [INFO] komodospellchecker: Using dictionary en-US
[2016-09-07 10:42:45,059] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-09-07 10:42:49,038] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138
[2016-09-07 10:42:52,502] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-09-07 10:42:52,516] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-09-07 10:42:52,532] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-09-07 10:42:53,094] [ERROR] koToolbox2: tool-deleted <built-in function id> notification failed
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koToolbox2.py", line 1364, in deleteItem
    if self.observerSvc:
AttributeError: 'Database' object has no attribute 'observerSvc'
[2016-09-07 10:42:53,483] [ERROR] koToolbox2: tool-deleted <built-in function id> notification failed
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koToolbox2.py", line 1364, in deleteItem
    if self.observerSvc:
AttributeError: 'Database' object has no attribute 'observerSvc'
[2016-09-07 10:42:53,655] [ERROR] koToolbox2: tool-deleted <built-in function id> notification failed
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\koToolbox2.py", line 1364, in deleteItem
    if self.observerSvc:
AttributeError: 'Database' object has no attribute 'observerSvc'
[2016-09-07 10:43:22,625] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-09-07 10:43:22,766] [ERROR] koScopeDocs-Py: Could not find cix for html5

**Comment by Naatan** [comment]
Please report a new bug, your issue does not sound like it's related beyond the fact that it involves the debugger.
