### ISSUE TITLE
IDE X, Reset Everethyng does not work

### ISSUE THREAD

**Issue by landy2005** [Komodo/KomodoEdit#1571]
### Short Summary

As part of other issues (#1544, #1523) I fount that this functionality also does not work as expected.

### Steps to Reproduce

Install IDE10 (can be upgraded from IDE9), use default config (all questions reply yes).
Than change color scheme to any other (is Classic), "OK".

Than try to reset "Troubleshooting > Reset Everything".
IDE restarted, but still used old config (with changed theme).
Same results if I complete moved config dir {{10.0}} to {{10.0.bak}} in {{$HOME/Library/Application Support/KomodoIDE}} and repeat steps.

### Platform Information
OS X El Capitan 10.11.5
Komodo IDE, version 10.0.0, build 89159, platform macosx.
Built on Wed May 11 15:42:24 2016.

**Comment by cgchoffman** [comment]
I can reproduce this.  The backup of your current profile never gets created.

> Same results if I complete moved config dir {{10.0}} to {{10.0.bak}} in {{$HOME/Library/Application Support/KomodoIDE}} and repeat steps.

@landy2005 can you elaborate on this?
This implies:
shutdown komodo
renamed folder
started Komodo (at this point Komodo would import an old profile)
Help > Troubleshooting > Reset Everything
Komodo restarts with same profile

I would expect that.  Please confirm.

**Comment by landy2005** [comment]
Yes, I did this again, same result (reset not work).

Additionally I see confirm message "... profile folder will backed up at /Users/mike/Library/Application Support/KomodoIDE/10.0-backup", but I not see any new folders here after restart:
```
$ ls -l ~/Library/Application\ Support/KomodoIDE/ | grep 10\.
drwxr-xr-x  31 mike  staff      1054 25 май 22:53 10.0
```

**Comment by cgchoffman** [comment]
Relevant logs:
```
2016-05-25 15:02:15,102] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform macosx, running on Darwin 15.3.0 version Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64)
[2016-05-25 15:02:15,102] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Wed May 11 15:42:24 2016
[2016-05-25 15:02:15,104] [ERROR] koInitService: 'list' object has no attribute 'push'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koInitService.py", line 290, in __init__
    self.checkStartupFlags()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koInitService.py", line 481, in checkStartupFlags
    paths.push(d[2])
AttributeError: 'list' object has no attribute 'push'
```
