### ISSUE TITLE
Not able to open files sometimes

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#1579]
### Short Summary

It just says "Komodo was unable to open the file: `filename`"

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10 nightly
*Operating System (and version)?* eOS 0.4

### Additional Information
```
2016-05-22 11:18:33,558] [INFO] Startup: Welcome to Komodo IDE 10.0.1 build 89178 (platform linux-x86_64, running on Linux 4.4.0-22-generic version #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016)
[2016-05-22 11:18:33,558] [INFO] Startup: /usr/bin/python built on Fri May 20 02:34:33 2016
[2016-05-22 11:18:33,620] [INFO] koInitService: Setting LC_CTYPE to utf-8
[2016-05-22 11:18:33,853] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-05-22 11:18:33,858] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///home/defman/.komodoide/10.0/XRE/extensions/emmet@chikuyonok.ru.xpi!/chrome.manifest:1
[2016-05-22 11:18:33,904] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-05-22 11:18:34,469] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-22 11:18:34,712] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-05-22 11:18:34,937] [ERROR] koScintillaSchemeService: The scheme specified in prefs (Flat_s2i.ksf) is unknown -- reverting to default
[2016-05-22 11:18:34,975] [ERROR] SchemeBase: scheme u'Flat_s2i.ksf' does not exist, using Default instead
[2016-05-22 11:18:35,264] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-05-22 11:18:35,372] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-05-22 11:18:35,421] [INFO] komodospellchecker: Spell checker loaded.
[2016-05-22 11:18:35,421] [INFO] komodospellchecker: Using dictionary en-US
[2016-05-22 11:18:35,496] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-05-22 11:18:35,537] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-05-22 11:18:38,301] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-05-22 11:18:38,302] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-05-22 11:18:38,304] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-05-22 11:18:39,011] [WARNING] console-logger: Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. (1) in http://localhost:57575/static/main.css?v=e90321e6c69148611e57fc1fcdab28a9:160
[2016-05-22 11:18:39,012] [WARNING] console-logger: Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. (1) in http://localhost:57575/static/main.css?v=e90321e6c69148611e57fc1fcdab28a9:162
[2016-05-22 11:18:39,013] [WARNING] console-logger: Unknown pseudo-class or pseudo-element '-webkit-scrollbar'.  Ruleset ignored due to bad selector. (1) in http://localhost:57575/static/main.css?v=e90321e6c69148611e57fc1fcdab28a9:2819
[2016-05-22 11:18:39,014] [WARNING] console-logger: Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. (1) in http://localhost:57575/static/main.css?v=e90321e6c69148611e57fc1fcdab28a9:2822
[2016-05-22 11:18:39,014] [WARNING] console-logger: Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. (1) in http://localhost:57575/static/main.css?v=e90321e6c69148611e57fc1fcdab28a9:2824
[2016-05-22 11:18:39,248] [ERROR] ko-shell: child process ended with code 256, stdout: , stderr: Traceback (most recent call last):
  File "/home/defman/.komodoide/10.0/XRE/extensions/komodo_terminal@activestate.com/content/../pylib/butterfly/butterfly.server.py", line 300, in <module>
    http_server.listen(port, address=host)
  File "/home/defman/.komodoide/10.0/XRE/extensions/komodo_terminal@activestate.com/pylib/tornado-systemd/tornado_systemd/__init__.py", line 29, in listen
    super(SystemdMixin, self).listen(port, address)
  File "/home/defman/.komodoide/10.0/XRE/extensions/komodo_terminal@activestate.com/pylib/tornado/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/defman/.komodoide/10.0/XRE/extensions/komodo_terminal@activestate.com/pylib/tornado/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback from ERROR in 'ko-shell' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    this.run/<@chrome://komodo/content/sdk/shell.js:162:17
    emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:96:9
    initialize/proc<.done@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/child_process.js:84:13
    _done@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/system/child_process/subprocess.js:1614:25

[2016-05-22 11:18:40,373] [ERROR] console-logger: TypeError: this.screen[(this.y + this.shift)] is undefined (2) in http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30:3
Traceback (most recent call last):
  File "http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30", line 3, in 

[2016-05-22 11:18:40,450] [DEBUG] console: log: WebSocket open {"0":{"isTrusted":true}}
[2016-05-22 11:18:40,462] [ERROR] console-logger: TypeError: l is null (2) in http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30:3
Traceback (most recent call last):
  File "http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30", line 3, in 

[2016-05-22 11:18:40,466] [WARNING] console-logger: XrayWrapper denied access to property callee (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. (1) in chrome://komodo/content/sdk/console.js:166
[2016-05-22 11:18:40,466] [WARNING] console-logger: XrayWrapper denied access to property callee (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. (1) in chrome://komodo/content/sdk/console.js:166
[2016-05-22 11:18:40,595] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/defman/Apps/Komodo/latest/lib/mozilla/components/koamAddonManager.js:138
[2016-05-22 11:18:40,982] [ERROR] console-logger: TypeError: l is null (2) in http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30:3
Traceback (most recent call last):
  File "http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30", line 3, in 

[2016-05-22 11:18:41,010] [ERROR] console-logger: TypeError: l is null (2) in http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30:3
Traceback (most recent call last):
  File "http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30", line 3, in 

[2016-05-22 11:18:41,015] [ERROR] console-logger: TypeError: l is null (2) in http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30:3
Traceback (most recent call last):
  File "http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30", line 3, in 

[2016-05-22 11:18:41,022] [ERROR] console-logger: TypeError: l is null (2) in http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30:3
Traceback (most recent call last):
  File "http://localhost:57575/static/main.min.js?v=b7764a0c94f8705c429ab5895209ad30", line 3, in 

[2016-05-22 11:18:42,697] [WARNING] views: Inconsistent view count in view_closed event
[2016-05-22 11:18:42,974] [WARNING] views: Inconsistent view count in view_opened event
[2016-05-22 11:18:43,030] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-22 11:18:43,536] [ERROR] CT::tracker.js: Scc error Error 128 running '[u'/usr/bin/git', 'show', u'HEAD:./Flat_s2i.ksf']'
  in '/home/defman/Projects/komodo/cli/komodo-scheme-to-interface': 
fatal: Path 'Flat_s2i.ksf' exists on disk, but not in 'HEAD'.
Traceback from ERROR in 'CT::tracker.js' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    exports.ChangeTracker.prototype.onError@chrome://trackchanges/content/tracker.js:200:5

[2016-05-22 11:18:49,160] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-22 11:18:49,161] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-22 11:18:49,162] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-22 11:18:49,163] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-22 11:18:49,164] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-22 11:19:30,240] [ERROR] SchemeBase: scheme u'Flat_s2i.ksf' does not exist, using Default instead
[2016-05-22 11:20:17,949] [WARNING] koLess: Reloading Skin
[2016-05-22 11:20:17,949] [WARNING] koLess: Clearing local and file cache
[2016-05-22 11:20:28,598] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-22 11:20:59,349] [WARNING] koLess: Reloading Skin
[2016-05-22 11:20:59,349] [WARNING] koLess: Clearing local and file cache
[2016-05-22 11:21:03,685] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
[2016-05-22 11:21:03,685] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
[2016-05-22 11:21:03,686] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
[2016-05-22 11:21:03,686] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
[2016-05-22 11:21:03,687] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
[2016-05-22 11:21:09,430] [WARNING] views: Inconsistent view count in view_closed event
[2016-05-22 11:21:09,765] [WARNING] views: Inconsistent view count in view_opened event
[2016-05-22 11:22:26,947] [WARNING] prefs: The 'editor-scheme' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-05-22 11:22:27,001] [WARNING] prefs: The 'interface-scheme' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-05-22 11:22:27,013] [WARNING] prefs: The 'widget-scheme' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-05-22 11:22:27,101] [WARNING] koLess: Reloading Skin
[2016-05-22 11:22:27,101] [WARNING] koLess: Clearing local and file cache
[2016-05-22 11:23:57,085] [WARNING] scc.history: could not load history results, exception: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsITreeSelection.select]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/scc/history.js :: _scc_history_dialog.prototype.load_history_for_url/async_callback.callback :: line 452"  data: no]
ERROR:xpcom:Unhandled exception calling 'int8 * addProjectAtPosition(in nsISomething, in int32);'
Traceback (most recent call last):
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koKPFTreeView.py", line 277, in addProjectAtPosition
    unwrapped_kpf = self._addProjectPrologue(kpf)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koKPFTreeView.py", line 300, in _addProjectPrologue
    self._tree.rowCountChanged(i, 1)
AttributeError: 'NoneType' object has no attribute 'rowCountChanged'
ERROR:xpcom:Unhandled exception calling 'S    int8 * currentProject(in nsISomething);'
Traceback (most recent call last):
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/server/policy.py", line 285, in _CallMethod_
    func(*params)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koKPFTreeView.py", line 404, in set_currentProject
    raise Exception("Add the project to the view before making it the current project")
Exception: Add the project to the view before making it the current project
[2016-05-22 11:24:00,970] [ERROR] open: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIKPFTreeView.currentProject]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo-places/content/project_places.js :: this.PlacesProjectManager.prototype.setCurrentProject :: line 75"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIKPFTreeView.currentProject]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo-places/content/project_places.js'
+ lineNumber (number) 75
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.PlacesProjectManager.prototype.setCurrentProject@chrome://komodo-places/content/project_places.'...748 chars
+ location (object) JS frame :: chrome://komodo-places/content/project_places.js :: this.PlacesProjectManager.prototype.setCurrentProject :: line 75
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo-places/content/project_places.js'
| + name (string) 'this.PlacesProjectManager.prototype.setCurrentProject'
| + lineNumber (number) 75
| + columnNumber (number) 8
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/project/projectManager.js :: projectManager.prototype.setCurrentProject :: line 1024
| + formattedStack (string) 'this.PlacesProjectManager.prototype.setCurrentProject@chrome://komodo-places/content/project_places.'...748 chars
| + stack
    this.PlacesProjectManager.prototype.setCurrentProject@chrome://komodo-places/content/project_places.js:75:8
    projectManager.prototype.setCurrentProject@chrome://komodo/content/project/projectManager.js:1024:8
    projectManager.prototype._addProject@chrome://komodo/content/project/projectManager.js:975:4
    projectManager.prototype.loadProject@chrome://komodo/content/project/projectManager.js:953:4
    project_openProjectFromURL@chrome://komodo/content/project/projectManager.js:1672:4
    open_openURIAtLine@chrome://komodo/content/library/open.js:157:12
    open_openURI@chrome://komodo/content/library/open.js:84:11
    viewMgrClass.prototype.onDblClick@chrome://komodo-places/content/places.js:193:16
    ondblclick@chrome://komodo-places/content/places_panel.xul:1:0
-- EXCEPTION END --
[2016-05-22 11:24:17,960] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-05-22 11:24:19,465] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:100:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-05-22 11:24:24,641] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

**Comment by Naatan** [comment]
Can you provide reproduction steps?

**Comment by Defman21** [comment]
It happens randomly for me when I'm working with ruby project

**Comment by Defman21** [comment]
If I'll find the steps I'll notify you

**Comment by Naatan** [comment]
I'll investigate this error, but unless that resolves the issue we will need more info.

```
[2016-05-22 11:24:00,970] [ERROR] open: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIKPFTreeView.currentProject]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo-places/content/project_places.js :: this.PlacesProjectManager.prototype.setCurrentProject :: line 75"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIKPFTreeView.currentProject]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo-places/content/project_places.js'
+ lineNumber (number) 75
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.PlacesProjectManager.prototype.setCurrentProject@chrome://komodo-places/content/project_places.'...748 chars
+ location (object) JS frame :: chrome://komodo-places/content/project_places.js :: this.PlacesProjectManager.prototype.setCurrentProject :: line 75
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo-places/content/project_places.js'
| + name (string) 'this.PlacesProjectManager.prototype.setCurrentProject'
| + lineNumber (number) 75
| + columnNumber (number) 8
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/project/projectManager.js :: projectManager.prototype.setCurrentProject :: line 1024
| + formattedStack (string) 'this.PlacesProjectManager.prototype.setCurrentProject@chrome://komodo-places/content/project_places.'...748 chars
| + stack
    this.PlacesProjectManager.prototype.setCurrentProject@chrome://komodo-places/content/project_places.js:75:8
    projectManager.prototype.setCurrentProject@chrome://komodo/content/project/projectManager.js:1024:8
    projectManager.prototype._addProject@chrome://komodo/content/project/projectManager.js:975:4
    projectManager.prototype.loadProject@chrome://komodo/content/project/projectManager.js:953:4
    project_openProjectFromURL@chrome://komodo/content/project/projectManager.js:1672:4
    open_openURIAtLine@chrome://komodo/content/library/open.js:157:12
    open_openURI@chrome://komodo/content/library/open.js:84:11
    viewMgrClass.prototype.onDblClick@chrome://komodo-places/content/places.js:193:16
    ondblclick@chrome://komodo-places/content/places_panel.xul:1:0
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
Are you still able to reproduce this?

**Comment by Defman21** [comment]
Nope.

**Comment by Naatan** [comment]
Leme know if you see this again and are able to reproduce.

**Comment by Defman21** [comment]
Yeah of course.

**Comment by shful** [comment]
Is this the same ? I see the trace with XDR magic number aud __globalPrefs is undefined when opening a file.
`Komodo Edit, version 10.1.1, build 17414, platform macosx. Built on Thu Sep 1 21:26:18 2016.`

Fresh installation, failed to open my 3rd file. Komodo Edit may have been in a bad state since Issue 1776 (could not close files) happened immediately before this error.

Could I provide something else ? Sadly, I cannot reproduce it currently.
Ruben

> [2016-09-14 15:48:57,762] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-09-14 16:01:00,466] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:516:17
    init@vieweditor:364:13
    newView@viewlistbase:502:17
    newView@viewmultiview:333:20
    createViewFromDocument@viewlistbase:119:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:20
-- EXCEPTION END --
[2016-09-14 16:01:03,902] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:608:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:732:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:757:20
-- EXCEPTION END --
[2016-09-14 16:02:27,981] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-09-14 16:02:27,981] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-09-14 16:02:27,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-09-14 16:02:27,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-09-14 16:02:27,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-09-14 16:02:27,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-09-14 16:02:27,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-09-14 16:02:27,983] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'

**Comment by Naatan** [comment]
Unfortunately unless someone has a reproducable case there isn't much we can do :(

**Comment by arnego2** [comment]
It happened to me just today, after going through some 22 files all in html + 3 css files Komodo was not able to open the next file in line, also html. 

By closing Komodo and going into the folder to open the html file supposedly unable to open and voila it opened and no more issues since. Could it be a cache which full?

**Comment by Naatan** [comment]
You effectively restarted Komodo, which is what is the known work around. Unfortunately it does not help us reproduce the problem so we can fix it.

**Comment by thatguypark** [comment]
I had the problem after a fresh download/install of Komodo Edit 11 on MacOSX.

A restarted did it for me, but considering I only opened 3 files before getting the error was daunting.  Though.....one thing that was odd that I did just before this issue happened, was that I tried closing my last open file before it happened, which wouldn't close.  I'm used to TextMate, in which you can close all open files (with the browser pane open) to get a blank screen.   I assume you can't do this in Komodo and need at least one file open?   Not sure is that's it, but might be of some help for this issue.
