### ISSUE TITLE
Preferences window subcategories break if loaded first

### ISSUE THREAD

**Issue by cyberbit** [Komodo/KomodoEdit#1598]
### Short Summary
The title is cryptic, but the issue is easy to reproduce. If a subcategory (**Editor > Smart Editing**, **Languages > PHP**, etc.) in Preferences is selected when the window is closed, the next load of Preferences tries to open at that subcategory, but fails and loads the first category instead. When navigating to the subcategory again, all the settings are blank.

FWIW, changing one of these settings, clicking OK, and reopening Preferences seems to fix the problem, but clears all the subcategory settings (save the changed one).

### Steps to Reproduce
1. Open the Preferences window.
2. Navigate to **Editor > Smart Editing**.
3. Click **Cancel**.
4. Open the Preferences window again.

### Expected results
The last opened subcategory is loaded normally.

### Actual results
The first subcategory is loaded, and the settings in the subcategory are blank.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* 10.0.0
*Operating System (and version)?* Windows 7

### Additional Information
After reopening Preferences:
![image](https://cloud.githubusercontent.com/assets/7350183/15508808/94560548-2196-11e6-8a6a-291be4119850.png)

After re-navigating to Editor > Smart Editing:
![image](https://cloud.githubusercontent.com/assets/7350183/15509048/a5d5ebd4-2197-11e6-9aea-3ccf3c45a828.png)

Note that the little arrow indicates that Editor is expanded, but it is not.

Full exception list:
```
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-05-24 09:48:37,655] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-05-24 09:48:37,655] [ERROR] prefs: Could not set widget 'widget-scheme' (pref ids 'widget-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-05-24 09:48:37,655] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-05-24 09:48:37,655] [ERROR] prefs: Could not set widget 'editor-scheme' (pref ids 'editor-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-05-24 09:48:37,655] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-05-24 09:48:37,655] [ERROR] prefs: Could not set widget 'interface-scheme' (pref ids 'interface-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-05-24 09:48:37,655] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-05-24 09:48:37,655] [ERROR] prefs: Could not set widget 'widget-scheme' (pref ids 'widget-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-05-24 09:48:37,655] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-05-24 09:48:37,655] [ERROR] prefs: Could not set widget 'editor-scheme' (pref ids 'editor-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-05-24 09:48:37,655] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-05-24 09:48:37,858] [ERROR] console-logger: XML or text declaration not at start of entity (0) in jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul:2
Traceback (most recent call last):
  File "jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul", line 2, in 
```

**Comment by cyberbit** [comment]
Reworded the title for slight clarity buff.

**Comment by Naatan** [comment]
Wow, awesome! We've been trying to figure out how this issue was happening for ages now. Thank you! :)

**Comment by Naatan** [comment]
Damnit, cannot reproduce this :( Can you still repro this @cyberbit ?

**Comment by cyberbit** [comment]
@Naatan Yup, using the same steps.

I do have a slight change for the workaround, though. If the Preferences window is loaded "normally" (not loading a subcategory), and a setting is changed (or just toggled back and forth) in the subcategory, and the dialog is saved, that subcategory **and all its siblings** start to work again.

I blame gremlins.

**Comment by Naatan** [comment]
Could you reproduce the error and share your full error log? Please restart Komodo beforehand so the error log is relatively clean.

**Comment by cyberbit** [comment]
Here you go! These are the steps I took in a fresh Safe Mode restart. It's very verbose, but I hope this narrows down the issue.

1. Use default settings for First Start.
2. Wait for Code Intelligence to preload.
3. Open Preferences via **Edit > Preferences**.
4. Navigate to **Editor > Smart Editing**.
5. Click **Cancel**.
6. Open Preferences via **Edit > Preferences**.
7. Open Error Log. Realize that the error didn't show up like before. (??)
8. Click **Cancel** in Preferences window.
9. Open Preferences again.
10. Navigate to **Smart Editing** again.
11. Click **Cancel** again.
12. Open Preferences for the _fourth_ time.
13. Copy all text from Error Log window.

And the results:
```
[2016-06-01 10:47:11,713] [INFO] Startup: Welcome to Komodo Edit 10.0.0 build 17209 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2016-06-01 10:47:11,713] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 10\lib\mozilla\komodo.exe built on Thu May 12 00:43:26 2016
[2016-06-01 10:47:12,313] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-06-01 10:47:12,713] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2016-06-01 10:47:12,714] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2016-06-01 10:47:12,920] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2016-06-01 10:47:14,115] [ERROR] console-logger: TypeError: redeclaration of variable val (2) in chrome://analytics/content/analytics.js:204
Traceback (most recent call last):
  File "chrome://analytics/content/analytics.js", line 204, in 

[2016-06-01 10:47:15,306] [WARNING] keybindings: [F1] was used for 'cmd_helpHelp', overriding to use 'cmd_toggleInteractiveShell'
[2016-06-01 10:47:15,306] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-06-01 10:47:16,565] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-06-01 10:47:16,880] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-06-01 10:47:19,779] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/components/koamAddonManager.js:138
[2016-06-01 10:47:19,779] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-06-01 10:47:19,905] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-06-01 10:47:20,076] [WARNING] commands: updateCommandset: cmdset_history
[2016-06-01 10:47:20,076] [WARNING] commands: updateCommandset: komodoFileSaveItems
[2016-06-01 10:47:20,076] [WARNING] commands: updateCommandset: cmdset_for_showHideMinimap
[2016-06-01 10:47:20,076] [WARNING] commands: updateCommandset: cmdset_cutcopydelete
[2016-06-01 10:47:20,076] [WARNING] commands: updateCommandset: cmdset_selection
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_view_codeintel_changed
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_view_or_language_changed
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_currentview_is_editor_on_html
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_view_dependent
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_undo
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_place_bufferOperations
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_place_treeOperations
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_markdown_previewability_changed
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_some_files_open
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_clipboard
[2016-06-01 10:47:20,092] [WARNING] commands: updateCommandset: cmdset_place_contextMenu
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-06-01 10:47:20,421] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-06-01 10:47:30,950] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-06-01 10:47:30,950] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-06-01 10:47:30,950] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-06-01 10:47:30,950] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-06-01 10:47:30,950] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-06-01 10:47:31,033] [WARNING] commands: updateCommandset: cmdset_projects_places
[2016-06-01 10:47:31,035] [WARNING] commands: updateCommandset: cmdset_place_bufferOperations
[2016-06-01 10:47:31,035] [WARNING] commands: updateCommandset: cmdset_place_treeOperations
[2016-06-01 10:47:31,036] [WARNING] commands: updateCommandset: cmdset_place_contextMenu
[2016-06-01 10:47:31,036] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:47:55,055] [WARNING] commands: updateCommandset: cmdset_clipboard
[2016-06-01 10:47:55,055] [WARNING] commands: updateCommandset: cmdset_place_contextMenu
[2016-06-01 10:48:08,792] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:08,792] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:10,441] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:10,441] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:12,345] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:12,361] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:24,446] [WARNING] commands: updateCommandset: cmdset_view_codeintel_changed
[2016-06-01 10:48:28,092] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:28,092] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:29,299] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:29,299] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:30,713] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:30,713] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:31,388] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:31,388] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:32,046] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:32,046] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:33,799] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:33,802] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:36,555] [ERROR] console-logger: XML or text declaration not at start of entity (0) in jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul:2
Traceback (most recent call last):
  File "jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul", line 2, in 

[2016-06-01 10:48:45,582] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:45,614] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:47,072] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:47,072] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:48,736] [ERROR] console-logger: XML or text declaration not at start of entity (0) in jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul:2
Traceback (most recent call last):
  File "jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul", line 2, in 

[2016-06-01 10:48:52,710] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:52,710] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:53,855] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:53,855] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:55,154] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:48:55,154] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:48:57,941] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2016-06-01 10:48:57,957] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2016-06-01 10:48:58,098] [WARNING] commands: updateCommandset: cmdset_undo
[2016-06-01 10:48:58,239] [WARNING] commands: updateCommandset: cmdset_undo
[2016-06-01 10:49:26,174] [WARNING] commands: updateCommandset: cmdset_clipboard
[2016-06-01 10:49:26,174] [WARNING] commands: updateCommandset: cmdset_place_contextMenu
[2016-06-01 10:49:30,874] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:49:30,874] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:49:32,430] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:49:32,430] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:49:33,895] [ERROR] console-logger: XML or text declaration not at start of entity (0) in jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul:2
Traceback (most recent call last):
  File "jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul", line 2, in 

[2016-06-01 10:49:51,378] [WARNING] commands: updateCommandset: cmdset_place_main
[2016-06-01 10:49:51,378] [WARNING] commands: updateCommandset: cmdset_openfiles
[2016-06-01 10:49:53,640] [ERROR] prefs: Could not set widget 'interface-scheme' (pref ids 'interface-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-06-01 10:49:53,640] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-06-01 10:49:53,640] [ERROR] prefs: Could not set widget 'widget-scheme' (pref ids 'widget-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-06-01 10:49:53,640] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-06-01 10:49:53,640] [ERROR] prefs: Could not set widget 'editor-scheme' (pref ids 'editor-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-06-01 10:49:53,640] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:104:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-06-01 10:49:53,640] [ERROR] prefs: Could not set widget 'interface-scheme' (pref ids 'interface-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-06-01 10:49:53,640] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-06-01 10:49:53,640] [ERROR] prefs: Could not set widget 'widget-scheme' (pref ids 'widget-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-06-01 10:49:53,640] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-06-01 10:49:53,640] [ERROR] prefs: Could not set widget 'editor-scheme' (pref ids 'editor-scheme') to values 'Default'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:417:27
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:563:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1

[2016-06-01 10:49:53,640] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._setElementFromPrefValue@chrome://komodo/content/pref/koPrefWindow.js:566:1
    koPrefWindow.prototype.onpageload@chrome://komodo/content/pref/koPrefWindow.js:1051:13
    initPanel@chrome://komodo/content/pref/koPrefWindow.js:112:5
    editsmart_OnLoad@chrome://komodo/content/pref/pref-editsmart.xul:109:9
    onload@chrome://komodo/content/pref/pref-editsmart.xul:1:1
-- EXCEPTION END --
[2016-06-01 10:49:53,842] [ERROR] console-logger: XML or text declaration not at start of entity (0) in jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul:2
Traceback (most recent call last):
  File "jar:file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%2010/lib/mozilla/distribution/bundles/places@activestate.com/places.jar!/content/pref_places.xul", line 2, in 

[2016-06-01 10:50:03,546] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-06-01 10:50:03,546] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-06-01 10:50:03,546] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-06-01 10:50:03,546] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-06-01 10:50:03,546] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-06-01 10:50:03,641] [WARNING] commands: updateCommandset: cmdset_selection
[2016-06-01 10:50:03,641] [WARNING] commands: updateCommandset: cmdset_clipboard
[2016-06-01 10:50:04,911] [WARNING] commands: updateCommandset: cmdset_selection
[2016-06-01 10:50:04,911] [WARNING] commands: updateCommandset: cmdset_clipboard
```

**Comment by Naatan** [comment]
Thank you @cyberbit!
