### ISSUE TITLE
Komodo 10 has a problem opening Komodo 8 projects

### ISSUE THREAD

**Issue by ESPlanner** [Komodo/KomodoEdit#1625]
I installed K10 on a MacBook Pro.  I've been using K8 for years but the Chrome integration was something I wanted for a project I'm working on.  I had no problem with K10 on Mac Pro tower.  What happens is that when I open a komodo project file nothing shows up in the projects pane.

### Steps to Reproduce

Open a project.

### Expected results

The project and it's directories should show up in the Project pane.

### Actual results

No project appears although K10 believes that it has opened the project (you can see the project name in the various menus).

### Platform Information

Komodo IDE, K10, Mavericks 10.11.5

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

[2016-05-28 06:50:20,578] [INFO] Startup: Welcome to Komodo IDE 10.0.0 build 89159 (platform macosx, running on Darwin 15.5.0 version Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64)
[2016-05-28 06:50:20,579] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Wed May 11 15:42:24 2016
[2016-05-28 06:50:20,677] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2016-05-28 06:50:21,003] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-05-28 06:50:21,044] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-05-28 06:50:21,261] [ERROR] console-logger: TypeError: redeclaration of variable val (2) in chrome://analytics/content/analytics.js:204
Traceback (most recent call last):
  File "chrome://analytics/content/analytics.js", line 204, in 

[2016-05-28 06:50:21,459] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-05-28 06:50:22,028] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-05-28 06:50:22,120] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-05-28 06:50:22,145] [INFO] komodospellchecker: Spell checker loaded.
[2016-05-28 06:50:22,145] [INFO] komodospellchecker: Using dictionary en-US
[2016-05-28 06:50:22,215] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-05-28 06:50:22,215] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-05-28 06:50:22,883] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2016-05-28 06:50:22,885] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2016-05-28 06:50:24,885] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-05-28 06:50:24,887] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-05-28 06:50:24,889] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-05-28 06:50:26,021] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138

**Comment by Defman21** [comment]
Did you mean Places pane (it's where you can use your files)? Also your log would be useful (Help - Troubleshooting - View Log File)

**Comment by ESPlanner** [comment]
Yeah, I just saw that part of the issue report and have updated the report.  Sorry about that.

**Comment by ESPlanner** [comment]
No, I mean the Projects pane (at least that's what it's labeled).  It's the one at the bottom of the left hand sidebar.

**Comment by Defman21** [comment]
Hmm, double-click on the header of this sub-pane to open it.

**Comment by ESPlanner** [comment]
Damn, that worked.  When I hovered over the title, it showed the "drag this to increase space" tool tip and I just assumed that was how you saw what was there.  It never occurred to me to try double clicking although I should have thought of it.  You might want to tweak the UI to make the double click thing a bit more obvious.  Thanks for the prompt response.

**Comment by Defman21** [comment]
Yeah, I agree, that's not obviously at all. However, there is an issue for it IIRC.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/1483
