### ISSUE TITLE
Breadcrumbs broken most of the time when using remote files

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#1635]
### Short Summary
I use the breadcrumb navigation very often, only in komodo 10 is broken most of the times.

### Steps to Reproduce
Open a file form a project with no local path

### Platform Information

Komodo Ide 10

### Additional Information
```
[2016-05-31 12:54:20,750] [ERROR] console-logger: TypeError: conn.list is not a function (2) in chrome://breadcrumbs/content/sdk/breadcrumbs.js:1546
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/sdk/breadcrumbs.js", line 1546, in 

[2016-05-31 12:54:26,980] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-31 12:54:26,982] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-05-31 12:55:28,803] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-05-31 12:55:29,023] [ERROR] console-logger: TypeError: conn.list is not a function (2) in chrome://breadcrumbs/content/sdk/breadcrumbs.js:1546
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/sdk/breadcrumbs.js", line 1546, in 

[2016-05-31 13:03:21,548] [ERROR] console-logger: Error: 'ftp://path/to/remote/directory' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-05-31 13:03:21,558] [ERROR] console-logger: Error: 'ftp://path/to/remote/directory' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-05-31 13:03:21,565] [ERROR] console-logger: Error: 'ftp://path/to/remote/directory' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 
```

**Comment by Naatan** [comment]
Fyi seems it breaks on remote files only, local files work fine.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/9eaba805634f51fc3b5f8c81abf84c5b5e9a40c9
