### ISSUE TITLE
Codeintel's Symbol Browser Will Not Work With Non-UTF8, Extended ASCII Paths

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#1700]
### Short Summary

Reference: http://forum.komodoide.com/t/code-browser-not-working/2857/10

It appears our apsw library cannot handle non-UTF8, extended ASCII characters in paths.
### Steps to Reproduce

Create a Komodo profile folder in a path that contains an extended ASCII character (e.g. `í`) and try to open a source file (any should do).
### Expected results

No problems with the symbol browser.
### Actual results

There's an error (see below). The symbol browser will not populate with that source file's contents.
### Platform Information

_Komodo Edit or IDE?_ Either
_Komodo Version?_ 10
_Operating System (and version)?_ Windows
### Additional Information

```
[2016-06-11 20:31:23,859] [ERROR] codeintel.oop.driver:
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\udl.py", line 483, in scan
    super(XMLParsingBufferMixin, self).scan(mtime, skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\database\multilanglib.py", line 871, in update_buf_data
    conn = self._get_symbols_db_conn()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 923, in _get_symbols_db_conn
    conn = apsw.Connection(symbols_db)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)
```

**Comment by mitchell-as** [comment]
Note: technically this is not limited to Windows, but since Linux and OSX have UTF-8-encoded filenames by default, they will not exhibit this issue as readily as Windows, which has a variable filesystem encoding.
