### ISSUE TITLE
Track changes failing w/ perforce project

### ISSUE THREAD

**Issue by concussiongfx** [Komodo/KomodoEdit#1750]
Project under perforce control does not display changes (v10.0.1). I tracked it down to a failure in koChangeTracker.py @ line 308. The string is missing %s

                else:
                    self.getDiskChangesAsync(handler, koDoc, koFile)
            except Exception as ex:
                log.exception("Exception while trying retrieve changes", ex)

**Comment by Naatan** [comment]
What happens when you change it to

```
            log.exception("Exception while trying retrieve changes: %s", ex) 
```

?

**Comment by concussiongfx** [comment]
Sorry, I should have stated that after changing the line to include %s, coloring worked. I do not see anything in the log w/ the above message, but I am seeing this:

`[2016-06-25 12:13:01,031] [ERROR] CT::tracker.js: Scc error P4LibError(u"Error 1 running '/usr/local/bin/p4 -d /**REMOVED** print -q shapeLayer.py': \nPerforce client error:\n\tConnect to server failed; check $P4PORT.\n\tTCP connect to perforce:**REMOVES** failed.\n\tnodename nor servname provided, or not known\n",)
Traceback from ERROR in 'CT::tracker.js' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:379:27
    exports.ChangeTracker.prototype.onError@chrome://trackchanges/content/tracker.js:200:5`

All SCC functionality appears to be working, so I am not sure why this is failing.

**Comment by concussiongfx** [comment]
also after fiddling around with UI colors the tracker stops working and I see this:

`[2016-06-25 12:09:19,389] [ERROR] koChangeTracker: Exception while trying retrieve changes: 'koDocumentBase' object has no attribute 'displayPath'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/extensions/trackchanges@activestate.com/components/koChangeTracker.py", line 304, in updateChangeTracker
    self.getSccChangesAsync(handler)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/extensions/trackchanges@activestate.com/components/koChangeTracker.py", line 265, in getSccChangesAsync
    self.clearPendingSccRequest()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/extensions/trackchanges@activestate.com/components/koChangeTracker.py", line 87, in clearPendingSccRequest
    self.koDoc.displayPath)
AttributeError: 'koDocumentBase' object has no attribute 'displayPath'`

**Comment by Naatan** [comment]
Does P4 work for you elsewhere in the UI? eg. the commit dialog? It sounds like it is not properly configured, and you need to set `P4PORT` in your `Preferences > Environment` prefs.

**Comment by tonyattwood** [comment]
Hello,

Here is the list of  upcoming events you may be interested in, you  may find more  information  here  <http://expert.seocostaricaexperts.com/e4nsghyw>

Speak to you later, tony.attwood@ntlworld.com

**Comment by concussiongfx** [comment]
Most of P4 looks to be working. I have not tried committing from komodo, but change notification, reverting, checking out ect all work. I do sometimes get into a situation where P4 can not check out files and this is the only time that the track changes feature works. So it appears that when P4 breaks, track changes works and when P4 is working, track changes does not.

**Comment by cgchoffman** [comment]
Sounds like when P4 is broken then Komodo reverts to using the second level of Track Changes; Show all changes since last change.   Did you try @Naatan's suggestion about configuring `P4PORT` in your prefs?

**Comment by concussiongfx** [comment]
I have P4PORT, P4CLIENT,P4PASSWD and P4USER all set in project prefs. Would it make a difference if it was set in the global prefs?

**Comment by cgchoffman** [comment]
It shouldn't but that doesn't mean there isn't a bug.  Give it a try.

**Comment by concussiongfx** [comment]
Moving all of the above vars to the global prefs fixes things, so there is definitely a bug w/ loading them from the project.

**Comment by cgchoffman** [comment]
That's great!...I mean that's very helpful.  Thanks for updating!

**Comment by cgchoffman** [comment]
I'm not actually able to reproduce.  To try and mimic the issue, without having to setup a P4 repo, I did the following:
1. Restarted in Safe mode (you know, to be safe)
2.  Created a batch file in a random folder
3. Created a project in an unrelated folder
4. Added the location of that batch to my Project > Prefs > Env: PATH
5. Open Commando > Shell: Enter the name of the batch file and execute

The file runs fine.  So Komodo is picking up the Environment prefs in my project just fine.  So perhaps the fact that moving your prefs from Project to global is just a red herring.  Does the issue persist if you revert back to the original configuration? ie. prefs only set in project?

**Comment by concussiongfx** [comment]
With the vars moved to global, I see:
- Version control tab show my current changed files / history
- I see file states in places / tabs
- saving a file checks it out
- If I open a modified file, track changes shows what has changed.

Moving the vars back to project and restart:
- Version control tab show my current changed files / history
- I see file states in places / tabs
- saving a file checks it out
- If I open a modified file, track changes DOES NOT show what has changed.

**Comment by cgchoffman** [comment]
Thanks again for double checking.  Will require more digging into P4 I guess.  Glad it's working for you now at least @concussiongfx.

**Comment by concussiongfx** [comment]
I did a little more digging today and found some more info. It does looks like most of the project P4* variables are not being used. I started moving vars one at a time and saw the following results.

- moved P4PORT first: checkout error that my user name was incorrect. P4 was using my computer login instead of the P4USER var still in project prefs
- moved P4USER: checkout error, unknown workspace
- moved P4CLIENT: no P4 error, but the file was not being checked out and remained locked
- Restarted Komodo, everything works. The only var left in project prefs is the P4 password.
