### ISSUE TITLE
Error when opening KOMODO cannot find path

### ISSUE THREAD

**Issue by tunedin76** [Komodo/KomodoEdit#1801]
### Short Summary

Error cannot find path when opening Komodo IDE 10
### Steps to Reproduce

Leave a project with a remote directory open with a couple of files in tabs - close Komodo 10 IDE - Reopen and "cannot find path"
### Expected results

no error
### Actual results

error
### Platform Information

Komodo IDE 10 on Win 10 Pro
### Additional Information

![capture](https://cloud.githubusercontent.com/assets/16789318/16807436/6130477e-48e6-11e6-918a-abe99ce706c1.PNG)

[error logs.zip](https://github.com/Komodo/KomodoEdit/files/361693/error.logs.zip)

**Comment by cgchoffman** [comment]
Can you determine if there is anything special about your setup?  I don't know what that path would be.  Does it makes sense for the remote connection it's attempting to make?

**Comment by tunedin76** [comment]
The error only happens if I leave the project open.. I get no error when I close the project before shutdown.  

If I close the project, the FTP (remote) folder still remains in folder view, and is there upon restart - with no error. I can open any file remotely from that window at restart no problem - so it is connecting without opening the project (no issue - just FYI)

The track/functions folder is there - it is a correct path.

**Comment by cgchoffman** [comment]
Did this just start happenings?  Did you make any changes recently before this occurred?  Have you tried any of the work around steps under *Help > Troubleshooting*?

Along with those steps, if you're using a Komodo project file you could try creating a new one and seeing if the issue continues.

**Comment by tunedin76** [comment]
It has been happening since purchase... I have tried the steps and I have tried erasing all my project files.  It's no big deal... I just wanted to make you aware

**Comment by cgchoffman** [comment]
yep, now we need to narrow it down so we can reproduce it.  So none of the workaround steps stopped the issue?  No matter what, if you tried to restart Komodo with the project with a remote folder open it would give that error?  I'm not able to reproduce the alert doing the following:
- create a project
- Right click > Add > Existing remote folder
- save the project
- Open that folder in Komodo and a file from that folder
- close Komodo and restart it

I don't get an alert but I do have these errors in the logs that shouldn't be happening:
```
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2016-07-14 09:03:24,250] [ERROR] console-logger: Error: 'sftp://stackato-1/home/stackato/blorp' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in
```

**Comment by babobski** [comment]
@cgchoffman I get this error also a lot, when I open an new window or on start of Komodo:
![2016-08-05 09_05_05](https://cloud.githubusercontent.com/assets/3530262/17428973/5a6f9d96-5aec-11e6-8b2f-75a54fea9e63.jpg)

I got these errors in my log:
```
ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: sccType
ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: sccType
[2016-08-05 09:07:05,720] [ERROR] console-logger: Error: 'null' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-08-05 09:07:05,736] [ERROR] console-logger: Error: 'null' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-08-05 09:07:05,736] [ERROR] console-logger: Error: 'null' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-08-05 09:07:06,299] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileStatusService.py", line 466, in _process
    if u.isLocal and not u.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2016-08-05 09:07:06,315] [ERROR] koFileStatusService: Exception checking uri: None
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileStatusService.py", line 621, in _process
    reason):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\fileStatusUtils.py", line 250, in updateFileStatus
    if koIFile.isLocal and not koIFile.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2016-08-05 09:07:06,315] [ERROR] koFileStatusService: Exception detail: AttributeError('isLocal',)
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileStatusService.py", line 621, in _process
    reason):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\fileStatusUtils.py", line 250, in updateFileStatus
    if koIFile.isLocal and not koIFile.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2016-08-05 09:07:06,331] [ERROR] koFileStatusService: KoFileStatusService thread exception Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileStatusService.py", line 590, in _process
    reason):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\extensions\publishing@ActiveState.com\components\koPublishingStatus.py", line 164, in needsToReCheckFileStatus
    uri_cache_key = self._norm_uri_cache_key(koFile.URI)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\fileStatusUtils.py", line 107, in _norm_uri_cache_key
    uri = unescapeURL(uri).strip("/")
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\python\lib\urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'

[2016-08-05 09:07:06,596] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileStatusService.py", line 466, in _process
    if u.isLocal and not u.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2016-08-05 09:07:07,408] [ERROR] console-logger: Error: 'ftp://Remote Server/httpdocs' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-08-05 09:07:07,408] [ERROR] console-logger: Error: 'ftp://Remote Server/httpdocs' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2016-08-05 09:07:07,424] [ERROR] console-logger: Error: 'ftp://Remote Server/httpdocs' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

```

The places widget is working ( it will open the remote list ) only the title bar remains empty, when I now click on the project the title bar is showing:
![2016-08-05 09_12_52](https://cloud.githubusercontent.com/assets/3530262/17429617/dbbc5f8a-5aef-11e6-93b2-25a4fc5194dc.jpg)

Looks like It try's to open the url while it is not available
```
[2016-08-05 09:07:05,720] [ERROR] console-logger: Error: 'null' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 
```

When I click on the project, the url is not null
```
[2016-08-05 09:07:07,408] [ERROR] console-logger: Error: 'ftp://Remote Server/httpdocs' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 
```
