### ISSUE TITLE
Logic problem when pressing enter in file with only line endings

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#188]
Create a PHP file, press enter a few times, this error will occur in your log, and you will be spammed by notifications:

```
[2015-04-17 12:04:16,712] [ERROR] koCodeIntel: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/oop/codebrowser.py", line 126, in do_locate_scope
    blob, lpath = buf.scoperef_from_pos(pos) or (None, None)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/accessor.py", line 163, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko9.10/mozilla/ko-rel/dist/bin/python/komodo/codeintel2/accessor.py", line 159, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
```

@toddw-as any advice?

**Comment by mitchell-as** [comment]
I cannot reproduce this. Does this still happen for you @Naatan?

**Comment by Naatan** [comment]
Still happening. I just created a blank PHP file (saved it as test.php) and started pressing enter.

**Comment by Defman21** [comment]
I also cannot reproduce it on Linux. Created a blank php file (saved it as `WORK.php`) and after I saved it I started pressing enter as a crazy man that loves Enter. Here's my log:
```
[2015-08-10 20:08:22,507] [INFO] Startup: Welcome to Komodo IDE 9.2.1 build 87631 (platform linux-x86_64, running on Linux 3.19.0-25-generic version #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015)
[2015-08-10 20:08:22,507] [INFO] Startup: /usr/bin/python built on Fri Aug 7 15:36:37 2015
[2015-08-10 20:08:22,998] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-08-10 20:08:23,005] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///home/defman/.komodoide/9.2/XRE/extensions/emmet@chikuyonok.ru.xpi!/chrome.manifest:1
[2015-08-10 20:08:23,006] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///home/defman/.komodoide/9.2/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///home/defman/.komodoide/9.2/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2015-08-10 20:08:23,006] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///home/defman/.komodoide/9.2/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2015-08-10 20:08:23,018] [ERROR] koResolve: File uri could not be resolved: less://komodo/skin/platform.less
[2015-08-10 20:08:23,045] [WARNING] console-logger: Unknown pseudo-class or pseudo-element 'moz-tree-cell'.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/komodo.css:14
[2015-08-10 20:08:23,046] [WARNING] console-logger: Expected end of selector or a user action pseudo-class after pseudo-element but found 'description'.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/komodo.css:211
[2015-08-10 20:08:23,086] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-08-10 20:08:23,755] [WARNING] console-logger: Unknown pseudo-class or pseudo-element 'moz-tree-cell'.  Ruleset ignored due to bad selector. (1) in chrome://global/skin/global.css:11
[2015-08-10 20:08:23,755] [WARNING] console-logger: Expected end of selector or a user action pseudo-class after pseudo-element but found 'description'.  Ruleset ignored due to bad selector. (1) in chrome://global/skin/global.css:208
[2015-08-10 20:08:23,803] [ERROR] koManifestLoader: Filename should be 'chrome.manifest'
[2015-08-10 20:08:23,806] [ERROR] koManifestLoader: Filename should be 'chrome.manifest'
[2015-08-10 20:08:24,454] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2015-08-10 20:08:24,872] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-08-10 20:08:24,873] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-08-10 20:08:24,873] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -4 (min 1)
[2015-08-10 20:08:24,874] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-08-10 20:08:25,276] [DEBUG] editorconfig: Setting editorconfig: {}
[2015-08-10 20:08:25,915] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-08-10 20:08:26,007] [ERROR] console-logger: TypeError: Argument 2 of EventTarget.addEventListener is not an object. (2) in chrome://todo/content/todo-ko7.js:582
Traceback (most recent call last):
  File "chrome://todo/content/todo-ko7.js", line 582, in 

[2015-08-10 20:08:26,473] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for HTML5
[2015-08-10 20:08:26,474] [WARNING] koLanguage: Asked for unknown language: 'None'
[2015-08-10 20:08:26,635] [ERROR] koDBConnSqlite3: Failed: OperationalError(OperationalError('unable to open database file',),)
[2015-08-10 20:08:28,153] [INFO] komodospellchecker: Spell checker loaded.
[2015-08-10 20:08:28,153] [INFO] komodospellchecker: Using dictionary en-US
[2015-08-10 20:08:28,234] [WARNING] koLess: Reloading Skin
[2015-08-10 20:08:28,235] [WARNING] koLess: Clearing local and file cache
[2015-08-10 20:08:28,926] [WARNING] koLess: Reloading Skin
[2015-08-10 20:08:29,211] [WARNING] console-logger: Unknown pseudo-class or pseudo-element 'moz-tree-cell'.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/komodo.css:14
[2015-08-10 20:08:29,211] [WARNING] console-logger: Expected end of selector or a user action pseudo-class after pseudo-element but found 'description'.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/komodo.css:211
[2015-08-10 20:08:29,212] [WARNING] console-logger: Unknown pseudo-class or pseudo-element 'moz-tree-cell'.  Ruleset ignored due to bad selector. (1) in chrome://global/skin/global.css:11
[2015-08-10 20:08:29,212] [WARNING] console-logger: Expected end of selector or a user action pseudo-class after pseudo-element but found 'description'.  Ruleset ignored due to bad selector. (1) in chrome://global/skin/global.css:208
[2015-08-10 20:08:29,469] [WARNING] console-logger: Unknown pseudo-class or pseudo-element 'moz-tree-cell'.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/komodo.css:14
[2015-08-10 20:08:29,470] [WARNING] console-logger: Expected end of selector or a user action pseudo-class after pseudo-element but found 'description'.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/komodo.css:211
[2015-08-10 20:08:29,471] [WARNING] console-logger: Unknown pseudo-class or pseudo-element 'moz-tree-cell'.  Ruleset ignored due to bad selector. (1) in chrome://global/skin/global.css:11
[2015-08-10 20:08:29,471] [WARNING] console-logger: Expected end of selector or a user action pseudo-class after pseudo-element but found 'description'.  Ruleset ignored due to bad selector. (1) in chrome://global/skin/global.css:208
[2015-08-10 21:42:26,607] [WARNING] console-logger: Key event not available on some keyboard layouts: key="q" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:26,608] [WARNING] console-logger: Key event not available on some keyboard layouts: key="a" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:26,610] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:26,611] [WARNING] console-logger: Key event not available on some keyboard layouts: key="e" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:26,612] [WARNING] console-logger: Key event not available on some keyboard layouts: key="c" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:26,613] [WARNING] console-logger: Key event not available on some keyboard layouts: key="p" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:26,614] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-08-10 21:42:32,889] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2015-08-10 21:42:33,150] [ERROR] console-logger: TypeError: dirtyIndicator is null (2) in chrome://openfiles/content/openfiles.js:526
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 526, in 

[2015-08-10 21:42:33,154] [ERROR] console-logger: TypeError: dirtyIndicator is null (2) in chrome://openfiles/content/openfiles.js:530
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 530, in 

[2015-08-10 21:42:33,346] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:33,371] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:33,846] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:33,868] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:33,878] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:33,897] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:37,720] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:37,742] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:37,856] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:37,878] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:38,678] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:38,698] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:39,822] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:39,843] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:39,976] [ERROR] AutoTriggerDoc: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js" line: 2874}]' when calling method: [ISciMoz::getTextRange]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "Error calling method on NPObject!" {file: "file:///home/defman/Komodo-IDE-9/lib/'...347 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
+ lineNumber (number) 78
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/project/peMacro.js line 696 > Function :: anonymous/</this.onKeyPress :: line 78
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/peMacro.js line 696 > Function'
| + name (string) 'anonymous/</this.onKeyPress'
| + lineNumber (number) 78
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'anonymous/</this.onKeyPress@chrome://komodo/content/project/peMacro.js line 696 > Function:78:30
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-08-10 21:42:39,995] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js:2874
Traceback (most recent call last):
  File "file:///home/defman/Komodo-IDE-9/lib/mozilla/components/scimoz_wrapper.js", line 2874, in 

[2015-08-10 21:42:44,886] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-08-10 21:44:36,198] [WARNING] console-logger: Key event not available on some keyboard layouts: key="q" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-08-10 21:44:36,199] [WARNING] console-logger: Key event not available on some keyboard layouts: key="a" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-08-10 21:44:36,200] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-08-10 21:44:36,201] [WARNING] console-logger: Key event not available on some keyboard layouts: key="e" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-08-10 21:44:36,201] [WARNING] console-logger: Key event not available on some keyboard layouts: key="c" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-08-10 21:44:36,202] [WARNING] console-logger: Key event not available on some keyboard layouts: key="p" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-08-10 21:44:36,203] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by Naatan** [comment]
Fairly certain this is the same issue as https://github.com/Komodo/KomodoEdit/issues/64#issuecomment-129552986, and it's caused by something in my profile.
