### ISSUE TITLE
Exception while registering Focus Mode

### ISSUE THREAD

**Issue by Dummbroesel** [Komodo/KomodoEdit#1895]
### Short Summary

Komodo seems to be crashing random when I'm using it, most likely if I tab in and out.

### Steps to Reproduce

Tab in and out. The crash appears more often when I use projects and have more as one window open.

### Platform Information

I am using Komodo Edit  
Komodo Edit, version 10.0.1, build 17276
Mac OS X 10.9.5

### Additional Information

[2016-08-04 09:52:26,699] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Awesomeuser/Desktop/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Awesomeuser/Desktop/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2016-08-04 09:52:26,700] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Awesomeuser/Desktop/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Users/Awesomeuser/Desktop/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[pystderr.txt](https://github.com/Komodo/KomodoEdit/files/401147/pystderr.txt)

**Comment by Defman21** [comment]
FocusMode is not related to your crashes but the error mostly appears in broken installations.

You may want to see #1007 for more info about crashes. There you can find a way of running Komodo in debug verbose mode which may help the developers find the problem.

**Comment by mitchell-as** [comment]
We're tracking random crashes (including the ones caused by tab in and tab out) in #1007. Please provide any additional information there. Thanks!
