### ISSUE TITLE
color scheme reloaded with out me opening color scheme editor

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1926]
### Short Summary

I just updated my keybindings then 'ok'd out of the prefs dialog.  Komodo then proceeded to reload my color scheme, that doesn't look like the one I thought I had loaded.

I reopened the color scheme editor and my `Default Mod` Scheme is still selected.  I re-applied and things are back to normal....i should have taken a screenshot...darn!

#### relevant logs
```

[2016-08-12 14:33:52,812] [WARNING] prefs: The '3' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,812] [WARNING] prefs: The 'hasFocus' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,815] [WARNING] prefs: The 'opened_projects_v7' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,815] [WARNING] prefs: The 'current_project' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,822] [WARNING] prefs: The 'topview' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,822] [WARNING] prefs: The 'windowNum' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,823] [WARNING] prefs: The 'restoreOnRestart' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,825] [WARNING] prefs: The 'timestamp' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,825] [WARNING] prefs: The 'history_rctabs' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,825] [WARNING] prefs: The 'rctabs_list' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:34:08,250] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-08-12 14:34:08,894] [WARNING] koLess: Reloading Skin
[2016-08-12 14:34:08,894] [WARNING] koLess: Clearing local and file cache
[2016-08-12 14:34:30,792] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

#### full logs

```
[2016-08-12 14:17:31,082] [INFO] Startup: Welcome to Komodo IDE 10.1.0-beta1 build 89417 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2016-08-12 14:17:31,082] [INFO] Startup: C:\Users\careyh\Komodo IDE Latest\lib\mozilla\komodo.exe built on Fri Aug 12 08:59:49 2016
[2016-08-12 14:17:39,043] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-08-12 14:17:39,091] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2016-08-12 14:17:39,095] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2016-08-12 14:17:40,016] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-08-12 14:17:43,456] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-08-12 14:17:47,815] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-08-12 14:17:48,989] [INFO] komodospellchecker: Spell checker loaded.
[2016-08-12 14:17:48,989] [INFO] komodospellchecker: Using dictionary en-US
[2016-08-12 14:17:52,164] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-08-12 14:17:52,184] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-08-12 14:17:55,563] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Users/careyh/Komodo%20IDE%20Latest/lib/mozilla/components/koamAddonManager.js:138
[2016-08-12 14:17:56,266] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-08-12 14:17:56,316] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-08-12 14:17:56,683] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-08-12 14:20:27,313] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-08-12 14:20:27,315] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-08-12 14:20:27,315] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-08-12 14:20:27,315] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-08-12 14:20:27,316] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-08-12 14:21:15,286] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-08-12 14:21:15,288] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-08-12 14:21:16,493] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-08-12 14:21:16,494] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-08-12 14:22:10,012] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-08-12 14:22:10,012] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-08-12 14:22:11,217] [WARNING] scc.history: could not load history results, exception: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsITreeSelection.select]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/scc/history.js :: _scc_history_dialog.prototype.load_history_for_url/async_callback.callback :: line 463"  data: no]
[2016-08-12 14:22:11,398] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-08-12 14:22:11,400] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-08-12 14:32:52,907] [WARNING] codeintel.db: database corruption during 'LangZone.remove_path': could not read blob_index for 'c:\users\careyh\projects\komodo\komodoide\src\components' dir: `C:\Users\careyh\AppData\Local\ActiveState\KomodoIDE\10.1\codeintel\db\python\c9fa77c02571e580c10a9711f1dfad02\blob_index' does not exist (resolution: recover)
[2016-08-12 14:32:52,917] [WARNING] codeintel.db: database corruption during 'LangZone.remove_path': 'kowindowsintegration.p' blob not in 'c9fa77c02571e580c10a9711f1dfad02\blob_index' (resolution: ignore)
[2016-08-12 14:32:52,921] [ERROR] codeintel.oop.driver: c9fa77c02571e580c10a9711f1dfad02\blob_index
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 626, in handleRequest
    meth(request, driver)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 889, in do_get_sections
    sections = buf.get_sections()
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 411, in get_sections
    return self.cached_sections
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 198, in blob_from_lang
    self._load_buf_data_once()
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 805, in get_buf_data
    self.remove_buf_data(buf)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 905, in remove_buf_data
    self.remove_path(buf.path)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 895, in remove_path
    self.changed_index(dir, "blob_index")
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1261, in changed_index
    self._index_and_atime_from_dbsubpath[dbsubpath][1] = now
KeyError: 'c9fa77c02571e580c10a9711f1dfad02\\blob_index'
[2016-08-12 14:32:53,091] [ERROR] koCodeIntel: c9fa77c02571e580c10a9711f1dfad02\blob_index
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 626, in handleRequest
    meth(request, driver)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 889, in do_get_sections
    sections = buf.get_sections()
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 411, in get_sections
    return self.cached_sections
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 198, in blob_from_lang
    self._load_buf_data_once()
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 805, in get_buf_data
    self.remove_buf_data(buf)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 905, in remove_buf_data
    self.remove_path(buf.path)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 895, in remove_path
    self.changed_index(dir, "blob_index")
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1261, in changed_index
    self._index_and_atime_from_dbsubpath[dbsubpath][1] = now
KeyError: 'c9fa77c02571e580c10a9711f1dfad02\\blob_index'

[2016-08-12 14:32:53,168] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 626, in handleRequest
    meth(request, driver)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 911, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 916, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 320, in scoperef_from_pos
    blob = self.blob_from_lang[self.lang]
TypeError: 'NoneType' object has no attribute '__getitem__'
[2016-08-12 14:32:53,318] [ERROR] koCodeIntel: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 626, in handleRequest
    meth(request, driver)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 911, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 916, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "C:\Users\careyh\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 320, in scoperef_from_pos
    blob = self.blob_from_lang[self.lang]
TypeError: 'NoneType' object has no attribute '__getitem__'

[2016-08-12 14:33:52,812] [WARNING] prefs: The '3' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,812] [WARNING] prefs: The 'hasFocus' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,815] [WARNING] prefs: The 'opened_projects_v7' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,815] [WARNING] prefs: The 'current_project' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,822] [WARNING] prefs: The 'topview' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,822] [WARNING] prefs: The 'windowNum' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,823] [WARNING] prefs: The 'restoreOnRestart' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,825] [WARNING] prefs: The 'timestamp' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,825] [WARNING] prefs: The 'history_rctabs' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:33:52,825] [WARNING] prefs: The 'rctabs_list' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-12 14:34:08,250] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-08-12 14:34:08,894] [WARNING] koLess: Reloading Skin
[2016-08-12 14:34:08,894] [WARNING] koLess: Clearing local and file cache
[2016-08-12 14:34:30,792] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-08-12 14:35:02,447] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-08-12 14:35:02,448] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-08-12 14:35:02,450] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-08-12 14:35:02,450] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-08-12 14:35:02,450] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by Naatan** [comment]
Reproducible? Steps to reproduce?

**Comment by cgchoffman** [comment]
> I just updated my keybindings then 'ok'd out of the prefs dialog. Komodo then proceeded to reload my color scheme, that doesn't look like the one I thought I had loaded.

First paragraph in the summary.  If you can't reproduce then feel free to close.  I can't.  Prefs always does weird things like this; saving prefs that were never opened in my session.

**Comment by Naatan** [comment]
I'm not able to reproduce this either.
