### ISSUE TITLE
Drag and drop file on dock icon results in half instantiated view that can't be closed

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#1954]
### Short Summary

I think this might only be an issue in OSX as it's not supported on Windows.  I'm not sure how Linux handles it.  It should either work or do nothing.  Atom seems to handle it fine so I'm leaning towards the former.

### Steps to Reproduce

Drag a file from Finder onto the Komodo icon in the Dock

### Expected results

File opens in Komodo

### Actual results

Komodo opens an error dialog that says " Komodo couldn't open file *file.name*" but there is no error.    There is now a partially instantiated view open that cannot be closed.  

### Additional Information

```
[2016-08-18 11:48:50,164] [INFO] Startup: Welcome to Komodo IDE 10.1.0 build 89453 (platform macosx, running on Darwin 15.6.0 version Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64)
[2016-08-18 11:48:50,164] [INFO] Startup: /Applications/Komodo IDE 10.1-rc1.app/Contents/MacOS/komodo built on Wed Aug 17 08:53:21 2016
[2016-08-18 11:48:50,521] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-08-18 11:48:51,070] [ERROR] console-logger: ReferenceError: require is not defined (2) in chrome://komodo/content/bindings/windows.xml:41
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 41, in 

[2016-08-18 11:48:51,092] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-08-18 11:48:51,757] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2016-08-18 11:48:52,166] [ERROR] ko.main: 
-- EXCEPTION START --
TypeError: ko.toolbox2 is undefined
+ stack
    uilayout_onload@chrome://komodo/content/library/uilayout.js:1843:13
    onloadDelay@chrome://komodo/content/komodo.js:429:9
    window.onload/<@chrome://komodo/content/komodo.js:563:13
-- EXCEPTION END --
[2016-08-18 11:48:52,241] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-08-18 11:48:52,321] [INFO] komodospellchecker: Spell checker loaded.
[2016-08-18 11:48:52,322] [INFO] komodospellchecker: Using dictionary en-US
[2016-08-18 11:48:53,476] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.1-rc1.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.1-rc1.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2016-08-18 11:48:53,483] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.1-rc1.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.1-rc1.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2016-08-18 11:48:54,291] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.1-rc1.app/Contents/Resources/components/koamAddonManager.js:138
[2016-08-18 11:48:55,963] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-08-18 11:48:55,965] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-08-18 11:48:55,967] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-08-18 11:49:08,371] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-08-18 11:49:08,375] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-08-18 11:53:02,914] [WARNING] views: Inconsistent view count in view_closed event
[2016-08-18 11:53:03,015] [WARNING] views: Inconsistent view count in view_opened event
[2016-08-18 11:53:10,128] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2016-08-18 11:58:15,861] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2016-08-18 11:58:18,254] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2016-08-18 12:02:32,700] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2016-08-22 12:06:04,738] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-08-22 12:07:05,135] [WARNING] prefs: The '1' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,136] [WARNING] prefs: The 'hasFocus' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,138] [WARNING] prefs: The 'opened_projects_v7' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,141] [WARNING] prefs: The 'topview' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,141] [WARNING] prefs: The 'windowNum' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,141] [WARNING] prefs: The 'restoreOnRestart' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,142] [WARNING] prefs: The 'timestamp' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,142] [WARNING] prefs: The 'history_rctabs' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:05,143] [WARNING] prefs: The 'rctabs_list' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-08-22 12:07:16,810] [WARNING] koLess: Reloading Skin
[2016-08-22 12:07:16,810] [WARNING] koLess: Clearing local and file cache
[2016-08-22 12:07:17,838] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2016-08-22 12:07:17,838] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2016-08-22 12:07:17,857] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2016-08-22 12:07:24,586] [WARNING] views: Inconsistent view count in view_closed event
[2016-08-22 12:07:24,725] [WARNING] views: Inconsistent view count in view_opened event
[2016-08-22 12:07:47,773] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-08-22 12:07:51,146] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:100:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-08-22 12:07:57,001] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1254
Traceback (most recent call last):
  File "vieweditor", line 1254, in 

[2016-08-22 12:07:58,487] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1254
Traceback (most recent call last):
  File "vieweditor", line 1254, in 

[2016-08-22 12:08:00,020] [WARNING] views: Inconsistent view count in view_closed event
[2016-08-22 12:08:00,023] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.currentView.makeCurrent is not a function
+ stack
    removeView@viewtabbedlist:175:21
    close@view-quickstart:209:21
    onxblmouseup@chrome://komodo/content/bindings/scrolltabs.xml:78:21
-- EXCEPTION END --
[2016-08-22 12:08:01,411] [ERROR] commands: An error occurred executing the cmd_bufferClose command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.currentView.close is not a function" {file: "chrome://komodo/content/views.js" line: 1338}]'[JavaScript Error: "this.currentView.close is not a function" {file: "chrome://komodo/content/views.js" line: 1338}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.currentView.close is not a function" {file: "chrome://komodo/content/views.'...282 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 239
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 239
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 191
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-08-22 12:08:01,416] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2016-08-22 12:08:01,420] [ERROR] console-logger: TypeError: this.currentView.close is not a function (2) in chrome://komodo/content/views.js:1338
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 1338, in 

[2016-08-22 12:08:02,583] [ERROR] commands: An error occurred executing the cmd_bufferClose command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.currentView.close is not a function" {file: "chrome://komodo/content/views.js" line: 1338}]'[JavaScript Error: "this.currentView.close is not a function" {file: "chrome://komodo/content/views.js" line: 1338}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.currentView.close is not a function" {file: "chrome://komodo/content/views.'...282 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 239
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 239
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 191
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-08-22 12:08:02,590] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2016-08-22 12:08:02,595] [ERROR] console-logger: TypeError: this.currentView.close is not a function (2) in chrome://komodo/content/views.js:1338
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 1338, in 

[2016-08-22 12:08:13,910] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-08-22 12:08:15,521] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:100:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-08-22 12:08:17,736] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1254
Traceback (most recent call last):
  File "vieweditor", line 1254, in 

[2016-08-22 12:08:18,584] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1254
Traceback (most recent call last):
  File "vieweditor", line 1254, in 

[2016-08-22 12:08:18,797] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1254
Traceback (most recent call last):
  File "vieweditor", line 1254, in 

[2016-08-22 12:08:18,978] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1254
Traceback (most recent call last):
  File "vieweditor", line 1254, in 

[2016-08-22 12:08:20,473] [ERROR] view.multiview: 
-- EXCEPTION START --
TypeError: this._koDoc is null
+ stack
    getState@vieweditor:1899:1
    getState@viewtabbedlist:358:28
    getState@viewmultiview:391:29
    _saveWorkspaceForIdx_aux@chrome://komodo/content/workspace.js:590:16
    view_saveWorkspace@chrome://komodo/content/workspace.js:661:1
-- EXCEPTION END --
[2016-08-22 12:13:11,985] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-08-22 12:13:49,131] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:100:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-08-22 12:13:55,103] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

**Comment by Naatan** [comment]
I cannot reproduce this.

Judging by the log something went wrong earlier on, the issue you're reporting is just fallout from this.

Please reopen if you can reproduce, but I doubt you will be able to. Keep an eye out for this error in the future:

```
[2016-08-22 12:07:47,773] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
```

**Comment by cgchoffman** [comment]
Confirmed.  Looks like it's working.
