### ISSUE TITLE
Code Browser broken if project opened in New window

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2002]
### Short Summary

If you open a project from an already open window into a new window from the Projects widget the code browser in that new window will be broken.
### Steps to Reproduce
- Open Komodo
- Click the gear in the Projects widget
- `Open Project in New Window`
- Select a project and open it
### Expected results

Good things
### Actual results

Code browser will not populate
### Platform Information

_Komodo Version?_ Komodo 10.1.1 and local build
### Additional Information

```
[2016-09-07 13:15:30,743] [INFO] Startup: Welcome to Komodo IDE 10.1.0 build 89455 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2016-09-07 13:15:30,743] [INFO] Startup: C:\Users\careyh\Komodo IDE latest\lib\mozilla\komodo.exe built on Mon Aug 22 08:23:01 2016
[2016-09-07 13:15:32,553] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-09-07 13:15:32,563] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2016-09-07 13:15:32,565] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///C:/Users/careyh/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2016-09-07 13:15:32,660] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-09-07 13:15:33,506] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-09-07 13:15:34,362] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-09-07 13:15:41,071] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -2 (min 1)
[2016-09-07 13:15:41,928] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -5 (min 1)
[2016-09-07 13:15:42,500] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -2 (min 1)
[2016-09-07 13:15:43,612] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-09-07 13:15:44,365] [INFO] komodospellchecker: Spell checker loaded.
[2016-09-07 13:15:44,365] [INFO] komodospellchecker: Using dictionary en-US
[2016-09-07 13:15:44,585] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-09-07 13:15:44,595] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-09-07 13:15:46,003] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-09-07 13:15:48,516] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for XUL
[2016-09-07 13:15:48,517] [WARNING] koLanguage: Asked for unknown language: 'None'
[2016-09-07 13:15:48,585] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]'[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js'...285 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 72
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 72
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset/commandset._updateTimer< :: line 99
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:72:22
command_updateCommandset/commandset._updateTimer<@chrome://komodo/content/library/commands.js:99:21
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-09-07 13:15:48,691] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-09-07 13:15:48,710] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-09-07 13:15:48,730] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
Exception in thread CommandmentsReader:
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\components\koCommandmentService.py", line 273, in run
    f = open(self._commandmentsFileName, 'r')
IOError: [Errno 2] No such file or directory: u'C:\\Users\\careyh\\AppData\\Local\\ActiveState\\KomodoIDE\\10.1\\commandments.txt'

[2016-09-07 13:15:51,380] [ERROR] console-logger: TypeError: ko.places.manager is undefined (2) in chrome://komodo-places/content/places.js:3749
Traceback (most recent call last):
  File "chrome://komodo-places/content/places.js", line 3749, in 

ERROR:xpcom:Unhandled exception calling 'int8 * matchesUri(in unicode &, out retval boolean);'
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\extensions\publishing@ActiveState.com\components\koPublishingSettings.py", line 272, in matchesUri
    uri = unquote(uri)
  File "C:\Users\careyh\Komodo IDE latest\lib\python\lib\urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'
[2016-09-07 13:15:52,230] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingSettings.matchesUri]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://publishing/content/publishing.js :: ko_pub_getSettingsForUri :: line 124"  data: no]
+ QueryInterface (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingSettings.matchesUri]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://publishing/content/publishing.js'
+ lineNumber (number) 124
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://publishing/content/publishing.js :: ko_pub_getSettingsForUri :: line 124
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://publishing/content/publishing.js'
| + name (string) 'ko_pub_getSettingsForUri'
| + lineNumber (number) 124
| + columnNumber (number) 16
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://publishing/content/publishing.js :: PublishingController.prototype.is_cmd_publishingOpenDialog_enabled :: line 340
| + formattedStack (string) 'ko_pub_getSettingsForUri@chrome://publishing/content/publishing.js:124:16
PublishingController.proto'...446 chars
| + inner (object) null
| + data (object) null
| -- EXCEPTION END --
[2016-09-07 13:15:59,138] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:15:59,141] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:15:59,329] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Users/careyh/Komodo%20IDE%20latest/lib/mozilla/components/koamAddonManager.js:138
[2016-09-07 13:16:00,259] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:16:00,262] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:16:00,348] [ERROR] koJavaScriptLinter: Problem deleting file des(c:\users\careyh\appdata\local\temp\tmpu6bzh2.js)
[2016-09-07 13:16:01,348] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:16:01,348] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:16:02,401] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:16:02,401] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:16:05,016] [ERROR] codeintel.oop.driver: remotefilelib.p
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 36, in do_get_buffer
    if buf.scan_time is None and not buf.accessor.content:
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 171, in scan_time
    self._load_buf_data_once()
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 810, in get_buf_data
    dbsubpath = join(dhash, dbfile_from_blobname[blobname])
KeyError: u'remotefilelib.p'
[2016-09-07 13:16:05,032] [ERROR] koCodeIntel: remotefilelib.p
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 36, in do_get_buffer
    if buf.scan_time is None and not buf.accessor.content:
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 171, in scan_time
    self._load_buf_data_once()
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 810, in get_buf_data
    dbsubpath = join(dhash, dbfile_from_blobname[blobname])
KeyError: u'remotefilelib.p'

[2016-09-07 13:16:10,608] [ERROR] codeintel.indexer: unexpected internal error in indexer: ignoring and continuing
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\indexer.py", line 516, in run
    self._iteration()
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\indexer.py", line 583, in _iteration
    buf.scan(mtime=request.mtime)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1137, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'remotefilelib.p'
[2016-09-07 13:16:12,260] [ERROR] codeintel.oop.driver: remotefilelib.p
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1137, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'remotefilelib.p'
[2016-09-07 13:16:12,273] [ERROR] koCodeIntel: remotefilelib.p
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1137, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'remotefilelib.p'

[2016-09-07 13:18:08,111] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:18:08,111] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:18:08,112] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:18:08,114] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:18:08,114] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:18:15,671] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-09-07 13:18:15,671] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-09-07 13:18:15,673] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-09-07 13:18:15,674] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-09-07 13:18:15,674] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-09-07 13:18:25,418] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:18:25,418] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:18:25,420] [WARNING] ko.launch: ko.launch.newWindow now takes an Array of URIs as of Komodo 9.1.  Please update.
    newWindow@chrome://komodo/content/launch.js:591:13
    this._openProject@chrome://komodo-places/content/project_places_SPV.js:261:9
    this.openProjectInNewWindow@chrome://komodo-places/content/project_places_SPV.js:222:5
    oncommand@chrome://komodo-places/content/places_panel.xul:1:1

[2016-09-07 13:18:25,459] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-09-07 13:18:26,322] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-09-07 13:18:26,713] [INFO] komodospellchecker: Spell checker loaded.
[2016-09-07 13:18:26,713] [INFO] komodospellchecker: Using dictionary en-US
[2016-09-07 13:18:26,798] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-09-07 13:18:26,805] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-09-07 13:18:27,125] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:18:27,125] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:18:27,312] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:18:27,312] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
ERROR:xpcom:Unhandled exception calling 'int8 * matchesUri(in unicode &, out retval boolean);'
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\careyh\Komodo IDE latest\lib\mozilla\extensions\publishing@ActiveState.com\components\koPublishingSettings.py", line 272, in matchesUri
    uri = unquote(uri)
  File "C:\Users\careyh\Komodo IDE latest\lib\python\lib\urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'
[2016-09-07 13:18:30,141] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingSettings.matchesUri]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://publishing/content/publishing.js :: ko_pub_getSettingsForUri :: line 124"  data: no]
+ QueryInterface (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingSettings.matchesUri]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://publishing/content/publishing.js'
+ lineNumber (number) 124
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://publishing/content/publishing.js :: ko_pub_getSettingsForUri :: line 124
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://publishing/content/publishing.js'
| + name (string) 'ko_pub_getSettingsForUri'
| + lineNumber (number) 124
| + columnNumber (number) 16
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://publishing/content/publishing.js :: PublishingController.prototype.is_cmd_publishingOpenDialog_enabled :: line 340
| + formattedStack (string) 'ko_pub_getSettingsForUri@chrome://publishing/content/publishing.js:124:16
PublishingController.proto'...446 chars
| + inner (object) null
| + data (object) null
| -- EXCEPTION END --
[2016-09-07 13:18:30,457] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-09-07 13:18:30,457] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-09-07 13:18:31,585] [WARNING] views: Inconsistent view count in view_closed event
[2016-09-07 13:18:31,759] [WARNING] views: Inconsistent view count in view_opened event
[2016-09-07 13:19:00,509] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:19:00,515] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:19:00,515] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:19:00,516] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:19:00,516] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-09-07 13:19:00,683] [ERROR] console-logger: TypeError: ko.codebrowser.manager is undefined (2) in chrome://komodo/content/codeintel/codebrowser.js:862
Traceback (most recent call last):
  File "chrome://komodo/content/codeintel/codebrowser.js", line 862, in 


```

**Comment by howdu** [comment]
I'm getting these same errors in my log but it's caused when file searching and throws error scintilla is undefined.

**Comment by cgchoffman** [comment]
@howdu i'm not clear what you're saying here.  Are you reporting that your Code Browser is broken after you perform a file search?  Unless you're using the same steps to reproduce the issue, you should report a new issue.

**Comment by Naatan** [comment]
This was reported before the code browser was changed for 11, so it was definitely not introduced in 11. And since 11 completely replaces the code browser this ticket is no longer relevant.
