### ISSUE TITLE
Git problems

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2071]
### Short Summary

Using git on command line inside komodo only, the git status doesn't update correct.
Had 7 files that where changes added and committed them.
But the dynamic button is still showing 7 changes.
![2016-09-30](https://cloud.githubusercontent.com/assets/3530262/18993546/07f55ea2-8724-11e6-8cad-a5694f34a5f0.png)

![2016-09-30r](https://cloud.githubusercontent.com/assets/3530262/18993605/45ddffbc-8724-11e6-89b6-99dd98feaba0.png)

The file in the places widget is showing the correct state (no blue colors anymore)
### Platform Information

Komodo ide 10.1.1 Windows 10

**Comment by Naatan** [comment]
Reproducible on a clean profile? It sounds like file status monitoring is not working properly.

**Comment by babobski** [comment]
@Naatan I have the same errors on work as on my home computer.
Also just tried to commit a file with the git tool, every thing works fine.
Only when I look on github nothing changed.

When I look at my error log, its full of errors.
Maybe the can give you a clue, about whats going on.
```
[2016-10-31 19:13:44,191] [INFO] Startup: Welcome to Komodo IDE 10.1.1 build 89474 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2016-10-31 19:13:44,191] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\komodo.exe built on Thu Sep 01 14:27:01 2016
[2016-10-31 19:13:45,296] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-10-31 19:13:45,303] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/emmet@chikuyonok.ru/chrome.manifest:1
[2016-10-31 19:13:45,303] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2016-10-31 19:13:45,548] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-10-31 19:13:46,095] [DEBUG] console: log: Less has finished and no sheets were loaded.
[2016-10-31 19:13:46,578] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2016-10-31 19:13:47,535] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -1 (min 1)
[2016-10-31 19:13:47,535] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -4 (min 1)
[2016-10-31 19:13:48,184] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 19:13:48,184] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 19:13:48,186] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 19:13:48,187] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 19:13:48,372] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -8 (min 1)
[2016-10-31 19:13:48,592] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of -4 (min 1)
[2016-10-31 19:13:48,595] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 19:13:50,375] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-10-31 19:13:50,664] [INFO] komodospellchecker: Spell checker loaded.
[2016-10-31 19:13:50,664] [INFO] komodospellchecker: Using dictionary en-US
[2016-10-31 19:13:50,790] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-10-31 19:13:50,803] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-10-31 19:13:50,836] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-10-31 19:13:52,720] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2016-10-31 19:13:52,779] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2016-10-31 19:13:53,210] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138
[2016-10-31 19:13:54,470] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for XUL
[2016-10-31 19:13:54,471] [WARNING] koLanguage: Asked for unknown language: 'None'
[2016-10-31 19:13:56,114] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-10-31 19:13:56,118] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-10-31 19:13:56,131] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-10-31 19:13:58,313] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2016-10-31 19:13:58,565] [WARNING] console-logger: Unexpected value scale(NaN) parsing transform attribute. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2016-10-31 19:13:58,565] [WARNING] console-logger: Unexpected value NaN parsing width attribute. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2016-10-31 19:13:58,566] [WARNING] console-logger: Unexpected value NaN parsing height attribute. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2016-10-31 19:13:58,566] [WARNING] console-logger: Unexpected value 0 0 NaN NaN parsing viewBox attribute. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.1/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2016-10-31 19:13:58,678] [ERROR] console-logger: NS_ERROR_NOT_AVAILABLE:  (2) in chrome://komodo/content/sdk/icons.js:600
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/icons.js", line 600, in 

[2016-10-31 19:14:04,275] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:14:04,275] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:14:04,552] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:14:04,553] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:14:05,457] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-31 19:14:05,459] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-31 19:14:05,460] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-31 19:14:07,381] [DEBUG] console: error: TypeError {}
[2016-10-31 19:14:57,552] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:14:57,552] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:14:57,747] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:14:57,749] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:16:36,151] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:16:36,151] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:16:36,316] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:16:36,319] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:17:08,451] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:17:08,453] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:17:08,822] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:17:08,825] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:17:17,773] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:17:17,826] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:17:18,203] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:17:18,206] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:17:18,423] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:17:18,423] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:18:48,984] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:18:49,000] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:18:49,019] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:18:49,408] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:18:49,410] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:18:49,614] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:18:49,615] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:19:33,460] [WARNING] prefs: The 'commit_message_history' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2016-10-31 19:19:33,806] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:33,822] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:33,836] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:34,141] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:19:34,144] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:19:34,144] [ERROR] console-logger: TypeError: selection.element(...).clearSelection is not a function (2) in chrome://komodo/content/scc/commit.js:112
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 112, in 

[2016-10-31 19:19:34,164] [ERROR] console-logger: TypeError: summaryTextbox.element(...).setSelectionRange is not a function (2) in chrome://komodo/content/scc/commit.js:54
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 54, in 

[2016-10-31 19:19:34,184] [ERROR] console-logger: TypeError: selection.element(...).clearSelection is not a function (2) in chrome://komodo/content/scc/commit.js:112
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 112, in 

[2016-10-31 19:19:34,203] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:19:34,204] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:19:34,430] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:34,460] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:34,480] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:34,608] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:34,624] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

[2016-10-31 19:19:34,637] [ERROR] console-logger: NS_ERROR_NOT_INITIALIZED:  (2) in chrome://komodo/content/scc/commit.js:556
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 556, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koAsyncOperations.py", line 62, in notifyCallback
    aOpCallback.callback(result, data)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koAsyncOperations.py", line 62, in notifyCallback
    aOpCallback.callback(result, data)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koAsyncOperations.py", line 62, in notifyCallback
    aOpCallback.callback(result, data)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2016-10-31 19:19:34,664] [WARNING] scc.history: could not load history results, exception: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsITreeSelection.select]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/scc/history.js :: _scc_history_dialog.prototype.load_history_for_url/async_callback.callback :: line 463"  data: no]
[2016-10-31 19:19:34,694] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2016-10-31 19:19:34,694] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2016-10-31 19:19:34,750] [ERROR] console-logger: TypeError: this._scc is undefined (2) in chrome://komodo/content/scc/commit.js:263
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 263, in 

[2016-10-31 19:19:34,769] [ERROR] console-logger: TypeError: diffBrowser.element(...).contentWindow is undefined (2) in chrome://komodo/content/scc/commit.js:503
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 503, in 

[2016-10-31 19:19:34,786] [ERROR] console-logger: TypeError: this._scc is undefined (2) in chrome://komodo/content/scc/commit.js:263
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 263, in 

[2016-10-31 19:21:18,061] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-10-31 19:21:18,062] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-10-31 19:21:18,062] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by Naatan** [comment]
Thanks @babobski, that log helps a lot :)

**Comment by Naatan** [comment]
For the record, I'm fixing the timeout errors. I can't really work on the rest as they require steps to reproduce. It's very well possible that fixing the timeout errors also fixes the rest though.

Let me know if you find exact reproduction steps.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/279bffdebecc5bb98cb2eb8d74b20c1b89aee12a
