### ISSUE TITLE
Komodo 10.1 crashes after hitting the Run button while debugging Perl

### ISSUE THREAD

**Issue by pepotterjr** [Komodo/KomodoEdit#2098]
### Short Summary

Komodo 10.1 - Komodo IDE, version 10.1.1, build 89474, platform win32-x86.
Built on Thu Sep 01 14:27:01 2016.

Crashes while using the debugger.  The code was stopped at a breakpoint.  

with Perl : This is perl 5, version 24, subversion 0 (v5.24.0) built for MSWin32-x64-multi-thread
(with 1 registered patch, 

This is twice today. 
### Steps to Reproduce

just debugging
### Expected results

no crash
### Actual results

n/a
### Platform Information

Windows 10 Pro
### Additional Information

pystderr.log 👍 

[2016-10-17 17:33:51,697] [INFO] Startup: Welcome to Komodo IDE 10.1.1 build 89474 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2016-10-17 17:33:51,697] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\komodo.exe built on Thu Sep 01 14:27:01 2016
[2016-10-17 17:33:52,315] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-10-17 17:33:52,385] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-10-17 17:33:52,878] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-10-17 17:33:53,516] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-10-17 17:33:54,657] [ERROR] ko.main: 
-- EXCEPTION START --
TypeError: ko.toolbox2 is undefined
- stack
  uilayout_onload@chrome://komodo/content/library/uilayout.js:1843:13
  onloadDelay@chrome://komodo/content/komodo.js:429:9
  window.onload@chrome://komodo/content/komodo.js:566:9
  -- EXCEPTION END --
  [2016-10-17 17:33:54,986] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
  [2016-10-17 17:33:55,188] [INFO] elastic_tabstops: Elastic tabstops loaded.
  [2016-10-17 17:33:55,232] [INFO] komodospellchecker: Spell checker loaded.
  [2016-10-17 17:33:55,232] [INFO] komodospellchecker: Using dictionary en-US
  [2016-10-17 17:33:55,351] [ERROR] koScopeDocs-Py: Could not find cix for ext
  [2016-10-17 17:33:55,358] [ERROR] koScopeDocs-Py: Could not find cix for html5
  [2016-10-17 17:33:55,676] [ERROR] console-logger: bad script XDR magic number (0) in :0
  Traceback (most recent call last):
  File "", line 0, in 

[2016-10-17 17:33:57,891] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]'[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72"  data: yes]
- QueryInterface (function) 3 lines
- message (string) '[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js'...285 chars
- result (number) 2153185313
- name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
- filename (string) 'chrome://komodo/content/library/commands.js'
- lineNumber (number) 72
- columnNumber (number) 0
- location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72
  | + QueryInterface (function) 3 lines
  | + language (number) 2
  | + languageName (string) 'JavaScript'
  | + filename (string) 'chrome://komodo/content/library/commands.js'
  | + name (string) '_command_updateCommand'
  | + lineNumber (number) 72
  | + columnNumber (number) 22
  | + sourceLine (string) ''
  | + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset/commandset._updateTimer< :: line 99
  | + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:72:22
  command_updateCommandset/commandset._updateTimer<@chrome://komodo/content/library/commands.js:99:21
  '
  | + inner (object) null
  | + data (object) [xpconnect wrapped nsISupports]
  | + QueryInterface (function) 3 lines
  | + initialize (function) 3 lines
  -- EXCEPTION END --
  [2016-10-17 17:33:58,404] [ERROR] console-logger: TypeError: ko.places.manager is undefined (2) in chrome://komodo-places/content/places.js:3749
  Traceback (most recent call last):
  File "chrome://komodo-places/content/places.js", line 3749, in 

[2016-10-17 17:33:58,413] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-10-17 17:33:58,415] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-10-17 17:33:58,424] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-10-17 17:33:58,691] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2016-10-17 17:33:59,989] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010/lib/mozilla/components/koamAddonManager.js:138
[2016-10-17 17:34:31,440] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-17 17:34:31,444] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-17 17:34:31,444] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-17 17:34:31,444] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-17 17:34:31,444] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-10-17 17:43:24,453] [ERROR] koCodeIntel:     INFO: eval 'compute_field_start' at util.t#85  <Trigger 'perl-calltip-call-signature' at 2142>
    INFO: start scope is (<blob 'util'>, [])
    DEBUG: is 'compute_field_start' from <from Test::Most import *>? no
    INFO: is 'compute_field_start' accessible on (<blob 'util'>, [])? no
    INFO: is 'compute_field_start' accessible on (<blob '*'>, [])? no
    ERROR: evaluating 'compute_field_start' at util.t#85: could not resolve 'compute_field_start'
[2016-10-17 17:47:38,305] [ERROR] koCodeIntel:     INFO: eval '$test_ref' at util.t#87  <Trigger 'perl-complete-object-subs' at 2210>
    INFO: start scope is (<blob 'util'>, [])
    INFO: is '$test_ref' accessible on (<blob 'util'>, [])? yes: <variable '$test_ref'>
    ERROR: evaluating '$test_ref' at util.t#87: no type-inference info for <variable '$test_ref'>
[2016-10-17 17:48:24,285] [ERROR] koCodeIntel:     INFO: eval '$test_ref' at util.t#89  <Trigger 'perl-complete-object-subs' at 2289>
    INFO: start scope is (<blob 'util'>, [])
    INFO: is '$test_ref' accessible on (<blob 'util'>, [])? yes: <variable '$test_ref'>
    ERROR: evaluating '$test_ref' at util.t#89: no type-inference info for <variable '$test_ref'>
[2016-10-17 17:49:07,542] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-10-17 17:49:10,368] [ERROR] console-logger: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. (0) in file:///c:/users/ppotter/appdata/local/temp/tmpraeldv.html:0
Traceback (most recent call last):
  File "file:///c:/users/ppotter/appdata/local/temp/tmpraeldv.html", line 0, in 

[2016-10-17 17:54:21,326] [WARNING] codeintel.manager: File u'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:21,345] [WARNING] codeintel.manager: File 'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:48,696] [WARNING] codeintel.manager: File u'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:48,697] [WARNING] codeintel.manager: File 'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:48,783] [WARNING] codeintel.manager: File u'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:48,783] [WARNING] codeintel.manager: File 'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:48,957] [WARNING] codeintel.manager: File u'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:48,957] [WARNING] codeintel.manager: File 'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:49,036] [WARNING] codeintel.manager: File u'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 17:54:49,036] [WARNING] codeintel.manager: File 'C:\Perl64\site\lib\DateTime\Locale\Data.pm' has size greater than 1MB (4376171)
[2016-10-17 18:01:39,048] [WARNING] console-logger: Unknown property 'foreground'.  Declaration dropped. (1) in less://komodo/skin/colorpicker/colorpicker.less:12
[2016-10-17 18:01:39,098] [WARNING] console-logger: Expected color but found '#'.  Error in parsing value for 'background-color'.  Declaration dropped. (1) in chrome://komodo/content/colorpicker/colorpicker.html:0
[2016-10-17 18:01:48,431] [WARNING] koLess: Reloading Skin
[2016-10-17 18:01:48,433] [WARNING] koLess: Clearing local and file cache
[2016-10-17 18:41:49,654] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-10-17 18:41:51,424] [ERROR] console-logger: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. (0) in file:///C:/scriptcare/perlsite/t/SCI/NCPDP/Telecom/tmph3hmqq.html:0
Traceback (most recent call last):
  File "file:///C:/scriptcare/perlsite/t/SCI/NCPDP/Telecom/tmph3hmqq.html", line 0, in 

Below is the contents of the  tmph3mgg.html file:

1..14

Sorry I did not notice the mention of the file in the above log:  
file:///c:/users/ppotter/appdata/local/temp/tmpraeldv.html:0

I will add to the report when I crash again...

Thanks 

Phillip

**Comment by cgchoffman** [comment]
Local or remote debugging?

**Comment by pepotterjr** [comment]
Hello Carey,

Local debugging... 

I notice Chrome is being referenced a lot with decoding these small html 
files.

I'm sure I'm way off base but would making the Internet Explorer my 
default browser help.

I've tried all the work arounds.  The crashes occur when in safe mode. 
I've delete  the profile folders and it seems to run better for a while 
but eventually starts crashing again.

I going to send one more collection of info if it crashes again.

Thank You,

Phillip

**Comment by pepotterjr** [comment]
Hey Carey,

If there is anything you would like for me to do... just ask.

Thanks

Phillip

**Comment by cgchoffman** [comment]
> I notice Chrome is being referenced a lot with decoding these small html
> files.

I don't understand.  What do HTML files have to do with this?

> I'm sure I'm way off base but would making the Internet Explorer my
> default browser help.

What does IE have to do with this?

What would help here is a minimum viable sample of code that reproduces the issue that you can send to us to reproduce.  So far local Perl debugging is working fine for me.

How exactly are you starting the debugging session?

**Comment by pepotterjr** [comment]
Hello Carey,

In the pystderr.log file if mentions 

[2016-10-17 17:49:10,368] [ERROR] console-logger: The character encoding 
of the HTML document was not declared. The document will render with 
garbled text in some browser configurations if the document contains 
characters from outside the US-ASCII range. The character encoding of the 
page must be declared in the document or in the transfer protocol. (0) in 
file:///c:/users/ppotter/appdata/local/temp/tmpraeldv.html:0
Traceback (most recent call last):
  File "file:///c:/users/ppotter/appdata/local/temp/tmpraeldv.html", line 
0, in 

and the last entry from the last crash

[2016-10-17 18:41:51,424] [ERROR] console-logger: The character encoding 
of the HTML document was not declared. The document will render with 
garbled text in some browser configurations if the document contains 
characters from outside the US-ASCII range. The character encoding of the 
page must be declared in the document or in the transfer protocol. (0) in 
file:///C:/scriptcare/perlsite/t/SCI/NCPDP/Telecom/tmph3hmqq.html:0
Traceback (most recent call last):
  File "file:///C:/scriptcare/perlsite/t/SCI/NCPDP/Telecom/tmph3hmqq.html
", line 0, in 

hence I mention the html files.  I'm way off base with the Chome or IE 
mention.

I will talk to my supervisors to see what I can arrange to send some code 
if it is possible.

I start the debugging session by hitting the run button or the step into 
button.

I start Komodo from a desktop icon ; linked to "C:\Program Files 
(x86)\ActiveState Komodo IDE 10\komodo.exe"

Thanks,

Phillip

**Comment by cgchoffman** [comment]
Oh you're talking about the log file.  Unless your perl code is doing something with HTML files I don't think it's related.  Unless Perl debugging isn't actually causing the crashes.  Hard to say with our the ability to reproduce the issue.

Could you try to respond to the ticket on Github rather clicking "reply" in your email?  It dumps a bunch of text from your email when you click reply (eg. my original email & TO +  FROM + Subject of that email).  It's a lot of noise in your response.

**Comment by pepotterjr** [comment]
Sorry will do.

**Comment by Naatan** [comment]
We're missing some detail here. Could you please provide detailed reproduction steps? I understand you say the crash is random, but I imagine that it still happens at more or less the same stage of debugging, we need to know how you start debugging and at what stage the crash happens.

**Comment by cgchoffman** [comment]
Hey nathanr, it's spaced out in the responses but he has provided most of that info:
- happens when stopped at a breakpoint
- this is local debugging started by clicking Run in Komodo
- He is going to try and get us a minimum viable code sample that reproduces the issue but needs to speak to his manager.

**Comment by pepotterjr** [comment]
It is always during debugging.  Most of the time it is exactly after I hit the Run button (the first time) or when after stopping at a break point.   I'm new to this I should be more specific.   

I'll know more about the code I can send by tomorrow.  I may have to just write some and see if it causes a crash.  I will definitely be doing that.

**Comment by Naatan** [comment]
Thanks @cgchoffman & @pepotterjr :) Will await code sample. Note it might be worth also reproducing it on some really basic Perl code (hello world type code), just to see if the issue is indeed with the code.

**Comment by pepotterjr** [comment]
Will do.

**Comment by Naatan** [comment]
@pepotterjr btw you can send your code sample to support@activestate.com and reference this ticket if you prefer your code not to be visible to everyone.

**Comment by pepotterjr** [comment]
thanks
