### ISSUE TITLE
File open edit fails with exception: this.__globalPrefs is undefined

### ISSUE THREAD

**Issue by oehhar** [Komodo/KomodoEdit#2107]
Komodo 10.1, Win 10 64 bit.

After installing Komodo on a temporary Laptop (orig is on service), I:
- installed komodo
- set up the tabbing prefs in the general prefs.
- set up the general font size with the color editor to 10 pt.
- selected a file for editing.
- a window opens "Komodo was unable to open the file"

The following exception was written to the log:

[2016-10-19 10:18:49,709] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --

A screenshot shows it:

![komodo_parse_open_exception](https://cloud.githubusercontent.com/assets/12413997/19592129/a7b42160-977a-11e6-8fd6-f168dbfa3a64.png)

This bug is *not* reproducible and disappears forever on restart. This has nothing to do with the file itself. The issue is probably due to the pirior setting of the prefs. I did not press "Apply" there, just ok.
If you find the issue by code inspection ok, otherwise just close and ignore.

Thanks for all your work,
Harald

**Comment by Naatan** [comment]
I'm not able to reproduce this either. Please let us know if the issue occurs again, without reproduction steps there isn't much we can do :( I don't see anything in the code that makes it obvious as to why __globalPrefs would be undefined.

Next time it happens try copying your error log before restarting Komodo though.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by Defman21** [comment]
I'm able to reproduce it, but unfortunately there are no reproduce steps. Mostly it happens when I open files via terminal (e.g. `komodo projectname.komodoproject`) 

```
ERROR:xpcom:Unhandled exception calling 'int8 * addUnopenedProjectAtPosition(in nsISomething, in int32);'
Traceback (most recent call last):
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koKPFTreeView.py", line 321, in addUnopenedProjectAtPosition
    self._tree.rowCountChanged(newProjectIndex, 1)
AttributeError: 'NoneType' object has no attribute 'rowCountChanged'
[2016-10-27 23:33:37,118] [ERROR] open: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIKPFTreeView.addUnopenedProjectAtPosition]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/project/projectManager.js :: projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView :: line 220"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIKPFTreeView.addUnopenedProjectAtPosition]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/project/projectManager.js'
+ lineNumber (number) 220
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView@chrome://komodo/content/project/p'...768 chars
+ location (object) JS frame :: chrome://komodo/content/project/projectManager.js :: projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView :: line 220
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/projectManager.js'
| + name (string) 'projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView'
| + lineNumber (number) 220
| + columnNumber (number) 8
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/project/projectManager.js :: projectManager.prototype.closeProjectEvenIfDirty :: line 229
| + formattedStack (string) 'projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView@chrome://komodo/content/project/p'...768 chars
| + stack
    projectManager.prototype.closeProjectEvenIfDirty_SingleProjectView@chrome://komodo/content/project/projectManager.js:220:8
    projectManager.prototype.closeProjectEvenIfDirty@chrome://komodo/content/project/projectManager.js:229:0
    projectManager.prototype.closeProject@chrome://komodo/content/project/projectManager.js:329:11
    project_openProjectFromURL@chrome://komodo/content/project/projectManager.js:1636:17
    open_openURIAtLine@chrome://komodo/content/library/open.js:157:12
    open_openURI@chrome://komodo/content/library/open.js:84:11
    viewManager.prototype.handle_open_file@chrome://komodo/content/views.js:1069:0
    viewManager.prototype.observe/<@chrome://komodo/content/views.js:1149:24
    this.waitForProjectManager/</delayFunc@chrome://komodo/content/workspace.js:503:16
-- EXCEPTION END --
[2016-10-27 23:33:52,432] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:484:17
    init@vieweditor:331:13
    newView@viewlistbase:469:17
    newView@viewmultiview:300:20
    createViewFromDocument@viewlistbase:86:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-10-27 23:33:53,997] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:100:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:574:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:20
-- EXCEPTION END --
[2016-10-27 23:33:57,877] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

**Comment by Naatan** [comment]
@Defman21 this just happened the one time or has it happened fairly frequently?

**Comment by Defman21** [comment]
Second one.

**Comment by Naatan** [comment]
@Defman21 if you repeatedly open a project or file from the terminal, are you able to reproduce it?

**Comment by Defman21** [comment]
Nope :(
