### ISSUE TITLE
Stuck notification in focus mode

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2108]
### Short Summary
I currently have a stuck notification, when working in focus mode.

### Platform Information
Komodo Ide 10.1.1 Windows 10

### Additional Information
![2016-10-21 13_17_14](https://cloud.githubusercontent.com/assets/3530262/19596959/d849b026-9791-11e6-8e08-943aa9179c6d.png)

And in my error log:
```
[2016-10-21 09:14:40,890] [DEBUG] console: error: TypeError {}
[2016-10-21 09:14:42,729] [DEBUG] console: error: TypeError {}
[2016-10-21 09:14:42,733] [ERROR] console-logger: TypeError: panel is null (2) in chrome://notify/content/sdk/notify.js:721
Traceback (most recent call last):
  File "chrome://notify/content/sdk/notify.js", line 721, in 

[2016-10-21 09:14:42,756] [DEBUG] console: error: TypeError {}
[2016-10-21 09:14:42,865] [ERROR] console-logger: TypeError: panel is null (2) in chrome://notify/content/sdk/notify.js:721
Traceback (most recent call last):
  File "chrome://notify/content/sdk/notify.js", line 721, in 

[2016-10-21 09:14:43,428] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:43,506] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:43,637] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:43,773] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:43,855] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,062] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,167] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,249] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,395] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,644] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,654] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:44,657] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:46,653] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:46,783] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 09:14:46,832] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
```
And a bit later:
```
[2016-10-21 10:43:42,105] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:46:53,049] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:46:54,338] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:47:00,898] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:47:01,372] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:47:01,529] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:47:01,686] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2016-10-21 10:47:03,667] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
```

**Comment by Naatan** [comment]
Are you able to reproduce this issue?

**Comment by babobski** [comment]
@Naatan got it reproduced.
Steps to reproduce:
- open two komodo windows, both in focus mode.
- Trigger intel scanning ( The scanning ... notification will show up ) 
- Move to the other komodo window

Now you will have a stuck notification and the following error:
```
[2016-10-23 11:27:39,421] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
```

**Comment by Naatan** [comment]
Thanks @babobski

**Comment by Naatan** [comment]
Is this still happening?

**Comment by babobski** [comment]
@Naatan Just tested it, but got it reproduced in 10.2

**Comment by Naatan** [comment]
Ok, thanks @babobski

**Comment by Naatan** [comment]
@Defman21 @cgchoffman please share your error log after reproducing.

**Comment by Defman21** [comment]
Sure, I'll do.

**Comment by Defman21** [comment]
Could it be related to the WM I'm using? (i3) I'm aware that Komodo has some problems with i3 and if this issue is one of them, then I guess my logs won't help.

**Comment by Naatan** [comment]
Could be. Hard to say for certain.

**Comment by codermjb** [comment]
What is focus mode?

And mine was in Xubuntu 16.0.4. i don't think I was in focus mode. And it was more when I was switching workspaces. I will let you know what was done before if I notice it again.
