### ISSUE TITLE
Consistent Crashes

### ISSUE THREAD

**Issue by playanywheredesigns** [Komodo/KomodoEdit#2122]
### Short Summary
While coding PHP mainly I have Komodo crash on me 3-10 a day.

### Steps to Reproduce
Open files, use the built in web viewer (or not) and work.  Application crashes.

### Expected results

Komodo quits when I quit it not before :)

### Actual results
Komodo Crashes

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.1.1
*Operating System (and version)?*  Mac OS X 10.12.1

### Additional Information

# ~/Library/Logs/CrashReporter/komodo-bin.crash.log 
This log does not exist which makes me wonder what is happening that the logs do not even get generated.

# Example submit
`Crash ID: bp-2a746046-9925-11e6-af69-080027a7c3ca
You can view details of this crash at https://crash-reports.komodo.activestate.com/submit/report/index/2a746046-9925-11e6-af69-080027a7c3ca?date=2016-10-23-13`
# pystderr.log
`[2016-10-31 18:57:23,819] [INFO] Startup: Welcome to Komodo IDE 10.1.1 build 89474 (platform macosx, running on Darwin 16.1.0 version Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64)
[2016-10-31 18:57:23,820] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Thu Sep 1 15:11:44 2016
[2016-10-31 18:57:23,924] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2016-10-31 18:57:24,347] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2016-10-31 18:57:24,405] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2016-10-31 18:57:24,821] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-10-31 18:57:24,928] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2016-10-31 18:57:26,145] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 18:57:26,260] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 18:57:26,749] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 18:57:26,749] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 18:57:26,851] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 18:57:26,949] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-10-31 18:57:27,510] [ERROR] ko.main: 
-- EXCEPTION START --
TypeError: ko.toolbox2 is undefined
+ stack
    uilayout_onload@chrome://komodo/content/library/uilayout.js:1843:13
    onloadDelay@chrome://komodo/content/komodo.js:429:9
    window.onload/<@chrome://komodo/content/komodo.js:563:13
-- EXCEPTION END --
[2016-10-31 18:57:27,675] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2016-10-31 18:57:27,744] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-10-31 18:57:27,766] [INFO] komodospellchecker: Spell checker loaded.
[2016-10-31 18:57:27,766] [INFO] komodospellchecker: Using dictionary en-US
[2016-10-31 18:57:27,833] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2016-10-31 18:57:27,833] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2016-10-31 18:57:28,299] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-10-31 18:57:29,269] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2016-10-31 18:57:29,270] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2016-10-31 18:57:29,937] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]'[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js'...285 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 72
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 72
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset/commandset._updateTimer< :: line 99
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:72:22
command_updateCommandset/commandset._updateTimer<@chrome://komodo/content/library/commands.js:99:21
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2016-10-31 18:57:30,716] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2016-10-31 18:57:30,718] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2016-10-31 18:57:30,720] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2016-10-31 18:57:30,724] [ERROR] console-logger: TypeError: ko.places.manager is undefined (2) in chrome://komodo-places/content/places.js:3749
Traceback (most recent call last):
  File "chrome://komodo-places/content/places.js", line 3749, in 

[2016-10-31 18:57:33,128] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2016-10-31 18:57:45,497] [WARNING] views: Inconsistent view count in view_closed event
[2016-10-31 18:57:45,643] [ERROR] codeintel.komodo.KoCodeIntelBuffer: Error calling section_from_line callback
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koCodeIntel.py", line 1746, in invoke_callback
    callback.onGetSection(section)
  File "<XPCOMObject method 'onGetSection'>", line 3, in onGetSection
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2016-10-31 18:57:45,675] [ERROR] console-logger: TypeError: this.section_arrows is undefined (2) in chrome://komodo/content/bindings/sectionlist.xml:197
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/sectionlist.xml", line 197, in `

 -- eg. Error logs, screenshots, workarounds --

**Comment by cgchoffman** [comment]
hi @playanywheredesigns, thanks for the report.  Can you reproduce this in Help > Troubleshooting > Safemode?

Can you give more concrete reproduction steps?  When exactly does Komodo crash?  What are you and
/or the editor doing when Komodo crashes?

**Comment by Defman21** [comment]
Looks familiar to #1007: foreground crashes on OSX

**Comment by cgchoffman** [comment]
> Looks familiar to #1007: foreground crashes on OSX

The only indication of this is that it's on OSX.  #1007 is a background crash only so we're missing key details hence the "Pending: Response" label.

**Comment by Defman21** [comment]
> #1007 is a background crash

Do'h, sorry :)
