### ISSUE TITLE
PHP Codeintel Cannot Handle Variable Assignment in Single-Line 'if' Conditional

### ISSUE THREAD

**Issue by mitchell-as** [Komodo/KomodoEdit#2241]
### Short Summary

Komodo's codeintel errors out when trying to assign a variable within a single-line 'if' conditional.

### Steps to Reproduce

Create a new PHP file with the following content:

```
<?php

		if($deleteFiles) $recordToDelete = $this->get($id);
```

### Expected results

No problems and a `$recordToDelete` global variable in the code browser.

### Actual results

An "IndexError" with the following traceback in the log:

```
Traceback (most recent call last):
  File "mozilla/ko-rel/dist/bin/python/komodo/codeintel2/citadel.py", line 264, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 616, in scan_purelang
    self.slave_css_cile_driver)
  File "mozilla/ko-rel/dist/bin/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 1285, in scan_multilang
    csl_tokens, css_tokens = phpciler.scan_multilang_content(buf.accessor.text)
  File "mozilla/ko-rel/dist/bin/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3426, in scan_multilang_content
    PHPLexer().tokenize_by_style(content, self.token_next)
  File "mozilla/ko-rel/dist/bin/python/komodo/codeintel2/udl.py", line 98, in tokenize_by_style
    return Lexer.tokenize_by_style(self, text, call_back)
  File "mozilla/ko-rel/dist/bin/python/komodo/SilverCity/Lexer.py", line 8, in tokenize_by_style
    call_back
  File "mozilla/ko-rel/dist/bin/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3386, in token_next
    self._addCodePiece()
  File "mozilla/ko-rel/dist/bin/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3197, in _addCodePiece
    self._addCodePiece()
  File "mozilla/ko-rel/dist/bin/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3238, in _addCodePiece
    doc=self.comment)
  File "mozilla/ko-rel/dist/bin/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 2865, in _variableHandler
    assignChar = text[p]
IndexError: list index out of range
```

### Platform Information

*Komodo Edit or IDE?* Either
*Komodo Version?* 10.1.x
*Operating System (and version)?* Any

### Additional Information

Wrapping the assignment statement with braces (`{ ... }`) works.

**Comment by mitchell-as** [comment]
Strange, I filed this bug, but I cannot reproduce this any more in 10.2.x.

**Comment by seattledeveloper** [comment]
@mitchell-as, I noticed this went away as well with the download last week, which appeared to have the same version number but was a new build.
