### ISSUE TITLE
(Windows) Komodo crashes whenever Git or other tool updates an open file

### ISSUE THREAD

**Issue by jimzag** [Komodo/KomodoEdit#2260]
### Short Summary
After Git SYNC (GitHub UI) or sometimes if changing branches I will find Komodo non responsive.  The windows cursor and greyed-out appearance of the app.  Need to close and re-open.  I first noticed this with another tool, Pinegrow which writes web pages.  If I had a particular page open in Komodo then saved that same page in Pinegrow, Komono crashes every time.

### Steps to Reproduce
See above

### Platform Information
Windows 10

*Komodo Edit or IDE?*
IDE 
*Komodo Version?* 
Komodo IDE, version 10.1.4, build 89515, platform win32-x86. Built on Fri Dec 16 10:34:21 2016
*Operating System (and version)?* 

### Additional Information

 -- eg. Error logs, screenshots, workarounds --

**Comment by jimzag** [comment]
I am curious if this problem has been reported by others.  I noticed there have been no notations made to date on the status.  Let me know if I can provide anything in particular: logs, etc.

**Comment by Defman21** [comment]
Once you reproduce the crash again, attach your log file (pystderr.log in your [profile folder](http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data#where-does-komodo-keep-settings-data_windows))

**Comment by Naatan** [comment]
We use Komodo with GIT to develop Komodo and are not seeing this crash.

Does disabling GIT make a difference?

**Comment by jimzag** [comment]
The lockup happened again today.  Not as frequently recently - may depend on something specific in the files. 
Here is the log and screenshot.  I had just performed a 'SYNC' in the Github UI and I know it had updates some of the files which had been open in Komodo.

Jim Z.

**Comment by jimzag** [comment]
Sent an example of the crash to S. Kislyakov.  Hope it is helpful in finding the cause.Jim Z.

**Comment by jimzag** [comment]
Also noticed Komodo is taking 25 - 30% CPU, so not crashed but stuck in processing.

**Comment by Naatan** [comment]
Please respond using the github web interface. Email responses include a lot of useless extra text and do not include attachments (we cannot see your logs).

Additionally, you did not say whether disabling GIT helped or not?

**Comment by Defman21** [comment]
I believe github hides my e-mail to something that behaves like noreply. So I didn't get your message :( Please do what Nathan said :)

**Comment by jimzag** [comment]
![komono_not_responding](https://cloud.githubusercontent.com/assets/5787294/22077245/609db618-dd81-11e6-9800-e911e43d9c3d.jpg)

[pystderr.zip](https://github.com/Komodo/KomodoEdit/files/714678/pystderr.zip)

Log and screen capture attached.  Also, I noted that the processor was at 25-30% when Komodo was in the 'not responding' state seen in the screen capture.
 
Regarding whether 'Disabling GIT' makes a difference, I assume that is a setting in Komodo.  I don't use the Git integration.  I had a quick look around in Preferences and did not see a setting like that.  Let me know where to look.

**Comment by cgchoffman** [comment]
> I had a quick look around in Preferences and did not see a setting like that. Let me know where to look.

@jimzag  Open the preferences and search `git` in the search field at the top of the left column.

**Comment by Naatan** [comment]
This seems fishy:

```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\watchdog\observers\api.py", line 186, in run
    self.queue_events(self.timeout)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\watchdog\observers\read_directory_changes.py", line 73, in queue_events
    self.watch.is_recursive)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\watchdog\observers\winapi_common.py", line 124, in read_directory_changes
    None)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\watchdog\observers\winapi.py", line 106, in _errcheck_bool
    raise ctypes.WinError()
WindowsError: [Error 5] Access is denied.
```

Are you perhaps pointing Komodo at files/directories that it does not have permission to read?

**Comment by jimzag** [comment]
The GIT operations at that time included pressing the SYNC button (on the GIT Windows App), and possibly creating a new branch and changing the selected branch.  In GIT obviously if you switch branches some files disappear or change according to what has occurred on that branch.  Perhaps there is brief inavailability of the folder during these type of GIT operations, and perhaps a timing-dependent failure encountered if there is a certain timing with respect to processing of any updates as Komono observes folder/ file changes.
I am pretty sure all files open at the time were in folders under c:\Dev\JBSDEV\BrowserApp2.  There were perhaps 6 files open.

**Comment by Naatan** [comment]
Please see whether disabling GIT works around the issue, see screenshot for assistance:

![image](https://cloud.githubusercontent.com/assets/278649/22081689/8915a28e-dd92-11e6-9e69-274efed32da5.png)

**Comment by jimzag** [comment]
[komodo_pystderr.zip](https://github.com/Komodo/KomodoEdit/files/718121/komodo_pystderr.zip)

Another crash occurred today after disabling Git integration.  Here is the sequence of events:
1. Disable Git integration
2. close and re-open Komodo
3. Select the Master branch in Git (from the Git UI)
4. press Git UI SYNC button
5. Observed that Komodo was no longer running

**Comment by Naatan** [comment]
See if disabling this setting makes a difference:

![image](https://cloud.githubusercontent.com/assets/278649/22155968/5203dbf8-deff-11e6-892b-ef8433f0378b.png)

**Comment by jimzag** [comment]
I have made the change.   Now that file change detection is turned off, is there a way I can tell Komodo to reread all files.  I certainly don't want to be editing an old version, such that when I save the changes it actually overwrites the current version with older content.
Thanks

**Comment by Naatan** [comment]
@jimzag the point of toggling that setting is not to fix your problem, but rather to diagnose it. Are you saying that toggling it worked around your issue? Komodo is no longer hanging/crashing?

**Comment by jimzag** [comment]
Right - understood.Yes, I have not seen a crash since toggling the 'detect updates' setting.  I have repeated the steps which previously would have caused the crash or hangup.
Jim

**Comment by Naatan** [comment]
Thanks @jimzag, I'm gonna see about creating a build with increased file notification logging. Until then I would recommend you use the workaround. Note you can manually refresh files by right clicking their tab and hitting "Refresh Status".
