### ISSUE TITLE
Unable to re-launch Komodo Edit due to previous SCP connection

### ISSUE THREAD

**Issue by Duncanmoo** [Komodo/KomodoEdit#2261]
### Short Summary
When starting Komodo Edit it crashes repeatedly if in the previous session the file explorer was connected to an scp resource that is no longer available.

### Steps to Reproduce
1. Open Komodo Edit and connect to a remote server in the "Open Remote Directory..." dialogue
2. Quit Komodo Edit
3. Disconnect your machine from that remote resource
4. Restart Komodo Edit

### Expected results
When I get the dialogue saying "Komodo Edit did not shut down cleanly..." then the file explorer should also not try and open the previous location.

### Actual results
Repeated crashing

### Platform Information

*Komodo Edit* 
*Komodo Version:* 10.1.4
*Operating System:* MacOS Sierra 10.12.2

### Additional Information
**Workaround:**
I edited prefs.xml and modied the values:
```
  <string id="lastHomePlace"></string>
  <string id="lastLocalDirectoryChoice"></string>
  <string id="places-open-nodes-v2"></string>
```

**Comment by Naatan** [comment]
> Repeated crashing

So Komodo outright crashes when you start it? ie. you essentially cannot run it?

**Comment by Duncanmoo** [comment]
Yes that is correct, my workaround allows me to get it running again. In fact even if the scp connection is to a virtual machine on my local, and that machine is running it still crashes.

It may have to do with my ssh connection to the server being private key based authentication?

I have submitted the crash reports (ID: 1484293062 Fri Jan 13 09:38:03 2017)

**Contents of pystderr.log:**
[2017-01-13 09:44:17,738] [INFO] Startup: Welcome to Komodo Edit 10.1.4 build 17456 (platform macosx, running on Darwin 16.3.0 version Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64)
[2017-01-13 09:44:17,738] [INFO] Startup: /Applications/Komodo Edit 10.app/Contents/MacOS/komodo built on Fri Dec 16 18:33:26 2016
[2017-01-13 09:44:17,920] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-01-13 09:44:18,208] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-01-13 09:44:18,263] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2017-01-13 09:44:18,492] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2017-01-13 09:44:18,492] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2017-01-13 09:44:18,727] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-01-13 09:44:18,862] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-01-13 09:44:19,517] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-01-13 09:44:22,257] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-01-13 09:44:22,278] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-01-13 09:44:22,505] [ERROR] console-logger: TypeError: document.getElementById(...) is null (2) in chrome://analytics/content/analytics.js:137
Traceback (most recent call last):
  File "chrome://analytics/content/analytics.js", line 137, in 

[2017-01-13 09:44:22,693] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-01-13 09:44:22,702] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-01-13 09:44:23,882] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2017-01-13 09:44:23,882] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2017-01-13 09:44:23,882] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2017-01-13 09:44:23,882] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2017-01-13 09:44:23,883] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2017-01-13 09:44:23,883] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2017-01-13 09:44:23,884] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2017-01-13 09:44:23,884] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2017-01-13 09:44:24,937] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-01-13 09:44:24,938] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-01-13 09:45:10,129] [WARNING] koSCPConnection: do_authenticateWithPassword::paramiko.BadAuthenticationType: ('Bad authentication type', [u'publickey']) (allowed_types=[u'publickey'])
[2017-01-13 09:45:10,130] [ERROR] koSCPConnection: SCP do_authenticateWithPassword ERROR: Remote SSH server does not allow password authentication. Allowed types are: u'publickey'
[2017-01-13 09:45:10,382] [ERROR] console-logger: NS_ERROR_NOT_AVAILABLE: Cannot call openModalWindow on a hidden window (2) in file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/components/nsPrompter.js:356
Traceback (most recent call last):
  File "file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/components/nsPrompter.js", line 356, in 

[2017-01-13 09:45:10,385] [ERROR] console-logger: NS_ERROR_NOT_AVAILABLE: Cannot call openModalWindow on a hidden window (2) in file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/components/nsPrompter.js:356
Traceback (most recent call last):
  File "file:///Applications/Komodo%20Edit%2010.app/Contents/Resources/components/nsPrompter.js", line 356, in

**Comment by Naatan** [comment]
That log is from when Komodo crashes?

**Comment by Duncanmoo** [comment]
Sorry @Naatan do you just ask silly questions on tickets to improve response time and put the ticket into "Pending: Response" state and it then sits for 4 days. 

Yes I think that is the log from the crash, and here is the output under "Details..." in the ActiveState crash reporter:
AdapterDeviceID: 0x 166
AdapterDriverVersion: 
AdapterVendorID: 0x8086
Add-ons: analytics%40activestate.com:1.0.0,breadcrumbs%40activestate.com:1.0,commando%40activestate.com:1.0,console%40activestate.com:1.0,editorconfig%40activestate.com:1.0.1,fontawesome%40activestate.com:1.0,golang%40activestate.com:1.3.3,icomoon%40activestate.com:1.0,industrial%40openoffice.org:1.0.0,klint%40dafizilla.sourceforge.net:1.4.0,koextgen%40activestate.com:0.2,komodospellchecker%40ActiveState.com:1.0,markdown-viewer%40activestate.com:0.3,openfiles%40activestate.com:1.0,railstools%40activestate.com:0.3.1,trackchanges%40activestate.com:1.0,zendframework%40ActiveState.com:0.8,check-compatibility%40dactyl.googlecode.com:1.3.1,elastic-tabstops%40activestate.com:0.1,focusmode%40activestate.com:1.0.2,kopy%40activestate.com:1.0,lintresults%40activestate.com:1.0,scope-bookmarks%40activestate.com:1.0,scope-combined%40activestate.com:1.0,scope-commands%40activestate.com:1.0,scope-openfiles%40activestate.com:1.0,scope-packages%40activestate.com:1.0,scope-tools%40activestate.com:1.0,scope-files%40activestate.com:1.0
BuildID: 17456
CrashTime: 1484635603
EMCheckCompatibility: false
EventLoopNestingLevel: 1
FramePoisonBase: 7ffffffff0dea000
FramePoisonSize: 4096
InstallTime: 1483957871
Notes: AdapterVendorID: 0x8086, AdapterDeviceID: 0x 166GL Layers? GL Context? GL Context+ GL Layers+ 
ProductID: {b1042fb5-9e9c-11db-b107-000d935d3368}
ProductName: Komodo Edit
PyxpcomMethod: {35c400a4-5792-438c-b915-65e30d58d557}::observe
ReleaseChannel: release
SecondsSinceLastCrash: 229
StartupTime: 1484635597
Theme: classic/1.0
Throttleable: 1
Vendor: ActiveState
Version: 10.1.4
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by Naatan** [comment]
> Sorry @Naatan do you just ask silly questions on tickets to improve response time and put the ticket into "Pending: Response" state and it then sits for 4 days.

That was completely uncalled for. Let me know when you're able to talk in a professional and courteous manner.

**Comment by Duncanmoo** [comment]
Closing the ticket because I said something that irked you is "professional"?

Apologies for criticizing your response style, you seemed to be mirroring what I had already said without moving it forward (and I assumed you were a Komodo Drone tasked with keeping the massive issue list under control).

**Comment by Naatan** [comment]
Criticizing my response style on the basis of your one single bug report. Not to mention you feel the need to berate whilst we supply you with "free" software. 

I take our users very seriously and would never respond without moving the issue forward. My response to you was completely valid, a log is almost completely useless without context.

I will not be spending my time on users that feel the need to treat others with contempt.

Please use a different editor, your attitude is not wanted here.
