### ISSUE TITLE
Cannot view code sidebar in PHP class.

### ISSUE THREAD

**Issue by jolyonralph** [Komodo/KomodoEdit#2266]
### Short Summary
Cannot view code sidebar in PHP class.

### Steps to Reproduce
Open PHP file, click to open code sidebar.

### Expected results
List of class functions as appears correctly with same file in KIDE v9

### Actual results

'Error scanning show_class.php. Unexpected error scanning show_class.php list index out of range.

### Platform Information

*Komodo IDE
*Komodo Version?* 10.1.4
*Operating System (and version)?* MacOS 10.12.2

### Additional Information

[2017-01-15 20:31:25,563] [ERROR] codeintel.citadel: unexpected error scanning `show_class.php'
Traceback (most recent call last):
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 264, in scan
    scan_tree = cile_driver.scan_purelang(self)
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/udl.py", line 616, in scan_purelang
    self.slave_css_cile_driver)
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 1285, in scan_multilang
    csl_tokens, css_tokens = phpciler.scan_multilang_content(buf.accessor.text)
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3426, in scan_multilang_content
    PHPLexer().tokenize_by_style(content, self.token_next)
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/udl.py", line 98, in tokenize_by_style
    return Lexer.tokenize_by_style(self, text, call_back)
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/python/komodo/SilverCity/Lexer.py", line 8, in tokenize_by_style
    call_back
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3386, in token_next
    self._addCodePiece()
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3197, in _addCodePiece
    self._addCodePiece()
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 3238, in _addCodePiece
    doc=self.comment)
  File "/private/var/folders/bj/j1xd10xx03g134rm0817fg5m0000gn/T/AppTranslocation/780E8689-FFA2-45B3-B7C6-8E0CDA1180C1/d/Komodo IDE 10.app/Contents/Resources/distribution/bundles/php_language@ActiveState.com/pylib/lang_php.py", line 2865, in _variableHandler
    assignChar = text[p]
IndexError: list index out of range

**Comment by Naatan** [comment]
This looks like bug #2250, a fix is committed and will be delivered with Komodo 10.2.
