### ISSUE TITLE
python build.py all trying to download the wrong mozilla base

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2290]
For some reason, it's trying to download the top branch:

```
target: all
target: src
running 'wget -t 5 -T 30 --progress=dot:mega -O /home/defman/projects/komodo/source/mozilla/mozilla-release.hg http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/mozilla-release.hg'
--2017-01-27 20:45:40--  http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/mozilla-release.hg
Resolving ftp.mozilla.org (ftp.mozilla.org)... 52.85.214.203
Connecting to ftp.mozilla.org (ftp.mozilla.org)|52.85.214.203|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-27 20:45:40 ERROR 404: Not Found.

Traceback (most recent call last):
  File "build.py", line 2959, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2955, in main
    return build(args)
  File "build.py", line 2779, in build
    newArgv = targetFunc(argv)
  File "build.py", line 2460, in target_all
    target_src()
  File "build.py", line 2110, in target_src
    _run("wget -t 5 -T 30 --progress=dot:mega -O %s %s" % (bundleFile, bundleURL), log.info)
  File "build.py", line 231, in _run
    raise OSError("error running '%s': %r" % (cmd, status))
OSError: error running 'wget -t 5 -T 30 --progress=dot:mega -O /home/defman/projects/komodo/source/mozilla/mozilla-release.hg http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/mozilla-release.hg': 8
```

Here's my config:

```
blessed = False
buildDir = '/home/defman/projects/komodo/source/mozilla/build'
buildOpt = []
buildTag = None
buildType = 'release'
changenum = 0
compiler = None
configureOptions = ['-k', '10.10']
enableMar = True
gcc = '/usr/bin/gcc'
gxx = '/usr/bin/g++'
jsStandalone = False
komodoCommaVersion = '10,10'
komodoUndottedVersion = '1010'
komodoVersion = '10.10'
mozBuildExtensions = []
mozObjDir = 'ko-rel'
mozSrcHgRepo = '3500'
mozSrcHgTag = None
mozSrcName = 'moz3500'
mozSrcScheme = '3500'
mozSrcType = 'hg'
mozVer = 35.0
mozconfig = "# Options for 'configure' (same as command-line options).\nmk_add_options MOZ_OBJDIR=@TOPSRCDIR@/ko-rel\nexport CC=/usr/bin/gcc\nexport CXX=/usr/bin/g++\nac_add_options --enable-stdcxx-compat\nac_add_options --disable-gstreamer\nac_add_options --enable-gold\nac_add_options --enable-help-viewer\nac_add_options --disable-tests\nac_add_options --enable-optimize\nac_add_options --disable-debug\nac_add_options --enable-application=komodo\n"
patchesDirs = ['patches-new']
platform = 'linux-x86_64'
platinfo = {'name': 'linux-x86_64', 'libc': 'libc6', 'distro_codename': 'loki', 'libcpp': 'libcpp6', 'glibc_ver': '2.23', 'arch': 'x86_64', 'distro_ver': '0.4', 'distro_desc': 'elementary OS 0.4 Loki', 'os': 'linux', 'glibc': 'glibc', 'os_ver': '4.4.0', 'distro': 'elementary'}
pyVer = '2.7'
python = '/home/defman/projects/komodo/source/mozilla/prebuilt/python2.7/linux-x86_64/bin/python'
pythonVersion = '2.7'
srcTreeName = 'moz3500-ko10.10'
stripBuild = False
universal = False
withCrashReportSymbols = False
withPGOCollection = False
withPGOGeneration = False
```

**Comment by Naatan** [comment]
@mook-as noted they appear to have moved these files. They can now be found at:

https://hg.cdn.mozilla.net/

@cgchoffman we'll have to update our build script.

**Comment by mook-as** [comment]
As I understand it, newer versions of Mercurial will grab the bundles automatically as needed (because the server advertises them), and the magic in our build scripts to do it manually is no longer needed.

**Comment by cgchoffman** [comment]
@mook-as is the magic you're referring to the steps where the repo is unbundled and patches are applied to get it to the correct version?  We can now just do something like `hg pull URL -versione`?

**Comment by mook-as** [comment]
I'm talking about [getBundleFromTree](https://github.com/Komodo/KomodoEdit/blob/c5ad0f9eefb7bde49e827b4e5bf140016c934c10/mozilla/support/get_mozilla_tree.py#L152), yeah. `cloneFromTree` should be able to just `hg clone URL --rev TAG` or something instead.  (Please test, of course.)

**Comment by cgchoffman** [comment]
> (Please test, of course.)

Never.

K i'll have a look.  Thanks for the heads up @mook-as and @Defman21.

**Comment by Defman21** [comment]
>Never.

Lol.

**Comment by cgchoffman** [comment]
This is fixed for the build system but haven't had time to look into implementing the suggestion from @mook-as.  Unfortunately, resolving this for external builds isn't a priority as very few people seem to build Komodo themselves.  PRs Welcome.

https://github.com/Komodo/KomodoEdit/commit/3395c204d447924d3a30563e59e07b96d260cbde

**Comment by Defman21** [comment]
I have a temporary workaround:

```diff
diff --git a/mozilla/build.py b/mozilla/build.py
index 2d546c774..044c823c7 100644
--- a/mozilla/build.py
+++ b/mozilla/build.py
@@ -2082,7 +2082,7 @@ def target_src(argv=["src"]):
         repoURL = getRepoFromTree(treeName)
         hgRepo = os.path.join(buildDir, "mozilla")
         bundleFile = os.path.abspath("%s.hg" % (treeName,))
-        bundleURL = "http://ftp.mozilla.org/pub/mozilla.org/firefox/bundles/%s.hg" % (treeName,)
+        bundleURL = "https://hg.cdn.mozilla.net/releases/mozilla-release/77d543972ad3279f0920e9eb1b236a3d0e9873c7.stream-legacy.hg"
 
         def inside_activestate_network():
             import socket
@@ -2109,7 +2109,7 @@ def target_src(argv=["src"]):
 
         _run("wget -t 5 -T 30 --progress=dot:mega -O %s %s" % (bundleFile, bundleURL), log.info)
         _run("hg init %s" % (hgRepo,), log.info)
-        _run("hg --cwd %s unbundle %s" % (hgRepo, bundleFile), log.info)
+        _run("hg --cwd %s debugapplystreamclonebundle %s" % (hgRepo, bundleFile), log.info)
         os.unlink(bundleFile)
         fixRemoteRepo(treeName, hgRepo)
         _run("hg --cwd %s pull" % (hgRepo,), log.info)
```

**Comment by Naatan** [comment]
Thanks @cgchoffman, basically we need to be able to detect what the url is. Since that URL does not look like it will remain the same after a new version is released.

**Comment by Naatan** [comment]
Should be able to get that from here: 

https://hg.cdn.mozilla.net/bundles.json

**Comment by Defman21** [comment]
What about the `hg debugapplystreamclonebundle` command? Is it ok?

**Comment by Naatan** [comment]
That's not really something that belongs in production, it's for debugging.
