### ISSUE TITLE
Can't drag and drop tools on toolbox any more

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2310]
### Short Summary

When you drag and drop a tool on the toolbox (not to be confused with dropping it on the editor which does something else) nothing appears to happen but the source file will disappear but nothing will be added to the toolbox.  Also note that you have to drop the tool on an empty space in the toolbox to hit this, NOT an item in the toolbox. 

It's working in:
Komodo IDE, version 10.2.0-alpha1, build 89798, platform win32-x86.
Built on Tue Jan 31 01:00:32 2017.

But it's not working in my local build.  I'm guessing it's due to @Naatan new Tools format changes.  I believe you/I/someone needs to redo the toolbox handler for `doDrop` in toolbox_commands: https://github.com/Komodo/KomodoIDE/blob/master//src/chrome/komodo/content/toolbox/toolbox2_command.p.js#L1498

I assume there is a new import function that's not being used.

**Comment by cgchoffman** [comment]
Looks like the files get copied into the profile\tools folder but then Komodo tries to reload the toolbox and fails:
```
[2017-02-02 15:38:03,971] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\AppData\Local\ActiveState\KomodoIDE\10.10\tools\Reload_open_files.komodotool
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 1727, in _testAndAddItem
    data = DataParser.readJsonData(fp)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 1984, in readJsonData
    return json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 14 column 2 - line 14 column 3 (char 275 - 276)
```

**Comment by Naatan** [comment]
@cgchoffman local build is 11, not 10.2 :) My change didn't land in 10.2.

**Comment by cgchoffman** [comment]
Ahh good.

**Comment by cgchoffman** [comment]
can't reproduce this any more
