### ISSUE TITLE
Logs are full of  `this._getRequireMethod is not a function` errors

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2348]
There isn't really any reproduction steps.  You'll just see the errors start to dump repeatedly into the logs.  Full error below:
```
[2017-02-16 15:32:32,822] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:227
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 227, in 
```

**Comment by Naatan** [comment]
Could you share a full log? I don't see any reason why this would happen, unless something was failing earlier on. 

I'm not seeing these errors myself.

**Comment by cgchoffman** [comment]
```
[2017-02-17 09:49:11,599] [INFO] Startup: Welcome to Komodo IDE 10.10.0-devel build 89487 (platform win64-x64, running on Windows post2012Server version 6.3.9600)
[2017-02-17 09:49:11,599] [INFO] Startup: C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\komodo.exe built on Thu Sep 15 11:51:16 2016
[2017-02-17 09:49:12,454] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-02-17 09:49:13,368] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-02-17 09:49:14,642] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2017-02-17 09:49:15,244] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-02-17 09:49:15,349] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-02-17 09:49:15,424] [INFO] komodospellchecker: Spell checker loaded.
[2017-02-17 09:49:15,426] [INFO] komodospellchecker: Using dictionary en-US
[2017-02-17 09:49:20,246] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/mozbuilds/IDE-10.10/moz3500-ko10.10/mozilla/ko-rel/dist/bin/components/koamAddonManager.js:138
[2017-02-17 09:49:20,483] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:20,486] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:20,486] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:20,499] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:20,500] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:20,502] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:23,052] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:23,052] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:23,052] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-17 09:49:24,832] [WARNING] console-logger: TypeError: variable src redeclares argument (5) in chrome://komodo/content/contrib/commonjs/marked.js:150
[2017-02-17 09:49:25,216] [ERROR] codeintel.komodo.KoCodeIntelManager: failed to get langAppInfo.version for language JavaScript
[2017-02-17 09:49:39,124] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-02-17 09:49:39,151] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-02-17 09:50:09,267] [WARNING] console-logger: ReferenceError: reference to undefined property this._path (5) in resource://gre/modules/osfile/osfile_win_front.jsm:901
[2017-02-17 09:52:06,210] [WARNING] console-logger: ReferenceError: reference to undefined property this.currentView.minimap (5) in chrome://komodo/content/views.js:2429
[2017-02-17 09:52:07,107] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-17 09:52:07,107] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-17 09:52:07,108] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-17 09:52:07,108] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-17 09:52:07,108] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-17 09:52:07,627] [WARNING] console-logger: ReferenceError: reference to undefined property bo.height (5) in chrome://komodo/content/find/find2.js:1679
[2017-02-17 09:52:08,099] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-02-17 09:52:08,101] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-02-17 09:52:08,105] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-02-17 09:52:09,571] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:227
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 227, in 

[2017-02-17 09:52:09,582] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:227
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 227, in 

[2017-02-17 09:52:10,575] [WARNING] console-logger: ReferenceError: assignment to undeclared variable w (d) in chrome://komodo/content/sdk/dialogs.js:194
[2017-02-17 09:52:14,085] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-17 09:52:14,086] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-17 09:52:14,088] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-17 09:52:14,088] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-17 09:52:14,089] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-17 09:52:32,051] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-02-17 09:52:32,052] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-02-17 09:52:32,404] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-02-17 09:52:32,405] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-02-17 09:52:32,592] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-02-17 09:52:32,592] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-02-17 09:52:33,009] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-02-17 09:52:33,009] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-02-17 09:52:35,622] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:227
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 227, in 

[2017-02-17 09:52:35,642] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:227
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 227, in 

[2017-02-17 09:52:35,653] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:227
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 227, in 

[2017-02-17 09:52:38,457] [WARNING] views: Inconsistent view count in view_closed event
[2017-02-17 09:52:38,875] [WARNING] views: Inconsistent view count in view_opened event
[2017-02-17 09:52:39,201] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-02-17 09:52:39,203] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2017-02-17 09:52:39,448] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
[2017-02-17 09:52:39,450] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
```

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/commit/03b44a20e7cde086d89a7bbb42aeb579671212c3 ?

**Comment by cgchoffman** [comment]
> 03b44a2 ?

yup
