### ISSUE TITLE
Backend File services break on startup with fresh profile

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2350]
### Short Summary

When I start my local 10.2.0 branch build (pulled in the latest as of 4pm PST) with a fresh profile there are some ugly errors in the logs and a lot of file status services don't work anymore.

### Steps to Reproduce

- build latest 10.2.0 branch or pull tomorrows RC
- set KOMODO_USERDATADIR
- start Komodo
- open a git enable project or file

### Expected results

Git stuff

### Actual results

The VC pane looks like it's working but it will never load any actually current repo information like changed files, untracked files, etc.
Also, if you change and save your open file, trackchanges will not reflect changes against the last commit and the file name in Places will not turn blue

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 10.2
*Operating System (and version)?* Windows

### Additional Information

```
[2017-02-16 16:43:51,375] [INFO] Startup: Welcome to Komodo IDE 10.10.0-devel build 89487 (platform win64-x64, running on Windows post2012Server version 6.3.9600)
[2017-02-16 16:43:51,375] [INFO] Startup: C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\komodo.exe built on Thu Sep 15 11:51:16 2016
[2017-02-16 16:43:52,203] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-02-16 16:43:53,023] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-02-16 16:43:54,253] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2017-02-16 16:43:54,809] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-02-16 16:43:54,907] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-02-16 16:43:54,973] [INFO] komodospellchecker: Spell checker loaded.
[2017-02-16 16:43:54,973] [INFO] komodospellchecker: Using dictionary en-US
[2017-02-16 16:43:59,361] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/mozbuilds/IDE-10.10/moz3500-ko10.10/mozilla/ko-rel/dist/bin/components/koamAddonManager.js:138
[2017-02-16 16:43:59,691] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:43:59,694] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:43:59,694] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:43:59,704] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:43:59,707] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:43:59,709] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:44:01,819] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:44:01,821] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:44:01,822] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-16 16:44:02,963] [ERROR] codeintel.komodo.KoCodeIntelManager: failed to get langAppInfo.version for language JavaScript
ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: sccType
[2017-02-16 16:44:04,736] [ERROR] koFileStatusService: unexpected error from koIFile.isDirectory
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileStatusService.py", line 56, in sortFileStatus
    if a[0].isDirectory and not b[0].isDirectory:
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isDirectory
[2017-02-16 16:44:04,759] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileStatusService.py", line 466, in _process
    if u.isLocal and not u.isNetworkFile:
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2017-02-16 16:44:04,779] [ERROR] koFileStatusService: Exception checking uri: None
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileStatusService.py", line 621, in _process
    reason):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\komodo\fileStatusUtils.py", line 250, in updateFileStatus
    if koIFile.isLocal and not koIFile.isNetworkFile:
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2017-02-16 16:44:04,805] [ERROR] koFileStatusService: Exception detail: AttributeError('isLocal',)
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileStatusService.py", line 621, in _process
    reason):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\komodo\fileStatusUtils.py", line 250, in updateFileStatus
    if koIFile.isLocal and not koIFile.isNetworkFile:
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2017-02-16 16:44:04,832] [ERROR] koFileStatusService: KoFileStatusService thread exception Traceback (most recent call last):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\components\koFileStatusService.py", line 590, in _process
    reason):
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\extensions\publishing@ActiveState.com\components\koPublishingStatus.py", line 164, in needsToReCheckFileStatus
    uri_cache_key = self._norm_uri_cache_key(koFile.URI)
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\bin\python\komodo\fileStatusUtils.py", line 107, in _norm_uri_cache_key
    uri = unescapeURL(uri).strip("/")
  File "C:\mozbuilds\IDE-10.10\moz3500-ko10.10\mozilla\ko-rel\dist\python\lib\urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'
[SNIP]
```

**Comment by Naatan** [comment]
Are you sure this is 10.2 after a distclean? This looks like the error I got when I switched from master to 10.2 without a distclean.

**Comment by cgchoffman** [comment]
If you can't reproduce I'll try another disk clean.

**Comment by cgchoffman** [comment]
Distclean seems to have fixed it.  Thanks @Naatan.  I'm
