### ISSUE TITLE
Auto-Abbreviations not working in 10.2

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2365]
### Short Summary
Auto-Abbreviations are not working in Komodo 10.2. I have some custom abbreviations for different languages. But they all don't work anymore in Komodo 10.2.
Even if I use the "insert abbreviations by name" it can't find the abbreviation.

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23246605/34fc7398-f995-11e6-9e0b-2c76825fa57e.png)

### Steps to Reproduce
Try to insert a Auto-Abbreviations.

### Expected results
Abbreviations will be insert.

### Actual results
No Abbreviations is found/inserted

### Platform Information
Komodo 10.2 Windows 10

**Comment by cgchoffman** [comment]
Logs please.

**Comment by babobski** [comment]
```
[2017-02-23 09:48:56,045] [INFO] Startup: Welcome to Komodo IDE 10.2.0 build 89833 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-02-23 09:48:56,045] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 10.2\lib\mozilla\komodo.exe built on Fri Feb 17 15:10:04 2017
[2017-02-23 09:49:00,207] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-02-23 09:49:00,207] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.2/XRE/extensions/emmet@chikuyonok.ru/chrome.manifest:1
[2017-02-23 09:49:00,207] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/Bob/AppData/Local/ActiveState/KomodoIDE/10.2/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2017-02-23 09:49:00,302] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-02-23 09:49:00,913] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-02-23 09:49:01,303] [DEBUG] console: log: Less has finished and no sheets were loaded.
[2017-02-23 09:49:02,226] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2017-02-23 09:49:07,921] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-02-23 09:49:09,023] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-02-23 09:49:10,039] [INFO] komodospellchecker: Spell checker loaded.
[2017-02-23 09:49:10,039] [INFO] komodospellchecker: Using dictionary en-US
[2017-02-23 09:49:10,446] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-02-23 09:49:11,795] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-02-23 09:49:11,809] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-02-23 09:49:13,006] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-02-23 09:49:13,124] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-02-23 09:49:13,249] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-02-23 09:49:15,217] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-02-23 09:49:15,249] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-02-23 09:49:15,263] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-02-23 09:49:18,290] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-02-23 09:49:18,290] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-02-23 09:49:18,290] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-02-23 09:49:18,290] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-02-23 09:49:18,290] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-02-23 09:49:18,290] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-02-23 09:49:18,290] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2010.2/lib/mozilla/components/koamAddonManager.js:138
[2017-02-23 09:49:18,836] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-23 09:49:18,836] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-23 09:49:18,836] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-02-23 09:49:19,118] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2017-02-23 09:49:19,118] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
ERROR:xpcom:Unhandled exception calling 'int8 * newURI(in utf8string &, in string, in nsISomething, out retval nsISomething);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10.2\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10.2\lib\mozilla\components\koSFTP.py", line 47, in newURI
    self.defaultPort, aSpec, aOriginCharset, aBaseURI)
  File "<XPCOMObject method 'init'>", line 3, in init
Exception: 2152398858 (NS_NET_STATUS_WAITING_FOR)
[2017-02-23 09:49:20,589] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:20,605] [ERROR] console-logger: Error: invalid URI: sftp://path to server/dev/httpdocs/narrowcasting (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js:37
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js", line 37, in 

[2017-02-23 09:49:20,621] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:20,637] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:20,653] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:21,855] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-23 09:49:21,855] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-02-23 09:49:21,855] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
ERROR:xpcom:Unhandled exception calling 'int8 * newURI(in utf8string &, in string, in nsISomething, out retval nsISomething);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10.2\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10.2\lib\mozilla\components\koSFTP.py", line 47, in newURI
    self.defaultPort, aSpec, aOriginCharset, aBaseURI)
  File "<XPCOMObject method 'init'>", line 3, in init
Exception: 2152398858 (NS_NET_STATUS_WAITING_FOR)
[2017-02-23 09:49:22,657] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:22,657] [ERROR] console-logger: Error: invalid URI: sftp://path to server/dev/httpdocs/narrowcasting (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js:37
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js", line 37, in 

[2017-02-23 09:49:22,674] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:22,690] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:22,690] [ERROR] console-logger: Error: 'sftp://path to server/dev/httpdocs/narrowcasting' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:168
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 168, in 

[2017-02-23 09:49:30,500] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-23 09:49:30,500] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-02-23 09:49:30,500] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by Naatan** [comment]
Can you show us a screenshot of your "log" snippet?

**Comment by babobski** [comment]
of course:
![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23267330/b4778dce-f9ea-11e6-9384-13395a28595e.png)

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23267602/80569ade-f9eb-11e6-9673-b6e15a4aa952.png)

I have the problem at home and at work, none of my custom Abbreviations are working.
Javascript:
```
log => console.log([cursor]);
```
Less:
```
dark => darken([tabstop], [tabstop:10%]);
light => lighten([tabstop], [tabstop:10%]);
@media => media(max-width: [tabstop:1200px]) {
[tabstop]
}
```

**Comment by Naatan** [comment]
The problem is your snippet was located in a custom subfolder, as a result it did not get a language set to it when it upgrated to 10.2. You need to manually select "JavaScript" from the "Pick a Language" dropdown.

I think this is sufficiently niche that it doesn't require fixing, but let's keep an eye out for this @cgchoffman.

**Comment by cgchoffman** [comment]
The upgrade script should have worked here but I can see why it didn't.  I used the Komodo languages to compare against the folders.  It's `JavaScript` in Komodo.  I should have made the comparison code lowercase all the strings.

**Comment by Naatan** [comment]
@cgchoffman did you notice it's in a sub folder called "console" ?

**Comment by cgchoffman** [comment]
Yep, that shouldn't matter.  The upgrade script cycles up the folder hierarchy until it finds a folder name that matches a language then sets it otherwise it moves on.  It should have hit `Javascript` and set that but it was probably looking for `JavaScript` :(

**Comment by babobski** [comment]
Ah, that's going on. Got it working now.

**Comment by cgchoffman** [comment]
@babobski, to clarify, you no longer rely on the folder structure of your Abbreviations folder.  Your snippets can be anywhere in your toolbox.  As long as they have a language field set in the snippet it will work in the correct files.  I think you saw that but just wanted to make sure.

**Comment by mistergraphx** [comment]
Hi 

is this ok in latest build : Komodo Edit, version 10.2.1, build 17665 ?

Indentation/expand is back in the editor but i can't have Abbreviations/snippets work in this release.
I always get "No abbreviation found".

**Comment by babobski** [comment]
@mistergraphx it should be fixed in the latest build as mentioned in this [post](http://community.komodoide.com/t/insert-abbreviation-snippet-by-name-broken-in-10-2/3420), if I look at your build number your using the latest release. 

Do you have the correct language configured in your abbreviation?

![afbeelding](https://cloud.githubusercontent.com/assets/3530262/23586136/96f0f6c6-018f-11e7-91af-8c9df221f510.png)

**Comment by mistergraphx** [comment]
Yes, i've modified all my snippets, since 10.2.0 and it was working as expected. This is broken since last  two updates, it seems.

![capture d ecran 2017-03-05 a 10 52 46](https://cloud.githubusercontent.com/assets/2979188/23586265/18f93000-0192-11e7-9dd0-3b00bb497c6a.png)

Anyway I can use the GoTo Anything dialog, thanks for solving the indentation bug so quickly wich was most annoying for me ;-)

I'm running mac osx 10.9 if it could help.

**Comment by cgchoffman** [comment]
@mistergraphx, it's working fine for me:
Komodo IDE, version 10.2.1, build 89847, platform win32-x86.
Built on Thu Mar 02 12:26:28 2017.

If it's still broken for you please file a new bug with appropriate details.

@babobski is it broken for you as well?

**Comment by babobski** [comment]
@cgchoffman Tested this yesterday, downloaded the latest Edit version. But this is also working for me. 
I see a lot of linting errors, so I think it might detects the wrong sub-language.

@mistergraphx noticed your using HTML5 but you have your syntax checking enabled for HTML, are all the linting results HTML related?

**Comment by cgchoffman** [comment]
Thanks for confirming @babobski.  @mistergraphx please file a new ticket.  Any debugging of your issues should be done in a new report since it is not related to the original reported issue.

**Comment by mistergraphx** [comment]
Thanks for your answer, i've filled a new issue here #2384

**Comment by cgchoffman** [comment]
@babobski, can you confirm what your abbreviations have set for "Auto-Abbreviation"?  Based on what I found in researching and fixing #2384 it looks like this should have been broken for you too, unless you have `Auto-Abbreviations` disabled in the snippets that are working.

**Comment by babobski** [comment]
Confirmed is broken in the latest nightly if "auto-abbrevation" is checked.

Note: I'm still using 10.2 for my daily work, but enabled "auto-abbrevation" for all my snippets as workaround for the original issue.
