### ISSUE TITLE
Re-launch w/ two windows causes 'Internal Komodo Error' Recursively

### ISSUE THREAD

**Issue by rcrowleyii** [Komodo/KomodoEdit#239]
UPDATE: The information below still applies, but I learned something new after mentioning this in the forums. This problem only appears when I open more than one window. I use two monitors, so I'm almost always working with one window in each at full screen. If I re-launch with just one window, I do not get the error dialog and no issues arise.

I recently upgraded from Komodo 8 to Komodo 9. When I relaunch the application the following error dialog box appears:

![untitled](https://cloud.githubusercontent.com/assets/1385045/7417384/994afe82-ef1a-11e4-81b1-2971f7b12853.jpg)

I cannot type anything into the text box and clicking 'OK' results in a new box appearing. To get back to work, I quit Komodo and click 'No' when the 'Komodo did not shutdown cleanly....Would you like to restore files..."  dialog box appears. If I click 'Yes' Komodo (logically) just does what it did last time with the Internal Komodo Error loop..

Here is what appears in the Komodo error log:

[2015-04-17 08:49:46,615] [INFO] Startup: Welcome to Komodo IDE 9.0.0 build 87165 (platform macosx, running on Darwin 14.3.0 version Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64)
[2015-04-17 08:49:46,615] [INFO] Startup: /Applications/Komodo IDE 9.app/Contents/MacOS/komodo built on Tue Mar 24 18:39:57 2015
[2015-04-17 08:49:46,751] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2015-04-17 08:49:47,199] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-04-17 08:49:47,200] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-04-17 08:49:47,201] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-04-17 08:49:47,201] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-04-17 08:49:47,245] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2316
[2015-04-17 08:49:47,285] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2316
[2015-04-17 08:49:47,314] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-04-17 08:49:47,618] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-04-17 08:49:47,618] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-04-17 08:49:48,072] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/components/koamAddonManager.js:138
[2015-04-17 08:49:48,834] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-17 08:49:48,958] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-17 08:49:49,303] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-17 08:49:50,945] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-04-17 08:49:51,502] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-04-17 08:49:51,511] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-04-17 08:49:51,512] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-04-17 08:49:51,782] [ERROR] console-logger: TypeError: Argument 2 of EventTarget.addEventListener is not an object. (2) in chrome://todo/content/todo-ko7.js:582
Traceback (most recent call last):
  File "chrome://todo/content/todo-ko7.js", line 582, in 

[2015-04-17 08:49:52,047] [DEBUG] places_js: waiting for document complete
[2015-04-17 08:49:52,850] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-04-17 08:49:53,380] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-04-17 08:49:53,400] [DEBUG] places_js: waiting for document complete
[2015-04-17 08:49:53,480] [ERROR] peMenu: 
-- EXCEPTION START --
TypeError: this.manager is undefined
+ stack
    this.getCustomMenus@chrome://komodo/content/toolbox/toolbox2.js:574:5
    this.onToolboxLoaded@chrome://komodo/content/project/peMenu.js:367:13
    peMenu.prototype.observe_aux@chrome://komodo/content/project/peMenu.js:122:17
    peMenu.prototype.observe/<@chrome://komodo/content/project/peMenu.js:63:17
-- EXCEPTION END --
[2015-04-17 08:49:53,480] [ERROR] peMenu: 
-- EXCEPTION START --
TypeError: this.manager is undefined
+ stack
    this.getCustomMenus@chrome://komodo/content/toolbox/toolbox2.js:574:5
    this.onToolboxLoaded@chrome://komodo/content/project/peMenu.js:367:13
    peMenu.prototype.observe_aux@chrome://komodo/content/project/peMenu.js:122:17
    peMenu.prototype.observe/<@chrome://komodo/content/project/peMenu.js:63:17
-- EXCEPTION END --
[2015-04-17 08:49:53,692] [ERROR] codeintel.komodo.KoCodeIntelManager: Error reading data from codeintel
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koCodeIntel.py", line 1174, in run
    self.handle(response)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/components.py", line 263, in wrapperFn
    threadMgr.mainThread.dispatch(method, dispatch_flags)
  File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)

**Comment by cgchoffman** [comment]
Hi Ross, this was fixed a few weeks ago and release in nightly builds.  it's now available in Komodo 9.0.1
See issue #171 

Try updating; Help > Check for Updates
or reinstalling http://downloads.activestate.com/Komodo/releases/9.0.1/
