### ISSUE TITLE
Komodo can't parse ActiveGo version output

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2412]
### Short Summary

Komodo fails to retrieve Go version when Go tool path is set.

### Steps to Reproduce

- Install ActiveGo
- Open  komodo Prefs > Languages > Go
- Set path to go.exe(go.so on osx and linux?)

### Expected results

Nothing

### Actual results

There is an error in the logs

### Additional Information

```
[2017-03-21 13:35:39,466] [ERROR] koAppInfo: Failed to check version of executable c:\activego\bin\go.exe
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\components\koAppInfo.py", line 190, in _isValidExecutable
    isvalid = self._isValidExecutableVersion(exe)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\components\koAppInfo.py", line 161, in _isValidExecutableVersion
    ver = self.getVersionForBinary(exe)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\extensions\golang@activestate.com\components\koGoAppInfo.py", line 56, in getVersionForBinary
    raise ServerException(nsError.NS_ERROR_UNEXPECTED, msg)
ServerException: 2147549183 (Can't find a version in `c:\activego\bin\go.exe -v` output of 'ActiveGo 1800 (beta) [402177] provided by ActiveState Software, Inc.
Built Tue Mar 21 13:35:39 PDT 2017

go version go1.8 windows/amd64
'/'')
```

**Comment by Naatan** [comment]
We need to change our re.match to re.search.
