### ISSUE TITLE
Komodo Code intel tries to build `outline.go` in a protected folder

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2414]
Sorry for the sparse report here.  I don't know what this code is supposed to be doing but it breaks on Windows. Code Browser doesn't seem to work either, nor the sections list.

I installed ActiveGo and configured it in prefs.  I have tried this with a community install of GO as well but it still doesn't work.

There is no code intelligence and I'm assuming it's because of this line in the docs:
`[2017-03-21 13:38:19,285] [WARNING] codeintel.go: '['go', 'build', 'C:\\Users\\cgcho\\Komodo IDE Latest\\lib\\mozilla\\extensions\\golang@activestate.com\\golib\\outline.go']' stderr: [mkdir C:\WINDOWS\go-build877789219: Access is denied.]`

**Comment by cgchoffman** [comment]
I'm not sure if these two errors are related but I restarted Komodo and I still can't get completions.  I'm getting this error every time I try:
```
[2017-03-21 15:10:57,506] [ERROR] koCodeIntel: godef: no identifier found
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 568, in run
    handler.handleRequest(request, self)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 626, in handleRequest
    meth(request, driver)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 885, in do_eval
    buf.async_eval_at_trg(trg, ctlr)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\python\komodo\codeintel2\buffer.py", line 215, in async_eval_at_trg
    self.langintel.async_eval_at_trg(self, trg, ctlr)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\extensions\golang@activestate.com\pylib\codeintel_go.py", line 230, in async_eval_at_trg
    return self.lookup_defn(buf, trg, ctlr)
  File "C:\Users\cgcho\Komodo IDE Latest\lib\mozilla\extensions\golang@activestate.com\pylib\codeintel_go.py", line 250, in lookup_defn
    raise CodeIntelError(error)
CodeIntelError: godef: no identifier found
```

I do have Prefs > Langs > Go > Godef set.

**Comment by mitchell-as** [comment]
@cgchoffman Please install the Komodo Developer Extension if you don't already have it, go to Tools > Extension Developer > Pyshell. Then enter:

  import tempfile
  tempfile.gettempdir()

What is the output? Is it `C:\WINDOWS`?

**Comment by cgchoffman** [comment]
I get the following:
```
import tempfile
tempfile.gettempdir()
'c:\\users\\cgcho\\appdata\\local\\temp'
```

**Comment by mitchell-as** [comment]
That's really weird. The outline is built in the directory given by `tempfile.gettempdir()`. I can't see where the error message is getting `C:\WINDOWS\go-buildX` from...

**Comment by Naatan** [comment]
I wonder if your earlier fix is related @mitchell-as.

@cgchoffman you should see if you can still repro this with tomorrows nightly.

**Comment by cgchoffman** [comment]
Sections list and code browser are working.  Go To Def is also working though I don't think that was related to this ticket.  I'm still not getting any completions, even for key words but I'm not clear if I"m supposed to be.  If we don't support code scanning to give completions we should at least support Go key words.  That can be done with Project > New From Template > New Komodo Language.
