### ISSUE TITLE
Color Scheme Editor doesn't display foreground / backgorund settings when it loads with "Editor" selected

### ISSUE THREAD

**Issue by rm-bergmann** [Komodo/KomodoEdit#2427]
### Short Summary

Color Scheme Editor doesn't display foreground / backgorund settings when it loads with "Editor" selected

### Steps to Reproduce

- Edit > Preferneces > Color Scheme > Open COlor Scheme Editor
- Make sure "Editor" is selected by default. There should be no foreground / background settings displaying in the center.
- Try click on 'Font' / 'Class' / 'Function.

![color-scheme](https://cloud.githubusercontent.com/assets/7300540/24463557/f6df95b6-149e-11e7-866c-b5eb69a69cdb.jpg)
'

### Expected results

I am expecting to see forground / background settings

### Actual results

No settings are displayed in the center. Screenshot and error log attached 

### Platform Information

*Komodo IDE X* 
*Operating System (and version)? Windows 10

### Additional Information

[komodo-error-log.txt](https://github.com/Komodo/KomodoEdit/files/879582/komodo-error-log.txt)

**Comment by Naatan** [comment]
Can you reproduce the problem with a different color scheme (one of the defaults maybe)? Looking at the log this may be related to your color scheme defining some colors that Komodo does not recognize.

**Comment by rm-bergmann** [comment]
It works fine when a default color scheme loads. My custom color scheme was created with Komodo IDE 8 / 9, then and it has been transfered every time I upgrade, so any colours I used originally came from an older version. The color picker was limited in the previous versions anyway, so best I create a new color scheme anyway.

**Comment by Naatan** [comment]
Alright, thanks for confirming.

**Comment by rm-bergmann** [comment]
Hi @Naatan 

I was tweaking my Komodo UI today and got it looking the best I've had it so far. Unfortunately I created a new file, somehow got an error and had to close Komodo and then lost some coulour changes. It's fine anyway, I have almost got it looking like it was, but struggling with some this bug mentioned above:

I still get this 'Color scheme editor bug' which I reported a while back, which makes it very difficult to tweak the UI. If I can get passed this it will help me find the right colours and contrast colours for the various parts of the UI. I don't want to change my colour profile and start all over again as I have a lot of custom colours for various languages I use etc (which I created and tweaked since Komodo 8). 

-- How do I find those problem colours that are causing this error and what they are attached to and replace them with similar colours so that Komodo can recognise them ? I have tried doing it via the color scheme editor but it breaks in some cases so I can't replace those colours in the color scheme editor.

I have opened (and attached) my 'profile' ksf file and can see a many of those settings.

The only languages I would have edited syntax colours for are : Javascript, PHP, CSS & LESS, so I assume the errors would be coming from within there.

[profile.zip](https://github.com/Komodo/KomodoEdit/files/1561272/profile.zip)

This is UI at it's current state, but still struggling with the contrast colours in the file browser. 

<img src="https://1drv.ms/i/s!Atsicy6FllW64HWG9isNe6n_az57" />

**Comment by rm-bergmann** [comment]
I just reproduced the problem mentioned in the above comment - when I create a new file - something breaks, and komodo says "Unable to open the file". The file is created and displays in the file browser but can't be opened.

I'm attaching the log file here:
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/1561325/pystderr.log)

This time I didn't loose any settings after re-opening, but when it re-opens, it opens without the files that I had opened before. The file opens fine after restarting komodo.

**Comment by Naatan** [comment]
Relevant error:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\components\koScintillaSchemeService.py", line 456, in getColor
    scincolor = self._colors[colorName]
KeyError: 'foldMarginColor'
[2017-12-14 23:17:20,436] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-12-14 23:17:20,638] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.getColor] (2) in chrome://komodo/content/dialogs/colorscheme.js:1002
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/colorscheme.js", line 1002, in 

[2017-12-14 23:17:25,555] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/dialogs/colorscheme.xul:0
ERROR:xpcom:Unhandled exception calling 'int8 * getColor(in string, out retval string);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\components\koScintillaSchemeService.py", line 456, in getColor
    scincolor = self._colors[colorName]
KeyError: 'foldMarginColor'
[2017-12-14 23:17:33,417] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaScheme.getColor] (2) in chrome://komodo/content/dialogs/colorscheme.js:1002
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/colorscheme.js", line 1002, in 
```

It seems it might have been looking at a color scheme that was corrupted or was for a much older version of Komodo. Either way we should handle this better.

For your other questions please open a new ticket or post on the forum. We handle one issue per ticket here on the issue tracker as otherwise it is hard to keep track of things.

**Comment by rm-bergmann** [comment]
Looks like I managed to fix this in my profile ksf file.

KeyError: 'foldMarginColor'

foldMarginColor did not exist in my profile ksf file. I opened a different profile ksf and saw it there so I copied it to my profile : 'foldMarginColor': 3160120

The color scheme editor seems to be a lot smoother now. If I find new errors I will update it here.

As for the other issue I mentioned, I will open a new ticket if it happens again and if I can state all steps to reproduce it.

Thanks.
