### ISSUE TITLE
codeintel mulfunction

### ISSUE THREAD

**Issue by ko-ichi-h** [Komodo/KomodoEdit#243]
Hello,

When I open some Perl files, I got errors like these in the "notification" tab of the bottom pain:

> AttributeError: 'NoneType' object has no attribute 'get'
> KeyError: u'gui_widget'

'gui_widget' here is the name of the Perl package as you see in the attached image. 

When it happens, the list of subroutines in the file (the "Code" tab of the right pain) will not be displayed. It is very inconvenient and destroy my productivity.

In the log file, I see the following logs. It looks like it happens only in MS Windows environment. I use Windows 8.1 Japanese.

Sorry for my poor English.

![komodo_errors](https://cloud.githubusercontent.com/assets/12220822/7445213/680ecaac-f1e4-11e4-8794-27689ca42e14.png)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[2015-05-03 22:17:01,799] [ERROR] codeintel.oop.driver: gui_widget
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 36, in do_get_buffer
    if buf.scan_time is None and not buf.accessor.content:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 171, in scan_time
    self._load_buf_data_once()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 808, in get_buf_data
    dbsubpath = join(dhash, dbfile_from_blobname[blobname])
KeyError: u'gui_widget'
[2015-05-03 22:17:01,861] [ERROR] koCodeIntel: gui_widget
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 36, in do_get_buffer
    if buf.scan_time is None and not buf.accessor.content:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 171, in scan_time
    self._load_buf_data_once()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 808, in get_buf_data
    dbsubpath = join(dhash, dbfile_from_blobname[blobname])
KeyError: u'gui_widget'

[2015-05-03 22:17:01,877] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 622, in handleRequest
    meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 885, in do_get_sections
    sections = buf.get_sections()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\buffer.py", line 411, in get_sections
    return self.cached_sections
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'
[2015-05-03 22:17:01,877] [ERROR] koCodeIntel: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 622, in handleRequest
    meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 885, in do_get_sections
    sections = buf.get_sections()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\buffer.py", line 411, in get_sections
    return self.cached_sections
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'

[2015-05-03 22:17:03,111] [ERROR] codeintel.indexer: unexpected internal error in indexer: ignoring and continuing
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\indexer.py", line 516, in run
    self._iteration()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\indexer.py", line 583, in _iteration
    buf.scan(mtime=request.mtime)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'gui_widget'
[2015-05-03 22:17:03,127] [ERROR] codeintel.oop.driver: gui_widget
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'gui_widget'
[2015-05-03 22:17:03,127] [ERROR] koCodeIntel: gui_widget
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\oop\codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\codeintel2\database\langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'gui_widget'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by cgchoffman** [comment]
Your english is just fine @ko-ichi-h.  Thanks for letting us know about your issues.  Is it possible for you to provide a file that is the minimum viable code sample you can find that produces the error?

**Comment by ko-ichi-h** [comment]
Hello,

When I open this file on Windows 8.1, I got the above errors.
http://khc.cvs.sourceforge.net/viewvc/khc/core/kh_lib/gui_widget.pm?revision=1.21

(This is the file in the above screen shot.)

**Comment by cgchoffman** [comment]
I can't reproduce this with the file you sent.  Could you please [reset your code intel database](https://community.activestate.com/faq/codeintel-database-fix) and try to reproduce the issue again?

**Comment by ko-ichi-h** [comment]
Woops, resetting the code intel database solved the problem.

Was it a FAQ?!
Sorry for bothering you.

**Comment by cgchoffman** [comment]
That's fine.  Just please try our forums first in the future before filing a bug: http://forum.komodoide.com/
