### ISSUE TITLE
Komodo IDE window appears distored and unreadable

### ISSUE THREAD

**Issue by sramshey** [Komodo/KomodoEdit#2481]
### Short Summary

On Mac OS 10.12.4 using the latest version of Komodo IDE the entire window appears distorted and unreadable on startup.

### Steps to Reproduce

You only have to launch the app. Nothing is usable because it is not rendering properly.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?* 10.2.1
*Operating System (and version)?* Mac OS 10.12.4

### Additional Information

 
![screen shot 2017-04-12 at 5 03 52 pm](https://cloud.githubusercontent.com/assets/1718483/24984406/08260086-1fa2-11e7-834f-62c213b31a7d.png)

**Comment by sramshey** [comment]
Pop up dialogue windows are also distorted and unreadable.
![screen shot 2017-04-12 at 5 05 04 pm](https://cloud.githubusercontent.com/assets/1718483/24984426/2fa0f350-1fa2-11e7-8523-cc05fd531fad.png)

**Comment by sramshey** [comment]
I re-downloaded and re-installed the app but the problem did not go away.

**Comment by Naatan** [comment]
This has to be something about your environment, as OSX is very standardized and we've not seen this before anywhere. I'm not trying to say "it's your fault", just setting the premise that we have to find out what about your environment is causing this to happen.

Let's start with the obvious; can you think of anything about your install that is non-standard and could have anything to do with screen artifacts like this?

**Comment by sramshey** [comment]
I can't think of anything particularly unusual about my environment, per se, but I did have it set to use a non-default color scheme (one of the Dark schemes). Could it be related to that?

**Comment by Naatan** [comment]
Easy to verify: can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by Naatan** [comment]
That's assuming you can still access the menu, otherwise you could follow these instructions:

http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings

**Comment by sramshey** [comment]
I restarted it in safe mode, and the appearance is still distorted. Full disclosure - the dialogue box confirming the restart is also distorted so it's hard to be 100% sure that I actually selected the corr
![screen shot 2017-04-12 at 5 10 55 pm](https://cloud.githubusercontent.com/assets/1718483/24984603/3aca8b78-1fa3-11e7-83a8-39c298d037a5.png)
ect option, but it did appear to restart.

**Comment by Naatan** [comment]
You say you have a custom color scheme, which would imply that you had Komodo running without issues before. What changed between it running properly and then showing these artifacts?

**Comment by sramshey** [comment]
Unfortunately I think I updated both the Komodo IDE version and also applied a Mac OS update before I noticed this behavior so it's impossible to narrow it down to one or the other as the root cause. The color scheme was "custom", but it was one of the ones that came supplied with the current version.

**Comment by Naatan** [comment]
Do these instructions help?

http://docs.komodoide.com/Troubleshooting/Komodo-has-weird-graphical-artifacts

**Comment by sramshey** [comment]
I do have a dual monitor setup, so it's possible it could be related to that

**Comment by Naatan** [comment]
> I do have a dual monitor setup, so it's possible it could be related to that

Anything unusual about the displays?

**Comment by sramshey** [comment]
Nothing unusual about the displays. They are Dell monitors.

I was able to locate the settings folder, but there is no prefs.js file in that location:

samshey@BEPRESS138:~/Library/Application Support/KomodoIDE/10.2/XRE$ ls
cache2                  extensions.json         places.sqlite           sessionCheckpoints.json
cert8.db                icons                   places.sqlite-shm       simple-storage
cookies.sqlite          key3.db                 places.sqlite-wal       xulstore.json
crashes                 lessCache               pluginreg.dat
extensions.ini          permissions.sqlite      secmod.db

**Comment by Naatan** [comment]
Go ahead and create it if it doesn't exist. I'll update the docs.

**Comment by sramshey** [comment]
OK so there was a bit of confusion. I think when I restarted in safe mode it moved aside the normal settings folder and created a new one.
```drwxr-xr-x  22 samshey  staff   748 Apr 12 17:13 10.2/
drwxr-xr-x  32 samshey  staff  1088 Apr 12 17:11 10.2-kotemp-original/```

In the newly created folder there was no `prefs.js` file, so I created it and added the line specified in the instructions. On restart, however, it looks like Komodo moved the original settings folder back into place, and it turns out that the original settings folder does have `prefs.js`, so I appended the line from the instructions and restarted the app again. The display is still distorted. I also note that `prefs.js` appears to have been overwritten upon restart because the line I added is now gone.
```samshey@BEPRESS138:~/Library/Application Support/KomodoIDE/10.2/XRE$ tail -5 prefs.js
user_pref("services.sso.userId", "4174480");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1489189064);
user_pref("toolkit.telemetry.previousBuildID", "89853");```

**Comment by Naatan** [comment]
Did you shutdown Komodo before modifying the prefs.js file?

Also, given the confusion over the profile folders it might be best if you follow the instructions here to try starting Komodo in safe-mode:

http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings#how-do-i-start-komodo-with-default-settings_start-komodo-from-a-temporary-profile_mac-osx

**Comment by sramshey** [comment]
Ok I did that. The initial dialogue boxes appeared just fine:
![screen shot 2017-04-12 at 5 42 37 pm](https://cloud.githubusercontent.com/assets/1718483/24985196/70487450-1fa7-11e7-9059-7ae51a45217c.png)
![screen shot 2017-04-12 at 5 42 55 pm](https://cloud.githubusercontent.com/assets/1718483/24985199/79989e9a-1fa7-11e7-91c8-039951b0fb54.png)


![screen shot 2017-04-12 at 5 42 15 pm](https://cloud.githubusercontent.com/assets/1718483/24985189/6599a876-1fa7-11e7-9122-58431f94b0c1.png)

However, after moving past the 3rd dialogue window, the main app opened and the image is still rendering badly:
![screen shot 2017-04-12 at 5 43 09 pm](https://cloud.githubusercontent.com/assets/1718483/24985208/9571e8e2-1fa7-11e7-87ff-f3f7c7766de9.png)

**Comment by Naatan** [comment]
Very strange. Could you share the pysdterr.log file located in your profile folder? I'd be surprised if it has anything useful, but worth a shot.

Also, can you access Komodo > Preferences or is that messed up too?

**Comment by sramshey** [comment]
The preferences window is screwy too:
![screen shot 2017-04-12 at 5 46 26 pm](https://cloud.githubusercontent.com/assets/1718483/24985262/ffbec530-1fa7-11e7-8326-86e8adc49b5b.png)

pystderr.log:
```
samshey@BEPRESS138:~/Library/Application Support/KomodoIDE/10.2$ cat pystderr.log
[2017-04-12 17:33:04,207] [INFO] Startup: Welcome to Komodo IDE 10.2.1 build 89853 (platform macosx, running on Darwin 16.5.0 version Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64)
[2017-04-12 17:33:04,207] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Wed Mar 8 12:59:55 2017
[2017-04-12 17:33:04,322] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-04-12 17:33:04,669] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-04-12 17:33:04,753] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-04-12 17:33:05,267] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in

[2017-04-12 17:33:05,410] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-04-12 17:33:05,420] [WARNING] keybindings: [Ctrl+D] was used for 'cmd_addNextSubstringToCaretSet', overriding to use 'cmd_vim_scrollHalfPageDown'
[2017-04-12 17:33:06,311] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-04-12 17:33:07,841] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-04-12 17:33:07,923] [INFO] komodospellchecker: Spell checker loaded.
[2017-04-12 17:33:07,923] [INFO] komodospellchecker: Using dictionary en-US
[2017-04-12 17:33:07,949] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-04-12 17:33:08,083] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-04-12 17:33:08,127] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-04-12 17:33:09,690] [ERROR] koToolbox2Components: Error initializing toolboxes
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koToolbox2Components.py", line 158, in initialize
    self.loadMainToolboxes()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koToolbox2Components.py", line 185, in loadMainToolboxes
    toolbox_id = self.toolboxLoader.loadToolboxDirectory("Shared Toolbox", sharedToolboxDir, koToolbox2.DEFAULT_TARGET_DIRECTORY)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/koToolbox2.py", line 1806, in loadToolboxDirectory
    os.makedirs(actualToolboxDir)
  File "/Applications/Komodo IDE 10.app/Contents/MacOS/../Frameworks/Python.framework/Versions/Current/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Applications/Komodo IDE 10.app/Contents/MacOS/../Frameworks/Python.framework/Versions/Current/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Applications/Komodo IDE 10.app/Contents/MacOS/../Frameworks/Python.framework/Versions/Current/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Application Support/KomodoIDE'
[2017-04-12 17:33:09,739] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in

[2017-04-12 17:33:09,742] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in

[2017-04-12 17:33:13,258] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-04-12 17:33:13,258] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-04-12 17:33:13,259] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-04-12 17:33:14,547] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-04-12 17:33:14,548] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-04-12 17:33:14,550] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-04-12 17:33:15,200] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-04-12 17:33:15,203] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-04-12 17:33:15,205] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-04-12 17:33:18,625] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-04-12 17:40:13,663] [WARNING] views: Inconsistent view count in view_closed event
```

**Comment by Naatan** [comment]
This doesn't look good:

```
OSError: [Errno 13] Permission denied: '/Library/Application Support/KomodoIDE'
```

Any reason that might be happening?

**Comment by sramshey** [comment]
Because the KomodoIDE folder doesn't exist there?
```
samshey@BEPRESS138:/Library/Application Support$ ls -laF
total 16
drwxr-xr-x  21 root     admin   714 Oct  7  2016 ./
drwxr-xr-x+ 65 root     wheel  2210 Dec 23 12:46 ../
-rw-r--r--   1 root     admin  2048 Jun 28  2016 .TNEMG5BjEx
-rw-r--r--   1 root     admin  2048 Aug 20  2014 .apCGqDzQt7
drwxr-xr-x   7 root     wheel   238 Oct 22  2015 Adobe/
drwxr-xr-x   3 root     admin   102 Oct  7  2016 App Store/
drwxr-xr-x  12 root     wheel   408 Oct  7  2016 Apple/
drwx------   5 root     admin   170 Jan 29  2015 ApplePushService/
drwxrwxr-x  20 root     admin   680 Mar  9 15:44 CrashReporter/
drwxrwxr-x  11 root     admin   374 Apr 11 11:04 DisplayLink/
drwxrwxr-x   8 root     wheel   272 Jan 29  2015 GarageBand/
drwxr-xr-x   4 root     admin   136 Dec 16  2015 Google/
drwxr-xr-x   4 root     admin   136 Mar 11  2015 Macromedia/
drwxrwxr-x   5 root     admin   170 Jan 29  2015 Microsoft/
drwxrwxrwx   7 samshey  staff   238 Jan 29  2015 Nikon/
drwxr-xr-x   3 root     admin   102 Mar 12  2015 Oracle/
drwxrwxr-t   3 root     admin   102 Sep 13  2016 ProApps/
drwxr-xr-x   3 root     wheel   102 Jul 30  2016 Script Editor/
drwxr-xr-x   6 root     wheel   204 Jun 14  2016 Tunnelblick/
drwx------   3 root     admin   102 Mar 27 11:23 com.apple.TCC/
drwxr-xr-x   3 root     wheel   102 Jul 30  2016 iLifeMediaBrowser/
```

It does exist in `~/Library/Application Support/` though, and appears to be writeable:
```
samshey@BEPRESS138:~/Library/Application Support$ ls -laF
total 16
drwx------+ 67 samshey  staff  2278 Apr 11 11:21 ./
drwx------@ 68 samshey  staff  2312 Feb  8 13:46 ../
-rw-r--r--@  1 samshey  staff    36 Mar 14  2013 .x99s835
-rw-r--r--@  1 samshey  staff    29 Mar 14  2013 .x99s867
drwxr-xr-x  21 samshey  staff   714 Mar 17 16:23 ActiveState/
drwx------  16 samshey  staff   544 Apr 11 11:21 AddressBook/
drwxr-xr-x   5 samshey  staff   170 Dec  3  2013 Adium/
drwxr-xr-x  10 samshey  staff   340 Jan 24  2013 Adium 2.0/
drwxr-xr-x   6 samshey  staff   204 Jan 20 15:18 Adobe/
drwxr-xr-x   2 samshey  staff    68 Jan 29  2013 Aperture/
drwxr-xr-x   3 samshey  staff   102 Apr 12 17:22 App Store/
drwx------  11 samshey  staff   374 Aug 30  2016 Atom/
drwx------   3 samshey  staff   102 Oct 22  2015 CEF/
drwxr-xr-x   7 samshey  staff   238 Apr 11 11:22 CallHistoryDB/
drwxr-xr-x   3 samshey  staff   102 Oct  2  2015 CallHistoryTransactions/
drwxr-xr-x   6 samshey  staff   204 Dec 20 10:20 CloudDocs/
drwxr-xr-x   3 samshey  staff   102 Jan 13  2014 Console/
drwx------  55 samshey  staff  1870 Apr 12 14:54 CrashReporter/
drwx------   3 samshey  staff   102 Oct  7  2016 DiskImages/
drwxr-xr-x   4 samshey  staff   136 Apr 11 10:23 Dock/
drwxr-xr-x   3 samshey  staff   102 Jan 29  2013 Dupin/
drwx------   5 samshey  staff   170 May 29  2013 Firefox/
drwxr-xr-x   8 samshey  staff   272 Mar 24  2016 Flickr/
drwxr-xr-x   8 samshey  staff   272 Nov  4 11:36 GitHub for Mac/
drwx------   6 samshey  staff   204 Nov  5  2014 Google/
drwxr-xr-x   4 samshey  staff   136 Aug  6  2013 Google Earth/
drwxr-xr-x   4 samshey  staff   136 Jan 24  2013 Growl/
drwxr-xr-x   6 samshey  staff   204 Mar 17  2016 HipChat/
drwxr-xr-x   3 samshey  staff   102 Sep 23  2015 JREInstaller/
drwxr-xr-x   8 samshey  staff   272 Jan 24 11:46 Java/
drwx------   3 samshey  staff   102 Mar  7  2013 Komodo IDE/
drwxr-xr-x  10 samshey  staff   340 Apr 12 17:28 KomodoIDE/
drwxr-xr-x   4 samshey  staff   136 Sep 22  2016 Macfusion/
drwx------   4 samshey  staff   136 Aug 20  2014 Microsoft/
drwxrwxrwx   3 samshey  staff   102 Jan 23  2013 MindVision/
drwxr-xr-x   3 samshey  staff   102 Jan 29  2013 MobileSync/
drwx------   3 samshey  staff   102 Mar  7  2013 Mozilla/
drwx------   3 samshey  staff   102 Dec 20  2013 NVIDIA/
drwxr-xr-x   3 samshey  staff   102 Jan 29  2015 NotificationCenter/
drwxr-xr-x   3 samshey  staff   102 Mar 12  2015 Oracle/
drwxr-xr-x   2 samshey  staff    68 May 29  2013 Preview/
drwxr-xr-x   5 samshey  staff   170 Jun 12  2013 Propane/
drwxr-xr-x   3 samshey  staff   102 Feb 12  2013 PyCharm20/
drwxr-xr-x   5 samshey  staff   170 Oct  2  2015 Quick Look/
drwxr-xr-x   3 samshey  staff   102 Mar 14  2013 SQLEditor/
drwxr-xr-x   2 samshey  staff    68 Feb 18  2014 Screen Sharing/
drwxr-xr-x  15 samshey  staff   510 Apr 11 11:22 Slack/
drwx------   3 samshey  staff   102 Jan 22  2013 SyncServices/
drwxr-x---   4 samshey  admin   136 Jun 14  2016 Tunnelblick/
drwxr-xr-x   3 samshey  staff   102 Oct 14 16:28 VLC/
drwxr-xr-x   3 samshey  staff   102 Sep 30  2013 Viscosity/
drwxr-xr-x   2 samshey  staff    68 Oct 30  2015 X11/
drwxr-xr-x   3 samshey  staff   102 Jun  6  2016 XQuartz/
drwxr-xr-x   5 samshey  staff   170 Apr 11 11:21 com.apple.ProtectedCloudStorage/
drwxr-xr-x   3 samshey  staff   102 Dec 17  2013 com.apple.QuickLook/
drwx------   3 samshey  staff   102 Oct 13 14:55 com.apple.TCC/
drwxr-xr-x   9 samshey  staff   306 Apr 12 17:42 com.apple.sharedfilelist/
drwxr-xr-x   3 samshey  staff   102 Aug  2  2016 com.apple.spotlight/
drwxr-xr-x   2 samshey  staff    68 Oct  3  2016 com.github.GitHub.ShipIt/
drwxr-xr-x   5 samshey  staff   170 Aug 30  2016 com.github.atom.ShipIt/
drwxr-xr-x   3 samshey  staff   102 Mar 17  2016 com.hipchat.HipChat/
drwxr-xr-x   3 samshey  staff   102 Jan 29  2015 iCloud/
drwxr-xr-x   3 samshey  staff   102 Feb 27  2014 iTerm/
drwxr-xr-x   3 samshey  staff   102 May 31  2016 iTerm2/
drwx------   4 samshey  staff   136 Oct  7  2016 icdd/
drwx------   3 samshey  staff   102 Oct 18 11:21 org.videolan.vlc/
drwxr-xr-x   5 samshey  staff   170 Apr 11 11:21 videosubscriptionsd/
```

**Comment by Naatan** [comment]
It doesn't exist on my Mac either, but the fact that it shows you a permission error is indicative of a problem. Whether it is related to the artifacts is hard to say, but as of right now seems to be our best lead.

I would recommend you try and run First Aid on your disk partition via Disk Utility.

**Comment by sramshey** [comment]
I took a shot at creating the missing folders just to see what would happen, and I had to create:
* `/Library/Application Support/KomodoIDE`
* `/Library/Application Support/KomodoIDE/10.2`
* `/Library/Application Support/KomodoIDE/10.2/tools`

but then I stopped getting permissions errors and `pydstderr.log` contained the following:
```
samshey@BEPRESS138:~/Library/Application Support/KomodoIDE/10.2$ cat pystderr.log
[2017-04-13 10:30:40,721] [INFO] Startup: Welcome to Komodo IDE 10.2.1 build 89853 (platform macosx, running on Darwin 16.5.0 version Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64)
[2017-04-13 10:30:40,721] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Wed Mar 8 12:59:55 2017
[2017-04-13 10:30:40,842] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-04-13 10:30:41,183] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-04-13 10:30:41,258] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-04-13 10:30:41,766] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in

[2017-04-13 10:30:41,916] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-04-13 10:30:41,927] [WARNING] keybindings: [Ctrl+D] was used for 'cmd_addNextSubstringToCaretSet', overriding to use 'cmd_vim_scrollHalfPageDown'
[2017-04-13 10:30:43,268] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-04-13 10:30:45,205] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-04-13 10:30:45,285] [INFO] komodospellchecker: Spell checker loaded.
[2017-04-13 10:30:45,285] [INFO] komodospellchecker: Using dictionary en-US
[2017-04-13 10:30:45,310] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-04-13 10:30:45,445] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-04-13 10:30:45,533] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-04-13 10:30:47,596] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in

[2017-04-13 10:30:47,599] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in

[2017-04-13 10:30:48,988] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-04-13 10:30:48,988] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-04-13 10:30:48,988] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-04-13 10:30:49,018] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-04-13 10:30:49,019] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-04-13 10:30:49,021] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-04-13 10:30:50,493] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-04-13 10:30:50,496] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-04-13 10:30:50,500] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-04-13 10:30:55,666] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-04-13 10:32:48,725] [WARNING] views: Inconsistent view count in view_closed event
```

Not sure of if any of that is helpful, but I think I may be getting close to the limit of my ability to really diagnose the issue. It seems to me like it's related to a failure to properly load some javascript library but I'm not sure which.

**Comment by Naatan** [comment]
You're having severe graphical artifacts, that's not related to the loading of a javascript file. 

Have you trying diagnosing your partition?

**Comment by sramshey** [comment]
I did, yes, and it did find some data corruption on the disk, so it's probably related to that. I will try to deal with it later after work. In the meantime I can use an older version if I need it.

**Comment by Naatan** [comment]
So you've established that the older version works? What version is that exactly?

**Comment by sramshey** [comment]
oh, it's actually a bit more complicated than that. I have a older linux version (squeeze) that is running on a vm where I'm developing on a legacy app. Sometimes it's easier to run the IDE directly on the VM and forward the window to my desktop through an ssh tunnel (i.e. ssh -X -CY), but the age of the linux kernel means I can't actually get the latest version of the IDE to run there... thus I'm using v 8.5.4 for linux

**Comment by Naatan** [comment]
I did notice you had X and XQuartz installed. I'm not thoroughly familiar with their inner workings on OSX but is there any chance they might be interfering?
