### ISSUE TITLE
Can't start Komodo 11 in Clean profile

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2606]
### Short Summary

Looks like this optimization has cause `radiogroup` sdk to  create elements incorrectly:
https://github.com/Komodo/KomodoIDE/commit/afebbce3a394c96c642c421f323c3e5aa571ed54#diff-1c861031ab79e91f5f56bc459ce916ad

If I revert that commit I can then start Komodo again.

When I start Komodo with commit the First start wizard won't open any more.
```
[2017-05-15 15:00:36,799] [DEBUG] console: trace: trace
chrome://komodo/content/sdk/dom.js                 218 insertIntoElem/<
chrome://komodo/content/sdk/dom.js                 370 queryObject.prototype.each
chrome://komodo/content/sdk/dom.js                 198 insertIntoElem
chrome://komodo/content/sdk/dom.js                 453 queryObject.prototype.append
chrome://komodo/content/sdk/ui/element.js          151 this.addElement
chrome://komodo/content/sdk/ui/element.js          106 this.initWithElement
chrome://komodo/content/sdk/ui/element.js          205 this.create
chrome://komodo/content/sdk/ui/container.js        31 this.addRow
_e://komodo/content/startupWizard/startupWizard.js 320 this.getPageEditor
_e://komodo/content/startupWizard/startupWizard.js 25 this.init
                                                   0 

[2017-05-15 15:00:36,852] [ERROR] console-logger: TypeError: Argument 1 of Node.appendChild is not an object. (2) in chrome://komodo/content/sdk/dom.js:219
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 219, in 
```

**Comment by cgchoffman** [comment]
I think this is also breaking slack.  I get the following when I try to `Share on Slack`:
```[2017-05-15 15:41:53,793] [ERROR] console-logger: TypeError: elem[k].options.attributes is undefined (2) in chrome://komodo/content/sdk/share/slack/dialog.js:147
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/share/slack/dialog.js", line 147, in 
```
