### ISSUE TITLE
Unittests Widget isn't reporting all passed tests

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2643]
### Short Summary

While reporting https://github.com/Komodo/KomodoEdit/issues/2642 I realized that a LOT of the tests aren't being reported as passed where the summary numbers are displayed beside the test class that was run.

For example, running the following test in the command line should result in 29 passed tests:
```
(env) C:\Users\cgcho\Projects\komodo\codeintel>python -m tests.language_tests.legacy.javascript.test_completer TestJavaScriptLegacyCompletions
No handlers could be found for logger "codeintel.db.database"
..s.....s.s........ss....s.x..s..s....sss
----------------------------------------------------------------------
Ran 41 tests in 0.593s

OK (skipped=11, expected failures=1)
```

But Komodo says none passed.
See the screenshot below.

![capture](https://user-images.githubusercontent.com/655154/26856821-17f853d8-4adb-11e7-8297-688dca615b93.PNG)

Some times tests DO show that things passed though:
```
(env) C:\Users\cgcho\Projects\komodo\codeintel>python -m tests.language_tests.legacy.ruby.test_goto_definition TestRubyL
egacyGotoDefinition
No handlers could be found for logger "codeintel.db.database"
.....F..
======================================================================
FAIL: test_peer_module_defns (__main__.TestRubyLegacyGotoDefinition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\cgcho\Projects\komodo\codeintel\tests\language_tests\legacy\ruby\test_goto_definition.py", line 119, in
 test_peer_module_defns
    self.assertDefinitionIs(files, env={"RUBYLIB": "."}, type=AbstractNamespace, name="Dolphin", file=os.path.join("dolp
hin","fin.rb"), line=1)
  File "C:\Users\cgcho\Projects\komodo\codeintel\tests\language_tests\common.py", line 421, in assertDefinitionIs
    self.assertIsNotNone(definition)
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 8 tests in 0.230s

FAILED (failures=1)
```
![capture](https://user-images.githubusercontent.com/655154/26856913-af865bbe-4adb-11e7-8af5-73e81941aba5.PNG)

**Comment by Naatan** [comment]
Please share an stdout of a test you ran that showed this problem. The shorter the stdout the better.

**Comment by cgchoffman** [comment]
I did.  It's in the original report.

**Comment by Naatan** [comment]
I need the complete stdout, not part of it. When I say shorter the better I mean ideally from a reproduction case with as little  output as possible, do not truncate the output.

**Comment by cgchoffman** [comment]
Do you not see this when you run the code intel unit tests in Komodo?  I don't think setting up a new test suite of custom tests is a good use of time right now to be frank.  I can paste the stdout from Komodo after running the test suite if that would help.

**Comment by cgchoffman** [comment]
@Naatan, I updated the output to show what Komodo outputs in stdout.  I ran the tests by class to get a little output as possible.  Unfortunately this doesn't reproduce the issue.  It looks like only running the entire test suite causes this issue.

Running the test suite again to confirm.
