### ISSUE TITLE
The First Start Wizard window is broken on the master branch

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2658]
### Short Summary

title. It only shows a Scintilla area and nothing else.

### Steps to Reproduce

1. Build Komodo from the master branch.
2. Ensure you don't have a profile in your `~/.komodoedit`. (Move it, don't delete or you're stuck with broken Komodo)

### Expected results

First Start Wizard works.

### Actual results

It doesn't.

### Platform Information

*Komodo Edit or IDE?* Edit
*Komodo Version?* master branch
*Operating System (and version)?* Arch Linux

### Additional Information

```
[2017-06-17 07:59:23,463] [ERROR] console-logger: While trying to require("ko/dom"): (0) in chrome://komodo/content/jetpack.js:153
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 153, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,468] [ERROR] console-logger: TypeError: this.getMostRecent is not a function (0) in chrome://komodo/content/jetpack.js:154
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 154, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,474] [ERROR] console-logger: this.getMain@chrome://komodo/content/sdk/windows.js:102:25
@chrome://komodo/content/sdk/dom.js:20:22
@chrome://komodo/content/sdk/dom.js:13:2
require@chrome://komodo/content/jetpack.js:150:1
@chrome://komodo/content/startupWizard/startupWizard.js:7:13
@chrome://komodo/content/startupWizard/startupWizard.js:3:2
 (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,477] [ERROR] console-logger: TypeError: this.getMostRecent is not a function (2) in chrome://komodo/content/sdk/windows.js:102
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/windows.js", line 102, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,635] [ERROR] window-bindings: 
-- EXCEPTION START --
TypeError: this.getMostRecent is not a function
+ stack
    this.getMain@chrome://komodo/content/sdk/windows.js:102:25
    root-element_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:34:21
-- EXCEPTION END --
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,681] [ERROR] console-logger: TypeError: require(...) is not a function (2) in viewbufferbase:110
Traceback (most recent call last):
  File "viewbufferbase", line 110, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,686] [ERROR] console-logger: While trying to require("ko/prefs"): (0) in chrome://komodo/content/jetpack.js:153
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 153, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,691] [ERROR] console-logger: TypeError: this.getMostRecent is not a function (0) in chrome://komodo/content/jetpack.js:154
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 154, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,694] [ERROR] console-logger: this.getMain@chrome://komodo/content/sdk/windows.js:102:25
@chrome://komodo/content/sdk/prefs.js:9:11
require@chrome://komodo/content/jetpack.js:150:1
window-chromeless_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:205:26
 (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2017-06-17 07:59:23,697] [ERROR] console-logger: TypeError: this.getMostRecent is not a function (2) in chrome://komodo/content/sdk/windows.js:102
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/windows.js", line 102, in 

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
```

**Comment by Defman21** [comment]
![screenshot_20170617_110215](https://user-images.githubusercontent.com/7100645/27251274-70072dbe-534c-11e7-88c5-e07e19f31dd9.png)

**Comment by cgchoffman** [comment]
I'm not sure what's going on here.  I don't know why there wouldn't be a `window`.  Passing it back to you @Naatan.
```
[2017-07-24 15:27:53,049] [ERROR] jetpack: While trying to require("ko/prefs"):
-- EXCEPTION START --
ReferenceError: window is not defined
+ stack
    this.getMain@chrome://komodo/content/sdk/windows.js:92:13
    @chrome://komodo/content/sdk/prefs.js:9:11
    require@chrome://komodo/content/jetpack.js:152:1
    @chrome://komodo/content/startupWizard/startupWizard.js:12:17
    @chrome://komodo/content/startupWizard/startupWizard.js:4:1
-- EXCEPTION END --
[2017-07-24 15:27:53,134] [ERROR] console-logger: ReferenceError: window is not defined (2) in chrome://komodo/content/sdk/windows.js:92
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/windows.js", line 92, in 

[2017-07-24 15:27:53,279] [ERROR] ko-dom: Failed injecting HTML: vbox
-- EXCEPTION START --
TypeError: document is undefined
+ stack
    $.createElement@chrome://komodo/content/sdk/dom.js:103:21
    this.initWithElement@chrome://komodo/content/sdk/ui/element.js:105:31
    this.create@chrome://komodo/content/sdk/ui/element.js:209:9
    Progress/init@chrome://komodo/content/sdk/progress.js:36:26
    Progress@chrome://komodo/content/sdk/progress.js:121:9
    this.get@chrome://komodo/content/sdk/progress.js:144:16
    @chrome://komodo/content/startupWizard/dependencyPage.js:13:20
    @chrome://komodo/content/startupWizard/dependencyPage.js:4:1
-- EXCEPTION END --
[2017-07-24 15:27:53,391] [ERROR] console-logger: TypeError: window is undefined (2) in chrome://komodo/content/sdk/dom.js:40
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 40, in 

[2017-07-24 15:27:53,661] [ERROR] window-bindings: 
-- EXCEPTION START --
ReferenceError: window is not defined
+ stack
    this.getMain@chrome://komodo/content/sdk/windows.js:92:13
    root-element_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:34:21
-- EXCEPTION END --
[2017-07-24 15:27:53,845] [ERROR] console-logger: TypeError: window is undefined (2) in chrome://komodo/content/sdk/dom.js:40
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 40, in 

[2017-07-24 15:27:53,933] [ERROR] console-logger: TypeError: require(...).getBoolean is not a function (2) in chrome://komodo/content/bindings/windows.xml:205
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 205, in 

```

**Comment by Naatan** [comment]
Simple case of ko/dom using the wrong window it seems.

**Comment by cgchoffman** [comment]
Hopefully but `require("ko/dom").window(window)` didn't fix it.

**Comment by cgchoffman** [comment]
Also, `prefs` are broken which shouldn't be `window` related.

**Comment by Naatan** [comment]
Are you sure it still gave the same error after you tried that? There might be more issues than just ko/dom using the wrong window going on.

**Comment by cgchoffman** [comment]
Seems to get the same error even with the new code.
`    var $ = require("ko/dom").window(window);`
Confirmed it loaded the new code in DOMi.
```
[2017-07-24 16:38:53,849] [ERROR] jetpack: While trying to require("ko/prefs"):
-- EXCEPTION START --
ReferenceError: window is not defined
+ stack
    this.getMain@chrome://komodo/content/sdk/windows.js:92:13
    @chrome://komodo/content/sdk/prefs.js:9:11
    require@chrome://komodo/content/jetpack.js:152:1
    @chrome://komodo/content/startupWizard/startupWizard.js:12:17
    @chrome://komodo/content/startupWizard/startupWizard.js:4:1
-- EXCEPTION END --
[2017-07-24 16:38:54,088] [ERROR] console-logger: ReferenceError: window is not defined (2) in chrome://komodo/content/sdk/windows.js:92
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/windows.js", line 92, in 

[2017-07-24 16:38:54,266] [ERROR] ko-dom: Failed injecting HTML: vbox
-- EXCEPTION START --
TypeError: document is undefined
+ stack
    $.createElement@chrome://komodo/content/sdk/dom.js:103:21
    this.initWithElement@chrome://komodo/content/sdk/ui/element.js:105:31
    this.create@chrome://komodo/content/sdk/ui/element.js:209:9
    Progress/init@chrome://komodo/content/sdk/progress.js:36:26
    Progress@chrome://komodo/content/sdk/progress.js:121:9
    this.get@chrome://komodo/content/sdk/progress.js:144:16
    @chrome://komodo/content/startupWizard/dependencyPage.js:13:20
    @chrome://komodo/content/startupWizard/dependencyPage.js:4:1
-- EXCEPTION END --
[2017-07-24 16:38:54,650] [ERROR] console-logger: TypeError: window is undefined (2) in chrome://komodo/content/sdk/dom.js:40
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 40, in 

[2017-07-24 16:38:54,928] [ERROR] window-bindings: 
-- EXCEPTION START --
ReferenceError: window is not defined
+ stack
    this.getMain@chrome://komodo/content/sdk/windows.js:92:13
    root-element_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:34:21
-- EXCEPTION END --
[2017-07-24 16:38:55,101] [ERROR] console-logger: TypeError: window is undefined (2) in chrome://komodo/content/sdk/dom.js:40
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/dom.js", line 40, in 

[2017-07-24 16:38:55,190] [ERROR] console-logger: TypeError: require(...).getBoolean is not a function (2) in chrome://komodo/content/bindings/windows.xml:205
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 205, in 
```

**Comment by Naatan** [comment]
Ah it's a prefs bug. ko/prefs has some dependence on the main window existing on line 9.

**Comment by cgchoffman** [comment]
Weird.  It worked fine when Komodo starts.  It only breaks when you use it from the Help menu.

**Comment by Naatan** [comment]
Huh, I would think it would happen the other way around.

**Comment by cgchoffman** [comment]
This is fixed now right? @Naatan

**Comment by Naatan** [comment]
I fixed it on IDE, this was for Edit. Might be fixed, but I don't currently have an Edit build to verify it with.

**Comment by cgchoffman** [comment]
Looks fixed.
