### ISSUE TITLE
Go to file does not work when any file name has '&' character

### ISSUE THREAD

**Issue by harpreetsb** [Komodo/KomodoEdit#266]
Just that,
I have a project, downloaded files from FTP to the folder.
The file names have - and _ the names. All php files.
After opening this particular project, "Go to FILE" (ctrl+shift+O) does not suggest any files.
If I close the project and open another project "Go To File" does not work either.
If I restart Komodo edit with some old project, "Go  To file" works fine. If I again try opening the new project(previously created), "Go to file" stops working working any further, untill i restart komodo edit with some other project.
below is the log

```
[2015-05-11 23:42:17,846] [INFO] Startup: Welcome to Komodo Edit 9.0.1 build 15745 (platform linux-x86_64, running on Linux 3.13.0-52-generic version #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015)
[2015-05-11 23:42:17,846] [INFO] Startup: /usr/bin/python built on Mon Apr 20 17:19:25 2015
[2015-05-11 23:42:18,354] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-05-11 23:42:18,356] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-05-11 23:42:18,358] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-05-11 23:42:18,359] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-05-11 23:42:18,360] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///home/harpreet/.komodoedit/9.0/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2015-05-11 23:42:18,403] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-05-11 23:42:18,580] [ERROR] console-logger: TypeError: redeclaration of const CC (2) in chrome://xtk/content/xtk.js:52
Traceback (most recent call last):
  File "chrome://xtk/content/xtk.js", line 52, in 

[2015-05-11 23:42:18,936] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-05-11 23:42:18,937] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-05-11 23:42:18,952] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-05-11 23:42:19,333] [WARNING] koSkin: Detected GTK theme via libgtk: Bluebird
[2015-05-11 23:42:19,716] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-05-11 23:42:19,751] [DEBUG] places_js: waiting for document complete
[2015-05-11 23:42:19,777] [ERROR] console-logger: TypeError: this._currentView is undefined (2) in chrome://komodowakatime/content/komodowakatime.js:196
Traceback (most recent call last):
  File "chrome://komodowakatime/content/komodowakatime.js", line 196, in 

[2015-05-11 23:42:19,851] [ERROR] console-logger: TypeError: Argument 2 of EventTarget.addEventListener is not an object. (2) in chrome://todo/content/todo-ko7.js:582
Traceback (most recent call last):
  File "chrome://todo/content/todo-ko7.js", line 582, in 

[2015-05-11 23:42:20,333] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-05-11 23:42:20,333] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-05-11 23:42:20,333] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-05-11 23:42:20,333] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-05-11 23:42:20,334] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-05-11 23:42:20,334] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-05-11 23:42:20,334] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-11 23:42:21,112] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///usr/lib/komodo-edit/mozilla/components/koamAddonManager.js:138
[2015-05-11 23:42:37,902] [WARNING] console-logger: Key event not available on some keyboard layouts: key="u" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-05-11 23:42:37,903] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-05-11 23:42:38,185] [ERROR] ko-dom: Failed injecting HTML: <richlistitem xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" class="" id="co-result-item-/var/www/html/tlead/terms-&-conditions.php"><hbox><hbox class="icon-wrapper" pack="center" align="center"><box class="icon" style="background-image: url(koicon:///var/www/html/tlead/terms-&-conditions.php?size=16)"/></hbox><hbox class="entry-wrapper" align="center" pack="center"><hbox class="prefix"><label class="title" value="terms-&#38;-conditions.php"/><label class="descriptionPrefix" value="ticklead"/></hbox> <description class="descriptionComplex"><html:div class="crop rtl" xmlns:html="http://www.w3.org/1999/xhtml"><html:span dir="ltr">/terms-&-conditions.php</html:span></html:div></description></hbox></hbox></richlistitem>
-- EXCEPTION START --
SyntaxError: An invalid or illegal string was specified
+ code (number) 12
+ message (string) 'An invalid or illegal string was specified'
+ result (number) 2152923148
+ name (string) 'SyntaxError'
+ filename (string) 'chrome://komodo/content/sdk/dom.js'
+ lineNumber (number) 60
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) '$.createElement@chrome://komodo/content/sdk/dom.js:60:12
this.renderResults@chrome://commando/content/sdk/commando.js:782:30
this.onSearch/<@chrome://scope-files/content/files.js:382:12
'
+ INDEX_SIZE_ERR (number) 1
+ DOMSTRING_SIZE_ERR (number) 2
+ HIERARCHY_REQUEST_ERR (number) 3
+ WRONG_DOCUMENT_ERR (number) 4
+ INVALID_CHARACTER_ERR (number) 5
+ NO_DATA_ALLOWED_ERR (number) 6
+ NO_MODIFICATION_ALLOWED_ERR (number) 7
+ NOT_FOUND_ERR (number) 8
+ NOT_SUPPORTED_ERR (number) 9
+ INUSE_ATTRIBUTE_ERR (number) 10
+ INVALID_STATE_ERR (number) 11
+ SYNTAX_ERR (number) 12
+ INVALID_MODIFICATION_ERR (number) 13
+ NAMESPACE_ERR (number) 14
+ INVALID_ACCESS_ERR (number) 15
+ VALIDATION_ERR (number) 16
+ TYPE_MISMATCH_ERR (number) 17
+ SECURITY_ERR (number) 18
+ NETWORK_ERR (number) 19
+ ABORT_ERR (number) 20
+ URL_MISMATCH_ERR (number) 21
+ QUOTA_EXCEEDED_ERR (number) 22
+ TIMEOUT_ERR (number) 23
+ INVALID_NODE_TYPE_ERR (number) 24
+ DATA_CLONE_ERR (number) 25
+ location (object) JS frame :: chrome://komodo/content/sdk/dom.js :: $.createElement :: line 60
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/sdk/dom.js'
| + name (string) '$.createElement'
| + lineNumber (number) 60
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://commando/content/sdk/commando.js :: this.renderResults :: line 782
| + formattedStack (string) '$.createElement@chrome://komodo/content/sdk/dom.js:60:12
this.renderResults@chrome://commando/content/sdk/commando.js:782:30
this.onSearch/<@chrome://scope-files/content/files.js:382:12
'
| + stack
    $.createElement@chrome://komodo/content/sdk/dom.js:60:12
    this.renderResults@chrome://commando/content/sdk/commando.js:782:30
    this.onSearch/<@chrome://scope-files/content/files.js:382:12
-- EXCEPTION END --
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:42:38,192] [ERROR] console-logger: not well-formed (0) in :1
Traceback (most recent call last):
  File "", line 1, in 

[2015-05-11 23:42:38,194] [ERROR] console-logger: TypeError: Argument 1 of Node.appendChild is not an object. (2) in chrome://commando/content/sdk/commando.js:784
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 784, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:42:39,150] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:42:39,518] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:42:39,873] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:42:39,943] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

[2015-05-11 23:43:34,022] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-05-11 23:43:34,022] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-05-11 23:43:34,022] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-05-11 23:43:34,022] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-05-11 23:43:34,023] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-05-11 23:43:34,023] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-05-11 23:43:34,023] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-11 23:45:16,329] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-05-11 23:45:16,330] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-05-11 23:45:16,330] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-05-11 23:45:16,330] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-05-11 23:45:16,330] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-05-11 23:45:16,331] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-05-11 23:45:16,331] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-11 23:45:16,761] [ERROR] console-logger: TypeError: this._currentView is undefined (2) in chrome://komodowakatime/content/komodowakatime.js:190
Traceback (most recent call last):
  File "chrome://komodowakatime/content/komodowakatime.js", line 190, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:45:40,696] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

[2015-05-11 23:45:41,049] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

[2015-05-11 23:45:41,217] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

[2015-05-11 23:45:41,649] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:45:41,833] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:45:42,029] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/usr/lib/komodo-edit/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/komodo-edit/mozilla/extensions/scope-files@activestate.com/components/koScopeFiles.py", line 75, in onSearchResults
    opts["callback"].callback(0, results)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-05-11 23:45:42,423] [ERROR] console-logger: TypeError: resultElem.element(...).clearSelection is not a function (2) in chrome://commando/content/sdk/commando.js:762
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 762, in 

[2015-05-11 23:45:47,390] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-05-11 23:46:48,203] [ERROR] console-logger: TypeError: remove is null (2) in chrome://komodo/content/pref/pref-mappeduri.xul:69
Traceback (most recent call last):
  File "chrome://komodo/content/pref/pref-mappeduri.xul", line 69, in 

[2015-05-11 23:52:02,723] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-05-11 23:52:02,723] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-05-11 23:52:02,723] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-05-11 23:52:02,723] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-05-11 23:52:02,724] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-05-11 23:52:02,724] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-05-11 23:52:02,724] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-05-11 23:52:03,451] [WARNING] console-logger: Key event not available on some keyboard layouts: key="u" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-05-11 23:52:03,453] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by Naatan** [comment]
Would you be able to provide a file list (`find .`) of the offending project?

**Comment by harpreetsb** [comment]
it has
>about-us.php
add-images.php
add-products.php
admin
category1.html
category.html
category.php
change-password.php
company-info.php
company_pages.html
company_pages.php
contact.php
css
define-php.php
forget-password.php
frontfooter.php
frontheader.php
images
index123.html
index.html
index.php
join.php
js
loaderB64.gif
localityajax.php
login.php
logout.php
my-account.php
Product_Page.html
product.php
redirectcat.php
showcity.php
showproductlist.php
SpryAssets
subcategory1.php
subcategory.php
terms-&-conditions.php

**Comment by harpreetsb** [comment]
Found the error
its the file names with '&' character causing "Go To File not run options"
in my case its the 
>terms-&-conditions.php

Please resolve this

**Comment by Naatan** [comment]
Perfect, thanks for digging! Will fix.
