### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by fjossandon** [Komodo/KomodoEdit#2668]
### Short Summary
I have been using Komodo to debug a program for a long time, but suddenly yesterday the debug started to crash before even starting, and it opens a new console with the following message:
```
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp", line 307, in <module>
    sys.exit( main(sys.argv) )
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp", line 166, in main
    _fixencoding()
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp", line 148, in _fixencoding
    codeset = locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Press RETURN to continue ...
```
There are other programs where debugger starts fine though. The thing is that I have not made any changes to locale. Not sure what is happening. I restarted the laptop fresh and still crashed. If I restart Komodo in Safe-mode then it starts ok.

### Steps to Reproduce
Right now every time I press Step In in the offending script, "Run without debugging" crashes too.

### Expected results
That debugger gets to the first line without crashing.

### Actual results
Crash.

### Platform Information

Komodo IDE, version 10.2.2, build 89895, platform macosx.
Built on Fri Apr 28 17:57:38 2017.

Mac OSX 10.11.6

### Additional Information
I dont see any additional entry made on pystderr.log when I start the debugger, but this is the current content:
```
[2017-07-01 12:26:00,186] [INFO] Startup: Welcome to Komodo IDE 10.2.2 build 89895 (platform macosx, running on Darwin 15.6.0 version Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64)
[2017-07-01 12:26:00,186] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Fri Apr 28 17:57:38 2017
[2017-07-01 12:26:00,232] [INFO] koInitService: installing Komodo samples to '/Users/fossandon/Library/Application Support/KomodoIDE/10.2/samples'
[2017-07-01 12:26:00,462] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-07-01 12:26:00,863] [WARNING] koLess: Clearing local and file cache
[2017-07-01 12:26:00,998] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-07-01 12:26:01,437] [ERROR] window-bindings: 
-- EXCEPTION START --
TypeError: w.require is not a function
+ stack
    root-element_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:35:17
-- EXCEPTION END --
[2017-07-01 12:26:01,503] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-07-01 12:26:02,217] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-07-01 12:26:02,793] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-07-01 12:26:03,192] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-07-01 12:26:03,218] [INFO] komodospellchecker: Spell checker loaded.
[2017-07-01 12:26:03,218] [INFO] komodospellchecker: Using dictionary en-US
[2017-07-01 12:26:03,846] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-07-01 12:26:04,136] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-07-01 12:26:04,140] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-07-01 12:26:04,991] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:04,991] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:04,992] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:04,994] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:04,994] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:04,995] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:05,110] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]'[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js" line: 3749}]' when calling method: [nsIController::isCommandEnabled]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "ko.places.manager is undefined" {file: "chrome://komodo-places/content/places.js'...285 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 72
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: _command_updateCommand :: line 72
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) '_command_updateCommand'
| + lineNumber (number) 72
| + columnNumber (number) 22
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_updateCommandset/commandset._updateTimer< :: line 99
| + formattedStack (string) '_command_updateCommand@chrome://komodo/content/library/commands.js:72:22
command_updateCommandset/commandset._updateTimer<@chrome://komodo/content/library/commands.js:99:21
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2017-07-01 12:26:05,886] [ERROR] console-logger: TypeError: ko.places.manager is undefined (2) in chrome://komodo-places/content/places.js:3749
Traceback (most recent call last):
  File "chrome://komodo-places/content/places.js", line 3749, in 

[2017-07-01 12:26:05,890] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:05,891] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:05,891] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-01 12:26:06,306] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-07-01 12:26:06,308] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
ERROR:xpcom:Creation of class '<class 'component:koCommandmentService.KoCommandmentService'>' failed!
Exception details follow

ERROR:xpcom:Unhandled exception calling 'int8 * createInstance(in nsISomething, in nsIID &, out retval InterfaceIs *);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/server/factory.py", line 57, in createInstance
    return self.klass()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koCommandmentService.py", line 444, in __init__
    self._reader = _CommandmentsReader(koDirs.userDataDir, ver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koCommandmentService.py", line 353, in __init__
    self._pipe = os.open(self._commandmentsFileName, os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/Users/fossandon/Library/Application Support/KomodoIDE/10.2/commandments.fifo'
[2017-07-01 12:26:06,331] [ERROR] koInitService: Unable to start 'koCommandmentService' service: '@activestate.com/koCommandmentService;1'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/components/koInitService.py", line 373, in loadStartupCategories
    getService(components.interfaces.nsIObserver)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-07-01 12:26:06,486] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-07-01 12:26:14,325] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-07-01 12:26:14,330] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-07-01 12:26:19,042] [WARNING] views: Inconsistent view count in view_closed event
[2017-07-01 12:26:19,329] [WARNING] views: Inconsistent view count in view_opened event
[2017-07-01 12:26:31,951] [ERROR] console-logger: TypeError: tab is undefined (2) in viewbrowser:133
Traceback (most recent call last):
  File "viewbrowser", line 133, in 

[2017-07-01 12:26:52,175] [WARNING] views: Inconsistent view count in view_closed event
```

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by fjossandon** [comment]
@Naatan No, as I said above `If I restart Komodo in Safe-mode then it starts ok.`. The weird thing is that it was working fine some days ago and I have not installed anything new in-between. One of the difference between Safe-mode and normal that I can think of is that Safe-mode does not execute the `Import additiona python directories` where some of the script dependencies are because they are part of the virtual environment where it normally runs (so the debugger enters the script, but fails in the import lines).

But I have not changed the content of that folder in a while, so if the reason were some issue with UTF-8/unicode in the dependencies, it would be odd that it's starting to fail now.

Also, since the crash is in the debugger itself, I cannot locate the offending line. I found this on Stackoverflow: https://stackoverflow.com/questions/38916461/valueerror-unknown-locale-utf-8-when-importing-pandas-in-python-2-7
So I will try and see if it helps.

**Comment by fjossandon** [comment]
Ok, I added it to the .bash_profile:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
But now the debugger opens a terminal window and a Komodo Alert appears that says `Debugger attempt with invalid cookie: pARM99b5Rb6fvdRIVLIYQQ==`.

**Comment by Naatan** [comment]
Could you please check your Prefs > Environment Variables screen, as well as Project > Prefs > Environment Variables. Ensure there's nothing going on there that looks off.

@mitchell-as that invalid cookie make any sense to you? It seems Komodo is receiving a debugging session without having any record of it having started.

**Comment by fjossandon** [comment]
@Naatan That looks off in what sense?? Those I have not touched in a long time.
For the Environment Variables I only have an overrided PATH: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/fossandon/Documents/project/venv/bin` and I see a Komodo variable: `XPC_SERVICE_NAME: com.activestate.KomodoIDE.56992`. I have not used the "Project" feature, so I have nothing there.

**Comment by mitchell-as** [comment]
@fjossandon Have you restarted Komodo after changing your `~/.bash_profile`? If that still does not work, what happens if you try also adding those environment variables to Komodo's environment variables? What about logging out of your computer and then back in?

**Comment by fjossandon** [comment]
@mitchell-as yes, I have restarted Komodo after every change to bash_profile, and I have restarted the computer too a few times. Where are Komodo variables?? I only see the Start up variables, and the User variables (where I added the extra path)

**Comment by mitchell-as** [comment]
Edit > Preferences > Environment is where Komodo's environment variable settings are.

**Comment by fjossandon** [comment]
So I think is the same than I already posted above. In summary for environment, I have an extra path to `/Users/fossandon/Documents/project/venv/bin` and an additional python import directories to 
`/Users/fossandon/Documents/project/venv/lib/python2.7/site-packages`. Note that other scripts still seems to debug fine, and is just one that refuses to debug.

Ok, something is really broken somewhere, I selected and commented out ALL script lines, and added a single non-commented line at the beginning, so the first lines looks like this:
```
temp = 0
# import argparse
# import cStringIO
# import hashlib
# import logging
```
I restarted Komodo and then I pressed Step In to debug, and it still crashed with the `Debugger attempt with invalid cookie` error.

I removed again the "export" lines stated above from .bash_profile, restarted Komodo and the previous error came back. The whole thing:
```
Last login: Thu Jul  6 08:28:04 on ttys004
ip-10-0-0-72:~ fossandon$ clear; cd "/Users/fossandon/Documents/pipelines"; (echo $shell | grep csh >/dev/null  && source /var/folders/yb/zz6t6v3x3gl4gwpzsxqzb0p40000gn/T/tmpMLyo5d.environ.csh  || source /var/folders/yb/zz6t6v3x3gl4gwpzsxqzb0p40000gn/T/tmpMLyo5d.environ.sh; /usr/bin/python -u "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp" -d 127.0.0.1:61520 -l WARN /Users/fossandon/Documents/pipelines/process_pipeline.py -r 9 -u -tmp /Users/fossandon/Downloads/Temp -f /Users/fossandon/Downloads/Temp/process_seqrun_191.txt -d /Users/fossandon/Downloads/Temp/seqRun_191 -b /Users/fossandon/Documents/seq_DB/Seq_DB_v1.fasta); echo $?>/var/folders/yb/zz6t6v3x3gl4gwpzsxqzb0p40000gn/T/tmpMLyo5d.retval; echo Press RETURN to continue ...; /bin/sh -c read RETURN; rm -f /var/folders/yb/zz6t6v3x3gl4gwpzsxqzb0p40000gn/T/tmpMLyo5d.lock; exit











Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp", line 307, in <module>
    sys.exit( main(sys.argv) )
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp", line 166, in main
    _fixencoding()
  File "/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/bin/pydbgp", line 148, in _fixencoding
    codeset = locale.getdefaultlocale()[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Press RETURN to continue ...
```
And please note the script now consist on a single line `temp = 0`.

I think the experiment above discards the imported directories and code dependecies as the source of the problem.

I was thinking to put the blame on the Github integration (since this seems independent from the script code itself), but if I open another script from the same repo and folder, the debugger starts fine.

I'm basically even more confused now.

**Comment by Naatan** [comment]
Could you try shutting down Komodo, deleting prefs.xml from your [profile dir](http://docs.komodoide.com/Troubleshooting/Where-does-Komodo-keep-settings-data) (make a backup) and then starting Komodo again. See if after that you can still reproduce the issue.

If you're using a project try also closing the project, so its preferences are not in effect.

**Comment by fjossandon** [comment]
@Naatan I shut down Komodo, went to the profile dir. Moved out the `prefs.xml`, deleted `pystderr.log`. Run Komodo, it shows me tutorial, I skip the tutorial, just open the script without configuring anything and the window appear again:
```
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Press RETURN to continue ...
```
(Or the invalid cookie error if I set the locale on .bash_profile as before).
In case it helps, the content of the new `pystderr.log` after those 2 actions (open Komodo, try to start the debugger), is:
```
[2017-07-06 10:01:22,556] [INFO] Startup: Welcome to Komodo IDE 10.2.2 build 89895 (platform macosx, running on Darwin 15.6.0 version Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64)
[2017-07-06 10:01:22,556] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Fri Apr 28 17:57:38 2017
[2017-07-06 10:01:22,649] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-07-06 10:01:22,823] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-07-06 10:01:23,235] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-07-06 10:01:23,614] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-07-06 10:01:23,735] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-07-06 10:01:23,924] [WARNING] ko-fileicons: Clearing icon cache
[2017-07-06 10:01:24,218] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-07-06 10:01:24,290] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-07-06 10:01:24,312] [INFO] komodospellchecker: Spell checker loaded.
[2017-07-06 10:01:24,312] [INFO] komodospellchecker: Using dictionary en-US
[2017-07-06 10:01:25,236] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-07-06 10:01:25,240] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-07-06 10:01:26,549] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-07-06 10:01:26,550] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-07-06 10:01:26,550] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-07-06 10:01:26,554] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-07-06 10:01:26,555] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-07-06 10:01:26,556] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-07-06 10:01:26,794] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-06 10:01:26,794] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-06 10:01:26,795] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-07-06 10:01:27,268] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-07-06 10:01:27,269] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-07-06 10:01:27,272] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-07-06 10:01:28,714] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-07-06 10:01:34,506] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-07-06 10:01:34,512] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-07-06 10:02:04,875] [WARNING] views: Inconsistent view count in view_closed event
[2017-07-06 10:02:05,223] [WARNING] views: Inconsistent view count in view_opened event
[2017-07-06 10:02:05,268] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-07-06 10:02:07,740] [ERROR] console-logger: TypeError: tab is undefined (2) in viewbrowser:133
Traceback (most recent call last):
  File "viewbrowser", line 133, in 

[2017-07-06 10:02:08,175] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```
Note: I'm not using a project.

**Comment by Naatan** [comment]
Can you reproduce the issue on a brand new .py file?

**Comment by fjossandon** [comment]
No. As I commented before, other .py files that I try to debug are not affected. It's very weird. Unfortunately for me, this script is the most important one.

I created a new script from within Komodo interface, but after saving it for some reason debug buttons do not respond and more errors appear in the logfile. The following exceptions appear many times:
```
[2017-07-06 10:53:08,686] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.currentView.makeCurrent is not a function
+ stack
    removeView@viewtabbedlist:175:21
    close_viewbase@viewbase:748:21
    close_viewbufferbase@viewbufferbase:597:20
    closeUnconditionally@vieweditor:1179:27
    close@vieweditor:1247:30
    onxblmouseup@chrome://komodo/content/bindings/scrolltabs.xml:78:21
-- EXCEPTION END --
[2017-07-06 10:53:08,710] [ERROR] console-logger: TypeError: editorView.uid is undefined (2) in chrome://openfiles/content/openfiles.js:447
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 447, in 

[2017-07-06 10:53:40,729] [ERROR] ko.dbg.invocation: 
-- EXCEPTION START --
TypeError: curView.makeCurrent is not a function
+ stack
    ko_dbg_invocation_doStart@chrome://komodo/content/debugger/debugger.js:2530:21
    DBG_Manager.prototype.doStep@chrome://komodo/content/debugger/debugger.js:646:13
    doStepIn@chrome://komodo/content/debugger/debuggerController.js:106:9
    DebuggerItemsController.prototype.do_cmd_dbgStepIn@chrome://komodo/content/debugger/debuggerController.js:112:9
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:9
    command_doCommand@chrome://komodo/content/library/commands.js:239:1
    debugger_doCommand@chrome://komodo/content/debugger/debuggerController.js:31:16
    oncommand@chrome://komodo/content/komodo.xul:1:1
-- EXCEPTION END --

[2017-07-06 10:53:55,426] [ERROR] console-logger: TypeError: editorView.uid is undefined (2) in chrome://openfiles/content/openfiles.js:447
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 447, in 

[2017-07-06 10:53:55,582] [ERROR] console-logger: TypeError: this.log is undefined (2) in viewbufferbase:774
Traceback (most recent call last):
  File "viewbufferbase", line 774, in 

[2017-07-06 10:53:57,482] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1255
Traceback (most recent call last):
  File "vieweditor", line 1255, in 
```
After restarting I can debug the new script fine but the original script remain with the same error.

**Comment by Naatan** [comment]
Please try Help > Troubleshooting > Reset File Preferences

**Comment by fjossandon** [comment]
@Naatan 
Ok, File preferences reset, Komodo restarted again just in case, and FINALLY!!!! The debugger went to the first line!!! 😄 
I reconfigured the general settings, added the script parameters and is working again. Thank you!!!

So what on earth was happening??? Any clue about it???

**Comment by Naatan** [comment]
You likely had a global or project level pref that was screwing things up that was getting applied to each individual file when you ran the debugger on a file. Hard to say what pref exactly, you might be able to tell from the debugging dialog when it shows.

Glad we got you sorted :)
