### ISSUE TITLE
There are no File templates

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2712]
### Short Summary

There are no File templates any more

### Steps to Reproduce

On Windows and Linux press Ctrl+shift+N
Opens commando into template scope

### Expected results

There to be templates like there used to be

### Actual results

There are none.

**Comment by Naatan** [comment]
I think this is probably a profile upgrade issue. Check if they exist in a clean profile?

**Comment by cgchoffman** [comment]
Same issue with clean profile.  Looks like toolbox.sqlite is broken?
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\mozilla\python\komodo\koToolbox2.py", line 347, in _import_files_templates
    shutil.copy(srcChild, destDir)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\python\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\python\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 13] Permission denied: u'C:\\Program Files (x86)\\ActiveState Komodo IDE 11 Beta\\lib\\support\\samples\\tools\\File Templates\\Languages'
[2017-07-25 12:44:32,045] [ERROR] koToolbox2: Failed to copy srcChild:C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\support\samples\tools\File Templates\Web to dest destDir:C:\Users\cgcho\Projects\TEMP\11.0\tools\File Templates
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\mozilla\python\komodo\koToolbox2.py", line 347, in _import_files_templates
    shutil.copy(srcChild, destDir)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\python\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\python\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 13] Permission denied: u'C:\\Program Files (x86)\\ActiveState Komodo IDE 11 Beta\\lib\\support\\samples\\tools\\File Templates\\Web'
[2017-07-25 12:44:32,096] [ERROR] koToolbox2: error upgrading `C:\Users\cgcho\Projects\TEMP\11.0\toolbox.sqlite': near ")": syntax error
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\mozilla\python\komodo\koToolbox2.py", line 119, in __init__
    self.upgrade()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\mozilla\python\komodo\koToolbox2.py", line 229, in upgrade
    upgrader(self, curr_ver, result_ver)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 Beta\lib\mozilla\python\komodo\koToolbox2.py", line 385, in _add_folder_template_table
    )")
OperationalError: near ")": syntax error
```

**Comment by Naatan** [comment]
Strange. I'll check it out, thanks!

**Comment by cgchoffman** [comment]
This also appears to be breaking importing the users old toolbox as well.

**Comment by Naatan** [comment]
Fixed with https://github.com/Komodo/KomodoIDE/commit/d1225ed4aa8ee045ce2a870b557defe80bcc6e85
