### ISSUE TITLE
SCC commands aren't working

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2725]
### Steps to Reproduce

Try to perform a commit in the commit dialog

### Expected results

The commit to work

### Actual results

**Kaboom**

```
ERROR:xpcom:Unhandled exception calling 'int8 * setPref(in unicode &, in nsISomething);'
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\components\koPrefs.py", line 434, in setPref
    pref = UnwrapObject(pref)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\python\xpcom\server\__init__.py", line 71, in UnwrapObject
    ret = _xpcom.UnwrapObject(ob)._obj_
ValueError: This XPCOM object is not implemented by Python
[2017-07-27 17:39:46,829] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPreferenceRoot.setPref] (2) in chrome://komodo/content/scc/commit.js:189
Traceback (most recent call last):
  File "chrome://komodo/content/scc/commit.js", line 189, in 
```

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoEdit/commit/1067112c56fa7c9c28d4c250771cc33c08d8d4dc
