### ISSUE TITLE
Log View blows up if opened twice

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2732]
### Short Summary

I know I filed this before but it's gotten worse and I can't find the original ticket.  If you open the logs view twice now the window totally fails, blank contents, no title bar, no window buttons to close, minimize, maximize.

I THINK this might be windows only.

### Steps to Reproduce

- *Help > Troubleshooting > View log 
- *Help > Troubleshooting > View log (yes do it twice)

### Expected results

Show the already open logs window

### Actual results

![logs](https://user-images.githubusercontent.com/655154/28739322-e6d731be-73ae-11e7-9d1d-afd976111f64.GIF)

### Platform Information

*Operating System (and version)?* Windows

### Additional Info

```
[2017-07-28 16:07:09,867] [ERROR] console-logger: ReferenceError: require is not defined (2) in chrome://komodo/content/library/open.js:13
Traceback (most recent call last):
  File "chrome://komodo/content/library/open.js", line 13, in 

[2017-07-28 16:07:09,928] [ERROR] console-logger: TypeError: ko.logging is undefined (2) in chrome://komodo/content/library/commands.js:23
Traceback (most recent call last):
  File "chrome://komodo/content/library/commands.js", line 23, in 

[2017-07-28 16:07:09,990] [ERROR] console-logger: TypeError: ko.logging is undefined (2) in chrome://komodo/content/tail/tail.js:13
Traceback (most recent call last):
  File "chrome://komodo/content/tail/tail.js", line 13, in 

[2017-07-28 16:07:10,220] [ERROR] console-logger: ReferenceError: log is not defined (2) in chrome://komodo/content/tail/tail.js:53
Traceback (most recent call last):
  File "chrome://komodo/content/tail/tail.js", line 53, in 

[2017-07-28 16:07:30,045] [ERROR] console-logger: TypeError: gView is undefined (2) in chrome://komodo/content/tail/tail.js:79
Traceback (most recent call last):
  File "chrome://komodo/content/tail/tail.js", line 79, in 

[2017-07-28 16:08:47,525] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:314
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 314, in 

[2017-07-28 16:08:49,502] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:314
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 314, in 
```

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/1562

**Comment by cgchoffman** [comment]
I knew you would find it for some reason @defman21.  Thanks!
