### ISSUE TITLE
Toolbox: Toolbox tools are not being imported properly 

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2741]
### Short Summary

I'm not sure what's going on at this point but it looks like the toolbox can't load a lot of the new tools.  It might be related to the tools being converted from the old format to the new.  All the tutorials got converted with no "logic" code included.  They just have duplicated "value" sections, ie. the steps of the tutorial.

### Steps to Reproduce

- Open Komodo with no profile, preferably using `KOMODO_USERDATADIR` in the command line

### Expected results

- nothing bad to happen

### Actual results

a bunch of stuff fails to load into the toolbox.

### Platform Information

*Komodo Edit or IDE?* 
*Komodo Version?* 
*Operating System (and version)?* 

### Additional Information

```
[2017-08-01 16:22:31,769] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 76 - 91)
[2017-08-01 16:22:32,295] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Print Debugging
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 75 - 89)
[2017-08-01 16:22:34,197] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\Go
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 62 - 77)
[2017-08-01 16:22:34,286] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\HTML
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 64 - 79)
[2017-08-01 16:22:34,377] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\JavaScript
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 70 - 85)
[2017-08-01 16:22:34,463] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\Komodo
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 66 - 81)
[2017-08-01 16:22:34,549] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\Perl
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 64 - 79)
[2017-08-01 16:22:34,638] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\PHP
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 63 - 78)
[2017-08-01 16:22:34,727] [ERROR] koToolbox2: Couldn't load json data for path C:\Users\cgcho\Projects\TEMP\11.11\tools\Folder Templates\Python
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\komodo\koToolbox2.py", line 777, in addFolder
    data = json.load(fp, encoding="utf-8")
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\python\lib\json\decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 2 - line 6 column 2 (char 66 - 81)
```

**Comment by cgchoffman** [comment]
BAH, nvm.  I think i need to `distclean`
