### ISSUE TITLE
Color picker doesnt work

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2753]
Just click a color in the color scheme editor

```
[2017-08-03 12:47:23,774] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIColorPickerAsync.pickColorAsync] (2) in chrome://komodo/content/dialogs/colorscheme.js:959
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/colorscheme.js", line 959, in 

[2017-08-03 12:47:24,633] [ERROR] colorscheme-editor: Unable to load the colorpicker with CID: @activestate.com/koColorPicker;1
-- EXCEPTION START --
TypeError: Components.classes[cid] is undefined
+ stack
    this.pickColor@chrome://komodo/content/dialogs/colorscheme.js:945:17
    this.fields.back.init/<@chrome://komodo/content/dialogs/colorscheme.js:690:1
-- EXCEPTION END --
[2017-08-03 12:47:24,636] [ERROR] koSysUtils: Unable to load the colorpicker with CID: u'@activestate.com/koColorPicker;1'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/components/koSysUtils.py", line 378, in pickColorAsync
    getService(components.interfaces.koIColorPickerAsync)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2147746132 (NS_ERROR_FACTORY_NOT_REGISTERED)
ERROR:xpcom:Unhandled exception calling 'int8 * pickColorAsync(in nsISomething, in string &, in double, optional in int32, optional in int32);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koSysUtils.py", line 390, in pickColorAsync
    getService(components.interfaces.koIColorPickerAsync)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2147746132 (NS_ERROR_FACTORY_NOT_REGISTERED)
[2017-08-03 12:47:24,640] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIColorPickerAsync.pickColorAsync] (2) in chrome://komodo/content/dialogs/colorscheme.js:959
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/colorscheme.js", line 959, in 
```

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/60175441bd3780c405a2928d2783949a3107ba2b
