### ISSUE TITLE
need to go up one dir level to refresh remote dir

### ISSUE THREAD

**Issue by vnoel** [Komodo/KomodoEdit#276]
Using Komodo Edit 9.0.1 and editing remote files.

New files have been created in the remote directory which is shown in the sidebar. When I select "Refresh View" in the right-click menu, the contents of the directory are not updated. I need to go up one folder level and Refresh from there for the contents of the initial directory to be updated and the new files to appear.

**Comment by cgchoffman** [comment]
Does this happen consistently?  If you created a new server connection with a different server or different credentials, are you able to reproduce this?  Please include your Error logs in a code snippet or gist: Help > Troubleshooting > View log file

**Comment by Defman21** [comment]
This thing happens with local files also. Try to remove a file with your file manager and click "Refresh view" - nothing will happens. Only if you change current folder in dropdown list at the top of the pane.

**Comment by Defman21** [comment]
Also the log:
```
[2015-05-19 21:09:14,595] [ERROR] koPlaceTreeView: Request:toggleOpenState_Open
Traceback (most recent call last):
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2435, in run
    rv = getattr(self, request)(args)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2509, in toggleOpenState_Open
    self.refreshTreeOnOpen_Aux(requester, uri, forceRefresh)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2481, in refreshTreeOnOpen_Aux
    items = requester.getDirListFromLocalPath(uri)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2325, in getDirListFromLocalPath
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/home/defman/Projects/java/minemod_01'
```

**Comment by cgchoffman** [comment]
I have seen this before but I just tried it and Places updates fine for me:
- Open a directory in Places
- Open that directory in Windows file explorer (WFE)
- delete a file from WFE
- File immediately is removed from Places.

Thanks for the error report @Defman21.  I assume that is a directory?  Does that directory exist?  Does it help to remove the "_" from the path?

**Comment by Defman21** [comment]
Yes, it's a directory. It **was** exist, I removed it and tried `Refresh View` after that.
The same error for folder without `_`
```
[2015-05-19 21:22:40,000] [ERROR] koPlaceTreeView: Request:toggleOpenState_Open
Traceback (most recent call last):
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2435, in run
    rv = getattr(self, request)(args)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2509, in toggleOpenState_Open
    self.refreshTreeOnOpen_Aux(requester, uri, forceRefresh)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2481, in refreshTreeOnOpen_Aux
    items = requester.getDirListFromLocalPath(uri)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2325, in getDirListFromLocalPath
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/home/defman/Projects/java/prog'
```

**Comment by Defman21** [comment]
Oh, sorry. I posted wrong log. If I removed a folder without `_` and try to `Refresh View` - nothing happens and nothing in the log.

**Comment by Defman21** [comment]
Finally I got it. If you have an opened file in the directory you removed e.g. 5 seconds ago and you trying to refresh view: you'll get this message:
```
[2015-05-19 21:27:24,510] [ERROR] koPlaceTreeView: Request:toggleOpenState_Open
Traceback (most recent call last):
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2435, in run
    rv = getattr(self, request)(args)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2509, in toggleOpenState_Open
    self.refreshTreeOnOpen_Aux(requester, uri, forceRefresh)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2481, in refreshTreeOnOpen_Aux
    items = requester.getDirListFromLocalPath(uri)
  File "/opt/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 2325, in getDirListFromLocalPath
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/home/defman/Projects/java/prog03'
```
If no files opened in the folder you removed and you tried to Refresh View - nothing happens and nothing in the log.

**Comment by vnoel** [comment]
This happens very consistently, every time actually. I just tried it again : go to a ssh folder in the sidebar, create a new file on that folder in the terminal, refresh the sidebar in Komodo : no change. Go up one level, refresh the sidebar : the new file shows up.

I have opened the Log File, but I don't see anything relevant there : https://gist.github.com/vnoel/b8eb28f96e28bea40b36#file-gistfile1-txt

I don't have another ssh server to test with right away.

**Comment by vnoel** [comment]
Another observation that could be relevant : if instead of being in the folder itself, I'm one level up in the sidebar with the folder opened so I see its content, I modify a file name and click "refresh" : no change either. If I then double-click the folder to make it the new root and *then* click refresh, the change shows up.

So maybe the problem is not that one needs to go up one level for refresh to work, but that one needs to change the root folder once before refresh works. I'll change the bug title to reflect that.

**Comment by cgchoffman** [comment]
@vnoel, thank you for the logs.  Did you reproduce the issue during that Komodo session?  That appears to just be start up logs.  I don't see anything relevant to the issue you're reporting.

**Comment by vnoel** [comment]
The logs above were obtained after I triggered the issue. As I said above, I didn't see anything relevant to this issue in them either, but I was asked for them and don't really know what to look for.
