### ISSUE TITLE
Fix "list index out of range" error

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2776]
```
[2017-08-09 10:45:45,163] [ERROR]  codeintel.scanner: Previous exception happened while scanning file: C:\Users\cgcho\Projects\komodo\KomodoIDE\src\modules\codeintel\server\contrib\legacy\udl\ludditelib\lex.py
[2017-08-09 10:45:45,910] [ERROR]  codeintel.scanner: list index out of range
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\scanner.py", line 49, in run
    Database.writeFileScope(filename, scanner.scan(filename))
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 1591, in scan
    return visitor.getScope(self.builtInScope)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 392, in getScope
    self.scope_symbols(moduleNS["symbols"])
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 282, in scope_symbols
    self.scope_symbol(var, parentIsClass)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 286, in scope_symbol
    self.scope_class(node)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 332, in scope_class
    self.scope_symbols(node["symbols"], parentIsClass=1)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 282, in scope_symbols
    self.scope_symbol(var, parentIsClass)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 288, in scope_symbol
    self.scope_function(node)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 381, in scope_function
    self.scope_symbols(symbols)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 282, in scope_symbols
    self.scope_symbol(var, parentIsClass)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 290, in scope_symbol
    self.scope_variable(node, parentIsClass)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 297, in scope_variable
    best_citdl = citdl.split()[0]
IndexError: list index out of range
[2017-08-09 10:45:45,911] [ERROR]  codeintel.scanner: Previous exception happened while scanning file: C:\Users\cgcho\Projects\komodo\KomodoIDE\src\modules\codeintel\server\contrib\legacy\udl\ludditelib\yacc.py
```

**Comment by mitchell-as** [comment]
https://github.com/Komodo/codeintel/commit/e95611220707a1cfe1b10a584563c9629a34c3d4

**Comment by mitchell-as** [comment]
Note: this bug was also in Codeintel v2.

**Comment by Naatan** [comment]
I see. So is this a fix or a workaround?

**Comment by mitchell-as** [comment]
This is a fix. That error will not happen any more.

**Comment by Naatan** [comment]
Still seeing this

```
<1502470159> [2017-08-11 12:50:01,218] [ERROR]  codeintel.scanner: list index out of range
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/scanner.py", line 49, in run
    Database.writeFileScope(filename, scanner.scan(filename))
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 1591, in scan
    return visitor.getScope(self.builtInScope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 392, in getScope
    self.scope_symbols(moduleNS["symbols"])
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 282, in scope_symbols
    self.scope_symbol(var, parentIsClass)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 286, in scope_symbol
    self.scope_class(node)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 332, in scope_class
    self.scope_symbols(node["symbols"], parentIsClass=1)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 282, in scope_symbols
    self.scope_symbol(var, parentIsClass)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 288, in scope_symbol
    self.scope_function(node)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 381, in scope_function
    self.scope_symbols(symbols)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 282, in scope_symbols
    self.scope_symbol(var, parentIsClass)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 290, in scope_symbol
    self.scope_variable(node, parentIsClass)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/python/scanner.py", line 297, in scope_variable
    best_citdl = citdl.split()[0]
IndexError: list index out of range
```

**Comment by mitchell-as** [comment]
Please supply the file this is happening on. Is your codeintel repo up to date with the fix I committed?

**Comment by Naatan** [comment]
Bah, thought I was up to date, apparently not. My bad.
