### ISSUE TITLE
Still can't import file templates

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2781]
### Steps to Reproduce

Seems to be failing when a parent path already exists which seems to happen some how with the File Template folder.

### Expected results

To have file templates when I start Komodo

### Actual results

```
[2017-08-09 11:07:52,542] [ERROR] koToolbox2: Failed to copy srcChild:C:\Users\cgcho\Komodo IDE 11.0\lib\support\samples\tools\File Templates\Languages to dest destDir:C:\Users\cgcho\AppData\Local\ActiveState\KomodoIDE\11.0\tools\File Templates
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\python\komodo\koToolbox2.py", line 347, in _import_files_templates
    shutil.copytree(srcChild, destDir)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\python\lib\shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\..\python\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 183] Cannot create a file when that file already exists: u'C:\\Users\\cgcho\\AppData\\Local\\ActiveState\\KomodoIDE\\11.0\\tools\\File Templates'
```

**Comment by Naatan** [comment]
For the record this works for me on Linux, so something to do with Windows paths I guess?

**Comment by cgchoffman** [comment]
Ya, it says `WindowsError` so hopefully that exception is only used when the error typically only happens on Windows.

**Comment by Naatan** [comment]
Don't see anything relevant. You don't even see `os` as a completion? Can you try it on some different files to make sure?

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/2413177a542e1367baf49fe45c0171fa4d532636
