### ISSUE TITLE
css and html autocompletion failes 

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2811]
### Short Summary
I'm testing out Komodo 11, but the css and html autocompletion is not wokring well.
When I use the CSS autocompletion it fails to insert the value.
When i use the HTML autocompletion it insert the tag wrong.
Whe i type `<di`, I select the div element from the list I end up with `<didiv`

### Platform Information
Komodo 11 Windows 10

**Comment by Defman21** [comment]
>Whe i type <di, I select the div element from the list I end up with <didiv

This will be fixed in the next update.

**Comment by Naatan** [comment]
> Whe i type <di, I select the div element from the list I end up with <didiv

This will be fixed in the next build.

I'm not having issues with CSS and HTML completions other then that. Please provide steps to reproduce.

**Comment by babobski** [comment]
With the css autocompetion, when i select a attribute from the dropdown. The value isn't inserted, but I and up un the next line.

My error log:
```
[2017-08-14 07:13:39,655] [INFO] Startup: Welcome to Komodo IDE 11.0.0-alpha1 build 90396 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-08-14 07:13:39,655] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\komodo.exe built on Wed Aug 09 23:00:21 2017
[2017-08-14 07:13:42,598] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-08-14 07:13:42,770] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-08-14 07:13:43,858] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-08-14 07:13:45,658] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2017-08-14 07:13:48,861] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-08-14 07:13:48,881] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-08-14 07:13:49,072] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-08-14 07:13:49,667] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-08-14 07:13:50,220] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-08-14 07:13:50,604] [INFO] komodospellchecker: Spell checker loaded.
[2017-08-14 07:13:50,605] [INFO] komodospellchecker: Using dictionary en-US
[2017-08-14 07:13:50,855] [INFO] codeintel/process: Starting CodeIntel
[2017-08-14 07:13:50,861] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2017-08-14 07:13:51,795] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-08-14 07:13:51,969] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-08-14 07:13:52,276] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-08-14 07:13:53,053] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for Less
[2017-08-14 07:13:53,055] [WARNING] koLanguage: Asked for unknown language: 'None'
[2017-08-14 07:13:56,092] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-08-14 07:13:56,118] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-08-14 07:13:56,153] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-08-14 07:13:56,345] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-14 07:13:56,345] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-14 07:13:56,345] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-14 07:13:56,361] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-14 07:13:56,362] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-14 07:13:56,365] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-14 07:13:56,881] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-14 07:13:56,917] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-14 07:13:56,950] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-14 07:13:56,989] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-14 07:13:57,025] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-14 07:13:57,025] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-14 07:13:57,026] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-14 07:13:57,596] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koamAddonManager.js:138
[2017-08-14 07:13:57,786] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-08-14 07:13:57,788] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-08-14 07:13:58,392] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-08-14 07:13:58,973] [DEBUG] console: error: SyntaxError {}
[2017-08-14 07:14:00,257] [DEBUG] codeintel/process: stdout: 
port:50783

pid:6472

[2017-08-14 07:14:00,259] [INFO] codeintel/process: CodeIntel started on port 50783
[2017-08-14 07:14:00,259] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-08-14 07:14:06,322] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-14 07:14:06,323] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-14 07:14:06,323] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-14 07:14:08,303] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-08-14 07:14:11,671] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:11,674] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:11,677] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:11,678] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:11,681] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:12,407] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:12,411] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:12,413] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:12,414] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:12,417] [WARNING] ko_locale: Locale not found, returning default for symbol.ATTR in chrome://codeintel/locale/codeintel.properties
[2017-08-14 07:14:17,730] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-08-14 07:14:26,903] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
ERROR:xpcom:Unhandled exception calling 'G     int8 * variablePrefix(out retval string);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
AttributeError: koCSSLanguage instance has no attribute 'variablePrefix'
[2017-08-14 07:14:26,976] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koILanguage.variablePrefix] (2) in chrome://codeintel/content/sdk/feature/completions/panel.js:354
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions/panel.js", line 354, in 

[2017-08-14 07:14:30,358] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
ERROR:xpcom:Unhandled exception calling 'G     int8 * variablePrefix(out retval string);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
AttributeError: koCSSLanguage instance has no attribute 'variablePrefix'
[2017-08-14 07:14:40,167] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koILanguage.variablePrefix] (2) in chrome://codeintel/content/sdk/feature/completions/panel.js:354
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions/panel.js", line 354, in 

ERROR:xpcom:Unhandled exception calling 'G     int8 * variablePrefix(out retval string);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
AttributeError: koCSSLanguage instance has no attribute 'variablePrefix'
[2017-08-14 07:14:45,005] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koILanguage.variablePrefix] (2) in chrome://codeintel/content/sdk/feature/completions/panel.js:354
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions/panel.js", line 354, in 

[2017-08-14 07:14:48,279] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-08-14 07:17:43,269] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-08-14 07:17:43,269] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-08-14 07:17:43,270] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by Naatan** [comment]
Thanks for the error log!
