### ISSUE TITLE
Help - Run First Start Wizard Again window is broken

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2817]
It looks like that:

![image](https://user-images.githubusercontent.com/7100645/29231632-a293667e-7ef0-11e7-92e4-ba742bff8108.png)

Error log:

```
[2017-08-11 23:56:32,625] [ERROR] console-logger: TypeError: $.createElement is not a function (2) in chrome://komodo/content/sdk/ui/element.js:105
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/ui/element.js", line 105, in 

[2017-08-11 23:56:32,694] [ERROR] window-bindings: 
-- EXCEPTION START --
ReferenceError: window is not defined
+ stack
    this.getMain@chrome://komodo/content/sdk/windows.js:92:13
    root-element_XBL_Constructor@chrome://komodo/content/bindings/windows.xml:34:21
-- EXCEPTION END --
[2017-08-11 23:56:32,792] [ERROR] console-logger: TypeError: require(...) is not a function (2) in viewbufferbase:77
Traceback (most recent call last):
  File "viewbufferbase", line 77, in 

[2017-08-11 23:56:32,910] [ERROR] console-logger: TypeError: require(...).getBoolean is not a function (2) in chrome://komodo/content/bindings/windows.xml:205
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 205, in 

[2017-08-11 23:56:32,980] [ERROR] console-logger: TypeError: this.dependencyInit is not a function (2) in chrome://komodo/content/startupWizard/startupWizard.js:20
Traceback (most recent call last):
  File "chrome://komodo/content/startupWizard/startupWizard.js", line 20, in 
```

I'm on Windows 10.

**Comment by Naatan** [comment]
This is fixed but not yet in the latest community QA build.

**Comment by Defman21** [comment]
Gotcha, thanks!
