### ISSUE TITLE
Komodo hangs when editing a HAML file

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#2847]
### Short Summary

title.

### Steps to Reproduce

1. Create a HAML file with the following content:
```
%div= @test
```
2. Put your cursor before the `@` symbol.
3. Start typing.

### Expected results

Everything works.

### Actual results

Everything hangs.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 90443
*Operating System (and version)?* Arch Linux

### Additional Information

```
[2017-08-15 20:13:45,657] [INFO] Startup: Welcome to Komodo IDE 11.0.0-alpha1 build 90443 (platform linux-x86_64, running on Linux 4.12.4-1-ARCH version #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017)
[2017-08-15 20:13:45,658] [INFO] Startup: /usr/bin/python built on Tue Aug 15 00:21:27 2017
[2017-08-15 20:13:45,723] [INFO] koInitService: Setting LC_CTYPE to utf-8
[2017-08-15 20:13:46,022] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-08-15 20:13:46,171] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-08-15 20:13:47,479] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2017-08-15 20:13:47,638] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/defman/Apps/Komodo/latest/lib/mozilla/components/koamAddonManager.js:138
[2017-08-15 20:13:50,062] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-08-15 20:13:50,235] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-08-15 20:13:50,430] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-08-15 20:13:50,467] [INFO] komodospellchecker: Spell checker loaded.
[2017-08-15 20:13:50,467] [INFO] komodospellchecker: Using dictionary en-US
[2017-08-15 20:13:50,530] [INFO] codeintel/process: Starting CodeIntel
[2017-08-15 20:13:50,532] [DEBUG] codeintel/process: PYTHONPATH: /home/defman/Apps/Komodo/latest/lib/python/bin/../lib/python2.7:/home/defman/Apps/Komodo/latest/lib/support/dbgp/pythonlib:/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib:/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/lib
[2017-08-15 20:13:52,050] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///home/defman/Apps/Komodo/latest/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-15 20:13:52,050] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///home/defman/Apps/Komodo/latest/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-15 20:13:52,051] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///home/defman/Apps/Komodo/latest/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-15 20:13:52,245] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-15 20:13:52,246] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-15 20:13:52,246] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-15 20:13:53,265] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-08-15 20:13:53,274] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-08-15 20:13:53,277] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-08-15 20:13:54,195] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-08-15 20:13:54,196] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-08-15 20:13:56,571] [DEBUG] codeintel/process: stdout: 
port:51771

pid:29601

[2017-08-15 20:13:56,572] [INFO] codeintel/process: CodeIntel started on port 51771
[2017-08-15 20:13:56,573] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-08-15 20:13:57,302] [WARNING] views: Inconsistent view count in view_closed event
[2017-08-15 20:13:57,409] [WARNING] views: Inconsistent view count in view_opened event
[2017-08-15 20:13:57,680] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
ERROR:xpcom:Unhandled exception calling 'int8 * getEnvVar(in unicode &, in nsISomething, in dipper retval unicode &);'
Traceback (most recent call last):
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/components/koEnviron.py", line 399, in getEnvVar
    envStr = prefs.getString("userEnvironmentStartupOverride", "")
  File "/home/defman/Apps/Komodo/latest/lib/mozilla/python/xpcom/client/__init__.py", line 406, in __getattr__
    raise AttributeError, "XPCOM component '%s' has no attribute '%s'" % (self._object_name_, attr)
AttributeError: XPCOM component '<unknown>' has no attribute 'getString'
[2017-08-15 20:13:57,997] [ERROR] codeintel/feature/scanner: scanCurrentWorkingDirectory Failed
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
+ lineNumber (number) 122
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
'
+ location (object) JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
| + name (string) 'this.getImportPaths'
| + lineNumber (number) 122
| + columnNumber (number) 26
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://codeintel/content/sdk/feature/scanner.js :: this.scanCurrentWorkingDirectory/< :: line 347
| + formattedStack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
'
| + stack
    this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
    this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
-- EXCEPTION END --
[2017-08-15 20:14:03,840] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-15 20:14:03,841] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-15 20:14:03,842] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-15 20:14:03,843] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-15 20:14:03,845] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
```

```
<1502817344> [2017-08-15 20:15:44,400] [INFO]  codeintel.db.database: Database initialized
<1502817344> [2017-08-15 20:15:44,400] [INFO]  codeintel.scanner: Starting threaded file scanner.
<1502817344> [2017-08-15 20:15:44,403] [DEBUG]  SocketServer: Initializing SocketServer
<1502817344> [2017-08-15 20:15:49,403] [INFO]  Server: Started CodeIntel server on port: 33337, pid: 30245
<1502817344> [2017-08-15 20:15:49,976] [DEBUG]  SocketServer: Starting handle loop
<1502817344> [2017-08-15 20:16:39,449] [WARNING]  ServiceThread: keepalive timeout reached, force stopping codeintel process
<1502817344> [2017-08-15 20:16:39,452] [WARNING]  ServiceThread: 
# ThreadID: 140003652925184
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/threading.py", line 783, in __bootstrap
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/scanner.py", line 41, in run
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/Queue.py", line 168, in get
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/threading.py", line 339, in wait

# ThreadID: 140003738330880
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/threading.py", line 783, in __bootstrap
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/threading.py", line 763, in run
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/servicethread.py", line 103, in __start
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/socketserver.py", line 31, in serve_blocking
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/SocketServer.py", line 238, in serve_forever
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/SocketServer.py", line 321, in process_request
File: "/home/defman/Apps/Komodo/latest/lib/python/lib/python2.7/SocketServer.py", line 334, in finish_request
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/socketserver.py", line 59, in __init__
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/socketserver.py", line 77, in handle

# ThreadID: 140003845776768
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib/server.py", line 214, in <module>
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib/server.py", line 118, in __init__
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib/server.py", line 131, in cycle
File: "/home/defman/Apps/Komodo/latest/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/servicethread.py", line 64, in cycle
<1502817344> [2017-08-15 20:16:39,452] [INFO]  Server: Exiting Forcefully
```

**Comment by Defman21** [comment]
Able to reproduce in safe mode as well.

**Comment by Defman21** [comment]
This does not happen in 90396.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/KomodoIDE/commit/4091ab5fc54880575f91a2ff50762433b3ff23eb

**Comment by Defman21** [comment]
Thanks! Now I have to wait for the new build.
