### ISSUE TITLE
utf8 encoding errors when scanning certain files

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2853]
No exact repro steps, this just happend when codeintel scans my komodo dir

```
<1502824507> [2017-08-15 15:15:40,026] [ERROR]  codeintel.scanner: 'utf8' codec can't decode byte 0xe9 in position 18: invalid continuation byte
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/scanner.py", line 49, in run
    Database.writeFileScope(filename, scanner.scan(filename))
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/ruby/scanner.py", line 108, in scan
    self.tokenizer = ruby_lexer.RubyLexer(self.content)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/ruby/ruby_lexer.py", line 64, in __init__
    Ruby.RubyLexer().tokenize_by_style(code, self._fix_token_list)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/SilverCity/Lexer.py", line 8, in tokenize_by_style
    call_back
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 18: invalid continuation byte
<1502824507> [2017-08-15 15:15:40,026] [ERROR]  codeintel.scanner: Previous exception happened while scanning file: /home/nathan/Projects/komodo-dev/src/rxx/rxx_ruby.rb

```

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/aacd82588a2fd62cbd1dccd4e5492bf2346868c9
