### ISSUE TITLE
Remove or clean up "unable to generate AST" error

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2854]
It's making the codeintel logs hard to read

```
<1502818666> [2017-08-15 12:01:42,635] [ERROR]  codeintel.python: Unable to generate AST.
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 1582, in scan
    ast_ = _getAST(self.content)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\codeintel@activestate.com\pylib\codeintel\lib\language\legacy\python\scanner.py", line 1395, in _getAST
    % errlineno)
ValueError: cannot recover from syntax error: line 1388
```

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/d8352dbd951b0193a865ecec982be23b6fdf63d9
