### ISSUE TITLE
In startup wizzard PHP is found, but the dropdown stays disabled

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2862]
In startup wizzard PHP is found, but the dropdown stays disabled.
It also doesn't get a green checked icon.
But when I look at **Help > Check configuration** it say's it's configured right for PHP:

![afbeelding](https://user-images.githubusercontent.com/3530262/29375250-9d90762c-82b4-11e7-8691-2a910e885f2c.png)

### Platform Information
Komodo IDE, version 11.0.0-alpha1, build 90456, platform win32-x86

### Additional Information

![afbeelding](https://user-images.githubusercontent.com/3530262/29375015-d351b222-82b3-11e7-8472-7fe23f64f6aa.png)

**Comment by cgchoffman** [comment]
Logs please. Also what distro of PHP is this?  I've never seen an EXE called `php-win.exe` in an PHP install i've used.  I assume that's ported from old prefs?  Our code would not have found that file.

**Comment by babobski** [comment]
In my old prefs the same file is used.

![afbeelding](https://user-images.githubusercontent.com/3530262/29377005-b610e712-82ba-11e7-9efa-b9766d98cd94.png)


It's a PHP 5.6.15, I [downloaded](http://windows.php.net/download#php-5.6).

![afbeelding](https://user-images.githubusercontent.com/3530262/29376503-1421d7a0-82b9-11e7-99db-c21dcfe932ab.png)

Log file:
```
[2017-08-16 19:37:30,926] [INFO] Startup: Welcome to Komodo IDE 11.0.0-alpha1 build 90456 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-08-16 19:37:30,927] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\komodo.exe built on Tue Aug 15 23:00:19 2017
[2017-08-16 19:37:31,726] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-08-16 19:37:31,928] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-08-16 19:37:33,039] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-08-16 19:37:33,364] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2017-08-16 19:37:34,072] [WARNING] keybindings: Upgrading keybindings from version: 51 to 54
[2017-08-16 19:37:34,615] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-08-16 19:37:34,888] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-08-16 19:37:35,055] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-08-16 19:37:35,115] [INFO] komodospellchecker: Spell checker loaded.
[2017-08-16 19:37:35,117] [INFO] komodospellchecker: Using dictionary en-US
[2017-08-16 19:37:35,257] [INFO] codeintel/process: Starting CodeIntel
[2017-08-16 19:37:35,260] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2017-08-16 19:37:35,834] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-08-16 19:37:37,365] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koamAddonManager.js:138
[2017-08-16 19:37:37,596] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-16 19:37:37,596] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-16 19:37:37,598] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-16 19:37:37,607] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-16 19:37:37,607] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-16 19:37:37,608] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-16 19:37:38,457] [ERROR] koToolbox2Components: Could not convert C:\Users\wie_w\AppData\Local\ActiveState\KomodoIDE\11.0\templates
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koToolbox2Components.py", line 698, in convert
    koToolbox2.DataParser.writeCleanData(open(fileTargetPath, "w"), data)
IOError: [Errno 13] Permission denied: u'\\ReadMe.ktf'
[2017-08-16 19:37:38,759] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,766] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,772] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,779] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,849] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,857] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,861] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,868] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,872] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,878] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,884] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:38,891] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,898] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,905] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,913] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,920] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,921] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,930] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,963] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,970] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,977] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,984] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:38,996] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:39,003] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:39,009] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:39,016] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:39,210] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,217] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,224] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,232] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,239] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,246] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,269] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,276] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,283] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:39,299] [WARNING] koLanguage: Asked for unknown language: 'Python-common'
[2017-08-16 19:37:41,849] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:42,062] [WARNING] koLanguage: Asked for unknown language: 'HTML-common'
[2017-08-16 19:37:42,105] [WARNING] koLanguage: Asked for unknown language: 'JavaScript-common'
[2017-08-16 19:37:49,072] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-08-16 19:37:49,081] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-08-16 19:37:49,089] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-08-16 19:37:49,153] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-16 19:37:49,154] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-16 19:37:49,154] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-16 19:37:49,710] [DEBUG] codeintel/process: stdout: 
port:62243

pid:8172

[2017-08-16 19:37:49,710] [INFO] codeintel/process: CodeIntel started on port 62243
[2017-08-16 19:37:49,710] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-08-16 19:37:50,438] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-16 19:37:50,474] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-16 19:37:50,509] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-16 19:37:50,543] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

ERROR:xpcom:Unhandled exception calling 'int8 * getEnvVar(in unicode &, in nsISomething, in dipper retval unicode &);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koEnviron.py", line 399, in getEnvVar
    envStr = prefs.getString("userEnvironmentStartupOverride", "")
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\client\__init__.py", line 406, in __getattr__
    raise AttributeError, "XPCOM component '%s' has no attribute '%s'" % (self._object_name_, attr)
AttributeError: XPCOM component '<unknown>' has no attribute 'getString'
[2017-08-16 19:37:50,611] [ERROR] codeintel/feature/scanner: scanCurrentWorkingDirectory Failed
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
+ lineNumber (number) 122
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirect'...480 chars
+ location (object) JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
| + name (string) 'this.getImportPaths'
| + lineNumber (number) 122
| + columnNumber (number) 26
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://codeintel/content/sdk/feature/scanner.js :: this.scanCurrentWorkingDirectory/< :: line 347
| + formattedStack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirect'...480 chars
| + stack
    this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
    this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    dialog_alert@chrome://komodo/content/library/dialogs.js:379:0
    _macro_error@chrome://komodo/content/project/peMacro.js:642:4
    macro_evalAsJavascript@chrome://komodo/content/project/peMacro.js:739:12
    _executeMacro@chrome://komodo/content/project/peMacro.js:106:29
-- EXCEPTION END --
[2017-08-16 19:37:50,785] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-08-16 19:37:50,786] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-08-16 19:37:51,354] [DEBUG] console: error: SyntaxError {}
ERROR:xpcom:Unhandled exception calling 'G     int8 * sccType(in dipper retval string &);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: sccType
[2017-08-16 19:37:51,361] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileStatusService.py", line 466, in _process
    if u.isLocal and not u.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2017-08-16 19:37:51,410] [ERROR] koFileStatusService: Exception checking uri: None
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileStatusService.py", line 621, in _process
    reason):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\komodo\fileStatusUtils.py", line 250, in updateFileStatus
    if koIFile.isLocal and not koIFile.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2017-08-16 19:37:51,507] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-08-16 19:37:51,523] [ERROR] koFileStatusService: Exception detail: AttributeError('isLocal',)
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileStatusService.py", line 621, in _process
    reason):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\komodo\fileStatusUtils.py", line 250, in updateFileStatus
    if koIFile.isLocal and not koIFile.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
[2017-08-16 19:37:51,576] [ERROR] koFileStatusService: KoFileStatusService thread exception Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileStatusService.py", line 590, in _process
    reason):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\publishing@ActiveState.com\components\koPublishingStatus.py", line 164, in needsToReCheckFileStatus
    uri_cache_key = self._norm_uri_cache_key(koFile.URI)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\komodo\fileStatusUtils.py", line 107, in _norm_uri_cache_key
    uri = unescapeURL(uri).strip("/")
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\python\lib\urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'

[2017-08-16 19:37:51,865] [ERROR] koFileStatusService: unexpected error from koIFile.isLocal or koIFile.isFile
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileStatusService.py", line 466, in _process
    if u.isLocal and not u.isNetworkFile:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koFileEx.py", line 72, in __getattr__
    raise AttributeError, attr
AttributeError: isLocal
ERROR:xpcom:Unhandled exception calling 'int8 * getEnvVar(in unicode &, in nsISomething, in dipper retval unicode &);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koEnviron.py", line 399, in getEnvVar
    envStr = prefs.getString("userEnvironmentStartupOverride", "")
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\client\__init__.py", line 406, in __getattr__
    raise AttributeError, "XPCOM component '%s' has no attribute '%s'" % (self._object_name_, attr)
AttributeError: XPCOM component '<unknown>' has no attribute 'getString'
[2017-08-16 19:37:52,229] [ERROR] codeintel/feature/scanner: scanCurrentWorkingDirectory Failed
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
+ lineNumber (number) 122
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
'
+ location (object) JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
| + name (string) 'this.getImportPaths'
| + lineNumber (number) 122
| + columnNumber (number) 26
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://codeintel/content/sdk/feature/scanner.js :: this.scanCurrentWorkingDirectory/< :: line 347
| + formattedStack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
'
| + stack
    this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
    this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
-- EXCEPTION END --
[2017-08-16 19:38:12,275] [ERROR] console-logger: TypeError: this._getRequireMethod is not a function (2) in chrome://komodo/content/bindings/windows.xml:314
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/windows.xml", line 314, in 

[2017-08-16 19:38:17,607] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-08-16 19:38:17,607] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-08-16 19:38:17,608] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by cgchoffman** [comment]
Thanks.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/7bf5df8f82986869c5aa42127c472e1333cdf3d4
