### ISSUE TITLE
Missing more preferences

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#2878]
### Short Summary
After using komodo 11 more intense, I noticed I'm missing more preferences.
My fold mark style has changed from arrows to square trees.

In komodo 11 the section about variable highlighting is missing.
And also the notifications section is broken:

![afbeelding](https://user-images.githubusercontent.com/3530262/29426832-2c739008-8388-11e7-9d0b-1c4fb98cd480.png)

### Additional Information
Error log:
```apache
[2017-08-17 18:56:41,122] [INFO] Startup: Welcome to Komodo IDE 11.0.0-alpha1 build 90456 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-08-17 18:56:41,122] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\komodo.exe built on Tue Aug 15 23:00:19 2017
[2017-08-17 18:56:44,250] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-08-17 18:56:44,628] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-08-17 18:56:46,957] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2017-08-17 18:56:49,434] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-08-17 18:56:49,457] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-08-17 18:56:49,717] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-08-17 18:56:50,329] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-08-17 18:56:50,884] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-08-17 18:56:51,187] [INFO] komodospellchecker: Spell checker loaded.
[2017-08-17 18:56:51,187] [INFO] komodospellchecker: Using dictionary en-US
[2017-08-17 18:56:51,684] [INFO] codeintel/process: Starting CodeIntel
[2017-08-17 18:56:51,687] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2017-08-17 18:56:52,773] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-08-17 18:56:53,730] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-08-17 18:56:56,576] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-08-17 18:56:56,598] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-08-17 18:56:56,638] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-08-17 18:56:56,697] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-17 18:56:56,698] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-17 18:56:56,698] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-17 18:56:56,710] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-17 18:56:56,710] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-17 18:56:56,710] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koLessProtocolHandler.js:154
[2017-08-17 18:56:56,719] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/koamAddonManager.js:138
[2017-08-17 18:56:57,211] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-17 18:56:57,213] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-17 18:56:57,213] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-17 18:56:58,234] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2017-08-17 18:56:58,236] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2017-08-17 18:56:58,697] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 18:56:58,732] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 18:56:58,766] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 18:56:58,801] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 18:56:59,700] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-08-17 18:56:59,700] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-08-17 18:56:59,720] [DEBUG] codeintel/process: stdout: 
port:53075

pid:8028

[2017-08-17 18:56:59,720] [INFO] codeintel/process: CodeIntel started on port 53075
[2017-08-17 18:56:59,720] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
ERROR:xpcom:Unhandled exception calling 'int8 * getEnvVar(in unicode &, in nsISomething, in dipper retval unicode &);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koEnviron.py", line 399, in getEnvVar
    envStr = prefs.getString("userEnvironmentStartupOverride", "")
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\client\__init__.py", line 406, in __getattr__
    raise AttributeError, "XPCOM component '%s' has no attribute '%s'" % (self._object_name_, attr)
AttributeError: XPCOM component '<unknown>' has no attribute 'getString'
[2017-08-17 18:57:00,890] [ERROR] codeintel/feature/scanner: scanCurrentWorkingDirectory Failed
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIUserEnviron.getEnvVar]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
+ lineNumber (number) 122
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
'
+ location (object) JS frame :: chrome://codeintel/content/sdk/codeintel.js :: this.getImportPaths :: line 122
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://codeintel/content/sdk/codeintel.js'
| + name (string) 'this.getImportPaths'
| + lineNumber (number) 122
| + columnNumber (number) 26
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://codeintel/content/sdk/feature/scanner.js :: this.scanCurrentWorkingDirectory/< :: line 347
| + formattedStack (string) 'this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
'
| + stack
    this.getImportPaths@chrome://codeintel/content/sdk/codeintel.js:122:26
    this.scanCurrentWorkingDirectory/<@chrome://codeintel/content/sdk/feature/scanner.js:347:38
-- EXCEPTION END --
[2017-08-17 18:57:01,943] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-08-17 19:53:36,697] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-08-17 19:53:36,763] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-08-17 19:53:36,763] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-08-17 19:53:36,763] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-08-17 19:53:36,763] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-08-17 19:53:36,849] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-08-17 19:53:36,874] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-08-17 19:53:36,885] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-08-17 19:53:36,963] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-08-17 19:53:37,230] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-08-17 19:53:37,230] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-08-17 19:53:37,230] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-08-17 19:53:37,230] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-08-17 19:53:37,232] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-08-17 19:53:37,233] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-08-17 19:53:37,233] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-08-17 19:53:37,233] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-08-17 19:53:37,233] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-08-17 19:54:21,279] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-17 19:54:21,280] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-08-17 19:54:21,282] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-17 19:54:47,219] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 

[2017-08-17 19:55:21,970] [WARNING] pref-intl: Could not retrieve JavaScript encoding from preferences, using default.
[2017-08-17 20:07:17,683] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 20:07:17,717] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 20:07:17,752] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 20:07:17,788] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/crypto-SDR.js", line 165, in 

[2017-08-17 20:11:11,150] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-08-17 20:11:11,150] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-08-17 20:11:11,151] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by Naatan** [comment]
Komodo resets certain preferences when you upgrade in order to ensure stability. Fold icons have been reset this release because the margins have changed and it felt appropriate. I believe we have a bug open for the pref screen, but please file such bugs separately, it's unrelated to the main issue you were reporting.

**Comment by babobski** [comment]
oke, will do 👍
