### ISSUE TITLE
Error when scanning symbols in file (ABCMeta ..)

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2888]
Open koDirs.p.py, see error in log:

```
<1503012041> [2017-08-17 19:22:33,584] [ERROR]  JsonRPC: Failed calling API method: getSymbolsInBuffer
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/jsonrpc.py", line 59, in process
    result = method["function"](*request["params"])
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/__init__.py", line 186, in getSymbolsInBuffer
    symbol = ServiceSymbol(member, name).toDict()
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/symbol.py", line 117, in toDict
    return dict(self);
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/symbol.py", line 112, in __iter__
    if attr.startswith('_') or callable(getattr(self, attr)):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/symbol.py", line 48, in type
    return Symbol.getSymbolType(self._symbol.__class__)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/db/model/symbol.py", line 162, in getSymbolType
    raise TypeError("AbstractSymbol subclass '%s' is not an immediate subclass of an AbstractSymbol subclass" % symbol_cls.__class__.__name__)
TypeError: AbstractSymbol subclass 'ABCMeta' is not an immediate subclass of an AbstractSymbol subclass

```

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/ca7064a7f4a9a868f687613c224c038fbd5f7391
