### ISSUE TITLE
Color Scheme crashes Komodo 10

### ISSUE THREAD

**Issue by ffurger** [Komodo/KomodoEdit#2905]
### Short Summary
Color Scheme crashes Komodo 10 on closing the window.

### Steps to Reproduce
Preferences > Color Scheme > do some changes > Close window > Crash
Subsequent ActiveState Crash Reporter crashes as well

### Expected results
No Crash

### Actual results
 ActiveState Crash Reporter doesn't work and Komodo 10 crashes

### Platform Information
Komodo IDE
Version 10.3.2
MacOS Sierra 10.12.6

### Additional Information
The crash happens every time I open the Color Scheme window

**Comment by mitchell-as** [comment]
Hi, please upgrade to Komodo 10.2.4, which should have resolved the OSX crashing issues.

**Comment by ffurger** [comment]
Mmmh, v. 10.2.4 is nowhere in sight…

**Comment by ffurger** [comment]
Indeed - and that version crashes

**Comment by mitchell-as** [comment]
Okay, and this crash happens every time you use the color scheme editor? (i.e. it's not random?)

**Comment by ffurger** [comment]
Yep - I tried several times, and each time it crashed. Not only that, but the crash reporter has never worked, either.

**Comment by mitchell-as** [comment]
@Naatan or @mjainQA can you reproduce this on your OSX boxes?

**Comment by Naatan** [comment]
I'm aware of intermittent crashes due to the color scheme editor, but they are very random in nature and I have yet to find repro steps. I just opened and closed the color scheme editor on OSX about 10 times and had no crash. 

@ffurger please report the crash when you get the crash report dialog and enter "closed color scheme editor" for the comment.

**Comment by mitchell-as** [comment]
But he says the crash reporting cannot even be used.

**Comment by Naatan** [comment]
@ffurger please elaborate what you meant by the crash reporter has never worked?

**Comment by ffurger** [comment]
You don’t get the crash because you don’t make any changes. As soon as you do any editing, the color scheme editor crashes on “close” - at least on my system.

I did submit a screenshot of the log in my initial bug report. Let me know if you need anything else.

-Franco

**Comment by Naatan** [comment]
I made changes.

I do not see any screenshots, I assume you attached it to an email. Those don't end up on github, please respond using the github interface.

**Comment by ffurger** [comment]
Ok, here is the entire sequence screenshot by screenshot. Each screenshot has a time stamp, so no confusion there (screenshot of the log file later):

<img width="951" alt="screen shot 2017-08-21 at 20 41 01" src="https://user-images.githubusercontent.com/30805047/29533258-56b573c8-86b1-11e7-9dbf-d7a538095db6.png">
<img width="957" alt="screen shot 2017-08-21 at 20 40 41" src="https://user-images.githubusercontent.com/30805047/29533259-56deb936-86b1-11e7-8bba-540e4ba0fec3.png">
<img width="948" alt="screen shot 2017-08-21 at 20 41 17" src="https://user-images.githubusercontent.com/30805047/29533263-5b7272ee-86b1-11e7-8be7-cd41c9a70513.png">
<img width="415" alt="screen shot 2017-08-21 at 20 41 28" src="https://user-images.githubusercontent.com/30805047/29533264-5b748d9a-86b1-11e7-84ff-cffb1f39325b.png">
<img width="485" alt="screen shot 2017-08-21 at 20 41 40" src="https://user-images.githubusercontent.com/30805047/29533265-5b9caea6-86b1-11e7-99af-7385d12c7917.png">

**Comment by ffurger** [comment]
And your system didn’t crash?

I have submitted new screenshots on github.

**Comment by ffurger** [comment]
This is the entire log file as of a few minutes ago:


[2017-08-21 20:46:11,747] [INFO] Startup: Welcome to Komodo IDE 10.2.3 build 89902 (platform macosx, running on Darwin 16.7.0 version Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64)
[2017-08-21 20:46:11,747] [INFO] Startup: /Applications/Komodo IDE 10.app/Contents/MacOS/komodo built on Tue Jul 11 12:32:32 2017
[2017-08-21 20:46:11,844] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-08-21 20:46:12,141] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-08-21 20:46:12,195] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-08-21 20:46:13,351] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-08-21 20:46:13,667] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-08-21 20:46:14,092] [ERROR] koToolbox2: Couldn't load json data for path /Users/sysAdmin/Library/Application Support/KomodoIDE/10.2/tools/Tutorials/Getting_Started.komodotool
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/koToolbox2.py", line 1716, in _testAndAddItem
    data = json.load(fp, encoding="utf-8")
  File "/Applications/Komodo IDE 10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/Applications/Komodo IDE 10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/Applications/Komodo IDE 10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Komodo IDE 10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[2017-08-21 20:46:14,356] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koamAddonManager.js:138
[2017-08-21 20:46:17,365] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2017-08-21 20:46:17,544] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-08-21 20:46:17,700] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-08-21 20:46:17,746] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-08-21 20:46:17,769] [INFO] komodospellchecker: Spell checker loaded.
[2017-08-21 20:46:17,769] [INFO] komodospellchecker: Using dictionary en-US
[2017-08-21 20:46:17,833] [ERROR] koScopeDocs-Py: Could not find cix for ext
[2017-08-21 20:46:17,877] [ERROR] koScopeDocs-Py: Could not find cix for html5
[2017-08-21 20:46:18,230] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-08-21 20:46:19,005] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-08-21 20:46:19,040] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-08-21 20:46:19,526] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-08-21 20:46:19,526] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-08-21 20:46:19,526] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2010.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-08-21 20:46:19,941] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-21 20:46:19,941] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-21 20:46:19,942] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-08-21 20:46:20,747] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-08-21 20:46:20,748] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-08-21 20:46:20,749] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'

**Comment by Naatan** [comment]
I've fixed the crash reporter on our end (server issue), could you please try sending in a crash report?

Thanks!

**Comment by ffurger** [comment]
Ok, crash report this time went through.

-Franco

**Comment by Naatan** [comment]
Are you able to reproduce this crash when editing the default colorscheme? Ie. create a new color scheme based on the default and edit that one.

If not, can you share a color scheme with which you can repro?

**Comment by ffurger** [comment]
The default color scheme crashes as well. I tried a few more, they all crashed. I have submitted the report with the names of the themes I used.

**Comment by Naatan** [comment]
Thanks @ffurger, I can't quite tell what is causing the crash exactly, but I'll be making an experimental change to Komodo 11 to hopefully resolve this crash.

**Comment by ffurger** [comment]
So can you reproduce the crash on your end?

One last thing: I am using a trial version of Komodo 10, which expires tomorrow. May be the problem as something to do with that. Just wanted to mention it.

Well, I guess I am going to wait until version 11 and give it another spin. I’d really like for your IDE to succeed. For my needs it’s the only solution out there that would take me to the next level, at least on the Mac. 

Best,
Franco

**Comment by Naatan** [comment]
I am not able to reproduce it now, though I have in the past had crashes on this screen.

The trial should not affect the stability of Komodo, at least that is highly unlikely.

You can always contact sales to have your trial extended.

**Comment by ffurger** [comment]
One more observation. I did some additional testing: Troubleshooting > reset everything.

When Komodo restarts I get to go through the usual couple of panes, but at the end, when the Komodo main window should open, the application crashes and a crash report is being sent to Apple. Your own crash reporter also has something to say, but it’s not terribly useful. See screenshot attached.

Komodo then restarts for the second time, and and this time around it opens the main application window. However, the color scheme problem remains.

One thing you should also know: I had an issue with some applications that were slow to open and would hide the mouse pointer. I searched for ever until I discovered that the culprit was Accessibility > Display > Cursor size. Anything larger than the default cursor size causes troubles in some applications. 

I am telling you this because I have the feeling that the color scheme issue may actually have nothing to do with Komodo itself. This doesn’t exactly reduce the search space for the issue, but it may bring you on some fresh thinking.



Best,
Franco

**Comment by Defman21** [comment]
Your screenshot wasn't attached. You should reply with the Github's interface.

**Comment by ffurger** [comment]
Here it comes:

<img width="442" alt="screen shot 2017-08-24 at 11 26 24" src="https://user-images.githubusercontent.com/30805047/29664903-e99adfb2-88d1-11e7-9398-22fe12ab08ed.png">

**Comment by Naatan** [comment]
I suspect the issue is with scintilla not being completely unloaded before the window is closed.
