### ISSUE TITLE
codeintel scan woes

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#2942]
Komodo IDE, version 11.0.0-alpha1, build 90514, platform linux-x86_64.
Built on Mon Aug 21 00:23:15 2017.

having quite a huge python project here, codeintel scan seems to be in pain

[codeintel3.log.zip](https://github.com/Komodo/KomodoEdit/files/1251061/codeintel3.log.zip)

**Comment by Naatan** [comment]
Please clarify what you mean, I don't have much to go on here other than that I understand you have a problem or dislike in regards to codeintel scans.

**Comment by mitchell-as** [comment]
@agroszer I agree those error messages look woeful, but without the files that produced them, there's nothing we can do.

Dev note: many of those errors are language parser related, and not introduced in Komodo 11.

**Comment by agroszer** [comment]
actually now that you say, codeintel seems not to work for me for imports, in KO10 after typing `import <space>` codeintel nicely popped up a list of importables (python)

**Comment by agroszer** [comment]
something is wrong with my codeintel, 

- any chance to find out what the DB contains? codeintel3.log seems not to log what exact files get scanned
- how to force rescanning (some) files?

**Comment by Naatan** [comment]
Saving a file should force it to be rescanned. Opening a project or changing the Places directory will force the directory in question to be scanned,

Make sure you're running the latest build.

**Comment by Naatan** [comment]
Note Komodo 11 doesn't give import completions on `import |`, it gives them once you start typing the module name.

**Comment by agroszer** [comment]
```
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/scanner.py", line 49, in run
    Database.writeFileScope(filename, scanner.scan(filename))
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 1090, in scan
    self.lexerClass().tokenize_by_style(self.content, self.token_next)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/SilverCity/Lexer.py", line 8, in tokenize_by_style
    call_back
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 3797, in token_next
    self._addCodePiece(self.styles, self.text, pos=0)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 3115, in _addCodePiece
    isLocal=isLocal)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 2953, in _variableHandler
    varType, typeNames, args, p = self._getVariableDetail(namelist, styles, text, p, assignmentChar=assignChar)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 2778, in _getVariableDetail
    if maybe_args[0] == "(" and maybe_args[-1] == ")":
IndexError: list index out of range
```
looks like yours

**Comment by agroszer** [comment]
```
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/scanner.py", line 49, in run
    Database.writeFileScope(filename, scanner.scan(filename))
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 1090, in scan
    self.lexerClass().tokenize_by_style(self.content, self.token_next)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/SilverCity/Lexer.py", line 8, in tokenize_by_style
    call_back
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 3760, in token_next
    self._addCodePiece(self.styles, self.text, pos=0)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 3164, in _addCodePiece
    isLocal=isLocal)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 2969, in _variableHandler
    isLocal=(not assignToCurrentScope))
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 1776, in addFunction
    jsclass = self._addClassPart(funcName, self.ADD_CLASS_FUNCTION, scopeNames, args=args, doc=doc, path=self.path)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 1922, in _addClassPart
    jsclass.functions[fn.name] = fn
AttributeError: 'NoneType' object has no attribute 'functions'
```

**Comment by Naatan** [comment]
Thanks @agroszer. I've committed a fix for the first error. For the second I'd need some code that reproduces it. Can you file a new bug for these on a case-by-case though? Right now this seems to just encapsulate "scanner bugs".
