### ISSUE TITLE
Project wizard gets stuck on checkout

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#2963]
I created a project, selected git and used the following clone url:

git@github.com:twbs/bootstrap.git

The wizard just gets stuck on running the command. Error log contains:

```
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/opt/komodo/lib/mozilla/components/koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-29 14:35:40,373] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 

[2017-08-29 14:49:25,588] [WARNING] views: Inconsistent view count in view_closed event
[2017-08-29 14:49:25,661] [WARNING] views: Inconsistent view count in view_opened event
[2017-08-29 14:49:38,794] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2017-08-29 14:50:10,272] [WARNING] console-logger: Unknown property 'color-rendering'.  Declaration dropped. (1) in file:///home/nathan/.komodoide/11.0/XRE/icons/fileicons/CSSCSS14.png.forcedAttrs.svg:0
[2017-08-29 14:50:10,273] [WARNING] console-logger: Unknown property 'color-rendering'.  Declaration dropped. (1) in file:///home/nathan/.komodoide/11.0/XRE/icons/fileicons/GoGO14.png.forcedAttrs.svg:0
[2017-08-29 14:50:10,278] [WARNING] console-logger: Unknown property 'color-rendering'.  Declaration dropped. (1) in file:///home/nathan/.komodoide/11.0/XRE/icons/fileicons/JSXJSX14.png.forcedAttrs.svg:0
[2017-08-29 14:50:10,279] [WARNING] console-logger: Unknown property 'color-rendering'.  Declaration dropped. (1) in file:///home/nathan/.komodoide/11.0/XRE/icons/fileicons/LessCSS14.png.forcedAttrs.svg:0
[2017-08-29 14:50:10,279] [WARNING] console-logger: Unknown property 'color-rendering'.  Declaration dropped. (1) in file:///home/nathan/.komodoide/11.0/XRE/icons/fileicons/SCSSSCS14.png.forcedAttrs.svg:0
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/opt/komodo/lib/mozilla/components/koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-29 14:51:12,533] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 

ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/opt/komodo/lib/mozilla/components/koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-29 14:51:16,520] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 

ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/components/koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/opt/komodo/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/opt/komodo/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/opt/komodo/lib/mozilla/components/koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-29 14:51:21,528] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 

```

**Comment by Naatan** [comment]
Seems this wasnt broken after all, it just takes a while.
