### ISSUE TITLE
Can't open properties of multiple Tools of the same type

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2995]
### Short Summary

It completely breaks the properties dialog if you open two tools at the same time that are of the same type.

### Steps to Reproduce

- in the Toolbox, right click > Properties of two tools of the same type

### Expected results

Two open dialogs
*NOTE* Komodo 10 swapped the open dialog to the newly opened properties.  Should make that work first otherwise this is an enhancement.

### Actual results

One broken dialog

#### Note

- You can have a NEW tool (ie. adding a new tool) open and open the properties of an existing tool.
- Komodo 10 just loaded 

#### Error
```
[2017-08-29 17:09:41,095] [ERROR] console-logger: TypeError: ko.logging is undefined (2) in chrome://komodo/content/library/dialogs.js:64
Traceback (most recent call last):
  File "chrome://komodo/content/library/dialogs.js", line 64, in 

[2017-08-29 17:09:41,158] [ERROR] console-logger: TypeError: ko.logging is undefined (2) in chrome://komodo/content/launch.js:17
Traceback (most recent call last):
  File "chrome://komodo/content/launch.js", line 17, in 

[2017-08-29 17:09:41,220] [ERROR] console-logger: ReferenceError: require is not defined (2) in chrome://komodo/content/project/macroProperties.js:10
Traceback (most recent call last):
  File "chrome://komodo/content/project/macroProperties.js", line 10, in 

[2017-08-29 17:09:41,602] [ERROR] console-logger: TypeError: ko.logging is undefined (2) in chrome://komodo/content/keybindings/keybindings.xml:84
Traceback (most recent call last):
  File "chrome://komodo/content/keybindings/keybindings.xml", line 84, in 

[2017-08-29 17:09:41,756] [ERROR] console-logger: TypeError: log is undefined (2) in chrome://komodo/content/project/macroProperties.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/project/macroProperties.js", line 160, in 
```

**Comment by Naatan** [comment]
Please reassign to me if you get stuck on this, fairly certain this is the require change I made. No point wasting time on this.
