### ISSUE TITLE
Can't use project templates in project Wizard

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#2996]
### Short Summary

I tried to make a Django project but it couldn't unzip the project when it downloaded it.

![capture](https://user-images.githubusercontent.com/655154/29850040-8ab0cdd8-8cdf-11e7-9878-ad4775959aea.PNG)

### Steps to Reproduce

- *Project menu > new Project*
- The only fields we care about are selecting *Django* in the Language
- click next
- Select the Django Template on the next page of the wizard
- click next

### Expected results

Project to be successfully downloaded and unzipped

### Actual results

Error dialog and a broken project

### Platform Information

Windows

### Additional Information

Not sure if the top part of the error is related.

```
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\components\koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\components\koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-29 17:30:39,209] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 

[2017-08-29 17:31:25,549] [ERROR] koutils: Failed extracting C:\Users\cgcho\AppData\Local\Temp\django\django\archive\1.10.6.zip
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\components\koUtils.py", line 75, in _unzip
    _target = open(_targetPath, "wb+")
IOError: [Errno 2] No such file or directory: u'C:\\Users\\cgcho\\Workspace\\poop\\.tx\\'
```

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/24bcd29a6773b36837cb2d76640878187fc86889
