### ISSUE TITLE
koPythonLinter: Error running pyflakes on file

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3015]
Komodo IDE, version 11.0.0-alpha1, build 90546, platform linux-x86_64.
Built on Fri Aug 25 00:23:09 2017.

```
[2017-08-31 09:41:35,764] [ERROR] koPythonLinter: Error running pyflakes on file u'/work/shoobx/shoobx.app/src/shoobx/app/services/process.py'
/tmp/#2s1CL8.py:393:11: expected an indented block
        pds = set([mainprocess.definition])
          ^

[2017-08-31 09:41:35,860] [ERROR] koLintService: lint_with_text exception
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koLintService.py", line 172, in lint_with_text
    newLintResults = UnwrapObject(linter).lint_with_text(request, text)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koPythonLinter.py", line 463, in lint_with_text
    m.group(1), m.group(2), m.group(3))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by cgchoffman** [comment]
Repro steps and sample code please.

**Comment by agroszer** [comment]
let's use https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/action.py

remove L92
```for action in self.executedActions:```

that causes for me a linter error on L92, now:
```handler = zope.component.queryMultiAdapter(```

![screenshot_2017-09-12_11-28-54](https://user-images.githubusercontent.com/350912/30318517-a4df31c6-97ad-11e7-9090-e63b00c51949.png)

with ```
[2017-09-12 11:28:14,170] [ERROR] koPythonLinter: Error running pyflakes on file u'/work/zopefix/z3c.form/src/z3c/form/action.py'
/tmp/#ACKimD.py:92:12: unexpected indent
            handler = zope.component.queryMultiAdapter(
           ^

[2017-09-12 11:28:14,227] [ERROR] koLintService: lint_with_text exception
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koLintService.py", line 172, in lint_with_text
    newLintResults = UnwrapObject(linter).lint_with_text(request, text)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koPythonLinter.py", line 463, in lint_with_text
    m.group(1), m.group(2), m.group(3))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by agroszer** [comment]
FTR:
![screenshot_2017-09-12_11-30-47](https://user-images.githubusercontent.com/350912/30318593-dc202596-97ad-11e7-9261-ea4c81ac2e7a.png)

**Comment by agroszer** [comment]
$ pyflakes --version
1.2.3
