### ISSUE TITLE
cannot add new snippet

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#3021]
### Short Summary
toolbox->abbreviations->new snippet ... has several errors:

- enter in editor pane does nothing
- tabstop/shortcut picker does nothing
- save does nothing

### Steps to Reproduce
toolbox->abbreviations->new snippet and attempt to create a new snippet. Eg, a multiline statement

### Expected results
A new snippet.

### Actual results
You can't save; saving does nothing.

### Platform Information

Komodo IDE, version 11.0.0-alpha1, build 90612, platform macosx.
Built on Thu Aug 31 09:16:05 2017.

### Additional Information

whole lotta 

[2017-08-31 14:48:48,470] [ERROR] console-logger: TypeError: scin is undefined (2) in chrome://komodo/content/project/snippetProperties.js:397
Traceback (most recent call last):
  File "chrome://komodo/content/project/snippetProperties.js", line 397, in 

in the log.

**Comment by neurobashing** [comment]
Similarly a new userscript dialog produces 

`
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 11.app/Contents/Resources/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 11.app/Contents/Resources/components/koTools.py", line 209, in getStringAttribute
    self.updateSelf()
  File "/Applications/Komodo IDE 11.app/Contents/Resources/components/koTools.py", line 678, in updateSelf
    info = _tbdbSvc.getMacroInfo(self.id)
  File "/Applications/Komodo IDE 11.app/Contents/Resources/python/komodo/koToolbox2.py", line 1347, in getMacroInfo
    self.getCommonToolDetails(path_id, obj, cu)
  File "/Applications/Komodo IDE 11.app/Contents/Resources/python/komodo/koToolbox2.py", line 1100, in getCommonToolDetails
    raise Exception("koToolbox2.py:getCommonToolDetails internal error: path_id:%d, table:common_details => None" % (path_id,))
Exception: koToolbox2.py:getCommonToolDetails internal error: path_id:980, table:common_details => None
[2017-08-31 14:53:14,309] [ERROR] macroproperties:
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIMacroTool.getStringAttribute]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/project/macroProperties.js :: onLoad :: line 89"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIMacroTool.getStringAttribute]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/project/macroProperties.js'
+ lineNumber (number) 89
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'onLoad@chrome://komodo/content/project/macroProperties.js:89:30
onload@chrome://komodo/content/project/macroProperties.xul:1:0
'
+ location (object) JS frame :: chrome://komodo/content/project/macroProperties.js :: onLoad :: line 89
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/project/macroProperties.js'
| + name (string) 'onLoad'
| + lineNumber (number) 89
| + columnNumber (number) 30
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/project/macroProperties.xul :: onload :: line 1
| + formattedStack (string) 'onLoad@chrome://komodo/content/project/macroProperties.js:89:30
onload@chrome://komodo/content/project/macroProperties.xul:1:0
'
| + stack
    onLoad@chrome://komodo/content/project/macroProperties.js:89:30
    onload@chrome://komodo/content/project/macroProperties.xul:1:0
-- EXCEPTION END --
[2017-08-31 14:53:16,722] [ERROR] console-logger: TypeError: gScintilla is null (2) in chrome://komodo/content/project/macroProperties.js:270
Traceback (most recent call last):
  File "chrome://komodo/content/project/macroProperties.js", line 270, in

[2017-08-31 14:53:17,492] [ERROR] console-logger: TypeError: gScintilla is null (2) in chrome://komodo/content/project/macroProperties.js:270
Traceback (most recent call last):
  File "chrome://komodo/content/project/macroProperties.js", line 270, in

[2017-08-31 14:53:17,616] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt,shift" (1) in chrome://komodo/content/project/macroProperties.xul:0
[2017-08-31 14:53:17,616] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt,shift" (1) in chrome://komodo/content/project/macroProperties.xul:0
[2017-08-31 14:53:17,617] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/project/macroProperties.xul:0
[2017-08-31 14:53:17,617] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt" (1) in chrome://komodo/content/project/macroProperties.xul:0
`

**Comment by cgchoffman** [comment]
This should be resolved by #3022.  My original fix for that actually broke this.  The new fixes both.  That's good programming right there!  2 bugs fixed at once ;).

Sorry for the hassle @neurobashing and thanks for reporting.
