### ISSUE TITLE
Can't load all templates in project wizard after Komodo start

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3022]
### Short Summary

I believe the catch here is taht you have to start the Project Wiz after starting Komodo.

### Steps to Reproduce

- Restart Komodo
- Open the project wizard
- enter fields name field only
- click next
- Open error logs
- You can also select *Show all templates*.  

### Expected results

To see all templates and no errors in logs

### Actual results

There is an error in the logs and not all templates are loaded

```
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\components\koTools.py", line 207, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'language'
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\mozbuilds\IDE-11.11\moz3500-ko11.11\mozilla\ko-rel\dist\bin\components\koToolbox2Components.py", line 823, in _findToolsAsyncCallback
    callback.callback(0, result)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2147500037 (NS_ERROR_FAILURE)
[2017-08-31 12:50:27,723] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://projectwizard/content/dialog/projectWizard.js:255
Traceback (most recent call last):
  File "chrome://projectwizard/content/dialog/projectWizard.js", line 255, in 
```

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/91d3b26ac5ac2a405cfeecca15b7adf2944376c9
