### ISSUE TITLE
KO11 Error inserting snippet

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3029]
Error inserting snippet

Komodo IDE, version 11.0.0-alpha1, build 90612.
Built on Thu Aug 31 09:16:06 2017.

![screenshot_2017-09-01_10-27-33](https://user-images.githubusercontent.com/350912/29961530-335d174e-8f00-11e7-828d-acf58ff78ce3.png)

last pystderr entries:
```
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koTools.py", line 210, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'name'
[2017-09-01 10:24:08,802] [ERROR] commandproperties: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/run/commandproperties.js :: OnLoad :: line 81"  data: no]
Traceback from ERROR in 'commandproperties' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:386:27
    OnLoad@chrome://komodo/content/run/commandproperties.js:112:9
    onload@chrome://komodo/content/run/commandproperties.xul:1:1
    openDialogWrap@chrome://komodo/content/komodo.js:641:19
    command_editProperties@chrome://komodo/content/project/peCommand.js:22:1
    this.editProperties_command@chrome://komodo/content/toolbox/toolbox2_command.js:51:5
    this.editPropertiesTool@chrome://komodo/content/toolbox/toolbox2_command.js:1345:9
    this.editPropertiesItem@chrome://komodo/content/toolbox/toolbox2_command.js:822:5
    oncommand@chrome://komodo/content/toolbox/toolboxPanel.xul:1:1

[2017-09-01 10:24:08,927] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koTools.py", line 210, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'name'
[2017-09-01 10:26:04,845] [ERROR] ko.projects: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/project/peCommand.js :: Run_CommandPart :: line 38"  data: no]
Traceback from ERROR in 'ko.projects' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:386:27
    part_invokePartById@chrome://komodo/content/project/partutils.js:63:9
    @chrome://komodo/content/keybindings/keybindings.js line 2603 > eval:1:33
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2603:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2774:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2658:5

```

**Comment by Naatan** [comment]
This is the same issue you reported earlier (same cause), and will be fixed in the next build.
