### ISSUE TITLE
KO11 Tools / command broken

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#3030]
Komodo IDE, version 11.0.0-alpha1, build 90612, platform linux-x86_64.
Built on Thu Aug 31 09:16:06 2017.

Can't start a Command from Tools...
Seems like right click properties is also weird

```
[2017-09-01 10:31:35,883] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
ERROR:xpcom:Unhandled exception calling 'int8 * getStringAttribute(in wstring, out retval wstring);'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-11/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/home/adi/Komodo-IDE-11/lib/mozilla/components/koTools.py", line 210, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: u'name'
[2017-09-01 10:33:06,660] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPart_Common.getStringAttribute] (2) in chrome://komodo/content/project/peCommand.js:38
Traceback (most recent call last):
  File "chrome://komodo/content/project/peCommand.js", line 38, in 
```

**Comment by agroszer** [comment]
editing the command also broke the key bindings... going back to build 90546, key bindings gone

**Comment by Naatan** [comment]
Thanks @agroszer, this is fixed in the upcoming build.
