### ISSUE TITLE
CodeIntel is passing buffer as a path

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3057]
Completions on large/complex files will not work and cause the following error:

```
<1504807345> [2017-09-07 14:23:32,619] [ERROR]  JsonRPC: Failed calling API method: getCompletions
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/jsonrpc.py", line 59, in process
    result = method["function"](*request["params"])
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/__init__.py", line 65, in getCompletions
    context = language.scanner.getCompletionContext(buf, pos, env)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 1122, in getCompletionContext
    return self._getCompletionContext(filename, position, env, self.tokens, line, column, scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/javascript/scanner.py", line 1218, in _getCompletionContext
    for basename in fetchFilesInDirectory(dirname, ".js", False, False):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/db/model/helpers.py", line 203, in fetchFilesInDirectory
    for db_file in db_files.iterator():
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/peewee.py", line 3223, in iterator
    return iter(self.execute().iterator())
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/peewee.py", line 3213, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/peewee.py", line 2892, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/playhouse/apsw_ext.py", line 107, in execute_sql
    self._execute_sql(cursor, sql, params)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/env/lib/python2.7/site-packages/playhouse/apsw_ext.py", line 100, in _execute_sql
    cursor.execute(sql, params or ())
  File "src/cursor.c", line 236, in resetcursor
SQLError: SQLError: LIKE or GLOB pattern too complex
```

Tracing the issue it seems that scanner.py is calling fetchFilesInDirectory with a dirname that is the entire buffer. It seems codeintel is assuming that getCompletionContext is passing a path rather than a buffer.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/213a320c589677069819dea7b5ca0e41bcc45829

**Comment by mitchell-as** [comment]
Hacked previous fix due to Komodo 11 RC constraints: https://github.com/Komodo/codeintel/commit/16ceb0a2dc83a79ad1f63a4ba868fd8d8f7e2f87

**Comment by Naatan** [comment]
Re-targeting for 11.1 so we can fix this properly.

**Comment by mitchell-as** [comment]
Fixed via https://github.com/Komodo/codeintel/commit/772e09b120461c1ca2645939fa17495774c01213
