### ISSUE TITLE
Seeing Commandment errors in the logs that are worrisome.

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3060]
### Short Summary

I don't know if there is any fallout as I have no idea what that files is for but it's not in any of my profiles so i'm not sure why it's looking for it or when it's supposed to exist.  I do know the commandments system is one of the first things to start so IF this breaks stuff it's potentially bad and may not be obvious that it's linked to stuff.

```
Exception in thread CommandmentsReader:
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\components\koCommandmentService.py", line 273, in run
    f = open(self._commandmentsFileName, 'r')
IOError: [Errno 2] No such file or directory: u'C:\\Users\\cgcho\\AppData\\Local\\ActiveState\\KomodoIDE\\11.0\\commandments.txt'

```

**Comment by cgchoffman** [comment]
Milestone of 11 because it needs to be looked at atleast.

**Comment by Naatan** [comment]
This file doesn't exist in any profile folder I have going back to 8.5. Seems that if this is indeed breaking something this has been broken for a while.

**Comment by cgchoffman** [comment]
I can open Komodo from the commandline and pass it a file to open so i'm going to punt.
