### ISSUE TITLE
Symbol Browser does not display everything it should (e.g. no global variables)

### ISSUE THREAD

**Issue by UlrichBlumensaat** [Komodo/KomodoEdit#3086]
### Short Summary
Compared Symbol Browser from Komodo 10.2.3 and Komodo 11 RC3 

If you create or open a Perl script the Symbol Browser does not display global variables (while KO 10.2.3 does it)

### Steps to Reproduce

Create a perl script:

```#!/usr/bin/perl -w
use strict;
my $abc = "def";
```

### Expected results

View -> Tabs and Sidebars -> Symbol Browser (menu item formerly called "Code" in KO 10 )
displays Symbol Browser
Symbol Browser should show "abc" under global variables

### Actual results

Symbol Browser does not show any global variables

### Platform Information

*RC3 of Komodo-IDE-11.0.0-90665-linux-x86_64.tar.gz* 
*CentOS Linux release 7.3.1611 (Core)* 

### Additional Information

Error log, not sure if relevant for issue:

```
[2017-09-14 12:34:50,627] [INFO] codeintel/process: CodeIntel started on port 54560
[2017-09-14 12:34:50,627] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-09-14 12:34:53,540] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg?size=14:0
[2017-09-14 12:34:55,467] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-14 12:34:55,467] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-14 12:34:55,467] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-14 12:34:55,468] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-14 12:34:55,468] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-09-14 12:34:58,461] [ERROR] console-logger: TypeError: callback is not a function (2) in chrome://komodo/content/project/peTemplate.js:77
Traceback (most recent call last):
  File "chrome://komodo/content/project/peTemplate.js", line 77, in 

[2017-09-14 12:35:29,276] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2017-09-14 12:36:13,770] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

[2017-09-14 12:36:13,901] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

[2017-09-14 12:36:14,021] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

[2017-09-14 12:36:14,149] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/ulrichb/Komodo-IDE-11/lib/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/api.py", line 186, in run
    self.queue_events(self.timeout)
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 763, in queue_events
    inotify_events = self._inotify.read_events()
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 600, in read_events
    self._event_mask)
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 661, in _add_watch
    Inotify._raise_error()
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 697, in _raise_error
    raise OSError(os.strerror(_errnum))
OSError: No space left on device

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ulrichb/Komodo-IDE-11/lib/python/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/api.py", line 186, in run
    self.queue_events(self.timeout)
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 763, in queue_events
    inotify_events = self._inotify.read_events()
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 600, in read_events
    self._event_mask)
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 661, in _add_watch
    Inotify._raise_error()
  File "/home/ulrichb/Komodo-IDE-11/lib/mozilla/python/komodo/watchdog/observers/inotify.py", line 697, in _raise_error
    raise OSError(os.strerror(_errnum))
OSError: No space left on device

[2017-09-14 12:48:02,662] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:48:02,663] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:48:02,663] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:48:02,663] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:48:02,664] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:50:08,337] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:50:08,339] [WARNING] console-logger: Key event not available on some keyboard layouts: key="w" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:50:08,339] [WARNING] console-logger: Key event not available on some keyboard layouts: key="n" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:50:08,339] [WARNING] console-logger: Key event not available on some keyboard layouts: key="s" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-09-14 12:50:08,340] [WARNING] console-logger: Key event not available on some keyboard layouts: key="d" modifiers="control,alt,shift" (1) in chrome://komodo/content/tail/tail.xul:0
```

**Comment by cgchoffman** [comment]
@UlrichBlumensaat in the symbol browser, click the gear menu and select "show all symbols". This is working as designed.  Thanks for reporting!

**Comment by Naatan** [comment]
![image](https://user-images.githubusercontent.com/278649/30452822-f83484c6-9964-11e7-993f-20ae494de8c3.png)
