### ISSUE TITLE
Cannot access files on NFS mounted Volume

### ISSUE THREAD

**Issue by gerrygrieve** [Komodo/KomodoEdit#3235]
Hi
    after a reboot of my workstation, Komodo refuses to
    reads files from a NFS-mounted volume.  No errors,
    but it never returns from trying to load the file.
    
    This worked fine last week,  I do not think there have been any
    changes to the system. The reboot was caused by a power outage
    in the building.
    Other apps ( eg Vim) can read & write to the Volume.

System Version:	macOS 10.12.6 (16G29)
Kernel Version:	Darwin 16.7.0

Komodo IDE, version 10.2.3, build 89902, platform macosx.
Built on Tue Jul 11 12:32:32 2017.
 _________________________________________________
Today's entries in LogFile
[2017-10-04 11:08:10,931] [ERROR] codeintel.indexer: unexpected internal error in indexer: ignoring and continuing
Traceback (most recent call last):
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/indexer.py", line 516, in run
    self._iteration()
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/indexer.py", line 583, in _iteration
    buf.scan(mtime=request.mtime)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/udl.py", line 483, in scan
    super(XMLParsingBufferMixin, self).scan(mtime, skip_scan_time_check)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/database/database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/database/multilanglib.py", line 939, in update_buf_data
    self._update_symbols_db(conn, action, blob)
  File "/Applications/Komodo IDE 10.app/Contents/Resources/python/komodo/codeintel2/database/langlib.py", line 961, in _update_symbols_db
    (blob.get("src"),))
AttributeError: 'NoneType' object has no attribute 'get'
[2017-10-04 11:16:44,653] [DEBUG] console: warn: Plural form unknown for locale "null"

**Comment by Naatan** [comment]
Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

Note you are running Komodo 10.2.3, the latest version is 11.0.0.
