### ISSUE TITLE
Code Intel restarts Many many times overs a a few hours

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3256]
### Short Summary

I don't have much information other than pystderr.py is over 4000 lines long and most of that is message that Code Intel restarted.  The codeintel.log file unfortunately only has the following:

```
<1507677269> [2017-10-10 16:14:29,360] [INFO]  codeintel.db.database: Database initialized
<1507677269> [2017-10-10 16:14:29,360] [INFO]  codeintel.scanner: Starting threaded file scanner.
<1507677269> [2017-10-10 16:14:29,362] [DEBUG]  SocketServer: Initializing SocketServer
<1507677269> [2017-10-10 16:14:34,368] [INFO]  Server: Started CodeIntel server on port: 57301, pid: 30804
<1507677269> [2017-10-10 16:14:34,495] [DEBUG]  SocketServer: Starting handle loop
```
[pystderr copy.txt](https://github.com/Komodo/KomodoEdit/files/1373731/pystderr.copy.txt)

### Steps to Reproduce

Start Komodo and let it sit for a while.  This appears to be reproducible on OSX.  I turned off all code intel prefs and restarted.  Komodo has only been runnin for aboutu 15 minutes or less and code intel has restarted 3 times.

### Expected results

Code intel not to continuously restart

### Actual results

Code intel restarts repeatedly.

### Platform Information

*Komodo Version?* *build 90755 (nightly)*
*Operating System (and version)?*  *OSX*

Logs after restart 
```
[2017-10-10 16:37:00,209] [INFO] Startup: Welcome to Komodo IDE 11.0.1 build 90755 (platform macosx, running on Darwin 16.7.0 version Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64)
[2017-10-10 16:37:00,209] [INFO] Startup: /Applications/Komodo IDE 11 90755.app/Contents/MacOS/komodo built on Tue Oct 10 09:26:02 2017
[2017-10-10 16:37:00,351] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-10-10 16:37:00,977] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-10-10 16:37:01,129] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-10-10 16:37:01,730] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-10-10 16:37:03,179] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-10-10 16:37:03,182] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-10-10 16:37:03,278] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-10-10 16:37:03,392] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-10-10 16:37:03,484] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-10-10 16:37:03,505] [INFO] komodospellchecker: Spell checker loaded.
[2017-10-10 16:37:03,505] [INFO] komodospellchecker: Using dictionary en-US
[2017-10-10 16:37:03,582] [INFO] codeintel/process: Starting CodeIntel
[2017-10-10 16:37:03,583] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11 90755.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11 90755.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2017-10-10 16:37:04,033] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koamAddonManager.js:138
[2017-10-10 16:37:04,149] [DEBUG] console: error: TypeError {}
[2017-10-10 16:37:04,279] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-10-10 16:37:04,470] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-10-10 16:37:04,927] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-10-10 16:37:04,927] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-10-10 16:37:04,927] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-10-10 16:37:04,930] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-10-10 16:37:04,930] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-10-10 16:37:04,930] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011%2090755.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-10-10 16:37:05,127] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for Text
[2017-10-10 16:37:05,128] [WARNING] koLanguage: Asked for unknown language: 'None'
[2017-10-10 16:37:05,167] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-10 16:37:05,168] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-10 16:37:05,168] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-10 16:37:05,516] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-10-10 16:37:05,517] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-10-10 16:37:06,382] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-10-10 16:37:06,390] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-10-10 16:37:06,392] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-10-10 16:37:06,591] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-10-10 16:37:09,028] [DEBUG] codeintel/process: stdout: 
port:57630

pid:30870

[2017-10-10 16:37:09,028] [INFO] codeintel/process: CodeIntel started on port 57630
[2017-10-10 16:37:09,028] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-10-10 16:37:44,267] [WARNING] views: Inconsistent view count in view_closed event
[2017-10-10 16:37:44,394] [WARNING] views: Inconsistent view count in view_opened event
[2017-10-10 16:38:44,366] [INFO] codeintel/process: onClose called, code: 9
[2017-10-10 16:38:44,367] [INFO] codeintel/process: Process stopped without a request to stop it, restarting ..
[2017-10-10 16:38:44,367] [INFO] codeintel/process: Restarting CodeIntel
[2017-10-10 16:38:44,367] [INFO] codeintel/process: Starting CodeIntel
[2017-10-10 16:38:44,370] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11 90755.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11 90755.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2017-10-10 16:38:49,667] [DEBUG] codeintel/process: stdout: 
port:57661

pid:30877

[2017-10-10 16:38:49,668] [INFO] codeintel/process: CodeIntel started on port 57661
[2017-10-10 16:38:49,668] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-10-10 16:39:49,765] [INFO] codeintel/process: onClose called, code: 9
[2017-10-10 16:39:49,765] [INFO] codeintel/process: Process stopped without a request to stop it, restarting ..
[2017-10-10 16:39:49,765] [INFO] codeintel/process: Restarting CodeIntel
[2017-10-10 16:39:49,765] [INFO] codeintel/process: Starting CodeIntel
[2017-10-10 16:39:49,766] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11 90755.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11 90755.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2017-10-10 16:39:55,017] [DEBUG] codeintel/process: stdout: 
port:57670

pid:30882

[2017-10-10 16:39:55,017] [INFO] codeintel/process: CodeIntel started on port 57670
[2017-10-10 16:39:55,017] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-10-10 16:42:55,251] [INFO] codeintel/process: onClose called, code: 9
[2017-10-10 16:42:55,252] [INFO] codeintel/process: Process stopped without a request to stop it, restarting ..
[2017-10-10 16:42:55,252] [INFO] codeintel/process: Restarting CodeIntel
[2017-10-10 16:42:55,252] [INFO] codeintel/process: Starting CodeIntel
[2017-10-10 16:42:55,255] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11 90755.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11 90755.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2017-10-10 16:43:00,494] [DEBUG] codeintel/process: stdout: 
port:57697

pid:30887

[2017-10-10 16:43:00,495] [INFO] codeintel/process: CodeIntel started on port 57697
[2017-10-10 16:43:00,495] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-10-10 16:43:50,563] [INFO] codeintel/process: onClose called, code: 9
[2017-10-10 16:43:50,564] [INFO] codeintel/process: Process stopped without a request to stop it, restarting ..
[2017-10-10 16:43:50,564] [INFO] codeintel/process: Restarting CodeIntel
[2017-10-10 16:43:50,564] [INFO] codeintel/process: Starting CodeIntel
[2017-10-10 16:43:50,565] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11 90755.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11 90755.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11 90755.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2017-10-10 16:43:55,835] [DEBUG] codeintel/process: stdout: 
port:57706

pid:30891

[2017-10-10 16:43:55,835] [INFO] codeintel/process: CodeIntel started on port 57706
[2017-10-10 16:43:55,835] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
```

**Comment by mitchell-as** [comment]
@cgchoffman Please post your codeintel.log file when this happens. @Naatan implemented a feature that if the separate codeintel process is unresponsive for 5 seconds, Komodo will kill the process and restart it (e.g. if it's hung).

**Comment by cgchoffman** [comment]
@mitchell-as I did post my code intel log.  It's in the *Short Summary* section.  This is all there was:
```
<1507677269> [2017-10-10 16:14:29,360] [INFO]  codeintel.db.database: Database initialized
<1507677269> [2017-10-10 16:14:29,360] [INFO]  codeintel.scanner: Starting threaded file scanner.
<1507677269> [2017-10-10 16:14:29,362] [DEBUG]  SocketServer: Initializing SocketServer
<1507677269> [2017-10-10 16:14:34,368] [INFO]  Server: Started CodeIntel server on port: 57301, pid: 30804
<1507677269> [2017-10-10 16:14:34,495] [DEBUG]  SocketServer: Starting handle loop
```

**Comment by Naatan** [comment]
This is essentially the same issue as #3265, once that is fixed we can have some actionable logs but until then it doesn't make sense to have multiple issues on this.
