### ISSUE TITLE
Auto completions broken for xul

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#3258]
### Short Summary
I'm currently having vacation, so I gave myself the task to update my addons to K11.
Only noticed the xul auto completions are completely broken/missing.

### Additional Information
Error log:
```
[2017-10-11 03:51:49,578] [INFO] Startup: Welcome to Komodo IDE 11.0.0 build 90668 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2017-10-11 03:51:49,578] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\komodo.exe built on Tue Sep 19 14:50:13 2017
[2017-10-11 03:51:50,815] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-10-11 03:51:50,821] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/extensions/inspector@mozilla.org/chrome.manifest:31
[2017-10-11 03:51:51,069] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-10-11 03:51:52,516] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:1184
[2017-10-11 03:51:54,944] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-10-11 03:51:54,982] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-10-11 03:51:55,137] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-10-11 03:51:56,144] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-10-11 03:51:56,430] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-10-11 03:51:56,572] [INFO] komodospellchecker: Spell checker loaded.
[2017-10-11 03:51:56,572] [INFO] komodospellchecker: Using dictionary en-US
[2017-10-11 03:51:56,875] [INFO] codeintel/process: Starting CodeIntel
[2017-10-11 03:51:56,878] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2017-10-11 03:51:58,102] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-10-11 03:51:58,736] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:1269
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 1269, in 

[2017-10-11 03:51:59,971] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for Markdown
[2017-10-11 03:51:59,973] [WARNING] koLanguage: Asked for unknown language: 'None'
[2017-10-11 03:52:01,364] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-10-11 03:52:01,378] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-10-11 03:52:01,403] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-10-11 03:52:01,540] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:01,540] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:01,542] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:01,552] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:01,552] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:01,553] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:01,559] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koamAddonManager.js:138
[2017-10-11 03:52:05,717] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:05,717] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:05,719] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-10-11 03:52:06,178] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/toolbar.svg:0
[2017-10-11 03:52:06,506] [DEBUG] codeintel/process: stdout: 
port:62911

pid:106700

[2017-10-11 03:52:06,506] [INFO] codeintel/process: CodeIntel started on port 62911
[2017-10-11 03:52:06,506] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-10-11 03:52:10,733] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-10-11 03:52:10,734] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-10-11 03:52:11,203] [WARNING] console-logger: Unexpected value scale(NaN) parsing transform attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-10-11 03:52:11,203] [WARNING] console-logger: Unexpected value NaN parsing width attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-10-11 03:52:11,203] [WARNING] console-logger: Unexpected value NaN parsing height attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-10-11 03:52:11,204] [WARNING] console-logger: Unexpected value 0 0 NaN NaN parsing viewBox attribute. (1) in file:///C:/Users/wie_w/AppData/Local/ActiveState/KomodoIDE/11.0/XRE/icons/chrome/icomoon/skin/5c7cf1a0cdeac6d886fc4d3b98f56f9f-arrow-up13.svg.png.forcedAttrs.svg:0
[2017-10-11 03:52:11,622] [ERROR] console-logger: NS_ERROR_NOT_AVAILABLE:  (2) in chrome://komodo/content/sdk/icons.js:609
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/icons.js", line 609, in 

[2017-10-11 03:52:12,727] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-10-11 03:52:12,746] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-10-11 03:52:12,747] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-10-11 03:52:12,747] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-10-11 03:52:12,747] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-10-11 03:52:12,812] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-10-11 03:52:12,818] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-10-11 03:52:12,819] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-10-11 03:52:12,865] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-10-11 03:52:13,407] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-10-11 03:52:33,413] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-10-11 03:52:33,414] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2017-10-11 03:52:33,414] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2017-10-11 03:52:48,882] [WARNING] views: Inconsistent view count in view_closed event
[2017-10-11 03:52:48,904] [WARNING] views: Inconsistent view count in view_opened event
[2017-10-11 03:52:53,559] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-10-11 03:53:03,973] [WARNING] views: Inconsistent view count in view_closed event
[2017-10-11 03:53:12,844] [WARNING] views: Inconsistent view count in view_opened event
[2017-10-11 03:53:17,240] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-10-11 03:54:38,898] [WARNING] views: Inconsistent view count in view_closed event
[2017-10-11 03:54:41,535] [WARNING] views: Inconsistent view count in view_opened event
[2017-10-11 03:54:43,390] [ERROR] lint: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [koILintService.addRequest]'
+ result (number) 2147549183
+ name (string) 'NS_ERROR_UNEXPECTED'
+ filename (string) 'chrome://komodo/content/lint/lint.js'
+ lineNumber (number) 443
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
+ location (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._issueRequest :: line 443
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/lint/lint.js'
| + name (string) 'this.lintBuffer.prototype._issueRequest'
| + lineNumber (number) 443
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/lint/lint.js :: this.lintBuffer.prototype._continueRequest :: line 387
| + formattedStack (string) 'this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
'
| + stack
    this.lintBuffer.prototype._issueRequest@chrome://komodo/content/lint/lint.js:443:12
    this.lintBuffer.prototype._continueRequest@chrome://komodo/content/lint/lint.js:387:8
-- EXCEPTION END --
[2017-10-11 03:55:00,266] [WARNING] views: Inconsistent view count in view_closed event
[2017-10-11 04:00:57,223] [ERROR] console-logger: TypeError: this.cancel is not a function (2) in chrome://komodo/content/bindings/wizard.xml:150
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/wizard.xml", line 150, in 

[2017-10-11 04:00:57,276] [ERROR] console-logger: TypeError: this.cancel is not a function (2) in chrome://komodo/content/bindings/wizard.xml:150
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/wizard.xml", line 150, in 

[2017-10-11 04:05:24,338] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-10-11 04:05:24,341] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-10-11 04:05:24,341] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-10-11 04:05:24,341] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-10-11 04:05:24,342] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-10-11 04:05:24,344] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-10-11 04:05:24,344] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-10-11 04:05:24,345] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-10-11 04:05:24,346] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-10-11 04:05:24,901] [WARNING] koLanguage: Asked for unknown language: 'Django XHTML Template'
[2017-10-11 04:05:24,901] [WARNING] koLanguage: Asked for unknown language: 'Django Text Template'
[2017-10-11 04:05:24,901] [WARNING] koLanguage: Asked for unknown language: 'Django Template'
[2017-10-11 04:05:24,903] [WARNING] koLanguage: Asked for unknown language: 'Laravel Blade Template'
[2017-10-11 04:05:24,903] [WARNING] koLanguage: Asked for unknown language: 'SGML'
[2017-10-11 04:05:24,904] [WARNING] koLanguage: Asked for unknown language: 'Django XML Template'
[2017-10-11 04:05:24,904] [WARNING] koLanguage: Asked for unknown language: 'Smarty Template'
[2017-10-11 04:05:24,904] [WARNING] koLanguage: Asked for unknown language: 'Django HTML Template'
[2017-10-11 04:05:24,905] [WARNING] koLanguage: Asked for unknown language: 'UDL'
[2017-10-11 04:05:39,085] [WARNING] views: Inconsistent view count in view_closed event
[2017-10-11 04:05:39,421] [WARNING] views: Inconsistent view count in view_opened event
[2017-10-11 04:05:58,983] [WARNING] koDocument: For file overlay.js, favoring contents language Node.js over filename language JavaScript
[2017-10-11 04:06:12,523] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

[2017-10-11 04:07:18,174] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-10-11 04:09:30,265] [WARNING] koDocument: setting `koDocument.codePage` is DEPRECATED, hardwired to 65001 (unicode mode): 65001 ignored
[2017-10-11 04:09:30,417] [ERROR] console-logger: TypeError: dirtyIndicator is null (2) in chrome://openfiles/content/openfiles.js:620
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 620, in 

[2017-10-11 04:09:30,463] [ERROR] console-logger: TypeError: dirtyIndicator is null (2) in chrome://openfiles/content/openfiles.js:624
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 624, in 

[2017-10-11 04:10:32,161] [WARNING] console-logger: Key event not available on some keyboard layouts: key="f" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-10-11 04:10:32,161] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2017-10-11 04:10:32,161] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by mitchell-as** [comment]
We're handling this in #3001.
