### ISSUE TITLE
Autocomplete Pop-Up does not persist

### ISSUE THREAD

**Issue by jcloggins** [Komodo/KomodoEdit#3286]
### Short Summary

Autocomplete Pop-Up flashes for about half a second while typing. 

### Steps to Reproduce

Normal editing of a Perl file (I have not tried any other languages)

### Expected results

While typing, autocomplete pops up a suggestion window that will persist for some length of time

### Actual results

While typing, autocomplete pops up a suggestion window that will show for about half a second and then go away.

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11.0
*Operating System (and version)?* Windows 7

### Additional Information

Error log consists of many instances of:

[2017-10-17 08:59:36,217] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

[2017-10-17 08:59:37,904] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

[2017-10-17 08:59:39,230] [ERROR] console-logger: TypeError: data is null (2) in chrome://codeintel/content/sdk/feature/completions.js:129
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions.js", line 129, in 

Note: I did not edit the entries - they end where they are shown to end

Autocomplete works as expected when using Ctl-J

**Comment by Naatan** [comment]
Could you see if the nightly resolves this for you?

http://downloads.activestate.com/Komodo/nightly/komodoide/latest/

**Comment by jcloggins** [comment]
That does seem to have fixed the problem
