### ISSUE TITLE
Refactoring not working in certain contexts

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3288]
### Short Summary

Specifically highlighting lines 198 to 216 in workspace.js  fails when you try to extract a method.

```
[2017-10-17 14:23:33,336] [ERROR] JSRefactoringLangSvc: categorizeVariables failed
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\refactoring@activestate.com\components\koJavaScriptRefactoringLanguageService.py", line 142, in categorizeVariables
    self.checkStructure(scimoz, selBytes, selStyles, selectionStart, selectionEnd)
  File "C:\Users\cgcho\Komodo IDE 11.0\lib\mozilla\extensions\refactoring@activestate.com\components\koJavaScriptRefactoringLanguageService.py", line 87, in checkStructure
    raise RefactoringException("Selection not fully contained within a block")
RefactoringException: Selection not fully contained within a block
```

**Comment by Naatan** [comment]
Have you verified that this works in 10?

**Comment by cgchoffman** [comment]
It did not work in Komodo 10.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/3942bf471894ab36e8a106ef83662df3c77e0e1c

**Comment by cgchoffman** [comment]
Damn you `re.match`.
