### ISSUE TITLE
No completions on large PHP projects

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3333]
### Steps to Reproduce

 * Create a larvel project
 * Type code to trigger completions

### Expected results

Get completions

### Actual results

No Completions

### Additional Information

```
<1509122513> [2017-10-27 12:54:50,520] [ERROR]  JsonRPC: Failed calling API method: getCompletions
Traceback (most recent call last):
  File "/opt/komodo-ide-nightly/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/jsonrpc.py", line 59, in process
    result = method["function"](*request["params"])
  File "/opt/komodo-ide-nightly/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/__init__.py", line 71, in getCompletions
    completions = context.getCompletions()
  File "/opt/komodo-ide-nightly/lib/mozilla/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/php/scanner.py", line 1056, in getCompletions
    self.scope.resolveMember(symbol.name).merge(symbol)
AttributeError: '_Import' object has no attribute 'merge'
 ```

**Comment by Naatan** [comment]
https://github.com/Komodo/codeintel/commit/33bf014a0c8257c686044c3191c1bbc94160fc53
