### ISSUE TITLE
Project Wizard gets stuck ...

### ISSUE THREAD

**Issue by ffurger** [Komodo/KomodoEdit#3369]
### Short Summary
Tried twice of create a new Project on page 7/12 of the initial tutorial. I even uninstalled and reinstalled Komodo 11, just in case. Every time The Project Wizard gets stuck and no project file is being created. See screenshot attached

### Steps to Reproduce
Just go through the tutorial until get to page 7

### Expected results
A new project is created with the expected name

### Actual results
No project gets created

### Platform Information

*Komodo IDE* 
*11.01* 
*Mac OS X High Sierra* 

### Additional Information

<img width="649" alt="screen shot 2017-11-16 at 11 25 59" src="https://user-images.githubusercontent.com/30805047/32886668-ad3adf36-cac1-11e7-8ebd-07d01873ce04.png">

**Comment by mitchell-as** [comment]
Hi, would you please share the contents of your error log? (Help > Troubleshooting > View Log File)

**Comment by ffurger** [comment]
Sure:

[2017-11-16 15:53:20,843] [INFO] Startup: Welcome to Komodo IDE 11.0.1 build 90791 (platform macosx, running on Darwin 17.3.0 version Darwin Kernel Version 17.3.0: Thu Nov  9 18:14:16 PST 2017; root:xnu-4570.31.3~2/RELEASE_X86_64)
[2017-11-16 15:53:20,843] [INFO] Startup: /Applications/Komodo IDE 11.app/Contents/MacOS/komodo built on Sun Oct 15 23:56:34 2017
[2017-11-16 15:53:20,960] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2017-11-16 15:53:21,348] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2017-11-16 15:53:21,396] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2017-11-16 15:53:21,784] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2017-11-16 15:53:22,142] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2017-11-16 15:53:22,461] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2017-11-16 15:53:22,464] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2017-11-16 15:53:22,574] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2017-11-16 15:53:22,660] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2017-11-16 15:53:22,741] [INFO] codeintel/process: Starting CodeIntel
[2017-11-16 15:53:22,743] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2017-11-16 15:53:22,824] [INFO] komodospellchecker: Spell checker loaded.
[2017-11-16 15:53:22,824] [INFO] komodospellchecker: Using dictionary en-US
[2017-11-16 15:53:22,873] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2017-11-16 15:53:23,506] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2017-11-16 15:53:23,572] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2017-11-16 15:53:24,090] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-11-16 15:53:24,090] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-11-16 15:53:24,090] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-11-16 15:53:24,093] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-11-16 15:53:24,093] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-11-16 15:53:24,094] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2017-11-16 15:53:24,852] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-11-16 15:53:24,853] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-11-16 15:53:24,853] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2017-11-16 15:53:25,581] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2017-11-16 15:53:25,588] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2017-11-16 15:53:25,590] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2017-11-16 15:53:25,771] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2017-11-16 15:53:25,899] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2017-11-16 15:53:25,900] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/110
[2017-11-16 15:53:26,546] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F110 (404)
[2017-11-16 15:53:28,065] [DEBUG] codeintel/process: stdout: 
port:52472

pid:3367

[2017-11-16 15:53:28,065] [INFO] codeintel/process: CodeIntel started on port 52472
[2017-11-16 15:53:28,066] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-11-16 15:54:23,871] [ERROR] console-logger: Error: The path already exists and is not a directory: /Applications/MAMP/htdocs/index.html (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:183
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 183, in 

[2017-11-16 15:55:52,733] [ERROR] console-logger: TypeError: this.cancel is not a function (2) in chrome://komodo/content/bindings/wizard.xml:150
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/wizard.xml", line 150, in 

[2017-11-16 15:55:52,780] [ERROR] console-logger: TypeError: this.cancel is not a function (2) in chrome://komodo/content/bindings/wizard.xml:150
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/wizard.xml", line 150, in

**Comment by mitchell-as** [comment]
Hi, it looks like you selected a file to create a project in rather than a directory. You probably meant to select the parent directory of "index.html".

**Comment by ffurger** [comment]
You’re right, it looks that way, but that’s not what I did. It would be strange if I had selected 4 times in a raw a file instead of the directory, but I’ll give it one more try.

-Franco

**Comment by cgchoffman** [comment]
It's not possible to select a file using the path selector.  It doesn't show you files.  You must have written `index.html` in manually.  And it would be easy to do that multiple times as that field suggests previous entries to you.  I can reproduce a hang issue if I create a file and manually enter it's name for the path.  If the file didn't exist Komodo would just create a folder called `index.html`.

**Comment by cgchoffman** [comment]
@ffurger, please try to reproduce the issue without using a file if you don't think it's that.  Otherwise the work item for this ticket is to make sure the user didn't select a file as the install folder.

**Comment by ffurger** [comment]
I found out what the problem is: Komodo and Default Folder don't seem to like each other much. When Default Folder is running, it adds an "index.html" to the path in the Komodo window. Disabling Default Folder takes care of the issue. Question is, who is causing the problem?

Default Folder is a very useful add-on to OS X that makes opening and saving files a lot easier. See
http://stclairsoft.com/DefaultFolderX/.

**Comment by cgchoffman** [comment]
IMO Komodo shouldn't hang, period, so we should handle this issue more gracefully regardless of interference from a third party application.  You shouldn't have been able to get to the "creation" screen with a file specified as a folder.

**Comment by cgchoffman** [comment]
@ffurger thanks for digging.

**Comment by ffurger** [comment]
Now that I think about this, the issue in this case goes deeper. I also noticed that sometime it took Komodo for ever to open up the window for creating a new project. In that case it just showed me first a pretty small black window with only the three small round buttons at the top left. Some other times it simply showed a black window of the right size - but no content at all. So it looks as if there is a pretty serious incompatibility.

**Comment by cgchoffman** [comment]
There is no evidence that Default FolderX is causing those other issues.  Those sound like different issues.  Please files those separately with reproduction steps so we can investigate them.

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/b11198301aa2528c1cf2dd2572408f3c3b6b2b89

**Comment by cgchoffman** [comment]
Komodo now prevents the user from continuing if they have managed to type a path to a file in the field.  It will show an "invalid path" warning message to indicate what the user did wrong.
