### ISSUE TITLE
Code Completion fails in Komodo IDE 11

### ISSUE THREAD

**Issue by wshearn** [Komodo/KomodoEdit#3375]
### Short Summary
In Komodo IDE 11 when the autocomplete dialog pops up I cannot press tab or enter to autocomplete.

### Steps to Reproduce
Setup Komodo IDE to work with golang
Open a golang project
Start typing something that should complete(ie `fmt.`)
Press tab or enter to try and auto complete

### Expected results
It autocompletes what I am typing

### Actual results
It enters either a tab space or a new line

### Platform Information

*Komodo Edit or IDE?* IDE
*Komodo Version?* 11
*Operating System (and version)?* Was able to reproduce it in OSX 10.13.1 and Ubuntu 16.04

### Additional Information
This is a regression from 10 as I tested the same steps there and everything worked as expected.

 Relevant snippets from the log:
```
[2017-11-19 05:13:44,648] [ERROR] console-logger: TypeError: invalid 'in' operand language.completion_prefixes (2) in chrome://codeintel/content/sdk/feature/completions/panel.js:365
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions/panel.js", line 365, in 

[2017-11-19 05:13:52,264] [ERROR] console-logger: TypeError: invalid 'in' operand language.completion_prefixes (2) in chrome://codeintel/content/sdk/feature/completions/panel.js:365
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions/panel.js", line 365, in 

[2017-11-19 05:13:58,424] [ERROR] console-logger: TypeError: invalid 'in' operand language.completion_prefixes (2) in chrome://codeintel/content/sdk/feature/completions/panel.js:365
Traceback (most recent call last):
  File "chrome://codeintel/content/sdk/feature/completions/panel.js", line 365, in 
```
Video of me reproducing it: https://i.imgur.com/quMFdyZ.gifv

**Comment by mitchell-as** [comment]
Hi, thanks for the report.

**Comment by Naatan** [comment]
What language was this?

**Comment by Defman21** [comment]
>Open a golang project

**Comment by davefultz** [comment]
Let me chime-in here. Just got 11.0.1 and code-intel with Python fails. I've tried resetting the db multiple times, removing the "use legacy python" from the prefs and nothing works.

Dave

**Comment by Naatan** [comment]
@davefultz there isn't enough to go on either your report or the OP's report to start combining issues at this point, Please report a new issue and be sure to provide details, eg. what are or aren't you seeing, does it work with other languages, etc.

**Comment by Naatan** [comment]
https://github.com/Komodo/KomodoIDE/commit/02cdb570468e0019d1bec68e05f672564be822f6
