### ISSUE TITLE
"New File from Template" not working on Mac

### ISSUE THREAD

**Issue by PalestinianLiberator** [Komodo/KomodoEdit#3387]
### Short Summary
Attempting to open a new file from the default templates is completely unresponsive after selecting the template to open.

If no file is already open, then a blank file is opened. If a file is already open and the "New File from Template" is selected, nothing happens. This occurs for all templates.

### Steps to Reproduce
Fresh install of Komodo IDE [trial version] 11.0.1 on Mac High Sierra.
Launch Program -> Select "New File from Template"

### Expected results
A new file is opened with the selected template.

### Actual results
Blank file opens if no file already open, otherwise nothing.

### Platform Information

Komodo IDE
11.0.1
Mac OS High Sierra

### Additional Information

Error Log:

[2017-11-27 04:32:00,137] [INFO] codeintel/process: CodeIntel started on port 63737
[2017-11-27 04:32:00,137] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2017-11-27 04:32:28,770] [WARNING] views: Inconsistent view count in view_closed event
[2017-11-27 04:32:28,860] [WARNING] views: Inconsistent view count in view_opened event
[2017-11-27 04:32:32,228] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg?size=14:0
[2017-11-27 04:32:34,761] [WARNING] views: Inconsistent view count in view_closed event
[2017-11-27 04:32:34,839] [WARNING] views: Inconsistent view count in view_opened event
[2017-11-27 04:32:34,945] [ERROR] console-logger: TypeError: callback is not a function (2) in chrome://komodo/content/project/peTemplate.js:77
Traceback (most recent call last):
  File "chrome://komodo/content/project/peTemplate.js", line 77, in

**Comment by Naatan** [comment]
Where are you using "New from Template" from?

**Comment by PalestinianLiberator** [comment]
Here is a video of me recreating the bug in various ways:
I attempt to open a "New File from Template" from the main screen, I use the shortcut "Shift + Command + N", I use the option from the file menu, and I attempt it both with a file open and without a file open.

https://www.youtube.com/watch?v=7cMsdN2tGrU&feature=youtu.be

**Comment by Naatan** [comment]
So the issue only happens when you already have a file open?

Can you reproduce this using `Help > Troubleshooting > Restart in Safe-mode` ?

Please verify that when restarting in safe-mode Komodo should be using the default UI (all your settings would be temporarily reset).

**Comment by PalestinianLiberator** [comment]
It happens both when a file is open, and when one isn't. I'm sorry if I wasn't clear.

If a file is already open and I attempt to open "New File from Template", nothing happens.
If no file is open, then it simply opens a completely blank file with no template.

Restarting in Safe-Mode yielded the same results as running it in normal mode. I went ahead and re-installed Komodo after wiping the installation clean and recreated the issue both in regular mode and in safe-mode.

**Comment by Naatan** [comment]
@mjainQA can you reproduce this on macos?

**Comment by cgchoffman** [comment]
I'm not able to reproduce this on Mac.

**Comment by caolandix** [comment]
This wasn't my bug which is why I acreated a new one... Anyway, here is my data:

Steps to Reproduce

I click File -> New From Template
Expected results

Choices appear
Actual results

no choices appear
Platform Information

Komodo IDE
Komodo Version? 11.1 The newest. I purchased a license 10 days ago.
Operating System (and version)? MacOS 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
Additional Information

I restarted in Safe Mode and the templates now show up. if I start again the templates disappear

[2018-10-23 09:57:14,647] [INFO] Startup: Welcome to Komodo IDE 11.1.0 build 91033 (platform macosx, running on Darwin 16.7.0 version Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64)
[2018-10-23 09:57:14,647] [INFO] Startup: /Applications/Komodo IDE 11.app/Contents/MacOS/komodo built on Wed May 30 10:04:57 2018
[2018-10-23 09:57:14,830] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2018-10-23 09:57:15,627] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-10-23 09:57:15,717] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
@chrome://komodo/content/komodo.js:15:1

[2018-10-23 09:57:16,285] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
File "", line 0, in

[2018-10-23 09:57:16,456] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2018-10-23 09:57:16,763] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-10-23 09:57:16,812] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2018-10-23 09:57:16,816] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2018-10-23 09:57:16,974] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2018-10-23 09:57:17,081] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-10-23 09:57:17,329] [INFO] codeintel/process: Starting CodeIntel
[2018-10-23 09:57:17,331] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2018-10-23 09:57:17,388] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-10-23 09:57:17,421] [INFO] komodospellchecker: Spell checker loaded.
[2018-10-23 09:57:17,421] [INFO] komodospellchecker: Using dictionary en-US
[2018-10-23 09:57:18,444] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in

[2018-10-23 09:57:18,445] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in

[2018-10-23 09:57:19,015] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,015] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,016] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,021] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,021] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,021] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:20,344] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-10-23 09:57:20,382] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-10-23 09:57:20,386] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2018-10-23 09:57:20,444] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-23 09:57:20,445] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-23 09:57:20,445] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-23 09:57:20,535] [ERROR] console-logger: TypeError: n is undefined (2) in chrome://komodo/content/contrib/commonjs/underscore.js:5
Traceback (most recent call last):
File "chrome://komodo/content/contrib/commonjs/underscore.js", line 5, in

[2018-10-23 09:57:21,370] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2018-10-23 09:57:21,371] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/111
[2018-10-23 09:57:21,897] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F111 (404)
[2018-10-23 09:57:21,898] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2018-10-23 09:57:22,982] [DEBUG] codeintel/process: stdout:
port:63950

pid:16920

[2018-10-23 09:57:22,982] [INFO] codeintel/process: CodeIntel started on port 63950
[2018-10-23 09:57:22,983] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1

**Comment by caolandix** [comment]
Any update on this?

**Comment by caolandix** [comment]
The templates come up in Safe mode but if I go back to regular, it fails again.

**Comment by cgchoffman** [comment]
Hrm, something went wrong there then.  Reset Everything does the same thing as Safe Mode but doesn't return to the original state.  You can manually reset by renaming *~/Library/Application Support/KomodoIDE/11.1*.  If you only want to reset the toolbox (which is where template files live) you can just remove/rename the *tools* folder and the file *toolbox.sqlite*.   Komodo should be turned off when you rename any files or folders in the profile directory.

**Comment by caolandix** [comment]
I shutdown Komodo, renamed 11.1 to 11.1.old, restarted Komodo. Same issue. :(

On October 31, 2018 11:08:25 AM PDT, Carey Hoffman <notifications@github.com> wrote:
>Hrm, something went wrong there then.  Reset Everything does the same
>thing as Safe Mode but doesn't return to the original state.  You can
>manually reset by renaming *~/Library/Application
>Support/KomodoIDE/11.1*.  If you only want to reset the toolbox (which
>is where template files live) you can just remove/rename the *tools*
>folder and the file *toolbox.sqlite*.   Komodo should be turned off
>when you rename any files or folders in the profile directory.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Komodo/KomodoEdit/issues/3387#issuecomment-434786353

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cgchoffman** [comment]
@caolandix can you make sure you open the ticket in the browser when you reply?  You're dropping your email signature into Github and the email you're responding to into the ticket.  I know Github says that you can reply but they don't handle replies properly.

Ok so this is an upgrade issue.  My mistake.  When you don't have a profile for the version you're starting Komodo will look for an older version then upgrade it to the version you're starting. 
 Sounds like something is going wrong in the upgrade process.   Before you workaround this could you move the `11.1` folder aside again, start Komodo, then share your logs?  THAT will have relevant logs output i bet as the.

To work around this you have to move the `KomodoIDE` folder aside and (if you have it) the `KomodoEdit` folder.

BUT,

**Comment by caolandix** [comment]
Okay so that worked...
I renamed these two:

~/.../Komodo IDE -> Komodo IDE.old
~/.../KomodoIDE -> KomodoIDE.old

And now the templates show up in New File from templates.

**Comment by cgchoffman** [comment]
Did you get a chance to do this?:
>  Before you workaround this could you move the 11.1 folder aside again, start Komodo, then share your logs?

**Comment by caolandix** [comment]
I did not. Did you still want to see them? It seems to be fixed

**Comment by cgchoffman** [comment]
@caolandix , if you have time, yes please but i've taken up a lot of your time so it's up to you.

**Comment by caolandix** [comment]
Yeah no worries. Do you want them from .old or the actual one being used?

**Comment by cgchoffman** [comment]
To reproduce the upgrade error you'll need to change `KomodoIDE.old` to `KomodoIDE`, then move the `11.1` folder in there so Komodo will attempt to upgrade from whatever older version you have in the `KomodoIDE` folder.  When you start Komodo after doing the above, grab your logs and share them here.
