### ISSUE TITLE
Can't open file called "Date.pm"

### ISSUE THREAD

**Issue by CaryMillsap** [Komodo/KomodoEdit#341]
Repro:
1. Create a file called "date.pm" in a directory within an existing Komodo project.
2. Double-click on the filename in Komodo to open it. Expected: file opens. What happens: file opens, just as I expected. Close the file.
3. In a separate Finder or Terminal window, rename the "date.pm" file to "Date.pm" (init cap 'D').
4. Double-click on the filename in Komodo to open it. Expected: file opens. What happens: nothing. The file will not open. Choosing Open from the context menu behaves the same way.
5. I can rename the file to "Date1.pm" or "D.pm" or anything else I like, and Komodo will open it just fine, but if the file is called "Date.pm", Komodo will not open it.

**Comment by cgchoffman** [comment]
Platform and Komodo version? (assuming Windows)

**Comment by CaryMillsap** [comment]
Mac OS X 10.10.3
Komodo IDE, version 9.1.0, build 87337, platform macosx.
Built on Fri May 29 20:57:45 2015.

**Comment by cgchoffman** [comment]
Oh weird.  K thank you for updating.  Sorry, for got to ask for your error logs.  When you experience the issue please paste your logs here; Help > Troubleshooting > View Log File.

**Comment by CaryMillsap** [comment]
Weird is right. The error log is absolutely empty before and after attempting to open the file.

**Comment by cgchoffman** [comment]
That's a bug on OSX that we're working on fixing.  Resize the error logs window and the content should reappear.

**Comment by CaryMillsap** [comment]
Ah, there we go! I knew the scroll bars were moving, but I couldn't figure out how to get to the content that was moving them.

Here's the error log generated by a fresh restart and then two attempted Open operations upon Date.pm:

* * *

[2015-06-12 12:31:24,594] [INFO] Startup: Welcome to Komodo IDE 9.1.0 build 87337 (platform macosx, running on Darwin 14.3.0 version Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64)
[2015-06-12 12:31:24,594] [INFO] Startup: /Applications/Komodo IDE 9.app/Contents/MacOS/komodo built on Fri May 29 20:57:45 2015
[2015-06-12 12:31:24,670] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2015-06-12 12:31:24,918] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-06-12 12:31:24,918] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-06-12 12:31:24,919] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-06-12 12:31:24,919] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-06-12 12:31:24,955] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-06-12 12:31:25,052] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2334
[2015-06-12 12:31:25,074] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2334
[2015-06-12 12:31:25,127] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-06-12 12:31:25,128] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-06-12 12:31:25,323] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-06-12 12:31:25,375] [WARNING] keybindings: [Meta+Shift+O] was used for 'cmd_dbgStepOver', overriding to use 'cmd_scope-files'
[2015-06-12 12:31:27,456] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-06-12 12:31:27,512] [DEBUG] places_js: waiting for document complete
[2015-06-12 12:31:29,594] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/components/koamAddonManager.js:138
ERROR:xpcom:Unhandled exception calling 'int8 * initWithFile(in nsISomething, in boolean);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocument.py", line 184, in initWithFile
    self._setupPrefs()
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocument.py", line 287, in _setupPrefs
    encoding_name = self._getEncodingNameForNewFile(language)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocument.py", line 248, in _getEncodingNameForNewFile
    return self.prefs.getString('encodingDefault')
  File "<XPCOMObject method 'getString'>", line 3, in getString
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
ERROR:xpcom:Unhandled exception calling 'int8 * createDocumentFromURI(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocumentService.py", line 212, in createDocumentFromURI
    return self.createNewDocumentFromURI(uri)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocumentService.py", line 197, in createNewDocumentFromURI
    doc.initWithFile(file,0)
  File "<XPCOMObject method 'initWithFile'>", line 3, in initWithFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-06-12 12:31:52,644] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI] (2) in chrome://komodo/content/views.js:537
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 537, in 

ERROR:xpcom:Unhandled exception calling 'int8 * initWithFile(in nsISomething, in boolean);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocument.py", line 184, in initWithFile
    self._setupPrefs()
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocument.py", line 287, in _setupPrefs
    encoding_name = self._getEncodingNameForNewFile(language)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocument.py", line 248, in _getEncodingNameForNewFile
    return self.prefs.getString('encodingDefault')
  File "<XPCOMObject method 'getString'>", line 3, in getString
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
ERROR:xpcom:Unhandled exception calling 'int8 * createDocumentFromURI(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocumentService.py", line 212, in createDocumentFromURI
    return self.createNewDocumentFromURI(uri)
  File "/Applications/Komodo IDE 9.app/Contents/Resources/components/koDocumentService.py", line 197, in createNewDocumentFromURI
    doc.initWithFile(file,0)
  File "<XPCOMObject method 'initWithFile'>", line 3, in initWithFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-06-12 12:33:06,205] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI] (2) in chrome://komodo/content/views.js:537
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 537, in

**Comment by cgchoffman** [comment]
I can't reproduce this at all.  @Naatan, can you?

**Comment by CaryMillsap** [comment]
Any way I can help, just let me know. I can put together a GoToMeeting if you'd like.

**Comment by Naatan** [comment]
Reproduced on OSX. @cgchoffman fwiw I think its vital that you do the rename outside of Komodo.

**Comment by cgchoffman** [comment]
ya i renamed in finder and terminal.  Both times the file opened fine in Komodo afterwards from Places.  Oh well.  You repro'd.

**Comment by Naatan** [comment]
Oddly enough I am no longer able to reproduce the issue :\ @CaryMillsap are you able to repro it consistently?

**Comment by CaryMillsap** [comment]
Yes. Every time.

I'll be happy to provide whatever you need: more log files, video,
GoToMeeting, ...whatever.

Komodo IDE, version 9.1.0, build 87337, platform macosx. Built on Fri May
29 20:57:45 2015.


Cary Millsap

**Comment by CaryMillsap** [comment]
I just upgraded to 9.2 and can confirm that I can still reproduce the problem.

Komodo IDE, version 9.2.0, build 87616, platform macosx. Built on Tue Aug 4 11:29:06 2015.

**Comment by Naatan** [comment]
Does Komodo show the file as "Date.pm" after renaming it (before opening)?

**Comment by CaryMillsap** [comment]
Komodo shows the name of the file in the Places sidebar.

   1. The file shows as "Date.pm" in the Places sidebar. Double-clicking
   this name will not open the file.
   2. After renaming "Date.pm" to "date.pm" in a separate Terminal window,
   it shows in the Places sidebar as "date.pm" (without requiring a
   refresh). Double-clicking this name opens the file just fine.
   3. After renaming "date.pm" to "Date-01.pm" in a separate Terminal
   window, it shows as "Date-01.pm" (without requiring a
   refresh). Double-clicking this name opens the file just fine.
   4. After renaming "Date-01.pm" to "Date.pm" in a separate Terminal
   window, it shows as "Date.pm" (without requiring a
   refresh). Double-clicking this name will not open the file.

Komodo IDE, version 9.2.0, build 87616, platform macosx.
Built on Tue Aug 4 11:29:06 2015.


Cary Millsap

**Comment by Naatan** [comment]
Thought I had reproduced it, but false alarm. Can you reproduce this with a [clean profile](http://beta.docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings)?

**Comment by CaryMillsap** [comment]
When I run with a clean profile, Komodo opens Date.pm.

How can I debug my profile?


Cary

**Comment by Naatan** [comment]
It's probably a setting on Date.pm that's causing an issue for you. Try deleting the doc-state.xmlc file from your profile folder while Komodo isn't running.

**Comment by CaryMillsap** [comment]
I renamed ~/Library/Application\ Support/KomodoIDE/9.2/doc-state.xmlc to
doc-state.xmlc.safe while Komodo wasn't running.

Now, I can open Date.pm from the Places panel, and Komodo seems to be
otherwise working fine as well.

Thank you,


Cary Millsap
