### ISSUE TITLE
Komodo Edit Run Command not working properly.

### ISSUE THREAD

**Issue by sidkapse** [Komodo/KomodoEdit#3446]
Changes done in code are getting reflected in command output only after restarting the Komodo Edit after saving the changes in the file.

Screen Recorder video:
Please click the link to see the bug video:
https://www.dropbox.com/s/qhl2s71qn51a5zw/Capture_2018_01_30_10_30_31.mov?dl=0

Please fill out the requested fields to the best of your ability.

### Short Summary
Changes done in code are getting reflected in command output only after restarting the Komodo Edit after saving the changes in the file.

### Steps to Reproduce
1) I have set up the Run key combination on my Mac i.e Shift+command(Meta)+R plus did all the settings asked by the Trainer Bill Weinman on Lynda.com for Python Essential Training course.
2) Then he asked me to open one of the exercise files, I opened it, then he asked press Shift+command+R, I did that I was able to see the output properly in command output i.e Hello World.
3) Then I tried doing a small change in print statement i.e 'Hello Worldsss.' and again clicked Shift+command+R but in command out but changes not getting reflected in Command Output.
4) I closed the Komodo Edit it asked me to save the changes I clicked save.
5) I opened the Komodo Edit again and pressed Shift+command+R the changes got reflected in Command Output.
6) Again made a little change in my print statement than again clicked Shift+command+R, same problem of "changes not reflecting in command output".
7) Then again I closed the Komodo Edit asked me to save I clicked save than again started Komodo Edit and pressed Shift+Command+R, I can see the changes in Command Output.

### Expected results
Changes should be reflected without restarting the software.

### Actual results
Changes not getting reflected without restarting the software.

### Platform Information

*Komodo Edit* 
*Komodo Version?* 
Komodo Edit, version 11.0.2, build 18122, platform macosx.
Built on Mon Dec 4 16:56:01 2017.

*Operating System (and version)?* 
Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,1
  Processor Name:	Intel Core i7
  Processor Speed:	1.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	8 GB

### Additional Information
eg. Error logs, screenshots, workarounds
<!--

Screen Recorder video:
Please click the link to see the bug video:
https://www.dropbox.com/s/qhl2s71qn51a5zw/Capture_2018_01_30_10_30_31.mov?dl=0

Logs:-

[2018-01-30 10:25:40,118] [INFO] Startup: Welcome to Komodo Edit 11.0.2 build 18122 (platform macosx, running on Darwin 15.6.0 version Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64)
[2018-01-30 10:25:40,118] [INFO] Startup: /Applications/Komodo Edit 11.app/Contents/MacOS/komodo built on Mon Dec 4 16:56:01 2017
[2018-01-30 10:25:40,218] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2018-01-30 10:25:40,485] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-01-30 10:25:40,527] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2018-01-30 10:25:40,715] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2018-01-30 10:25:40,715] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2018-01-30 10:25:40,877] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-01-30 10:25:40,985] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2018-01-30 10:25:41,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-01-30 10:25:41,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-01-30 10:25:41,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-01-30 10:25:41,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-01-30 10:25:41,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-01-30 10:25:41,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-01-30 10:25:41,862] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-01-30 10:25:41,862] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-01-30 10:25:41,948] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-01-30 10:25:41,949] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-01-30 10:25:41,949] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-01-30 10:25:41,949] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-01-30 10:25:41,949] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-01-30 10:25:41,949] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-01-30 10:25:41,949] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-01-30 10:25:41,950] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-01-30 10:25:42,515] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-01-30 10:25:42,529] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-01-30 10:25:42,607] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2018-01-30 10:25:42,613] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2018-01-30 10:25:42,617] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2018-01-30 10:25:42,624] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2018-01-30 10:25:42,628] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2018-01-30 10:25:42,633] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2018-01-30 10:25:42,720] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-01-30 10:25:43,182] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2018-01-30 10:25:43,185] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2018-01-30 10:25:43,528] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-01-30 10:25:43,528] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-01-30 10:25:43,528] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-01-30 10:25:43,528] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-01-30 10:25:43,529] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-01-30 10:25:43,529] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-01-30 10:25:43,530] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-01-30 10:25:43,530] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-01-30 10:25:44,158] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2018-01-30 10:25:45,200] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-01-30 10:25:45,202] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-01-30 10:25:48,616] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-01-30 10:25:48,616] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-01-30 10:25:48,616] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-01-30 10:25:48,616] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-01-30 10:25:48,616] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-01-30 10:25:48,617] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-01-30 10:25:48,617] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-01-30 10:25:48,617] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-01-30 10:26:17,033] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in

**Comment by sidkapse** [comment]
Changes done in code are getting reflected in command output only after restarting the Komodo Edit after saving the changes in the file.

**Comment by mitchell-as** [comment]
Hi, you need to save the file before running it. (You do not have to quit Komodo Edit). Run commands can only read the saved versions of files, not a working version in Komodo Edit.

Note: If you purchase Komodo IDE, you can use it's "Run in-line" feature in order to execute unsaved code and get what you expect.

**Comment by sidkapse** [comment]
I figured it out already.
Anyway thanks for the support.

Have a nice day.

**Comment by sidkapse** [comment]
Hello,
Please find the attached screenshot.
Why am I getting this error?
How to solve it?

Thankyou.

**Comment by Defman21** [comment]
Please use the Github interface to reply. Replying via e-mail does not attach anything.

**Comment by mitchell-as** [comment]
Also, please ask these kinds of support questions on our forum: https://community.komodoide.com/
