### ISSUE TITLE
error while try opening file 

### ISSUE THREAD

**Issue by ahmadmarafa** [Komodo/KomodoEdit#3459]
Some time komodo open new tab with out any content and i got File Open Error message
" Komodo was unable to open the file .... " 

**Komodo Edit, version 11.0.2, build 18122, platform linux-x86_64. Built on Mon Dec 4 16:56:06 2017**

Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 937, in 

[2018-02-01 23:27:08,998] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:361:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:485:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:510:20
-- EXCEPTION END --
[2018-02-01 23:27:12,748] [ERROR] view.tabbed: 
-- EXCEPTION START --
TypeError: this.__globalPrefs is undefined
+ stack
    initPrefs@vieweditor:509:17
    init@vieweditor:355:13
    newView@viewlistbase:502:17
    newView@viewmultiview:333:20
    createViewFromDocument@viewlistbase:119:24
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:361:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:485:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:510:20
-- EXCEPTION END --
[2018-02-01 23:27:14,649] [ERROR] views: 
-- EXCEPTION START --
TypeError: view is null
+ stack
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:361:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:485:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:510:20
-- EXCEPTION END --

**Comment by babobski** [comment]
I have this bug also very often, in both K10.2.2 and in K11.0.2:

![afbeelding](https://user-images.githubusercontent.com/3530262/35796541-30d77432-0a5d-11e8-8296-f30620ea0c42.png)

Happens to me very often, most of the time when I try to open the file again it will open the file.

```
ERROR:xpcom:Unhandled exception calling 'G     int8 * executablePath(out retval wstring);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 276, in _CallMethod_
    ret = func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koAppInfo.py", line 134, in get_executablePath
    executables = self.FindExecutables()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koAppInfo.py", line 262, in FindExecutables
    self._executables += self._locateExecutables(exename, self.defaultInterpreterPrefName)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koAppInfo.py", line 223, in _locateExecutables
    executables = which.whichall(exeName, exts=exts, path=paths)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\which.py", line 309, in whichall
    return list( whichgen(command, path, verbose, exts) )
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\which.py", line 257, in whichgen
    match = _getRegisteredExecutable(command)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\komodo\which.py", line 103, in _getRegisteredExecutable
    if registered and not os.path.exists(registered[0]):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\..\python\lib\genericpath.py", line 18, in exists
    os.stat(path)
TypeError: must be encoded string without NULL bytes, not str
ERROR:xpcom:Unhandled exception calling 'int8 * load();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koDocument.py", line 522, in load
    self._loadFromFile(self.file)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koDocument.py", line 533, in _loadFromFile
    self._guessLanguage()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koDocument.py", line 471, in _guessLanguage
    guessLanguageFromFullContents(fileNameLanguage, buffer, self)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koLanguage.py", line 718, in guessLanguageFromFullContents
    newLang = self._distinguishJavaScriptOrNode(buffer)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\components\koLanguage.py", line 861, in _distinguishJavaScriptOrNode
    if not nodeJSAppInfo.executablePath:
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\client\__init__.py", line 396, in __getattr__
    return getattr(interface, attr)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 10\lib\mozilla\python\xpcom\client\__init__.py", line 494, in __getattr__
    return NS_InvokeByIndex(self._comobj_, method_index, args)
Exception: 2147500037 (NS_ERROR_FAILURE)
[2018-02-05 10:11:37,362] [WARNING] codeintel.css: Unable to process CSS selector '[type="checkbox"]'
[2018-02-05 10:11:58,864] [ERROR] views: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.load]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._newViewFromURI :: line 568"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocument.load]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/views.js'
+ lineNumber (number) 568
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:568:12
viewManager.prototype.'...232 chars
+ location (object) JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._newViewFromURI :: line 568
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/views.js'
| + name (string) 'viewManager.prototype._newViewFromURI'
| + lineNumber (number) 568
| + columnNumber (number) 12
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/views.js :: viewManager.prototype._doFileOpen :: line 701
| + formattedStack (string) 'viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:568:12
viewManager.prototype.'...232 chars
| + stack
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:568:12
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:701:11
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:726:19
-- EXCEPTION END --
```

**Comment by Naatan** [comment]
Are you able to reproduce it reliably or is it seemingly random?

**Comment by ahmadmarafa** [comment]
it's random , however i think i fixed it just by changing  
var urllist = data.split('\n'); 
to 
var urllist = data.trim().split('\n');
and add 
if(urllist[u] == null) continue ;
after 
 for (var u=0; u < urllist.length; ++u)

**Comment by Naatan** [comment]
Where did you change this?

**Comment by ahmadmarafa** [comment]
chrome://komodo/content/views.js line 934

**Comment by Naatan** [comment]
Thanks, nice digging!

**Comment by Defman21** [comment]
Yaay, it's finally fixed! I've had the same problem but it wasn't happening that often so I didn't bother to file an issue.

**Comment by cgchoffman** [comment]
I'm sure this goes without saying but please try the Nightly when it's available and try to confirm it's resolved.  That would be greatly appreciated.  We were never able to reproduce this internally so I couldn't test this fix.

**Comment by Defman21** [comment]
Will do.
