### ISSUE TITLE
Komodo 10 can't debug ruby 2.4.3

### ISSUE THREAD

**Issue by luc-j-bourhis** [Komodo/KomodoEdit#3474]
### Short Summary

Running a script with ruby 2.4.3 through Komodo 10 debugger results in a stack trace

### Steps to Reproduce

Open any ruby script in Komodo 10, at it simplest, 

```
puts "Hello, World!
```

and then launch the debugger. In the following, that file is saved in `/Users/luc/Downloads/hello.rb`

### Expected results

The debugger works!

### Actual results

A stack trace:

```
wrong number of arguments (given 2, expected 1)
/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:562:in `initialize'
/Users/luc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/byebug-10.0.0/lib/byebug/context.rb:145:in `new'
/Users/luc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/byebug-10.0.0/lib/byebug/context.rb:145:in `processor'
/Users/luc/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/byebug-10.0.0/lib/byebug/context.rb:98:in `at_line'
/Users/luc/Downloads/hello.rb:1:in `<top (required)>'
/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:423:in `debug_load'
/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:423:in `start'
/Applications/Komodo IDE 10.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:1836:in `<main>'
```

### Platform Information

* Komodo IDE 10
* MacOS 10.12.6
* Ruby 2.4.3

**Comment by luc-j-bourhis** [comment]
I think this [recent commit](https://github.com/deivid-rodriguez/byebug/commit/8b13bdfe0092c9186b4ee92231e81d5ad0c8cccf#diff-1ecacb2aa047da75e7dfcd5733d40754) to byebug is the culprit

**Comment by mitchell-as** [comment]
Thanks for the report. You'll have to use Byebug < 10 for now.
