### ISSUE TITLE
Word wrap greyed out

### ISSUE THREAD

**Issue by tcdaly** [Komodo/KomodoEdit#349]
When I open a text file outside of the currently loaded project, the 'word wrap' option in the 'view' menu is greyed out.  When I open another file (from the currently loaded project), then switch back to the first text file, the 'word wrap' option is available (even though I have made no changes to the original text file, or to program preferences).  This looks like a bug?

Komodo Edit, version 9.1.0, build 15798, platform win32-x86. Built on Sat May 30 06:10:24 2015

**Comment by cgchoffman** [comment]
I can't seem to reproduce this.  Opened a new text file (ctrl + n), click View > Word wrap (it is not grayed out).  Any thing in your error logs? Help > Troubleshooting > View Log file.

**Comment by tcdaly** [comment]
I can still reproduce here.  It happens to the first file that is opened or created.  Once the 2nd file is opened, 'word wrap' becomes available in both files.

In error log, I have:

[2015-06-17 19:07:31,368] [ERROR] console-logger: TypeError: topView.findViewsForURI is not a function (2) in chrome://breadcrumbs/content/breadcrumbs.js:430
Traceback (most recent call last):
  File "chrome://breadcrumbs/content/breadcrumbs.js", line 430, in 

[above error repeats multiple times]

[2015-06-17 19:07:30,696] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [koIAppInfoEx.localHelpFile] (2) in chrome://komodo/content/browse.js:206
Traceback (most recent call last):
  File "chrome://komodo/content/browse.js", line 206, in

**Comment by cgchoffman** [comment]
Ahh there it is, this is issue #329
