### ISSUE TITLE
Completions failing for PHP 

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#3490]
```
<1519681201> [2018-02-26 16:43:38,539] [DEBUG]  service: Getting completions for /home/nathan/Projects/Samples/laravel5-quickstart/server.php at pos 221
<1519681201> [2018-02-26 16:43:42,233] [ERROR]  JsonRPC: Failed calling API method: getCompletions
Traceback (most recent call last):
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/server/jsonrpc.py", line 59, in process
    result = method["function"](*request["params"])
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/service/__init__.py", line 71, in getCompletions
    completions = context.getCompletions()
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/php/scanner.py", line 1073, in getCompletions
    completions = super(PHPScopeCompletionContext, self).getCompletions()
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/completions.py", line 131, in getCompletions
    self.import_resolver.resolveImports(scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/common.py", line 696, in resolveImports
    self.resolveImport(symbol, scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/php/import_resolver.py", line 50, in resolveImport
    symbol = self._symbol_resolver.resolve(scope, import_symbol.type)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/common.py", line 917, in resolve
    self._import_resolver.resolveImports(scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/common.py", line 696, in resolveImports
    self.resolveImport(symbol, scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/php/import_resolver.py", line 50, in resolveImport
    symbol = self._symbol_resolver.resolve(scope, import_symbol.type)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/common.py", line 849, in resolve
    self._import_resolver.resolveImports(scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/common.py", line 696, in resolveImports
    self.resolveImport(symbol, scope)
  File "/home/nathan/Projects/komodo-dev/mozilla/build/moz3500-ko11.10/mozilla/ko-rel/dist/bin/extensions/codeintel@activestate.com/pylib/codeintel/lib/language/legacy/php/import_resolver.py", line 62, in resolveImport
    symbol = symbol.resolveMember(name_part)
AttributeError: '_Import' object has no attribute 'resolveMember'
```

File I was using:

```
<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

$uri = urldecode(
    parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
);


// This file allows us to emulate Apache's "mod_rewrite" functionality from the
// built-in PHP web server. This provides a convenient way to test a Laravel
// application without having installed a "real" web server software here.
if ($uri !== '/' && file_exists(__DIR__.'/public'.$uri)) {
    return false;
}

require_once __DIR__.'/public/index.php';

```

**Comment by Naatan** [comment]
I can no longer reproduce this. I suspect this was related to my hosed build.
