### ISSUE TITLE
Refactoring: Rename variable isn't working

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3541]
### Steps to Reproduce
- Using the sample python code below try to use refactoring to rename a variable in the sample
```
import subprocess

def Usage(app_name):
    print("Usage: %s [-v | --verbose] [-h | --help]  [-f | --inputFormat] [[-i | --inputFile] filename] [[-u | --username] | [-tOutputType | --outputType]] [-U] [-G] " % app_name)
    print("       -h == display program options")
    print("       -f == input Format (%s) default %s" % (INPUT_TYPES, EMAIL))
    print("       -i == input filename")
    print("       -u == output usernames (cannot be used with -e option)")
    print("       -t == outputType (%s) default %s" % (OUTPUT_TYPES, USERID))
    print("       -U == Userids in inputfile")
    print("       -G == use GUI")
    print("       -v == verbose messages")

    sys.exit(2)

	
arrUser = "foo@nvidia.com' , 'bar@nvidia.com"
arrOwner = "schehab@nvidia.com"
mgr = 2155
rootpath = 'C:\\tmp\\encrypt\\'
fileExport = rootpath + 'ExcelFiles\\'
exportFile = fileExport + str(mgr) + '-Org.xlsx'
cmd = 'powershell -command ". \'' + rootpath + 'encryptFile.ps1\'; $arrUser = \'' + str(arrUser) + '\'; $arrOwner = \'' + arrOwner + '\'; $filePath = \'' + exportFile + '\'; EncryptFile $arrUser $arrOwner $filePath '

if __name__ == "__main__":
    # get application name
    Usage("AIP-Test")

subprocess.call(cmd)
```

### Expected results

It to work

### Actual results

It does not work.

**Comment by cgchoffman** [comment]
This is broken again:
```
[2018-05-16 16:52:54,737] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js:2922
Traceback (most recent call last):
  File "file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js", line 2922, in 

[2018-05-16 16:52:54,834] [ERROR] console-logger: Error: Error calling method on NPObject! (2) in file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js:2922
Traceback (most recent call last):
  File "file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js", line 2922, in 

[2018-05-16 16:52:58,421] [ERROR] console-logger: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Error calling method on NPObject!" {file: "file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js" line: 2922}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js" line: 2922}]' when calling method: [ISciMoz::getTextRange] (2) in chrome://refactoring/content/refactoring.js:694
Traceback (most recent call last):
  File "chrome://refactoring/content/refactoring.js", line 694, in 

[2018-05-16 16:52:58,546] [ERROR] console-logger: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Error calling method on NPObject!" {file: "file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js" line: 2922}]'[JavaScript Error: "Error calling method on NPObject!" {file: "file:///C:/mozbuilds/IDE-11.11/moz3500-ko11.11/mozilla/ko-rel/dist/bin/components/scimoz_wrapper.js" line: 2922}]' when calling method: [ISciMoz::getTextRange] (2) in null:0
Traceback (most recent call last):
  File "null", line 0, in 

[2018-05-16 16:53:16,328] [WARNING] console-logger: ReferenceError: reference to undefined property this._path (5) in resource://gre/modules/osfile/osfile_win_front.jsm:901
```

**Comment by cgchoffman** [comment]
I finally figured this out.  Refactoring is working for the most part but the sample code I was using breaks refactoring as is.  I'll write that up separately.
