### ISSUE TITLE
Link Views menu item isn't disabling properly

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3542]
### Short Summary

Link two view *View menu > Scrolling > Link Splitviews*
Then unlink them.

```
[2018-05-02 11:09:09,743] [ERROR] commands: An error occurred executing the cmd_unlinkViews command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]'[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]'[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]' when calling method: [nsIController::doCommand]'
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 239
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 239
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync/< :: line 196
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2018-05-02 11:09:09,829] [ERROR] commands: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2018-05-02 11:09:09,927] [ERROR] console-logger: TypeError: null has no properties (2) in vieweditor:140
Traceback (most recent call last):
  File "vieweditor", line 140, in 

[2018-05-02 11:09:13,831] [ERROR] commands: An error occurred executing the cmd_unlinkViews command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]'[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]'[JavaScript Error: "null has no properties" {file: "vieweditor" line: 140}]' when calling method: [nsIController::doCommand]'
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 239
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 239
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 239
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync/< :: line 196
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:239:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
'
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2018-05-02 11:09:13,895] [ERROR] commands: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2018-05-02 11:09:14,188] [ERROR] console-logger: TypeError: null has no properties (2) in vieweditor:140
Traceback (most recent call last):
  File "vieweditor", line 140, in 
```

**Comment by cgchoffman** [comment]
https://github.com/Komodo/KomodoIDE/commit/ed9f8f7c9e44d426021902dffc800cf952d936fa
