### ISSUE TITLE
"Show in Filemanager" fails.

### ISSUE THREAD

**Issue by jellisii** [Komodo/KomodoEdit#3545]
### Short Summary

I am attempting to quickly navigate to a non-code file within a project.  When I right click the file and click "Show in File Manager", an error occurs.

### Steps to Reproduce

RIght click a file, click "Show in File Manager"

### Expected results

A file manager window appears.  My current file manager is Thunar 1.6.12 (XFCE)

### Actual results

AN error happens, putting the following in the notification stack:

```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISysUtils.ShowFileInFileManager]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo-places/content/places.js :: ManagerClass.prototype.doShowInFinder :: line 2378"  data: no]
```

### Platform Information

Komodo IDE, version 11.0.2, build 90813, platform linux-x86_64.
Built on Mon Dec 4 10:20:45 2017.

I'm currently using Xubuntu 17.10.

**Comment by mitchell-as** [comment]
Hi, would you please post the full traceback? Thanks.

**Comment by jellisii** [comment]
```
ERROR:xpcom:Unhandled exception calling 'int8 * ShowFileInFileManager(in wstring);'
Traceback (most recent call last):
  File "/home/jellisii/Komodo-IDE-11/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/home/jellisii/Komodo-IDE-11/lib/mozilla/components/koSysUtils.py", line 242, in ShowFileInFileManager
    raise "NOT IMPLEMENTED"
TypeError: exceptions must be old-style classes or derived from BaseException, not str
[2018-05-14 11:34:03,608] [ERROR] commands: An error occurred executing the cmd_places_showInFinder command
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISysUtils.ShowFileInFileManager]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo-places/content/places.js :: ManagerClass.prototype.doShowInFinder :: line 2378"  data: no]
+ QueryInterface (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISysUtils.ShowFileInFileManager]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo-places/content/places.js'
+ lineNumber (number) 2378
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo-places/content/places.js :: ManagerClass.prototype.doShowInFinder :: line 2378
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo-places/content/places.js'
| + name (string) 'ManagerClass.prototype.doShowInFinder'
| + lineNumber (number) 2378
| + columnNumber (number) 8
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo-places/content/placeController.js :: PlacesController.prototype.do_cmd_places_showInFinder :: line 122
| + formattedStack (string) 'ManagerClass.prototype.doShowInFinder@chrome://komodo-places/content/places.js:2378:8
PlacesControll'...420 chars
| + inner (object) null
| + data (object) null
| -- EXCEPTION END --
[2018-05-14 11:34:03,657] [ERROR] console-logger: uncaught exception: 2147500037 (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

**Comment by mitchell-as** [comment]
Thank you. The trace points to the fact that we do not recognize Thunar as a file manager.

Dev note: koSysUtils.py:232 needs to add a check for Thunar.
