### ISSUE TITLE
Popup window blank content 

### ISSUE THREAD

**Issue by manhg** [Komodo/KomodoEdit#3561]
### Short Summary

Confirm window becomes blank (such as confirmation file save, alerts...)
This only happened after macOS upgraded to High Sierra (10.13)

### Steps to Reproduce
* Open an existing file
* Edit it and close (without hitting save)
* Closing confirm dialog appears, content is not shown.

### Expected results

Normal popup

### Actual results

Content is not showed.
If I change application and come back to Komodo, the content will show up.

### Platform Information

*Komodo Edit
*Komodo Version: 10, 11
*Operating System (and version): macOS High Sierra (10.13)

### Additional Information
Got
![image](https://user-images.githubusercontent.com/6258044/41400273-a7f0827a-6ff7-11e8-8330-7697f5d37a90.png)

![image](https://user-images.githubusercontent.com/6258044/41400080-12075324-6ff7-11e8-9a58-8e28132e5d94.png)

Expected
![image](https://user-images.githubusercontent.com/6258044/41400070-0c019b88-6ff7-11e8-8d90-bf9e31a6f14b.png)

Log file

```[2018-06-14 17:22:05,898] [INFO] Startup: Welcome to Komodo Edit 11.0.2 build 18122 (platform macosx, running on Darwin 17.6.0 version Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64)
[2018-06-14 17:22:05,898] [INFO] Startup: /Applications/Komodo Edit 11.app/Contents/MacOS/komodo built on Mon Dec 4 16:56:01 2017
[2018-06-14 17:22:06,011] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2018-06-14 17:22:06,299] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-06-14 17:22:06,608] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2018-06-14 17:22:06,609] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2018-06-14 17:22:06,647] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2018-06-14 17:22:07,429] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2018-06-14 17:22:08,132] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-06-14 17:22:08,224] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-06-14 17:22:08,708] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2018-06-14 17:22:08,715] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2018-06-14 17:22:09,039] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2018-06-14 17:22:11,921] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-06-14 17:22:11,921] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-06-14 17:22:11,921] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-06-14 17:22:11,921] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-06-14 17:22:11,922] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-06-14 17:22:11,922] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-06-14 17:22:11,923] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-06-14 17:22:11,923] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-06-14 17:22:11,941] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-06-14 17:22:11,943] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-06-14 17:22:35,744] [WARNING] views: Inconsistent view count in view_closed event
[2018-06-14 17:22:35,771] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-06-14 17:22:35,771] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-06-14 17:22:35,771] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-06-14 17:22:35,771] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-06-14 17:22:35,772] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-06-14 17:22:35,772] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-06-14 17:22:35,773] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-06-14 17:22:35,773] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-06-14 17:22:35,923] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:297:17
    initWithDocument@vieweditor:410:13
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:361:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:485:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:510:20
-- EXCEPTION END --
[2018-06-14 17:22:35,931] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:297:17
    initWithDocument@vieweditor:410:13
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:361:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:485:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:510:20
-- EXCEPTION END --
[2018-06-14 17:22:35,936] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    set_koDoc@vieweditor:297:17
    initWithDocument@vieweditor:410:13
    createViewFromDocument@viewlistbase:133:17
    viewManager.prototype._newViewFromURI@chrome://komodo/content/views.js:361:20
    viewManager.prototype._doFileOpen@chrome://komodo/content/views.js:485:12
    viewManager.prototype.doFileOpenAsync/<@chrome://komodo/content/views.js:510:20
-- EXCEPTION END --
[2018-06-14 17:22:36,060] [WARNING] views: Inconsistent view count in view_opened event
[2018-06-14 17:22:37,356] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2018-06-14 17:25:24,505] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-06-14 17:25:24,505] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-06-14 17:25:24,505] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-06-14 17:25:24,506] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-06-14 17:25:24,506] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-06-14 17:25:24,506] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-06-14 17:25:24,506] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-06-14 17:25:24,507] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
```

**Comment by cgchoffman** [comment]
Thanks for the report.  This is fixed and will be released in Komodo 11.1. ref: #3475
