### ISSUE TITLE
go to definition does not work for some Perl variables

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#3562]
### Short Summary

Komodo version is 11.1.  
OS is Windows 10.  

Go to definition only works for a subset of perl variable calls, which seem to be only those using a simple single sigil.  Double sigil and list subscripts do not work.

Several of the issues were previously fixed in komodo 10.1 under issue #1514.  The code below includes all checks from that issue, as well as some additional checks.  

Lines flagged as ```does not work in 11.1``` do work correctly under 10.2.3.

### Steps to Reproduce

```perl
#  checks from #1514
my $hashref = {};
my %y = %$hashref;     #  does not work in 11.1
my %z = %{$hashref};   #  works

my $arrayref = [];
my @a2 = @$arrayref;   #  does not work in 11.1
my @a1 = @{$arrayref}; #  works

my $scalar = '';
my $s1 = $$scalar;     #  does not work in 11.1
my $s2 = ${$scalar};   #  works

my @array;
my $aref1 = \ @array;  #  works
my $aref2 = \@array;   #  works (fixed under #1514)
my $aref3 = [@array];  #  works

my %hash;
my $href1 = \ %hash;   # works
my $href2 = \%hash;    # works (fixed under #1514)
my %href3 = {%hash};   # works

my $sc = '';
my $sref1 = \ $sc;     #  works
my $sref2 = \$sc;      #  works (fixed under #1514)


#  new checks

my %hash1;
my @array1;
my $aref = [];

foreach my $var3 (0..1) {
    print $var3;          #  works
}

push @array1, 5;          #  works
print $array1[0];         #  does not work in 11.1

push @{$aref}, 5;         #  works
print $aref->[0];         #  works
push @$aref, 5;           #  does not work in 11.1

$hash1{a} += 5;           #  does not work in 11.1
$hash{b}++;               #  does not work in 11.1

my @hash_vals = @hash1{qw /a b/};  #  does not work in either 10.2.3 or 11.1

```

### Expected results

See comments in above code block.

### Actual results

See comments in above code block.

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*       11.1
*Operating System (and version)?*   Windows 10

### Additional Information

Error log is below.  The actions taken were to open the script, and then use ```go to definition``` on each variable (on the right hand side of any assignments) for each line marked with ```works``` or ```does not work```,  via the right click menu, starting from the top.

```
[2018-06-22 11:23:00,569] [INFO] Startup: Welcome to Komodo IDE 11.1.0 build 91033 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2018-06-22 11:23:00,569] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\komodo.exe built on Wed May 30 10:04:55 2018
[2018-06-22 11:23:01,523] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-06-22 11:23:01,696] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2018-06-22 11:23:02,586] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2018-06-22 11:23:03,884] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-06-22 11:23:03,930] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2018-06-22 11:23:03,946] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2018-06-22 11:23:04,039] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2018-06-22 11:23:04,884] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-06-22 11:23:05,164] [INFO] komodospellchecker: Spell checker loaded.
[2018-06-22 11:23:05,164] [INFO] komodospellchecker: Using dictionary en-US
[2018-06-22 11:23:05,227] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-06-22 11:23:05,414] [INFO] codeintel/process: Starting CodeIntel
[2018-06-22 11:23:05,414] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2018-06-22 11:23:08,072] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 11:23:08,072] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 11:23:08,088] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 11:23:08,088] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 11:23:08,088] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 11:23:08,088] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 11:23:08,102] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koamAddonManager.js:138
[2018-06-22 11:23:08,447] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-06-22 11:23:08,447] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-06-22 11:23:08,461] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2018-06-22 11:23:08,586] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-22 11:23:08,586] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-22 11:23:08,586] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-22 11:23:09,197] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2018-06-22 11:23:09,650] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2018-06-22 11:23:09,650] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/111
[2018-06-22 11:23:12,259] [DEBUG] codeintel/process: stdout: 
port:60947

pid:1588

[2018-06-22 11:23:12,259] [INFO] codeintel/process: CodeIntel started on port 60947
[2018-06-22 11:23:12,259] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2018-06-22 11:23:12,477] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F111 (404)
[2018-06-22 11:23:17,479] [DEBUG] console: error: {}
[2018-06-22 11:23:20,371] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2018-06-22 11:23:25,073] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:23:25,089] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:23:25,089] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:23:25,559] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:24:50,759] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:24:50,759] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:24:50,776] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 11:25:21,065] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by cgchoffman** [comment]
Thanks for the report.
