### ISSUE TITLE
rename variable with perl list dereferencing and double sigils

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#3563]
### Short Summary

Komodo IDE 11.1

Variable renaming is inconsistent with list subscripts in perl.  A double sigil deref like ```@$aref``` is only renamed if there is a preceding deref that uses parentheses, e.g. ```@{$aref}```.  If the parenthetical form follows the double sigil form then the double sigil form is not renamed.

This is presumably related to #3562 .

### Steps to Reproduce

In each of the examples, call ```rename variable``` on ```$aref``` on the line it is defined.  

```perl
my @newlist;
my $aref = [0..3];
##@newlist = @{$aref};   #  unchanged, but commented out
@newlist = @$aref;       #  unchanged
```

```perl
my @newlist;
my $aref = [0..3];
@newlist = @$aref;       #  unchanged
@newlist = @{$aref};     #  is changed
```

```perl
my @newlist;
my $aref = [0..3];
@newlist = @{$aref};     #  is changed
@newlist = @$aref;       #  is changed

```

### Expected results

$aref should be renamed each time unless in a commented line (one could argue it should be, but that's really a separate issue).

### Actual results

Comments in code blocks indicate the result.  

### Platform Information

*Komodo Edit or IDE?*   IDE
*Komodo Version?*   11.1
*Operating System (and version)?*   Windows 10

### Additional Information

 

Error log is for the first example.  Komodo was started with that file opened.  

```
[2018-06-22 12:29:01,650] [INFO] Startup: Welcome to Komodo IDE 11.1.0 build 91033 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2018-06-22 12:29:01,650] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\komodo.exe built on Wed May 30 10:04:55 2018
[2018-06-22 12:29:02,555] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-06-22 12:29:02,618] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2018-06-22 12:29:03,134] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-06-22 12:29:03,400] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2018-06-22 12:29:04,855] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-06-22 12:29:04,901] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2018-06-22 12:29:04,917] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2018-06-22 12:29:04,996] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2018-06-22 12:29:05,855] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-06-22 12:29:06,198] [INFO] komodospellchecker: Spell checker loaded.
[2018-06-22 12:29:06,198] [INFO] komodospellchecker: Using dictionary en-US
[2018-06-22 12:29:06,276] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-06-22 12:29:06,401] [INFO] codeintel/process: Starting CodeIntel
[2018-06-22 12:29:06,417] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2018-06-22 12:29:10,200] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-06-22 12:29:10,200] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-06-22 12:29:10,216] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2018-06-22 12:29:10,357] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 12:29:10,357] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 12:29:10,357] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 12:29:10,357] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 12:29:10,357] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 12:29:10,371] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-22 12:29:10,904] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-22 12:29:10,904] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-22 12:29:10,904] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-22 12:29:11,092] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2018-06-22 12:29:13,625] [DEBUG] codeintel/process: stdout: 
port:61313

pid:15468

[2018-06-22 12:29:13,625] [INFO] codeintel/process: CodeIntel started on port 61313
[2018-06-22 12:29:13,625] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2018-06-22 12:29:14,171] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2018-06-22 12:29:14,171] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/111
[2018-06-22 12:29:14,562] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koamAddonManager.js:138
[2018-06-22 12:29:14,905] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F111 (404)
[2018-06-22 12:29:19,094] [DEBUG] console: error: {}
[2018-06-22 12:29:21,470] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2018-06-22 12:29:43,365] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:44,115] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:44,349] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:44,349] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:44,349] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:55,789] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:55,805] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:29:55,805] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koISCCDVCS.getValue] (2) in chrome://komodo/content/scc/scc.js:498
Traceback (most recent call last):
  File "chrome://komodo/content/scc/scc.js", line 498, in 

[2018-06-22 12:30:06,667] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0

```

**Comment by cgchoffman** [comment]
Thanks for the report @shawnlaffan
