### ISSUE TITLE
Komodo 11.1 freezing.

### ISSUE THREAD

**Issue by JohnWSteel** [Komodo/KomodoEdit#3566]
### Short Summary
From time to time Komodo will not open, even though the process is visible in Task Manager, some times there is more than one instance of the process. It eventually causes the computer to freeze. Closing the task releases the computer but Komodo will not open until after the PC is re-booted and will then work normally for a time. This never happens when the program is running, only when Komodo is closed and then reopened.
This has only happened since the last update.

### Steps to Reproduce
Close Komodo and then try to reopen

### Expected results
Komodo should open

### Actual results
Komodo does not open, though process visible in Task Manager, if left will eventually cause the PC to freeze until the process is forced closed via Task Manager.

### Platform Information

*Komodo Edit or IDE?*  IDE
*Komodo Version?*  11.1 91033 win 32-x86
*Operating System (and version)?* Windows 10 pro 1803 fully updated

### Additional Information

[2018-06-24 18:34:19,901] [INFO] Startup: Welcome to Komodo IDE 11.1.0 build 91033 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2018-06-24 18:34:19,901] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\komodo.exe built on Wed May 30 10:04:55 2018
[2018-06-24 18:34:20,338] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-06-24 18:34:20,369] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2018-06-24 18:34:20,776] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-06-24 18:34:21,134] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2018-06-24 18:34:21,306] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-06-24 18:34:21,447] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2018-06-24 18:34:21,463] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2018-06-24 18:34:21,572] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2018-06-24 18:34:21,769] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-06-24 18:34:21,878] [INFO] komodospellchecker: Spell checker loaded.
[2018-06-24 18:34:21,878] [INFO] komodospellchecker: Using dictionary en-US
[2018-06-24 18:34:21,910] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-06-24 18:34:21,971] [INFO] codeintel/process: Starting CodeIntel
[2018-06-24 18:34:21,971] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2018-06-24 18:34:23,299] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-24 18:34:23,299] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-24 18:34:23,299] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-24 18:34:23,315] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-24 18:34:23,315] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
[2018-06-24 18:34:23,315] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koLessProtocolHandler.js:154
ERROR:xpcom:Unhandled exception calling 'int8 * matchesUri(in unicode &, out retval boolean);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\publishing@ActiveState.com\components\koPublishingSettings.py", line 272, in matchesUri
    uri = unquote(uri)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\lib\urllib.py", line 1217, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split'
[2018-06-24 18:34:23,519] [ERROR] commands: doing _updateCommand: cmd_publishingOpenDialog: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingSettings.matchesUri]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://publishing/content/publishing.js :: ko_pub_getSettingsForUri :: line 124"  data: no]
+ QueryInterface (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPublishingSettings.matchesUri]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://publishing/content/publishing.js'
+ lineNumber (number) 124
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://publishing/content/publishing.js :: ko_pub_getSettingsForUri :: line 124
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://publishing/content/publishing.js'
| + name (string) 'ko_pub_getSettingsForUri'
| + lineNumber (number) 124
| + columnNumber (number) 16
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://publishing/content/publishing.js :: PublishingController.prototype.is_cmd_publishingOpenDialog_enabled :: line 359
| + formattedStack (string) 'ko_pub_getSettingsForUri@chrome://publishing/content/publishing.js:124:16
PublishingController.proto'...446 chars
| + inner (object) null
| + data (object) null
| -- EXCEPTION END --
[2018-06-24 18:34:23,658] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-24 18:34:23,658] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-24 18:34:23,658] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-06-24 18:34:23,940] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2018-06-24 18:34:24,799] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-06-24 18:34:24,799] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-06-24 18:34:24,799] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2018-06-24 18:34:24,956] [ERROR] console-logger: TypeError: n is undefined (2) in chrome://komodo/content/contrib/commonjs/underscore.js:5
Traceback (most recent call last):
  File "chrome://komodo/content/contrib/commonjs/underscore.js", line 5, in 

[2018-06-24 18:34:25,408] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koamAddonManager.js:138
[2018-06-24 18:34:25,674] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2018-06-24 18:34:25,674] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/111
[2018-06-24 18:34:26,236] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F111 (404)
[2018-06-24 18:34:27,502] [DEBUG] codeintel/process: stdout: 
port:50137

pid:2368

[2018-06-24 18:34:27,502] [INFO] codeintel/process: CodeIntel started on port 50137
[2018-06-24 18:34:27,502] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2018-06-24 18:34:32,701] [DEBUG] console: error: {}

**Comment by mitchell-as** [comment]
Hi, when this happens and you kill Komodo via task manager, is there another python.exe process running? If so, try killing that. (Please be careful in case you have other Python programs running.) Then try running Komodo again. If it starts without needing a reboot, then the external codeintel is causing trouble and we'll go from there.

**Comment by JohnWSteel** [comment]
Thanks for the response, it is behaving at the moment but have not used it much. I don’t know how to identify a Python process in Task Manager, as far as I know I do not have any running.

I don’t know if it helps but when it acts up Komodo does not show as an App in Task Manager, just as a Background Process. When working properly it shows as an App.

**Comment by mitchell-as** [comment]
When you open the task manager and Komodo is running, two related processes should show up: komodo.exe and python.exe. (If there is just one python.exe, you know it is Komodo's external codeintel process). When Komodo starts acting up and you have to kill it, see if that python.exe is still present. If so, codeintel is misbehaving and we'll go from there.

**Comment by JohnWSteel** [comment]
Thanks, I will wait for it to happen again.

As usual with these things it was happening daily, sometimes more than once, up to the point I contacted you, it has not happened since.

**Comment by cdcmicro** [comment]
@JohnWSteel ,

>I don’t know how to identify a Python process in Task Manager, as far as I know I do not have any running.

Have a look at ProcessExplorer  (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).  It'll show you the child processes, and let you selectively kill them.

![screenshot_062618_103311_am](https://user-images.githubusercontent.com/13684992/41929249-540eb648-792c-11e8-8c4d-e881aeb28f43.jpg)

**Comment by JohnWSteel** [comment]
Thanks I was getting confused for a moment. I can see the processes running under the apps, I though it meant to look for any other program running Python.

Thanks for the link to Process Explorer, looks useful.

**Comment by JohnWSteel** [comment]
It has eventually happened again.

 

When trying to open Komodo it does not open, the PC starts to freeze.

 

Task manager does not show  Komodo  running as an App

 

Komodo does however show as a background process, and there will be one process for each time you have tried to run Komodo.

 

There is no sign of any Python.exe running either when Komodo is there as a background process or after it is killed.

 

Killing all the Komodo background processes puts the PC back to normal operation, but as long as they are running the PC frequently freezes making it almost impossible to do anything. It is not possible to start Komodo until after a PC reboot.

 

In case it is relevant at the same time I have CuteFTP, Malwarebytes, MS Outlook 2016, Team Viewer 13 and Windows Explorer running at the same time.

 

Attached is the dump from ProcessExplorer, hopefully that will come through.

 

If I reboot the PC then Komodo will run and now shows as an App with python.exe, console window host and windows command process processor, all 32 bit.

 

I don’t know if this casts any further light on the situation.

 

Thanks

John

**Comment by mitchell-as** [comment]
Okay, so it appears that the last time you quit Komodo, the python.exe (Codeintel) process exited. However, the komodo.exe process persisted. Then when you try and run Komodo again, it will not start.

@Naatan is there any reason you can think of as to why the komodo.exe process would not die on quit, but python.exe (Codeintel) would?

**Comment by Naatan** [comment]
Some other child process would be my only guess.. like a linter? @JohnWSteel could you check with your process manager if the komodo process has any child processes (when you reproduce)?

Also, when you reproduce the issue please send us a copy of your pystderr.log (before restarting Komodo). You can find it in your profile folder: http://docs.activestate.com/komodo/11/manual/trouble.html#appdata_dir

**Comment by JohnWSteel** [comment]
OK I will do so, I have actually just reinstalled Komodo 11.1 and since the reinstall I have had no problems and in fact Komodo seems to open much faster and run better than before. The problem seemed to start after the upgrade to 11.1, maybe something went wrong then.

But I will let you know if it happens again and send as much information as I can.

Thanks for your help.

**Comment by JohnWSteel** [comment]
As this problem has not reappeared since I reinstalled the program and I have extensively used it over the past three weeks I think I can now assume that has cured it.

Thanks for your help

John

**Comment by Naatan** [comment]
Thanks for the follow up!

**Comment by JohnWSteel** [comment]
Sorry to say this problem has returned  and seems to worse than it was previously though it did seem to settle down between July last year and the update to 11.1.1 which I did in December. Just to resume on the problem.

 

From a clean boot Komodo will run OK.

 

I can close and reopen Komodo without problems for a while, but it seems that after some time with either Komodo open or not running, any attempt to run Komodo will fail and if it is already running then it will freeze the computer at intervals, normally the computer will run OK for about 10 seconds and then freeze totally and be unresponsive to the mouse for about 5 seconds, this will continue until Komodo is force closed via Task Manager.

 

Although I can not be 100% sure it seems this issue starts after the PC has been to sleep, I usually notice it first thing in the morning when I try to start Komodo.

 

When this happens Komodo appears in Task Manager as a background process but not as an App, sometimes Python will be running separately as a background process but not all the  time. The attached JPG Komodo First Run after boot shows Task Manager when Komodo is running OK. The JPG Komodo after closing shows Task Manager after Komodo has been closed and after trying to run it again unsuccessfully.

 

I also attach three logs 

Komodo Clean Boot before running is the log before running Komodo, 

Komodo after first run pystderr is the log after Komodo runs successfully and is still running,

Komodo after not responding is the log when Komodo has been run, closed and then fails to start again.

 

I am running Windows 10 Pro 10.0.17134 Build 17134

Komodo IDE, version 11.1.1, build 91089, platform win32-x86. Built on Wed Dec 12 11:57:06 2018.

 

Many thanks

 

John

**Comment by cgchoffman** [comment]
> I also attach three logs

Too attached images and files to a ticket you need to open the ticket in your brower then drag and drop them.  It's not possible to attach files to your email response to the ticket.  Do that @JohnWSteel ?

**Comment by JohnWSteel** [comment]
These are the attachments
![komodo after closing](https://user-images.githubusercontent.com/13707454/53768390-9b3b8680-3ed0-11e9-9305-05bb8a4e3c63.jpg)
[Komodo after first run pystderr.log](https://github.com/Komodo/KomodoEdit/files/2928528/Komodo.after.first.run.pystderr.log)
[Komodo after not responding.log](https://github.com/Komodo/KomodoEdit/files/2928529/Komodo.after.not.responding.log)
[Komodo clean boot before running pystderr.log](https://github.com/Komodo/KomodoEdit/files/2928531/Komodo.clean.boot.before.running.pystderr.log)
![komodo first run after boot](https://user-images.githubusercontent.com/13707454/53768443-bc03dc00-3ed0-11e9-8705-75ed9b01f3ac.jpg)

**Comment by cgchoffman** [comment]
I see a lot of TCP errors that look like Komodo can't reach Code Intel and keeps trying to restart it.  Have you changed anything recently that could block Komodo on a network (namely localhost) level?  Could you also get your code intel logs next time this happens?  Same folder as the other logs, codeintel3.log.

**Comment by JohnWSteel** [comment]
[codeintel3.log](https://github.com/Komodo/KomodoEdit/files/2954357/codeintel3.log)
[pystderr.log](https://github.com/Komodo/KomodoEdit/files/2954360/pystderr.log)

These are the two log files from this morning when Komodo froze and I had to close it down via Task Manager, I have not run Komodo since then.
I have not changed anything recently, the only changes have been the regular updates to various programs.
Thanks

**Comment by cgchoffman** [comment]
Thanks for the codeintel3.log.  That looked very familiar.  I found this ticket that I filed almost a year ago: https://github.com/Komodo/KomodoEdit/issues/3529. They are basically the same symptoms.   Komodo can't close, code intel starts crashing at around 2 am and keeps crashing all through the nice.  I thought we had resolved it with https://github.com/Komodo/KomodoEdit/issues/3536 though.  I haven't seen that issues since.

What language are you working?  Approximately how big is your project?  Are you able to reduce it's size by taking advantage of the applicable languages "exclude" directory preference?

**Comment by JohnWSteel** [comment]
Thanks for the reply, at least it is good to know it is possibly Komodo and not my system.
I use Perl, the project is around 80 files, though I rarely have more than 4 or 5 actually open at any time. Files range from about 2k up to my library file which is 97k most are below 10k though.
Not sure how the 'exclude' would help as all files are in the same directory.
From memory the problem seemed to go away with the update from 11.0 to 11.1 but has come back after the update to 11.1.1 even if it did not completely go away it was vastly reduced between the two updates. I can usually work through the day but after the PC goes to sleep the issues start and I can not run Komodo again properly until after a system reboot.
Many thanks for your help.

**Comment by cgchoffman** [comment]
Thanks for that additional info.  Doesn't sound like your project should be causing Komodo any trouble.  I think we have all the debugging information we need from you @JohnWSteel so I think you should try *Help > troubleshooting > Reset Codeintel Database*.

**Comment by JohnWSteel** [comment]
Thanks

I have reset the database, unfortunately no improvement. I can open Komodo after a reboot and continue to open and close it all day, even after the PC has gone to sleep. But after sleeping overnight it refused to open without rebooting the PC.

Best wishes

John

**Comment by cgchoffman** [comment]
@JohnWSteel, when that happens do you check for the Python process we've mentioned before and is it there? 

What about an entire profile reset?  Here's how you can do that but keep working:
- In CMD run `set KOMODO_USERDATADIR=C:\Some\path\you\will\remember`
- (if Komodo is on your path) type `ko` and press enter

This will start a brand spankin new Komodo instance, totally separate from your working instance.  Open your project in that instance then just let it sit.  You can continue working in the original Komodo instance.  If you don't mind working with default preferences then you could work from the brand new instance as well.  Either way, make sure it runs for a day or two and see if the issue happens again.

**Comment by JohnWSteel** [comment]
Thanks, I did this yesterday and the second instance of Komodo was running OK. I worked on my normal instance all day without problems and left both instances running but minimised overnight. This morning when I tried to maximise the window with my instance running the computer started to freeze, at first for about 10 seconds at a time then 10 seconds working, the working time got shorter and shorter until the computer essentially froze up and I had to turn it off and boot again to get it working. Currently I have just started my usual instance of Komodo and it seems to be working fine. But that is normal, the problem only seems to happen overnight and is does not matter whether Komodo is left open or closed.
I will attach a screen grab of Task Manager which I managed to get whilst the system was still responding a little.
When Komodo will not start there is only Komodo as a Background Process in Task Manager and no Python.

Best wishes
John
![komodo_no_respond](https://user-images.githubusercontent.com/13707454/54475354-35ac9b80-47e8-11e9-929d-effa1bc0df67.jpg)

**Comment by cgchoffman** [comment]
@JohnWSteel, so `End Task` on the hung Komodo process doesn't free up your computer?  You always have to reboot?

**Comment by JohnWSteel** [comment]
If I can get into Task Manager before the computer totally freezes I can close the Komodo process and it will be OK, though Komodo will not run again until after a reboot.

But I only have a short time to get into task manager with the computer freezing at intervals, at first around 10 seconds working and 10 seconds frozen, the frozen periods then start to get longer and the working periods shorter.

**Comment by cgchoffman** [comment]
@JohnWSteel please remember to open the ticket in a browser.  You've posted your email in your last two comments by replying to the ticket from your email client.  

The test with the fresh profile was flawed, my fault.  For it to be a valid test you should ONLY use the Fresh Komodo.  The fact that your computer crashes completely negates the test of the fresh profile.  Can you work from a fresh profile?  If it works fine for an extended period you can start adding things back in from the old profile, specifically, *XRE\extensions*, *schemes*, *tools* and finally prefs.xml (remember to delete prefs.xmlc).

**Comment by JohnWSteel** [comment]
I will try, but probably not until next week as I have a project I must finish. Not sure it will be any better as my install is pretty basic with very few additions or changes. Will let you know.
Thanks

**Comment by cgchoffman** [comment]
@JohnWSteel might also be worth trying it without that malware program running.  Virus detection programs are notorious for breaking legitimate programs.
