### ISSUE TITLE
New File from Template command does not show template list or open new window

### ISSUE THREAD

**Issue by doughemi** [Komodo/KomodoEdit#3576]
### Short Summary
New--> File from Template menu item does not show template list.

### Steps to Reproduce
Select File-->New-->File from Template from menu bar

### Expected results
List of templates shown from which to select template

### Actual results
Window flashes near Go to Anything field in top right corner, immediately replaced by another window with menu Go Tools Template. No new file window opens

### Platform Information

*Komodo Edit or IDE?* Komodo Edit 11.1.0
*Komodo Version?* 
*Operating System (and version)?* Mac OS X 10.12.6

### Additional Information
Error Log:
[2018-07-17 00:53:14,186] [INFO] Startup: Welcome to Komodo Edit 11.1.0 build 18196 (platform macosx, running on Darwin 16.7.0 version Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64)
[2018-07-17 00:53:14,186] [INFO] Startup: /Applications/Komodo Edit 11.app/Contents/MacOS/komodo built on Wed May 23 00:03:29 2018
[2018-07-17 00:53:14,323] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2018-07-17 00:53:14,725] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-07-17 00:53:14,760] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2018-07-17 00:53:15,152] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-07-17 00:53:15,565] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-07-17 00:53:15,990] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-07-17 00:53:16,103] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-07-17 00:53:16,598] [ERROR] koToolbox2Components: Error initializing toolboxes
Traceback (most recent call last):
  File "/Applications/Komodo Edit 11.app/Contents/Resources/components/koToolbox2Components.py", line 174, in initialize
    self.loadMainToolboxes()
  File "/Applications/Komodo Edit 11.app/Contents/Resources/components/koToolbox2Components.py", line 192, in loadMainToolboxes
    toolbox_id = self.toolboxLoader.loadToolboxDirectory("", stdToolboxDir, koToolbox2.DEFAULT_TARGET_DIRECTORY)
  File "/Applications/Komodo Edit 11.app/Contents/Resources/python/komodo/koToolbox2.py", line 1944, in loadToolboxDirectory
    os.path.walk(actualToolboxDir, self.walkFunc, False)
  File "/Applications/Komodo Edit 11.app/Contents/MacOS/../Frameworks/Python.framework/Versions/Current/lib/python2.7/posixpath.py", line 246, in walk
    walk(name, func, arg)
  File "/Applications/Komodo Edit 11.app/Contents/MacOS/../Frameworks/Python.framework/Versions/Current/lib/python2.7/posixpath.py", line 238, in walk
    func(arg, top, names)
  File "/Applications/Komodo Edit 11.app/Contents/Resources/python/komodo/koToolbox2.py", line 1880, in walkFunc
    existing_child_paths)
  File "/Applications/Komodo Edit 11.app/Contents/Resources/python/komodo/koToolbox2.py", line 1842, in _testAndAddItem
    new_id = self.db.addTool(data, data['type'], path, fname, parent_id)
KeyError: 'type'
ERROR:xpcom:Unhandled exception calling 'int8 * getStandardToolboxID(out retval int32);'
TypeError: int() argument must be a string or a number, not 'NoneType'
ERROR:xpcom:Unhandled exception calling 'int8 * initialize(in nsISomething);'
Traceback (most recent call last):
  File "/Applications/Komodo Edit 11.app/Contents/Resources/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/Applications/Komodo Edit 11.app/Contents/Resources/components/koToolbox2HTreeView.py", line 261, in initialize
    self._std_toolbox_id = self.toolbox2Svc.getStandardToolboxID()
  File "<XPCOMObject method 'getStandardToolboxID'>", line 3, in getStandardToolboxID
Exception: 2147500037 (NS_ERROR_FAILURE)
[2018-07-17 00:53:16,759] [ERROR] ko.widgets: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2HTreeView.initialize]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: Toolbox2Manager.prototype.initialize :: line 104"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2HTreeView.initialize]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/toolbox/toolbox2.js'
+ lineNumber (number) 104
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'Toolbox2Manager.prototype.initialize@chrome://komodo/content/toolbox/toolbox2.js:104:4
this.onload@c'...367 chars
+ location (object) JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: Toolbox2Manager.prototype.initialize :: line 104
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/toolbox/toolbox2.js'
| + name (string) 'Toolbox2Manager.prototype.initialize'
| + lineNumber (number) 104
| + columnNumber (number) 4
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: this.onload :: line 274
| + formattedStack (string) 'Toolbox2Manager.prototype.initialize@chrome://komodo/content/toolbox/toolbox2.js:104:4
this.onload@c'...367 chars
| + stack
    Toolbox2Manager.prototype.initialize@chrome://komodo/content/toolbox/toolbox2.js:104:4
    this.onload@chrome://komodo/content/toolbox/toolbox2.js:274:4
    window.onload/<@chrome://komodo/content/komodo.js:566:45
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:234:16
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2457:14
-- EXCEPTION END --
[2018-07-17 00:53:16,763] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2018-07-17 00:53:16,765] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2018-07-17 00:53:18,728] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'multiple_caret_area'
[2018-07-17 00:53:18,755] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/crypto-SDR.js", line 165, in 

[2018-07-17 00:53:18,758] [ERROR] console-logger: NS_ERROR_FAILURE: Couldn't decrypt string (2) in file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/crypto-SDR.js:165
Traceback (most recent call last):
  File "file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/crypto-SDR.js", line 165, in 

[2018-07-17 00:53:18,813] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-07-17 00:53:18,873] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-07-17 00:53:19,328] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2018-07-17 00:53:29,659] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'multiple_caret_area'

**Comment by Naatan** [comment]
> replaced by another window with menu Go Tools Template

I'm not sure what this means, could you share a screenshot?

**Comment by Naatan** [comment]
It would appear you do not have any templates. Normally Komodo automatically seeds some sample templates when you first install it, did you upgrade from an older version perhaps? Maybe something went wrong there.

Note you can find your templates in your toolbox.

**Comment by doughemi** [comment]
It appears you are right about no templates.  I attempted to create a new template using the File->Save as Other->Template... menu and got the following message:

> [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIToolbox2Service.getStandardToolbox]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: this.getStandardToolbox :: line 512"  data: no]
>                                          Tue Jul 24 2018 12:56:44 GMT-0400 (EDT)
I did update to Komodo 11 by downloading the installer, but did not delete older versions first. Can I perform a "clean" install by deleting the application and the ~Application Support/Komodo folder and then installing the current version?

**Comment by doughemi** [comment]
I answered my own question by trying it! Operation appears normal now.
