### ISSUE TITLE
Remote location open in Places breaks Commando

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3586]
### Short Summary

I'm not sure what's going on here, hopepfully fixing #3565 will resolve this as well but when i try to use Commando while I have a remote folder open in places I get a ton of errors in my logs and couldn't find a file that I knew was there.  Not sure why it gets the same error as #3565 but i guess i'll find out.

```
ERROR:xpcom:Unhandled exception calling 'int8 * newURI(in utf8string &, in string, in nsISomething, out retval nsISomething);'
Traceback (most recent call last):
  File "C:\Users\cgcho\Komodo IDE 11.1\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\cgcho\Komodo IDE 11.1\lib\mozilla\components\koSFTP.py", line 47, in newURI
    self.defaultPort, aSpec, aOriginCharset, aBaseURI)
  File "<XPCOMObject method 'init'>", line 3, in init
Exception: 2152398858 (NS_NET_STATUS_WAITING_FOR)
[2018-07-30 11:24:25,845] [ERROR] console-logger: Error: invalid URI: sftp://Stackato - 10.19.0.148/home/stackato/drupal (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js:37
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/url.js", line 37, in 
```

**Comment by cgchoffman** [comment]
The fix for #3565  has no effect on this issue.  :(

**Comment by Naatan** [comment]
This is missing repro steps, labels and a milestone.

**Comment by cgchoffman** [comment]
Repro is in the desc.
