### ISSUE TITLE
Ruby debugging on Mac broken 11.1

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#3600]
### Short Summary

Debugging Ruby 2.3 appears to be broken on OSX (perhaps other platforms)

ref: https://community.komodoide.com/t/ruby-debugging-with-komodo-ide-11-1-for-mac/4380

### Steps to Reproduce

Debug a file with Ruby 2.3 

### Additional Information

Error:
```
wrong number of arguments (given 2, expected 1)
/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:562:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/byebug-10.0.2/lib/byebug/context.rb:145:in `new'
/Library/Ruby/Gems/2.3.0/gems/byebug-10.0.2/lib/byebug/context.rb:145:in `processor'
/Library/Ruby/Gems/2.3.0/gems/byebug-10.0.2/lib/byebug/context.rb:98:in `at_line'
/Users/pemcg/git/cfme-log-parsing/ems_refresh_timings.rb:1:in `<top (required)>'
/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:423:in `debug_load'
/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:423:in `start'
/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/rubylib/rdbgp2.rb:1836:in `<main>'
```

**Comment by cgchoffman** [comment]
So Byebug 10 broke the debugger which means the fix is easy.  Use Byebug 9.1!

```
$ gem uninstall byebug
$ gem install byebug -v 9.1.0
```

Until we have more time to dig into why/how Byebug's interface changed and how it broke Komodo, the above will be the workaround.
