### ISSUE TITLE
Error building mozilla 

### ISSUE THREAD

**Issue by zafarqos** [Komodo/KomodoEdit#361]
Following the instructions to assemble Komo Edit, ran into following building error:

Command: 
~/KomodoEdit/mozilla$ python build.py distclean all

Output (Last Part):
'
'
1069056K ........ ........ ........ ........ ........ ........ 99%  894K 3s
1072128K ........ ........ ........                           100%  890K=31m11s

2015-06-21 04:28:10 (574 KB/s) - ‘/home/mininet/KomodoEdit/mozilla/mozilla-release.hg’ saved [1099471620/1099471620]

running 'hg init /home/mininet/KomodoEdit/mozilla/build/moz3500-ko9.10/mozilla'
sh: 1: hg: not found
Traceback (most recent call last):
  File "build.py", line 2959, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2955, in main
    return build(args)
  File "build.py", line 2779, in build
    newArgv = targetFunc(argv)
  File "build.py", line 2460, in target_all
    target_src()
  File "build.py", line 2111, in target_src
    _run("hg init %s" % (hgRepo,), log.info)
  File "build.py", line 231, in _run
    raise OSError("error running '%s': %r" % (cmd, status))
OSError: error running 'hg init /home/mininet/KomodoEdit/mozilla/build/moz3500-ko9.10/mozilla': 127

**Comment by Naatan** [comment]
You need to install Mercurial, will update the readme .. but basically you'll want to follow the mozilla dependencies guide.
