### ISSUE TITLE
EsLint fails to parse output

### ISSUE THREAD

**Issue by rm-bergmann** [Komodo/KomodoEdit#3610]
### Short Summary
Eslint is not parsing any output on lint checking. 

### Expected results
Expecting to see eslint error and warning messages similar to the JSHint messages. (Also a nice to have will be an automatic 1 click fix, like webstorm has.)

### Actual results
Every time the lint checker is triggered, this warning message is logged in the Komodo log:

[2018-09-26 15:34:06,069] [WARNING] koEsLintLinter: Failed to parse the eslint output!
[2018-09-26 15:34:06,069] [WARNING] koEsLintLinter: The output was: 

### Platform Information
Komodo IDE 11.1.0
Windows 10 latest

### Additional Information

![eslint-config](https://user-images.githubusercontent.com/7300540/46137490-a8798880-c241-11e8-8ac0-598cfb596bb0.png)

[komodo-log.txt](https://github.com/Komodo/KomodoEdit/files/2423483/komodo-log.txt)

**Comment by rm-bergmann** [comment]
More info about this problem:

The error log I linked to above is what I get on my work set up. I have just tried this on my home set up and I get different erros in the log. I may know why they are different but I will have to check some config tomorrow. 

Here's the new errors I get at my home set up:

[Note: I replaced the actual file path with <PATH-TO-FILE>]

[2018-11-01 21:54:34,934] [ERROR] process: process.py: can't execute None (C:\Users\info\node_modules\.bin\eslint --no-color --format json --config C:\www\sites\<PROJECT>\.eslintrc.js --stdin --stdin-filename C:\www\<PATH-TO-FILE>\file.js)

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_  return 0, func(*params)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\components.py", line 237, in run  self.result = self.fn(*self.args, **self.kwargs)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\komodo\process.py", line 328, in __init__ creationflags=flags)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\lib\subprocess.py", line 711, in __init__
errread, errwrite)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\komodo\process.py", line 146, in _execute_child  startupinfo)

WindowsError: [Error 193] %1 is not a valid Win32 application

[2018-11-01 21:54:34,969] [ERROR] koLintService: lint_with_text exception
Traceback (most recent call last):
 
File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\components\koLintService.py", line 172, in lint_with_text  newLintResults = UnwrapObject(linter).lint_with_text(request, text)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\components\koESLintLinter.py", line 105, in lint_with_text
    p = process.ProcessOpen(cmd, cwd=cwd, env=env, stdin=process.PIPE)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\components.py", line 263, in wrapperFn  threadMgr.mainThread.dispatch(method, dispatch_flags)

File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)
[2018-11-01 21:54:45,836] [ERROR] process: process.py: can't execute None 

(C:\Users\info\node_modules\.bin\eslint --no-color --format json --config C:\www\sites\<PATH-TO-FILE>\.eslintrc.js --stdin --stdin-filename C:\www\sites\<PATH-TO-FILE>\file.js)
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\server\policy.py", line 303, in _CallMethod_   return 0, func(*params)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\components.py", line 237, in run  self.result = self.fn(*self.args, **self.kwargs)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\komodo\process.py", line 328, in __init__   creationflags=flags)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\lib\subprocess.py", line 711, in __init__
    errread, errwrite)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\komodo\process.py", line 146, in _execute_child   startupinfo)

WindowsError: [Error 193] %1 is not a valid Win32 application
[2018-11-01 21:54:45,872] [ERROR] koLintService: lint_with_text exception

Traceback (most recent call last):
File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\components\koLintService.py", line 172, in lint_with_text  newLintResults = UnwrapObject(linter).lint_with_text(request, text)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\components\koESLintLinter.py", line 105, in lint_with_text   p = process.ProcessOpen(cmd, cwd=cwd, env=env, stdin=process.PIPE)

File "C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\python\xpcom\components.py", line 263, in wrapperFn  threadMgr.mainThread.dispatch(method, dispatch_flags)

File "<XPCOMObject method 'dispatch'>", line 3, in dispatch 
Exception: 2147500037 (NS_ERROR_FAILURE)

[2018-11-01 21:55:59,489] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
