### ISSUE TITLE
"New File from Template" not working on Mac #3387

### ISSUE THREAD

**Issue by caolandix** [Komodo/KomodoEdit#3617]
### Short Summary
The same problem as bug #3387

### Steps to Reproduce
I click File -> New From Template

### Expected results
Choices appear

### Actual results
no choices appear

### Platform Information
*Komodo IDE* 
*Komodo Version?* 11.1 The newest. I purchased a license 10 days ago.
*Operating System (and version)?* MacOS 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64

### Additional Information
I restarted in Safe Mode and the templates now show up. if I start again the templates disappear

 [2018-10-23 09:57:14,647] [INFO] Startup: Welcome to Komodo IDE 11.1.0 build 91033 (platform macosx, running on Darwin 16.7.0 version Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64)
[2018-10-23 09:57:14,647] [INFO] Startup: /Applications/Komodo IDE 11.app/Contents/MacOS/komodo built on Wed May 30 10:04:57 2018
[2018-10-23 09:57:14,830] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2018-10-23 09:57:15,627] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-10-23 09:57:15,717] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2018-10-23 09:57:16,285] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-10-23 09:57:16,456] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2018-10-23 09:57:16,763] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-10-23 09:57:16,812] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2018-10-23 09:57:16,816] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2018-10-23 09:57:16,974] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2018-10-23 09:57:17,081] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-10-23 09:57:17,329] [INFO] codeintel/process: Starting CodeIntel
[2018-10-23 09:57:17,331] [DEBUG] codeintel/process: PYTHONPATH: /Applications/Komodo IDE 11.app/Contents/MacOS/../lib/python2.7;/Applications/Komodo IDE 11.app/Contents/SharedSupport/dbgp/pythonlib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/lib;/Applications/Komodo IDE 11.app/Contents/Resources/extensions/codeintel@activestate.com/content/../pylib/codeintel/env/Lib/site-packages
[2018-10-23 09:57:17,388] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-10-23 09:57:17,421] [INFO] komodospellchecker: Spell checker loaded.
[2018-10-23 09:57:17,421] [INFO] komodospellchecker: Using dictionary en-US
[2018-10-23 09:57:18,444] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2018-10-23 09:57:18,445] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2018-10-23 09:57:19,015] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,015] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,016] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,021] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,021] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:19,021] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koLessProtocolHandler.js:154
[2018-10-23 09:57:20,344] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-10-23 09:57:20,382] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-10-23 09:57:20,386] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2018-10-23 09:57:20,444] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-23 09:57:20,445] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-23 09:57:20,445] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-23 09:57:20,535] [ERROR] console-logger: TypeError: n is undefined (2) in chrome://komodo/content/contrib/commonjs/underscore.js:5
Traceback (most recent call last):
  File "chrome://komodo/content/contrib/commonjs/underscore.js", line 5, in 

[2018-10-23 09:57:21,370] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2018-10-23 09:57:21,371] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/111
[2018-10-23 09:57:21,897] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F111 (404)
[2018-10-23 09:57:21,898] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2018-10-23 09:57:22,982] [DEBUG] codeintel/process: stdout: 
port:63950

pid:16920

[2018-10-23 09:57:22,982] [INFO] codeintel/process: CodeIntel started on port 63950
[2018-10-23 09:57:22,983] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1

**Comment by Naatan** [comment]
Please respond to the bug, don't create a new one.
