### ISSUE TITLE
Error Exception

### ISSUE THREAD

**Issue by mshrage-snt-net** [Komodo/KomodoEdit#3618]
### Short Summary
Javascript exception on attempt to connect to remote server.
### Steps to Reproduce
Open remote file, select my remote server, get the exception seen below.
### Expected results
Connection established and home directory shown.
### Actual results
Error: '[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]'
### Platform Information
*Komodo IDE 
*Komodo Version 11.1 
*Operating System (and version) Windows 10
### Additional Information

[2018-10-25 09:15:47,549] [INFO] Startup: Welcome to Komodo IDE 11.1.0 build 91033 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2018-10-25 09:15:47,549] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\komodo.exe built on Wed May 30 10:04:55 2018
[2018-10-25 09:15:48,926] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-10-25 09:15:48,930] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/jim/AppData/Local/ActiveState/KomodoIDE/11.1/XRE/extensions/inspector@mozilla.org/chrome.manifest:31
[2018-10-25 09:15:49,334] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2018-10-25 09:15:50,250] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2018-10-25 09:15:50,323] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-10-25 09:15:50,466] [WARNING] ko.widgets: Could not restore widget unittest-widget
[2018-10-25 09:15:50,474] [WARNING] ko.widgets: Could not restore widget symbolbrowser-widget
[2018-10-25 09:15:50,688] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/11
[2018-10-25 09:15:51,013] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-10-25 09:15:51,361] [INFO] komodospellchecker: Spell checker loaded.
[2018-10-25 09:15:51,362] [INFO] komodospellchecker: Using dictionary en-US
[2018-10-25 09:15:51,434] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-10-25 09:15:51,688] [INFO] codeintel/process: Starting CodeIntel
[2018-10-25 09:15:51,691] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2018-10-25 09:15:52,720] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011/lib/mozilla/components/koamAddonManager.js:138
[2018-10-25 09:15:53,417] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-25 09:15:53,417] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-25 09:15:53,417] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-25 09:15:53,720] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-25 09:15:53,720] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-25 09:15:53,720] [WARNING] console-logger: XUL box for tab element contained an inline #text child, forcing all its children to be wrapped in a block. (1) in chrome://unittest/content/views/panel.xul:0
[2018-10-25 09:15:54,198] [ERROR] console-logger: TypeError: n is undefined (2) in chrome://komodo/content/contrib/commonjs/underscore.js:5
Traceback (most recent call last):
  File "chrome://komodo/content/contrib/commonjs/underscore.js", line 5, in 

[2018-10-25 09:15:54,526] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F11 (404)
[2018-10-25 09:15:54,526] [DEBUG] ko.launch: versioncheck on http://docs.komodoide.com/changelog/111
[2018-10-25 09:15:54,786] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-10-25 09:15:54,792] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-10-25 09:15:54,839] [INFO] koInitService: Adding pre startup service for 'koDBGPManager': '@activestate.com/koDBGPManager;1'
[2018-10-25 09:15:55,581] [DEBUG] ko.launch: Response: http://docs.komodoide.com/__omnigollum__/auth/github?origin=%2Fcreate%2Fchangelog%2F111 (404)
[2018-10-25 09:15:58,489] [DEBUG] codeintel/process: stdout: 
port:58854

pid:3852

[2018-10-25 09:15:58,490] [INFO] codeintel/process: CodeIntel started on port 58854
[2018-10-25 09:15:58,490] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2018-10-25 09:16:03,733] [DEBUG] console: error: {}
[2018-10-25 09:18:36,450] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:20:36,984] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:22:42,529] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:22:55,148] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:23:01,648] [ERROR] console-logger: TypeError: sfile is null (2) in chrome://komodo/content/dialogs/filebrowser/filebrowser.js:826
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowser.js", line 826, in 

[2018-10-25 09:23:06,457] [ERROR] console-logger: TypeError: sfile is null (2) in chrome://komodo/content/dialogs/filebrowser/filebrowser.js:826
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowser.js", line 826, in 

[2018-10-25 09:23:25,760] [ERROR] console-logger: TypeError: sfile is null (2) in chrome://komodo/content/dialogs/filebrowser/filebrowser.js:826
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowser.js", line 826, in 

[2018-10-25 09:23:31,487] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:27:13,368] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:30:31,312] [ERROR] filepicker.remote: 
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [koIRemoteConnectionService.getConnection2]'
+ result (number) 2147500033
+ name (string) 'NS_ERROR_NOT_IMPLEMENTED'
+ filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
+ lineNumber (number) 1559
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
+ location (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: connectToServer :: line 1559
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/dialogs/filebrowser/filebrowser.js'
| + name (string) 'connectToServer'
| + lineNumber (number) 1559
| + columnNumber (number) 21
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/dialogs/filebrowser/filebrowser.js :: onServerChanged :: line 1599
| + formattedStack (string) 'connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
onServerChanged@c'...920 chars
| + stack
    connectToServer@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1559:21
    onServerChanged@chrome://komodo/content/dialogs/filebrowser/filebrowser.js:1599:8
    oncommand@chrome://komodo/content/dialogs/filebrowser/filebrowser.xul:1:0
    injectOpenHandler/tw.openDialog@chrome://komodo/content/global.js:120:21
    openDialogWrap@chrome://komodo/content/komodo.js:641:18
    ko.windowManager.openDialog@chrome://komodo/content/library/windowManager.js:95:18
    filepicker_remoteFileBrowser@chrome://komodo/content/library/filepickers.js:913:18
    filepicker_openRemoteFiles@chrome://komodo/content/library/filepickers.js:938:22
    @chrome://komodo/content/library/controller.js line 111 > eval:1:0
    broadcasterController.prototype.doCommand@chrome://komodo/content/library/controller.js:111:0
    command_doCommand@chrome://komodo/content/library/commands.js:239:0
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:196:12
-- EXCEPTION END --
[2018-10-25 09:34:24,492] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by Naatan** [comment]
What type of server are you connecting to? Could you share some specifics?

**Comment by mshrage-snt-net** [comment]
Our website is hosted on a  bluehost.com shared server.  They do not provide a way to install Xdebug.  I think I tried to do it once but could not.  My best guess is that they are using customized software running on Red Hat Linux.

**Comment by Naatan** [comment]
Ok, but are you using FTP, FTPS, .. ? Any info on what server version?

**Comment by mshrage-snt-net** [comment]
I am trying to debug wordpress PHP scripts from Komodo IDE – not sure why you are asking about FTP or FTPS.  
uname -r returns:   3.10.0-693.11.6.1.ELK.el6.x86_64

**Comment by Naatan** [comment]
Your ticket description and error log imply you are using the Remote Server File Browser, which has nothing to do with debugging PHP scripts.

If you are using a host that does not allow you to install xdebug then all of this is a moot point though, xdebug is required to debug PHP.
