### ISSUE TITLE
Komodo IDE codeintel breaks on multiline f-strings

### ISSUE THREAD

**Issue by devdave** [Komodo/KomodoEdit#3627]
### Short Summary

lexical rules https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

`f""" some string """` works

<pre>
f"""
some string 
"""
</pre>

Does not work

### Steps to Reproduce

Paste 
<pre>
f"""
some string 
"""
</pre>
Inside of a version compatible Python +3.6 file

### Expected results

Atleast the codeintel parser should just ignore the entire text block as, in my opinion, things have gone horribly wrong if someone is declaring methods/functions or local variables inside of a f-string.

### Actual results

The codeintel widget is blank with "No symbols found" message.

### Platform Information

Komodo IDE 11 (Nightly from Nov. 8th 2018)
Windows 10
Python 3.7 

### Additional Information

I found this by removing half the file's contents, waiting for codeintel, and if it broke returning the offending code and dividing it half until I got to the offending block of code. 

Initially I thought it was the same `async` problem that took dbgp down and while I did find jsonrpc.py inside of code intel had the reserved word used with `registerMethod` but in post-change testing it didn't fix anything.

I am using these to manufacture multiline SQL products so it is a lot easier/readable to have everything in one string.

In pystderr.og the error that repeated when I added the offending line was 

<pre>
[2018-11-15 08:30:06,223] [ERROR] socket-tcp: Error occurred: error : NetworkError
Traceback from ERROR in 'socket-tcp' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:411:27
    connection/onError@chrome://komodo/content/sdk/socket/tcp.js:101:17
    ts_callListener@file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/TCPSocket.js:340:5
    TCPSocket.prototype._maybeReportErrorAndCloseIfOpen@file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/TCPSocket.js:828:7
    ts_onStopRequest@file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%2011%20nightly/lib/mozilla/components/TCPSocket.js:885:5

[2018-11-15 08:30:06,276] [INFO] codeintel/process: onClose called, code: 9
[2018-11-15 08:30:06,278] [INFO] codeintel/process: Process stopped without a request to stop it, restarting ..
[2018-11-15 08:30:06,278] [INFO] codeintel/process: Restarting CodeIntel
[2018-11-15 08:30:06,278] [INFO] codeintel/process: Starting CodeIntel
[2018-11-15 08:30:06,282] [DEBUG] codeintel/process: PYTHONPATH: C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\python\..\lib\python2.7;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\support\dbgp\pythonlib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\lib;C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\extensions\codeintel@activestate.com\content\..\pylib\codeintel\env\Lib\site-packages
[2018-11-15 08:30:14,017] [DEBUG] codeintel/process: stdout: 
port:50004

pid:17660

[2018-11-15 08:30:14,017] [INFO] codeintel/process: CodeIntel started on port 50004
[2018-11-15 08:30:14,017] [DEBUG] codeintel/process: Calling callbacks for: started, number: 1
[2018-11-15 10:20:40,473] [ERROR] console-logger: TypeError: n is undefined (2) in chrome://komodo/content/contrib/commonjs/underscore.js:5
Traceback (most recent call last):
  File "chrome://komodo/content/contrib/commonjs/underscore.js", line 5, in 

[2018-11-15 10:20:45,959] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
*Submitter note: line is repeated over 10 times*
[2018-11-15 10:20:50,858] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:366
[2018-11-15 10:33:28,204] [ERROR] koPythonLinter: Error running pyflakes on file u'C:\\Users\\dward\\Desktop\\projects\\json_catch\\tests\\test_dblib.py'
c:\users\dward\appdata\local\temp\#atmbls.py:177:12: unexpected character after line continuation character
    "\n" \ 
           ^

[2018-11-15 10:33:28,237] [ERROR] koLintService: lint_with_text exception
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koLintService.py", line 172, in lint_with_text
    newLintResults = UnwrapObject(linter).lint_with_text(request, text)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 11 nightly\lib\mozilla\components\koPythonLinter.py", line 463, in lint_with_text
    m.group(1), m.group(2), m.group(3))
AttributeError: 'NoneType' object has no attribute 'group'
[2018-11-15 10:33:32,269] [WARNING] console-logger: Empty string passed to getElementById(). (1) in chrome://global/content/bindings/richlistbox.xml:361
</pre>

**Comment by devdave** [comment]
Some quick additional facts:

That <pre>
f"""
blah
"""
</pre>

code breaks on my mobile work laptop using Windows+WSL and on my other work laptop which is running a recent flavor of Debian linux. 

The super odd thing, to me, is that single line f"blah" strings don't affect codeintel.
