### ISSUE TITLE
Can not create remote SCP files

### ISSUE THREAD

**Issue by omers** [Komodo/KomodoEdit#3631]
### Short Summary

Can not create remote SCP files

### Steps to Reproduce
Right click and new file

### Expected results
New file should be created

### Actual results
Nothing

### Platform Information

Still happens to me.
Komodo Edit, version 11.1.0, build 18196, platform win32-x86. Built on Wed May 23 00:44:25 2018.

### Additional Information

[2018-11-26 13:54:58,628] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2018-11-26 13:55:01,996] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2018-11-26 13:55:31,365] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2018-11-26 13:55:33,562] [ERROR] console-logger: ReferenceError: view is not defined (2) in chrome://openfiles/content/openfiles.js:585
Traceback (most recent call last):
  File "chrome://openfiles/content/openfiles.js", line 585, in 

[2018-11-26 13:55:34,927] [ERROR] console-logger: Error: 'scp://PC/home/harbana/Repos/Tests' does not have a local path (2) in chrome://komodo/content/library/uriparse.js:201
Traceback (most recent call last):
  File "chrome://komodo/content/library/uriparse.js", line 201, in 

[2018-11-26 13:55:42,700] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'

**Comment by omers** [comment]
Installed 'nightly' 11.1.1 version which solved my issue
