### ISSUE TITLE
Dropdown Lists Stop Working

### ISSUE THREAD

**Issue by ssigwart** [Komodo/KomodoEdit#3639]
### Short Summary
Dropdown components stop working after a few uses.
- The directory breadcrumbs stop expanding.
- The "List all Tabs" button stops working.
- The find history stops showing (though I can still use the up and down keys to go through them).

### Steps to Reproduce
It seems sporadic, but as of today, it seems like I only get a handful of uses of the components before they stop working.

### Expected results
The components continue working.

### Actual results
The components don't show their dropdown list.

### Platform Information
Komodo Edit 11.1.0 (also tried nightly 1.11.1)
macOS Mojave

### Additional Information

I already tried restarting in safe mode, but it didn't help.  The program is also very laggy and often has high CPU usage.  However, I've had this problem for the past few major versions of Komodo Edit, so I'm not sure if that's related to the problem or not.

The `.git` folder is not really empty:
![image](https://user-images.githubusercontent.com/1426848/49545493-d4516400-f8ab-11e8-917c-9ff7dfbb459e.png)

Clicking the arrow next to the "T" stops showing anything.
![image](https://user-images.githubusercontent.com/1426848/49545906-fdbebf80-f8ac-11e8-8807-3273b21d306e.png)
- On an unrelated note, is that always supposed to reset to case sensitive when you restart Komodo Edit?

**Comment by Naatan** [comment]
Please share your error log after reproducing the issue.

You can find your error log at Help > Troubleshooting > View Log File.

**Comment by ssigwart** [comment]
Here it is:
```
[2018-12-10 12:13:51,162] [INFO] Startup: Welcome to Komodo Edit 11.1.0 build 18196 (platform macosx, running on Darwin 18.2.0 version Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64)
[2018-12-10 12:13:51,162] [INFO] Startup: /Applications/Komodo Edit 11.app/Contents/MacOS/komodo built on Wed May 23 00:03:29 2018
[2018-12-10 12:13:51,234] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2018-12-10 12:13:51,431] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2018-12-10 12:13:51,463] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2018-12-10 12:13:51,725] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2018-12-10 12:13:51,787] [WARNING] keybindings: [Shift+Down] was used for 'cmd_selectLineNext', overriding to use 'cmd_selectLineNext'
[2018-12-10 12:13:52,011] [WARNING] ko.widgets: Pref path doesn't exist: windowWorkspace, 1
[2018-12-10 12:13:52,138] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
[2018-12-10 12:13:52,179] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2018-12-10 12:13:52,446] [ERROR] console-logger: Exception while registering Focus Mode (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:11
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 11, in 

[2018-12-10 12:13:52,447] [ERROR] console-logger: [object Object] (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/extensions/focusmode@activestate.com/bootstrap.js", line 12, in 

[2018-12-10 12:13:53,101] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-12-10 12:13:53,102] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-12-10 12:13:53,102] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-12-10 12:13:53,102] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-12-10 12:13:53,102] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-12-10 12:13:53,102] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-12-10 12:13:53,102] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-12-10 12:13:53,103] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2018-12-10 12:13:53,357] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20Edit%2011.app/Contents/Resources/components/koamAddonManager.js:138
[2018-12-10 12:13:54,721] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2018-12-10 12:13:54,731] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2018-12-10 12:14:12,350] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2018-12-10 12:14:12,350] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2018-12-10 12:14:12,350] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2018-12-10 12:14:12,350] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2018-12-10 12:14:12,351] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2018-12-10 12:14:12,351] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2018-12-10 12:14:12,351] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2018-12-10 12:14:12,351] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
```

**Comment by Naatan** [comment]
Are you certain this is a log that was produced once the issue was reproduced (not before) ?

**Comment by ssigwart** [comment]
Yes.  I was able to reproduce it by starting up Komodo Edit, then clicking the "List All Tabs" button twice.  The second time, it didn't work.

Are all the other warnings and errors in this log expected?

**Comment by VAF77** [comment]
I have the same problem, OS X Mojave 10.14.1 (18B75)

**Comment by Naatan** [comment]
Interesting. I'm on Mojave and have not seen this. Try disabling GPU acceleration?

http://docs.activestate.com/komodo/11/manual/trouble.html#artifacts

**Comment by ssigwart** [comment]
Closing since #3648 is the same issue.
