### ISSUE TITLE
Can't open General Preferences from Commando through "combined" scope

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#364]
OS: Linux (Ubuntu)

Steps to reproduce:
1. Open Komodo Edit 9.1.0
2. Open Commando window (Ctrl+Shift+O or click, results are the same)
3. Type "prefe" (no quotes)
4. Press enter

*Expected*
Commando closes. General Preferences window opens.

*Actual*
Commando does not close. General Preferences window does not open.

*Workaround*
1. Open Komodo Edit
2. Open Commando window (Ctrl+Shift+O or click, results are the same)
3. Press Alt+2 (select "Commands" scope)
4. Type "prefe" (no quotes)
5. Press enter

Log to follow.

**Comment by ervumlens** [comment]
Log file after reproducing the error five times.

[2015-06-22 13:41:28,004] [INFO] Startup: Welcome to Komodo Edit 9.1.0 build 15798 (platform linux-x86_64, running on Linux 3.13.0-37-generic version #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014)
[2015-06-22 13:41:28,004] [INFO] Startup: /usr/bin/python built on Sat May 30 05:22:08 2015
[2015-06-22 13:41:30,021] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-06-22 13:41:30,022] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///home/phillip/Komodo-Edit-9/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-06-22 13:41:30,023] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///home/phillip/Komodo-Edit-9/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-06-22 13:41:30,023] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///home/phillip/Komodo-Edit-9/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-06-22 13:41:30,154] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-06-22 13:41:30,802] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:18
[2015-06-22 13:41:30,802] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-06-22 13:41:31,691] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-06-22 13:41:32,148] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_blockSelect', overriding to use 'cmd_blockSelect'
[2015-06-22 13:41:32,149] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_blockSelect', overriding to use 'cmd_blockSelect'
[2015-06-22 13:41:32,149] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_blockSelect', overriding to use 'cmd_blockSelect'
[2015-06-22 13:41:32,149] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_blockSelect', overriding to use 'cmd_blockSelect'
[2015-06-22 13:41:32,149] [WARNING] keybindings: [Ctrl+B] was used for 'cmd_blockSelect', overriding to use 'cmd_blockSelect'
[2015-06-22 13:41:32,711] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-06-22 13:41:32,711] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-06-22 13:41:32,711] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-06-22 13:41:32,711] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-06-22 13:41:32,712] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-06-22 13:41:32,712] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-06-22 13:41:32,713] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-06-22 13:41:32,970] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-06-22 13:41:32,970] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-06-22 13:41:32,970] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-06-22 13:41:32,970] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-06-22 13:41:32,971] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-06-22 13:41:32,971] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-06-22 13:41:32,972] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-06-22 13:41:33,279] [WARNING] koSkin: Detected GTK theme via libgtk: Xfce-dusk
[2015-06-22 13:41:33,844] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-06-22 13:41:33,883] [DEBUG] places_js: waiting for document complete
[2015-06-22 13:41:35,589] [WARNING] console-logger: Key event not available on some keyboard layouts: key="u" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-06-22 13:41:35,589] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-06-22 13:41:35,709] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-06-22 13:41:35,709] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-06-22 13:41:35,709] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-06-22 13:41:35,709] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-06-22 13:41:35,710] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-06-22 13:41:35,710] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-06-22 13:41:35,711] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-06-22 13:41:38,560] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/phillip/Komodo-Edit-9/lib/mozilla/components/koamAddonManager.js:138
[2015-06-22 13:43:14,853] [ERROR] console-logger: TypeError: selected.data is undefined (2) in chrome://scope-combined/content/everything.js:77
Traceback (most recent call last):
  File "chrome://scope-combined/content/everything.js", line 77, in 

[2015-06-22 13:43:16,597] [ERROR] console-logger: TypeError: selected.data is undefined (2) in chrome://scope-combined/content/everything.js:77
Traceback (most recent call last):
  File "chrome://scope-combined/content/everything.js", line 77, in 

[2015-06-22 13:43:17,204] [ERROR] console-logger: TypeError: selected.data is undefined (2) in chrome://scope-combined/content/everything.js:77
Traceback (most recent call last):
  File "chrome://scope-combined/content/everything.js", line 77, in 

[2015-06-22 13:43:17,612] [ERROR] console-logger: TypeError: selected.data is undefined (2) in chrome://scope-combined/content/everything.js:77
Traceback (most recent call last):
  File "chrome://scope-combined/content/everything.js", line 77, in 

[2015-06-22 13:43:17,906] [ERROR] console-logger: TypeError: selected.data is undefined (2) in chrome://scope-combined/content/everything.js:77
Traceback (most recent call last):
  File "chrome://scope-combined/content/everything.js", line 77, in 

[2015-06-22 13:43:30,513] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-06-22 13:43:30,513] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-06-22 13:43:30,513] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-06-22 13:43:30,513] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-06-22 13:43:30,514] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-06-22 13:43:30,514] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-06-22 13:43:30,515] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-06-22 13:43:36,141] [WARNING] console-logger: Key event not available on some keyboard layouts: key="u" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-06-22 13:43:36,142] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by ervumlens** [comment]
The following appears to be the error:

[2015-06-22 13:43:16,597] [ERROR] console-logger: TypeError: selected.data is undefined (2) in chrome://scope-combined/content/everything.js:77
Traceback (most recent call last):
  File "chrome://scope-combined/content/everything.js", line 77, in

**Comment by ervumlens** [comment]
FWIW, I can reproduce this problem with other commands (things that show "cmd_..." in Commando) as well. Macros run and files, websites open as expected.

**Comment by cgchoffman** [comment]
Can't repro on Windows.  I'm seeing the issue on OSX and Linux though.
