### ISSUE TITLE
UI unresponsive, makes display driver crash

### ISSUE THREAD

**Issue by carlbolduc** [Komodo/KomodoEdit#383]
Install the latest build this week, build info:
Komodo IDE, version 9.1.0, build 87337, platform win32-x86. Built on Fri May 29 18:45:28 2015

UI is unresponsive, it may take several seconds to display a menu. Windows often tells me that the display driver is crashing/recovering.

**Comment by Naatan** [comment]
What build did you update from?

I find it hard to believe that Komodo is causing display driver crashes.. are you sure you're not doing anything else at the same time? Have you tried restarting your computer?

**Comment by carlbolduc** [comment]
Here you go:
![notresponding](https://cloud.githubusercontent.com/assets/410440/8420293/df009754-1e8e-11e5-91d5-a38e03206746.jpg)

It's not an upgrade, it's a fresh install.

You can see on the screenshot that the menu is not displaying, though we can see the drop shadow where the menu should be. The display driver crash happens when I open the menu. Other UI elements are not responding to my mouse clicks.

**Comment by Naatan** [comment]
Anything in the error log? [It's pystderr.log in your profile folder](https://community.activestate.com/faq/komodo-profile-structure).

Note this log is truncated each time you start Komodo.

**Comment by carlbolduc** [comment]
Here is the content of the file:

    [2015-06-30 09:37:10,812] [INFO] Startup: Welcome to Komodo IDE 9.1.0 build 87337 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
    [2015-06-30 09:37:10,812] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Fri May 29 18:45:28 2015
    [2015-06-30 09:37:12,022] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
    [2015-06-30 09:37:12,023] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
    [2015-06-30 09:37:12,023] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
    [2015-06-30 09:37:12,023] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
    [2015-06-30 09:37:12,122] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
        @chrome://komodo/content/komodo.js:15:1
    
    [2015-06-30 09:37:12,522] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
    [2015-06-30 09:37:12,522] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:20
    [2015-06-30 09:37:12,905] [ERROR] console-logger: bad script XDR magic number (0) in :0
    Traceback (most recent call last):
      File "", line 0, in 
    
    [2015-06-30 09:37:13,105] [WARNING] keybindings: [Ctrl+Shift+U] was used for 'cmd_convertLowerCase', overriding to use 'cmd_scope-sections'
    [2015-06-30 09:37:14,739] [WARNING] root: ko.findresults was already loaded, re-creating it.
    
    [2015-06-30 09:37:14,779] [DEBUG] places_js: waiting for document complete
    [2015-06-30 09:37:16,513] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
    [2015-06-30 09:38:01,480] [WARNING] views: Inconsistent view count in view_closed event
    [2015-06-30 09:38:01,549] [ERROR] codeintel.komodo.KoCodeIntelManager: Error reading data from codeintel
    Traceback (most recent call last):
      File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koCodeIntel.py", line 1161, in run
        ch = self.pipe.read(1)
      File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\win32_named_pipe.py", line 212, in read
        raise ctypes.WinError(ctypes.get_last_error())
    WindowsError: [Error 109] The pipe has been ended.
