### ISSUE TITLE
[Bugs] Don't Work local debugger NodeJS

### ISSUE THREAD

**Issue by Nemial** [Komodo/KomodoEdit#3836]
### Short Summary
When using the Local NodeJS debugger (version 12.4.1), it does not work

### Steps to Reproduce
1.Open any JS file
2.Select NodeJS language
3. Go to the Debug tab and run

### Actual results
Debug Output:
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '_debugger'
Require stack:
- /opt/komodo-ide/lib/support/dbgp/nodejslib/lib/v8dbg.js
- /opt/komodo-ide/lib/support/dbgp/nodejslib/lib/dbgp.js
- /opt/komodo-ide/lib/support/dbgp/nodejslib/bin/node-dbgp
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/komodo-ide/lib/support/dbgp/nodejslib/lib/v8dbg.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/komodo-ide/lib/support/dbgp/nodejslib/lib/v8dbg.js',
    '/opt/komodo-ide/lib/support/dbgp/nodejslib/lib/dbgp.js',
    '/opt/komodo-ide/lib/support/dbgp/nodejslib/bin/node-dbgp'
  ]
}
```

### Platform Information

*Komodo IDE 12.0.0
*Slackware Current

**Comment by th3coop** [comment]
https://github.com/Komodo/KomodoEdit/issues/3749
