### ISSUE TITLE
Issue when trying to compile on raspbian buster

### ISSUE THREAD

**Issue by Kakiking** [Komodo/KomodoEdit#3882]
I got an Issue when trying to compile KomodoEdit on Raspbian Buster, see Steps to reproduce for the commands I used, see adittional Information for the error

### Steps to Reproduce

run:
```
sudo apt install git zip unzip wget mercurial subversion autoconf2.13 \
	libgtk2.0-dev libdbus-glib-1-dev yasm libasound2-dev \
	libpulse-dev libxt-dev autoconf2.13
```(I had to add --fix-missing because it somehow first failed)

run:
```
git clone https://github.com/Komodo/KomodoEdit.git --branch master --single-branch --depth 1
cd KomodoEdit/mozilla
python build.py configure --gcc gcc --gxx g++-4.9 -k 12.10
```Last line should raise the error

### Platform Information

Komodo Edit
OS: Raspbian Buster
Hadware: Raspberry Pi 3B+

### Additional Information

Error:
```
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ python build.py configure --gcc gcc --gxx g++-4.9 -k 12.10
  File "build.py", line 156
    except ValueError, ex:
                     ^
SyntaxError: invalid syntax
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ 
```

**Comment by Kakiking** [comment]
ok, got it, I had to use python2 instead of python, but I still have an error:
```
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ python2 build.py configure --gcc gcc --gxx g++-4.9 -k 12.10
target: configure
Traceback (most recent call last):
  File "build.py", line 2965, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2961, in main
    return build(args)
  File "build.py", line 2785, in build
    newArgv = targetFunc(argv)
  File "build.py", line 987, in target_configure
    pi = platinfo.PlatInfo()
  File "../util/platinfo.py", line 188, in __init__
    self._init_linux()
  File "../util/platinfo.py", line 418, in _init_linux
    raise InternalError("unknown Linux architecture: '%s'" % arch)
platinfo.InternalError: unknown Linux architecture: 'armv7l'

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* Please report this error by adding a bug here:
*     http://code.google.com/p/platinfo/issues/list
* or, by sending an email to <trentm@gmail.com>.
*
* I'd like to keep improving `platinfo.py' to cover as many platforms
* as possible. Please be sure to include the error message above and
* any addition information you think might be relevant. Thanks!
* -- Trent
*
* platinfo version: (0, 14, 5)
* python version: sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0)
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ 
```

**Comment by Laniture** [comment]
@Kakiking  I'm not sure if it's even possible to get it to work on arm. But if you really want to try.


This is the file throwing the error [KomodoEdit//util/platinfo.py](https://github.com/Komodo/KomodoEdit/blob/master/util/platinfo.py#L418)
You could try to replace
`raise InternalError("unknown Linux architecture: '%s'" % arch)` line 418
with 
`self.arch = "armv7l"`
or
`self.arch = "x86"`

**Comment by th3coop** [comment]
We haven't put any effort into getting Komodo building on Arm processors.  @Laniture's suggesting seems like a good start but expect to more hacks to get this working!

**Comment by Kakiking** [comment]
I forked the repo and pushed the changes to there, because I guess I'll have to make many changes :sweat_smile: 
https://github.com/Kakiking/KomodoEdit.git

**Comment by Kakiking** [comment]
ok error again, Something is missing :monocle_face: 
```
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ python2 build.py configure --gcc gcc --gxx g++-4.9 -k 12.10
target: configure
build: warning: Failed to get changenum, using 0 instead
Traceback (most recent call last):
  File "build.py", line 2965, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2961, in main
    return build(args)
  File "build.py", line 2785, in build
    newArgv = targetFunc(argv)
  File "build.py", line 1314, in target_configure
    mtime_zip = os.stat(prebuiltDir+".zip").st_mtime
OSError: [Errno 2] No such file or directory: 'prebuilt/python2.7/linux-armv7l.zip'
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ 
```

**Comment by th3coop** [comment]
@Kakiking looks like you need a Python install for arm.

**Comment by Kakiking** [comment]
@th3coop python installl? I have python 2 and 3 installed if you mean that

**Comment by th3coop** [comment]
```
OSError: [Errno 2] No such file or directory: 'prebuilt/python2.7/linux-armv7l.zip'
pi@raspberrypi:~/github repos/KomodoEdit/mozilla $ 
```

Did you look at the other files in that folder?  They are prebuilt Python interpreters/installs.  We do not ship a prebuilt Python for Arm.  You will need to provide that yourself.

**Comment by Kakiking** [comment]
ok, I'll get a python 2 install and add it there and then try again :)
