### ISSUE TITLE
Can Login active State, Komodo startup error NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by bwarbis** [Komodo/KomodoEdit#3891]
### Short Summary
Komodo opens and works but is not able to log into ActiveState. This is true with both komodo-edit and komodo-ide. This is a fresh install of freebsd 12.1 onto an older i386 p4 machine. When komodo opens it also give an error2147500037 (NS_ERROR_FAILURE). I know that the network/internet is working (filling this form)

### Steps to Reproduce
Open Komodo edit/ide

### Expected results
Program opens successfully with no error message. ability to log into activestate when prompted.

### Actual results
Get aforementioned error message. When using "edit" I am still abel to work and open documents. When I use the IDE no login means no ide/editor....

### Platform Information

*Komodo Edit or IDE? BOTH
*Komodo Version? 11/02 
*Operating System (and version)? Freebsd 12.1

**Comment by th3coop** [comment]
@bwarbis, please try the latest Komodo IDE 12 and report back.

**Comment by th3coop** [comment]
Link to download: https://www.activestate.com/products/komodo-ide/download-ide/?_ga=2.172069479.557968868.1600710697-860307084.1507232229

**Comment by bwarbis** [comment]
Um.. ok sp I am stupid and pasted the version but wound up with a some freaking date.. I aplogize for nay confusion as I just downloaded and installed. I have confirmed that I do indeed have version Komodo-IDE-12.0.1-91869-linux-x86.

**Comment by th3coop** [comment]
@bwarbis please share your logs that you got the original error from.

**Comment by bwarbis** [comment]
As requested here is the log that I have. I see I have some permissions issues and other things that are not loading properly, that being said the software seems to work ok as an editor and I don't have to log in to use it in that mode but as the IDE requires a login I can go no further...

[2020-09-21 09:56:41,600] [INFO] Startup: Welcome to Komodo Edit 11.0.2 build 18122 (platform linux-x86, running on Linux 2.6.32 version FreeBSD 12.1-RELEASE r354233 GENERIC)
[2020-09-21 09:56:41,600] [INFO] Startup:  built on Mon Dec 4 16:56:09 2017
[2020-09-21 09:56:42,997] [WARNING] koInitService: Unable to determine the current locale settings, please set LANG environment variable. Defaulting to en_US.iso8859-1
[2020-09-21 09:56:42,998] [INFO] koInitService: Setting LC_CTYPE to utf-8
[2020-09-21 09:56:47,503] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2020-09-21 09:56:48,125] [WARNING] root: [object Object].logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2020-09-21 09:56:49,785] [WARNING] console-logger: Expected identifier for pseudo-class or pseudo-element but found ' '.  Ruleset ignored due to bad selector. (1) in chrome://komodo/skin/codeintel.css:1
[2020-09-21 09:56:49,788] [WARNING] console-logger: Unexpected end of file while searching for closing } of invalid rule set. (1) in chrome://komodo/skin/codeintel.css:42
[2020-09-21 09:56:51,538] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2020-09-21 09:56:53,178] [WARNING] keybindings: [F1] was used for 'cmd_helpHelp', overriding to use 'cmd_toggleInteractiveShell'
[2020-09-21 09:56:53,182] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2020-09-21 09:56:57,099] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2020-09-21 09:56:57,100] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2020-09-21 09:56:57,100] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2020-09-21 09:56:57,101] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2020-09-21 09:56:57,104] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2020-09-21 09:56:57,106] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2020-09-21 09:56:57,107] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2020-09-21 09:56:57,109] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2020-09-21 09:57:00,583] [INFO] koInitService: Adding pre startup service for 'koFileStatusService': '@activestate.com/koFileStatusService;1'
ERROR:xpcom:Unhandled exception calling 'int8 * addObserver(in nsISomething, in wstring, in int32, in int32);'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koFileNotificationService.py", line 203, in addObserver
    raise OSError(message)
OSError: Function not implemented
[2020-09-21 09:57:01,344] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2020-09-21 09:57:02,383] [ERROR] CT::margin.js: couldn't get the insert-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:59:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2020-09-21 09:57:02,385] [ERROR] CT::margin.js: couldn't get the delete-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:65:32
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2020-09-21 09:57:02,387] [ERROR] CT::margin.js: couldn't get the change-color
-- EXCEPTION START --
TypeError: this.view.scheme.getInterfaceStyleRaw is not a function
+ stack
    exports.MarginController.prototype._initMarkerStyles@chrome://trackchanges/content/margin.js:71:33
    refreshMarginProperies@chrome://trackchanges/content/margin.js:120:9
    MarginController@chrome://trackchanges/content/margin.js:44:5
    exports.ChangeTracker.prototype.changeTrackingOn@chrome://trackchanges/content/tracker.js:63:19
    ChangeTracker@chrome://trackchanges/content/tracker.js:27:5
    this.onViewOpenedHandler@chrome://trackchanges/content/trackchanges.js:88:26
    this.init/<@chrome://trackchanges/content/trackchanges.js:49:13
    this.init@chrome://trackchanges/content/trackchanges.js:46:1
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:187:5
    onloadDelay/<@chrome://komodo/content/komodo.js:464:9
-- EXCEPTION END --
[2020-09-21 09:57:03,764] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/komodo/process.py", line 361, in __init__
    creationflags=flags)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/komodo/subprocess32.py", line 812, in __init__
    restore_signals, start_new_session)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/komodo/subprocess32.py", line 1557, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 13] Permission denied
ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/komodo/process.py", line 361, in __init__
    creationflags=flags)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/komodo/subprocess32.py", line 812, in __init__
    restore_signals, start_new_session)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/komodo/subprocess32.py", line 1557, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 13] Permission denied
[2020-09-21 09:57:05,435] [ERROR] koJavaScriptLinter: Problem running GenericJSLinter
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koJavaScriptLinter.py", line 373, in lint_with_text
    p = process.ProcessOpen(cmd, cwd=cwd, env=self._setLDLibraryPath(), stdin=fd)
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/components.py", line 263, in wrapperFn
    threadMgr.mainThread.dispatch(method, dispatch_flags)
  File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)
[2020-09-21 09:57:05,439] [ERROR] koLintService: lint_with_text exception
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koLintService.py", line 205, in lint_with_text
    newLintResults = UnwrapObject(linter).lint_with_text(request, text)
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koJavaScriptLinter.py", line 404, in lint_with_text
    if len(warnLines) % 2 == 1:
UnboundLocalError: local variable 'warnLines' referenced before assignment
[2020-09-21 09:57:06,882] [INFO] koInitService: Adding pre startup service for 'KoMemoryReporter': '@activestate.com/koMemoryReporter;1'
[2020-09-21 09:57:06,908] [INFO] koInitService: Adding pre startup service for 'koCommandmentService': '@activestate.com/koCommandmentService;1'
[2020-09-21 09:57:12,092] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2020-09-21 09:57:12,093] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2020-09-21 09:57:12,094] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2020-09-21 09:57:12,094] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2020-09-21 09:57:12,098] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2020-09-21 09:57:12,100] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2020-09-21 09:57:12,101] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2020-09-21 09:57:12,103] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2020-09-21 09:57:13,795] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/command.svg:0
[2020-09-21 09:57:14,311] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///usr/local/share/komodo-edit/lib/mozilla/components/koamAddonManager.js:138
[2020-09-21 10:08:03,100] [ERROR] console-logger: TypeError: ko.places.projects.doDragEnter is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,105] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,131] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,173] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,197] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,258] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,274] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,294] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

[2020-09-21 10:08:03,314] [ERROR] console-logger: TypeError: ko.places.projects.doDragOver is not a function (2) in chrome://komodo-places/content/places_panel.xul:1
Traceback (most recent call last):
  File "chrome://komodo-places/content/places_panel.xul", line 1, in 

ERROR:xpcom:Unhandled exception calling 'int8 * addObserver(in nsISomething, in wstring, in int32, in int32);'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koFileNotificationService.py", line 203, in addObserver
    raise OSError(message)
OSError: Function not implemented
[2020-09-21 10:50:58,077] [ERROR] koPlaceTreeView: Can't watch path: /home/administrator
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 496, in _addWatchForChanges
    _notificationsToReceive)
  File "<XPCOMObject method 'addObserver'>", line 3, in addObserver
Exception: 2147500037 (NS_ERROR_FAILURE)
ERROR:xpcom:Unhandled exception calling 'int8 * addObserver(in nsISomething, in wstring, in int32, in int32);'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koFileNotificationService.py", line 203, in addObserver
    raise OSError(message)
OSError: Function not implemented
ERROR:xpcom:Unhandled exception calling 'int8 * addObserver(in nsISomething, in wstring, in int32, in int32);'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koFileNotificationService.py", line 203, in addObserver
    raise OSError(message)
OSError: Function not implemented
ERROR:xpcom:Unhandled exception calling 'int8 * addObserver(in nsISomething, in wstring, in int32, in int32);'
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/python/xpcom/server/policy.py", line 303, in _CallMethod_
    return 0, func(*params)
  File "/usr/local/share/komodo-edit/lib/mozilla/components/koFileNotificationService.py", line 203, in addObserver
    raise OSError(message)
OSError: Function not implemented
[2020-09-21 10:51:05,295] [ERROR] koPlaceTreeView: Can't watch path: /home/administrator/Outlook
Traceback (most recent call last):
  File "/usr/local/share/komodo-edit/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 496, in _addWatchForChanges
    _notificationsToReceive)
  File "<XPCOMObject method 'addObserver'>", line 3, in addObserver
Exception: 2147500037 (NS_ERROR_FAILURE)
[2020-09-21 10:51:15,910] [WARNING] views: Inconsistent view count in view_closed event

**Comment by th3coop** [comment]
A couple things:
- Edit doesn't have a log in screen. Only IDE does.  I'm going to update your original description to reflect that.
- These logs say you're using Edit 11 `Welcome to Komodo Edit 11.0.2 build 18122`

Start Komodo 12 and provide the following:
- screenshot of the failed logging
- logs from *~/.komodoide/pystderr.log*
