### ISSUE TITLE
Komodo Edit 9.1.0 print and print preview is blank on Win8.1 Pro

### ISSUE THREAD

**Issue by lfelia** [Komodo/KomodoEdit#410]
When I open a file (on windows) I can edit the file, but if I print the file or display print preview, all that shows are any headers I have selected, not the page text.

I don't print often, so I am not certain when this stopped working. On Linux x86_64 it works fine.

Any Ideas?

**Comment by Naatan** [comment]
I cannot reproduce this on Windows 8. Can you share your error log after having opened the print preview dialog? `Help > Troubleshooting > View Log File`.

**Comment by lfelia** [comment]
This is the error log:

[2015-07-10 12:37:17,414] [INFO] Startup: Welcome to Komodo Edit 9.1.0 build 15786 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2015-07-10 12:37:17,414] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\komodo.exe built on Thu May 21 06:47:28 2015
[2015-07-10 12:37:18,648] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-07-10 12:37:18,650] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209%20nightly/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-07-10 12:37:18,651] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209%20nightly/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-07-10 12:37:18,654] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209%20nightly/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-07-10 12:37:18,773] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-07-10 12:37:19,153] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-07-10 12:37:19,154] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:20
[2015-07-10 12:37:19,746] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-07-10 12:37:21,131] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-07-10 12:37:21,183] [DEBUG] places_js: waiting for document complete
[2015-07-10 12:37:22,309] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-10 12:37:22,309] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-10 12:37:22,309] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-10 12:37:22,309] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-10 12:37:22,311] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-10 12:37:22,311] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-10 12:37:22,311] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-10 12:37:22,780] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209%20nightly/lib/mozilla/components/koamAddonManager.js:138
ERROR:xpcom:Unhandled exception calling 'G     int8 * exists(out retval boolean);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\python\xpcom\server\policy.py", line 274, in _CallMethod_
    ret = getattr(self._obj_, name) # Let attribute error go here!
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koFileEx.py", line 102, in __getattr__
    raise AttributeError, attr
AttributeError: exists
[2015-07-10 12:37:25,266] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIFileEx.exists] (2) in chrome://komodo/content/library/uilayout.js:995
Traceback (most recent call last):
  File "chrome://komodo/content/library/uilayout.js", line 995, in 

[2015-07-10 12:37:26,407] [ERROR] ko-fileicons: Exception in timeout for sdk/icons._createPngFromSvg()
-- EXCEPTION START --
Error: path does not exist: C:\Users\lfeli_000\AppData\Local\ActiveState\KomodoEdit\9.1\XRE\icons\fileicons\Unknown16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
[2015-07-10 12:37:26,417] [ERROR] ko-fileicons: Exception in timeout for sdk/icons._createPngFromSvg()
-- EXCEPTION START --
Error: path does not exist: C:\Users\lfeli_000\AppData\Local\ActiveState\KomodoEdit\9.1\XRE\icons\fileicons\Unknown16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
[2015-07-10 12:37:26,421] [ERROR] ko-fileicons: Exception in timeout for sdk/icons._createPngFromSvg()
-- EXCEPTION START --
Error: path does not exist: C:\Users\lfeli_000\AppData\Local\ActiveState\KomodoEdit\9.1\XRE\icons\fileicons\Unknown16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
[2015-07-10 12:37:26,427] [ERROR] ko-fileicons: Exception in timeout for sdk/icons._createPngFromSvg()
-- EXCEPTION START --
Error: path does not exist: C:\Users\lfeli_000\AppData\Local\ActiveState\KomodoEdit\9.1\XRE\icons\fileicons\Unknown16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
[2015-07-10 12:37:28,579] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-10 12:37:28,579] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-10 12:37:28,581] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-10 12:37:28,581] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-10 12:37:28,581] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-10 12:37:28,581] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-10 12:37:28,582] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-10 12:37:41,141] [ERROR] console-logger: TypeError: redeclaration of const JetPack (2) in chrome://komodo/content/jetpack.js:10
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 10, in 

[2015-07-10 12:37:41,187] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-10 12:37:41,187] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-10 12:37:41,187] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-10 12:37:41,187] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-10 12:37:41,188] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-10 12:37:41,188] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-10 12:37:41,190] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-07-10 12:37:56,788] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-07-10 12:37:56,789] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-07-10 12:37:56,789] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-07-10 12:37:56,789] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-07-10 12:37:56,789] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-07-10 12:37:56,789] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-07-10 12:37:56,790] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'

**Comment by Naatan** [comment]
I don't see anything relevant in there. Could you share a screenshot of your Prefs > Printing window? (You need to toggle "Show Advanced" at the bottom left of the pref window).

**Comment by lfelia** [comment]
I fixed this. Somehow "Scale font sizes from screen to print" was set to 0 instead of 1, and then no text shows. When I set it to 1 it worked fine.
