### ISSUE TITLE
Closing a focused markdown file while previewing throws exception, does not correctly fire "view closed" events

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#468]
**Problem**
Closing a markdown file while it's being previewed closes both the file and the preview. If the markdown file has focus at that time, an exception is thrown.

Whether or not the markdown file has focus, the appropriate "file closed" events are not fired in this scenario (as seen in the `File` &rarr; `Close` menu and other places), and the log warns about inconsistent `view_closed` events. 

I don't know if there are multiple problems here or just one. Sorry.

> Komodo Edit, version 9.1.0, build 15798, platform linux-x86_64. Built on Sat May 30 05:22:08 2015.

**Steps to Reproduce**
1. Open Komodo Edit with no open files, to simplify the test case. This may require closing all files and restarting Komodo.
2. Open a markdown file. 
3. Open the markdown file preview.
4. Put focus back on the markdown file. This step is important.
5. Close the markdown file. Different methods of closing produce different exceptions. In this case, I'm using the keyboard shortcut.

**Expected**
All views are now closed. 
The `File` &rarr; `Close` &rarr; `Current File` menu item is disabled.
Nothing interesting appears in the logs.

**Actual**
All views are now closed. :+1:
The `File` &rarr; `Close` &rarr; `Current File` menu item is enabled. :-1:
Something interesting appears in the logs. :hatching_chick:

```
[2015-07-30 21:28:53,538] [WARNING] views: Inconsistent view count in view_closed event
[2015-07-30 21:28:53,555] [ERROR] commands: An error occurred executing the cmd_bufferClose command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1067}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1067}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1067}]'[JavaScript Error: "this.log is undefined" {file: "vieweditor" line: 1067}]' when calling method: [nsIController::doCommand]'
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommandAsync :: line 215
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync@chrome://'...476 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-07-30 21:28:53,560] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-07-30 21:28:53,575] [ERROR] view.multiview: 
-- EXCEPTION START --
TypeError: newView.makeCurrent is not a function
+ stack
    onxblview_list_closed/<@chrome://komodo/content/bindings/views-multi.xml:527:25
-- EXCEPTION END --
[2015-07-30 21:28:53,586] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1067
Traceback (most recent call last):
  File "vieweditor", line 1067, in 
```

Closing the markdown file by clicking on the tab's X produces this similar error:

```
[2015-07-30 21:37:27,942] [WARNING] views: Inconsistent view count in view_closed event
[2015-07-30 21:37:27,973] [ERROR] view.multiview: 
-- EXCEPTION START --
TypeError: newView.makeCurrent is not a function
+ stack
    onxblview_list_closed/<@chrome://komodo/content/bindings/views-multi.xml:527:25
-- EXCEPTION END --
[2015-07-30 21:37:27,988] [ERROR] console-logger: TypeError: this.log is undefined (2) in vieweditor:1067
Traceback (most recent call last):
  File "vieweditor", line 1067, in 
```

**Comment by Naatan** [comment]
Reproduced, luckily this does not affect the end user.
