### ISSUE TITLE
Cannot open submenus in hamburger menu

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#477]
When I hover on an item in the hamburger menu, I'm not able to see a submenu for this item if the item have a submenu.
Here's the log:
```
[2015-08-03 18:27:06,404] [INFO] Startup: Welcome to Komodo IDE 9.2.0 build 87613 (platform linux-x86_64, running on Linux 3.19.0-25-generic version #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015)
[2015-08-03 18:27:06,404] [INFO] Startup: /usr/bin/python built on Fri Jul 31 01:55:38 2015
[2015-08-03 18:27:07,133] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-08-03 18:27:07,140] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///home/defman/.komodoide/9.2/XRE/extensions/emmet@chikuyonok.ru.xpi!/chrome.manifest:1
[2015-08-03 18:27:07,140] [WARNING] console-logger: Trying to re-register CID '{4e5c9764-d465-4fef-ae24-8032f257d174}' already registered by file:///home/defman/.komodoide/9.2/XRE/extensions/koextensiondev@activestate.com/components/pyShell.py. (1) in file:///home/defman/.komodoide/9.2/XRE/extensions/koextensiondev@activestate.com/components/component.manifest:2
[2015-08-03 18:27:07,141] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///home/defman/.komodoide/9.2/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2015-08-03 18:27:07,636] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-08-03 18:27:08,117] [ERROR] koManifestLoader: Filename should be 'chrome.manifest'
[2015-08-03 18:27:08,121] [ERROR] koManifestLoader: Filename should be 'chrome.manifest'
[2015-08-03 18:27:08,659] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2015-08-03 18:27:09,412] [ERROR] console-logger: TypeError: this._currentView is undefined (2) in chrome://komodowakatime/content/komodowakatime.js:196
Traceback (most recent call last):
  File "chrome://komodowakatime/content/komodowakatime.js", line 196, in 

[2015-08-03 18:27:09,549] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-08-03 18:27:09,727] [ERROR] console-logger: TypeError: Argument 2 of EventTarget.addEventListener is not an object. (2) in chrome://todo/content/todo-ko7.js:582
Traceback (most recent call last):
  File "chrome://todo/content/todo-ko7.js", line 582, in 

[2015-08-03 18:27:10,187] [ERROR] koDBConnSqlite3: Failed: OperationalError(OperationalError('unable to open database file',),)
[2015-08-03 18:27:11,342] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-08-03 18:27:11,346] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-08-03 18:27:11,349] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1132:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 
```

**Comment by Naatan** [comment]
Thanks Defman. Fixed on IDE repo.

**Comment by Defman21** [comment]
Oh lol, that was an issue actually. I thought that something just broken in my profile folder :smiley:
