### ISSUE TITLE
Revert changes no longer works in the most recent Komodo IDE build

### ISSUE THREAD

**Issue by shelldweller** [Komodo/KomodoEdit#511]
Clicking on revert changes closes popup; nothing gets reverted. (In the prev build this feature was also a bit quirky: first click: nothing, second click: popup closed and changes reverted).

Build info:
Komodo IDE, version 9.2.0, build 87616, platform macosx.
Built on Tue Aug 4 11:29:06 2015.

![image](https://cloud.githubusercontent.com/assets/451485/9152739/a4dcbb14-3e02-11e5-96ca-f84cd240f33a.png)

**Comment by Defman21** [comment]
Not able to reproduce it on Linux... Hmm... Can you share your error log? (`Help - Troubleshooting - View log file`). Also, do you use SCC in the folder with this file? (like git) (btw I've tried to revert some changes in a file with SCC and without SCC, in both cases it reverts my new changes perfectly).

**Comment by shelldweller** [comment]
Yes this directory is within a git repository.

There appears to be nothing relevant in the log file. Here it is. Just restarted Komodo to get a fresh one:
```
[2015-08-08 19:34:41,885] [INFO] Startup: Welcome to Komodo IDE 9.2.0 build 87616 (platform macosx, running on Darwin 13.4.0 version Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64)
[2015-08-08 19:34:41,885] [INFO] Startup: /Applications/Komodo IDE 9.app/Contents/MacOS/komodo built on Tue Aug 4 11:29:06 2015
[2015-08-08 19:34:42,078] [WARNING] koInitService: Unable to determine the current locale settings, defaulting to mac-roman
[2015-08-08 19:34:43,022] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-08-08 19:34:43,350] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2366
[2015-08-08 19:34:43,415] [WARNING] console-logger: Expected end of value but found 'solid'.  Error in parsing value for 'border-width'.  Declaration dropped. (1) in chrome://global/skin/global.css:2366
[2015-08-08 19:34:43,495] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-08-08 19:34:44,474] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///Applications/Komodo%20IDE%209.app/Contents/Resources/components/koamAddonManager.js:138
[2015-08-08 19:34:45,657] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-08-08 19:34:46,631] [DEBUG] editorconfig: Setting editorconfig: {}
[2015-08-08 19:34:47,777] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-08-08 19:34:48,180] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for CSS
[2015-08-08 19:34:48,181] [WARNING] koLanguage: Asked for unknown language: 'None'
[2015-08-08 19:34:48,619] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-08-08 19:34:48,620] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-08-08 19:34:48,621] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1132:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2015-08-08 19:34:50,362] [INFO] komodospellchecker: Spell checker loaded.
[2015-08-08 19:34:50,363] [INFO] komodospellchecker: Using dictionary en-US
[2015-08-08 19:34:54,474] [WARNING] console: Plural form unknown for locale "null"
```

**Comment by Defman21** [comment]
Did you press `Revert changes` before sharing the log file? Does `Revert Changes` works in other files? Could you try to revert changes in a file which is not under git control?

**Comment by shelldweller** [comment]
Yes I did press "revert changes" before opening the log. No it does not work on other files, including those which are not under git control.

**Comment by Defman21** [comment]
I'll try to reproduce it, but it seems like something specific to OSX.

**Comment by Defman21** [comment]
Can I ask you for one last thing? Could you try to start Komodo with clean profile and reproduce the bug?
```bash
export KOMODO_USERDATADIR="/tmp/ko_temp_data"
/path/to/komodo/binary/komodo
```
That will temporary set your user data to `/tmp/ko_temp_data`, it will work only for current terminal session.

**Comment by shelldweller** [comment]
Same thing.

**Comment by Defman21** [comment]
Thanks. I'm still trying to reproduce the issue, but no luck with that :|

**Comment by Naatan** [comment]
Reproduced on OSX, it seems like the click is going right through the button.

@mitchell-as could any of your changes in 9.2 be stealing panel focus on click? Something in Scintilla?
