### ISSUE TITLE
Codeintel burps on "form"

### ISSUE THREAD

**Issue by agroszer** [Komodo/KomodoEdit#544]
After opening `form.py` the following keeps popping up after every few line up/down moves.
It's pretty annoying.

```
[2015-08-19 15:05:12,635] [ERROR] codeintel.oop.driver: form
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 885, in do_get_sections
    sections = buf.get_sections()
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 411, in get_sections
    return self.cached_sections
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 198, in blob_from_lang
    self._load_buf_data_once()
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 139, in _load_buf_data_once
    self._blob_from_lang_cache = self.mgr.db.get_buf_data(self)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/database/database.py", line 1032, in get_buf_data
    return self._get_lang_zone(buf.lang).get_buf_data(buf)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/database/langlib.py", line 808, in get_buf_data
    dbsubpath = join(dhash, dbfile_from_blobname[blobname])
KeyError: u'form'
```

```
[2015-08-19 15:05:18,434] [ERROR] codeintel.oop.driver: form
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/database/database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/database/langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'form'
[2015-08-19 15:05:18,835] [ERROR] koCodeIntel: form
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/codebrowser.py", line 26, in handleRequest
    return meth(request, driver)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/codebrowser.py", line 50, in do_get_buffer
    buf.scan()
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 290, in scan
    skip_scan_time_check=skip_scan_time_check)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/database/database.py", line 1046, in update_buf_data
    skip_scan_time_check=skip_scan_time_check)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/database/langlib.py", line 1040, in update_buf_data
    dbfile = blob_index[blobname]
KeyError: u'form'
```

```
[2015-08-19 15:05:24,204] [ERROR] codeintel.oop.driver: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 885, in do_get_sections
    sections = buf.get_sections()
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 411, in get_sections
    return self.cached_sections
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'
[2015-08-19 15:05:24,226] [ERROR] koCodeIntel: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 885, in do_get_sections
    sections = buf.get_sections()
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 411, in get_sections
    return self.cached_sections
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 330, in cached_sections
    self._sections_cache = (now, md5sum, list(self.sections))
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/buffer.py", line 303, in sections
    for s in self.langintel.sections_from_buf(self):
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by agroszer** [comment]
That wrecks other tabs with the
```
  File "/home/adi/Komodo-IDE-910/lib/mozilla/python/komodo/codeintel2/citadel.py", line 55, in sections_from_buf
    blob = buf.blob_from_lang.get(self.lang)
AttributeError: 'NoneType' object has no attribute 'get'
```

restarting without `form.py` helps then

**Comment by Naatan** [comment]
I cannot reproduce this simply by naming a file `form.py`, could you share the contents of this file?

**Comment by agroszer** [comment]
naaah, sorry

**Comment by Naatan** [comment]
Unfortunately not much we can do here then. Please let us know if you can reproduce it with a test case which you can share.

**Comment by agroszer** [comment]
Turns out it's NOT about content.
The very same file in /tmp... does not burp.
Same location, single # as content burps too.
Complete tree copied to /tmp does not burp.
Maybe there's some crap in the codeintel DB? How to rebuild that?

**Comment by Naatan** [comment]
You can simply delete the codeintel folder from your profile folder while Komodo is not running. It will rebuild it the next time you start it.

Could it be the path? Any special characters?

**Comment by agroszer** [comment]
yah, rebuilding the codeintel DB helped

no special chars... not even a space, maybe bad shutdown or power loss wrecked the DB
