### ISSUE TITLE
Exception logged from editorconfig when opening Markdown preview or other browser 

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#555]
(`.editorconfig` code is now part of KE, but it's maintained in a separate project. I'm logging this here because that's what I do, but let me know if belongs to the "komodo-editorconfig" project instead.)

Probably just a nuisance error.

**Problem**
Opening a browser view (e.g. the Markdown preview) produces an exception in the logs.

```
ERROR:xpcom:Unhandled exception calling 'int8 * get_properties(in unicode &, in dipper retval unicode &);'
Traceback (most recent call last):
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/extensions/editorconfig@activestate.com/components/koEditorConfig.py", line 27, in get_properties
    except exceptions.ParsingError:
NameError: global name 'exceptions' is not defined
[2015-08-24 13:08:57,499] [ERROR] editorconfig: Exception while parsing editorconfig
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIEditorConfig.get_properties]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://editorconfig/content/editorconfig.js :: viewChanged :: line 22"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIEditorConfig.get_properties]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://editorconfig/content/editorconfig.js'
+ lineNumber (number) 22
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'viewChanged@chrome://editorconfig/content/editorconfig.js:22:24
'
+ location (object) JS frame :: chrome://editorconfig/content/editorconfig.js :: viewChanged :: line 22
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://editorconfig/content/editorconfig.js'
| + name (string) 'viewChanged'
| + lineNumber (number) 22
| + columnNumber (number) 24
| + sourceLine (string) ''
| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
| + formattedStack (string) 'viewChanged@chrome://editorconfig/content/editorconfig.js:22:24
'
| + stack
    viewChanged@chrome://editorconfig/content/editorconfig.js:22:24
-- EXCEPTION END --
```

**Comment by mitchell-as** [comment]
This should be fixed in the upcoming 9.2.1: https://github.com/Komodo/komodo-editorconfig/commit/df95d32947ab4d06e678088f466678bbe5f616e5
