### ISSUE TITLE
An error when creating a directory

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#563]
Easy to reproduce.
Open Places panel, right-click on any **file** (it's important), then just hover on any element in the context menu, then **right-click** on an empty space in the left pane and be sure that the item in the file tree is selected (just right-click on an empty space very fast) and try to create a folder.

Error:
```
ERROR:xpcom:Unhandled exception calling 'int8 * addNewFolderAtParent(in wstring, in int32);'
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 1543, in addNewFolderAtParent
    os.mkdir(fullPath)
OSError: [Errno 20] Not a directory: '/server/defman21.me/index.html/fefe'
[2015-08-30 19:01:10,499] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 
```

Simple patch to fix it: 
```patch
--- koPlaceTreeView.py	2015-08-30 19:05:25.524419277 +0300
+++ koPlaceTreeView.py 	2015-08-30 19:05:59.979161136 +0300
@@ -1536,6 +1536,7 @@
         else:
             parentPath = self._rows[parentIndex].path
         if self.safe_isLocal():
+            parentPath = os.path.dirname(parentPath)
             fullPath = os.path.join(parentPath, basename)
             if os.path.exists(fullPath):
                 raise ServerException(nsError.NS_ERROR_INVALID_ARG,

```

**Comment by Naatan** [comment]
Thanks Defman. That's not a proper fix since it would also execute when a folder is selected. Better would be to check whether the selection is a file and only then execute the new line you added. I'll make this fix, thanks for pointing us to the source of the issue!

**Comment by Naatan** [comment]
Seems the issue is more complex than I thought, even when fixing the issue at hand other issues arise (file status service for some reason doesn't get a proper file pointer).

This indicates to me that we should fix the underlying issue: right clicking on the tree should always change the selection.
