### ISSUE TITLE
Komodo 9.2.0 Snippet Editing Fails to Save

### ISSUE THREAD

**Issue by wdbaker54** [Komodo/KomodoEdit#566]
I cannot save an edited snippet. The steps I took are:
1. Opened Komodo IDE 9.2.0 in Ubuntu 14.04 LTS
2. Opened a snippet I created for editing.
3. Deleted a line I no longer wanted in the snippet
4. Did a Ctrl-S to save it and an error box appeared without saving the snippet.
![screenshot from 2015-09-01 10 45 53](https://cloud.githubusercontent.com/assets/401129/9612012/13718c2e-5098-11e5-847f-ce6e979ae869.png)

My pystderr.log showed:
```
[2015-09-01 10:52:12,797] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/bill/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2015-09-01 10:52:18,528] [DEBUG] editorconfig: Setting editorconfig: {}
[2015-09-01 10:52:18,539] [WARNING] RefactoringLanguageServiceBase: Can't find a refactoring service for Komodo Snippet
[2015-09-01 10:52:18,539] [WARNING] koLanguage: Asked for unknown language: 'None'
ERROR:xpcom:Unhandled exception calling 'int8 * close();'
Traceback (most recent call last):
  File "/home/bill/Komodo-IDE-9/lib/mozilla/python/xpcom/server/policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "/home/bill/Komodo-IDE-9/lib/mozilla/python/komodo/URIlib.py", line 1111, in close
    tool.save() # updates filesystem tool & DB
  File "/home/bill/Komodo-IDE-9/lib/mozilla/components/koTools.py", line 776, in save
    self.saveToolToDisk()
  File "/home/bill/Komodo-IDE-9/lib/mozilla/components/koTools.py", line 350, in saveToolToDisk
    logic = self.getStringAttribute("logic")
  File "/home/bill/Komodo-IDE-9/lib/mozilla/components/koTools.py", line 215, in getStringAttribute
    return unicode(self._attributes[name])
KeyError: 'logic'
[2015-09-01 10:52:21,262] [ERROR] koDocument: save: can't write to file u'snippet2://1673/Add_Logging.snippet'
Traceback (most recent call last):
  File "/home/bill/Komodo-IDE-9/lib/mozilla/components/koDocument.py", line 1684, in save
    self.file.close()
  File "<XPCOMObject method 'close'>", line 3, in close
Exception: 2147500037 (NS_ERROR_FAILURE)
```

I hope this is enough for you.

**Comment by Defman21** [comment]
https://github.com/Komodo/KomodoEdit/issues/504

**Comment by wdbaker54** [comment]
Thanks for the quick link. The nightly corrected the problem.
