### ISSUE TITLE
GoLang prefs dont save on OSX

### ISSUE THREAD

**Issue by Naatan** [Komodo/KomodoEdit#58]
Workaround:

Define your Go PATH in Prefs > Environment

**Comment by jbuberel** [comment]
FWIW, this definitely affects both the 'go tool' and the 'gocode' settings. Haven't tested yet with godef.

**Comment by raphaeljlps** [comment]
Don`t work with godef either. I'm having the same problem.

**Comment by fraherm** [comment]
+1

**Comment by Naatan** [comment]
Yeah its all of the prefs in the Go pref dialog, oddly works fine on Linux though. Will fix.

**Comment by cgchoffman** [comment]
More details in issue [18](https://github.com/Komodo/komodo-go/issues/18) in the komodo-go repo.

**Comment by SamWyndham** [comment]
Hi.  Regarding the workaround, what are the names of the environment variables? Thanks

**Comment by Naatan** [comment]
Find out where your go executable is located using `which go` in your terminal. If you're using Windows I assume you will know where you installed it as it would ask you during installation.

Copy the path (excluding the executable itself) and add it to the PATH environment variable, ensure that you separate your path from the existing entries using the path separator, which is either a color or a semi-colon (just look at your existing PATH entry to find out).

**Comment by SamWyndham** [comment]
Thanks @Naatan !

**Comment by cgchoffman** [comment]
Another report with lots of detail, just incase they are needed: https://bugs.activestate.com/show_bug.cgi?id=106459

**Comment by Naatan** [comment]
Assigning to @toddw-as as I am scared of touching this for a minor release myself, it seems the way the golang info is defined is not in line with other languages.

Relevant logs:

```
[2015-04-06 15:37:22,360] [ERROR] koGoAppInfo: Failed to import koAppInfo
Traceback (most recent call last):
  File "/Applications/Komodo IDE 9.app/Contents/Resources/extensions/golang@activestate.com/components/koGoAppInfo.py", line 22, in <module>
    from koAppInfo import KoAppInfoEx
ImportError: No module named koAppInfo
[2015-04-06 15:37:22,386] [ERROR] console-logger: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance] (2) in chrome://golang/content/pref/pref-golang.js:98
Traceback (most recent call last):
  File "chrome://golang/content/pref/pref-golang.js", line 98, in 

[2015-04-06 15:37:30,176] [ERROR] prefs: Could not get preference value from element 'gocodeDefaultLocation'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:261:27
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:597:13
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    doApply@chrome://komodo/content/pref/pref.js:69:12
    oncommand@chrome://komodo/content/pref/pref.xul:1:1

[2015-04-06 15:37:30,177] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:598:19
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    doApply@chrome://komodo/content/pref/pref.js:69:12
    oncommand@chrome://komodo/content/pref/pref.xul:1:1
-- EXCEPTION END --
[2015-04-06 15:37:30,177] [ERROR] prefs: Could not get preference value from element 'godefDefaultLocation'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:261:27
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:597:13
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    doApply@chrome://komodo/content/pref/pref.js:69:12
    oncommand@chrome://komodo/content/pref/pref.xul:1:1

[2015-04-06 15:37:30,177] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:598:19
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    doApply@chrome://komodo/content/pref/pref.js:69:12
    oncommand@chrome://komodo/content/pref/pref.xul:1:1
-- EXCEPTION END --
[2015-04-06 15:37:31,705] [ERROR] prefs: Could not get preference value from element 'gocodeDefaultLocation'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:261:27
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:597:13
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:296:16
    doOk@chrome://komodo/content/pref/pref.js:63:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1

[2015-04-06 15:37:31,705] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:598:19
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:296:16
    doOk@chrome://komodo/content/pref/pref.js:63:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1
-- EXCEPTION END --
[2015-04-06 15:37:31,706] [ERROR] prefs: Could not get preference value from element 'godefDefaultLocation'
Traceback from ERROR in 'prefs' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:261:27
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:597:13
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:296:16
    doOk@chrome://komodo/content/pref/pref.js:63:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1

[2015-04-06 15:37:31,706] [ERROR] prefs: 
-- EXCEPTION START --
Error: Invalid preference
+ stack
    koPrefWindow.prototype._getPrefValueFromElement@chrome://komodo/content/pref/koPrefWindow.js:598:19
    koPrefWindow.prototype._doSavePrefElements@chrome://komodo/content/pref/koPrefWindow.js:881:37
    koPrefWindow.prototype.savesinglepageprefs@chrome://komodo/content/pref/koPrefWindow.js:927:14
    koPrefWindow.prototype.savepageprefs@chrome://komodo/content/pref/koPrefWindow.js:917:18
    koPrefWindow.prototype._onOK@chrome://komodo/content/pref/koPrefWindow.js:260:14
    koPrefWindow.prototype.onApply@chrome://komodo/content/pref/koPrefWindow.js:305:16
    koPrefWindow.prototype.onOK@chrome://komodo/content/pref/koPrefWindow.js:296:16
    doOk@chrome://komodo/content/pref/pref.js:63:10
    oncommand@chrome://komodo/content/pref/pref.xul:1:1
-- EXCEPTION END --
[2015-04-06 15:37:32,415] [ERROR] console-logger: NS_ERROR_XPC_GS_RETURNED_FAILURE: Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService] (2) in resource://gre/modules/PlacesUtils.jsm:1865
Traceback (most recent call last):
  File "resource://gre/modules/PlacesUtils.jsm", line 1865, in 
```

Culprit: https://github.com/Komodo/komodo-go/blob/master/components/koGoAppInfo.py#L22

**Comment by toddw-as** [comment]
Tweaked preferences to properly display the golang preferences
https://github.com/Komodo/komodo-go/commit/b4b583824508340d4926a8d9a15bda2e226273bc

and fixed the bad import of koAppInfo:
https://github.com/Komodo/komodo-go/commit/17ea8cd9be4f9a16bd854467f7fdbf40fc8b132d

**Comment by toddw-as** [comment]
@Naatan @cgchoffman Something to remember (and perhaps fix in the future):

I discovered another problem with the go-lang prefs. Komodo uses a *whitelist* of pref names that are passed to the out-of-process worker, and the golang prefs were not part of that list, so it wouldn't work correctly for what the user set in their preferences.

Fixed in commit:
  https://github.com/Komodo/KomodoIDE/commit/c615bf0 (master)
  https://github.com/Komodo/KomodoIDE/commit/524acde (9.0.1 branch)
  https://github.com/Komodo/KomodoEdit/commit/491da47 (master)
  https://github.com/Komodo/KomodoEdit/commit/cda1f1c (9.0.1 branch)
