### ISSUE TITLE
SDK problem: cannot require('file')

### ISSUE THREAD

**Issue by neurobashing** [Komodo/KomodoEdit#601]
While fiddling with an extension I include a bunch of SDK modules, mostly logging and shell. When I do

```
    var file = require('ko/file');
```

I get the following errors (and the extension code doesn't run):

```
[2015-09-11 15:05:17,505] [ERROR] console-logger: While trying to require("ko/file"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in

[2015-09-11 15:05:17,507] [ERROR] console-logger: TypeError: ko.moreKomodo is undefined (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in

[2015-09-11 15:05:17,510] [ERROR] console-logger: @chrome://komodo/content/sdk/file.js:4:9
@chrome://komodo/content/sdk/file.js:1:1
require@chrome://komodo/content/jetpack.js:154:20
@chrome://gitbranchextension/content/gitbranch.js:13:16
@chrome://gitbranchextension/content/gitbranch.js:10:1
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in

[2015-09-11 15:05:17,512] [ERROR] console-logger: TypeError: ko.moreKomodo is undefined (2) in chrome://komodo/content/sdk/file.js:4
Traceback (most recent call last):
  File "chrome://komodo/content/sdk/file.js", line 4, in
```

**Comment by Naatan** [comment]
The SDK's are basically in beta, they need polish. You can work around this with:

```
var _window = require("ko/windows").getMain();
var koFile = _window.require("ko/file");
```

**Comment by neurobashing** [comment]
same result. This is the 9.2.1 release, FWIW.

**Comment by Naatan** [comment]
Can you give some context, where are you trying to require this module?

**Comment by neurobashing** [comment]
an extension, in the main body of the IIFE. I require() logging, shell, and file; file barfs, shell and logging do fine.

**Comment by neurobashing** [comment]
i moved it into a function (just the file require bit) and it seems to be happier.

**Comment by Naatan** [comment]
Maybe you were calling it before ko.moreKomodo is ready, try hooking it up to a startup event?

**Comment by cgchoffman** [comment]
Not clear if this is actually a bug.  Or was the code called in the wrong place?
