### ISSUE TITLE
CodeIntel produces an error when viewing an image

### ISSUE THREAD

**Issue by ervumlens** [Komodo/KomodoEdit#602]
Viewing an image in Komodo triggers a CodeIntel error.

Here is an example message in the Notifications pane (details vary by image):

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte
                                         Fri Sep 11 2015 14:30:25 GMT-0500 (CDT)
```

Here is the output in the log:

```
[2015-09-11 14:30:25,131] [ERROR] codeintel.oop.driver: 
Traceback (most recent call last):
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 819, in do_scan_document
    buf = driver.get_buffer(request)
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 364, in get_buffer
    encoding=request.get("encoding"))
  File "/home/ervumlens/Komodo-Edit-9/lib/mozilla/python/komodo/codeintel2/manager.py", line 445, in buf_from_path
    content = codecs.open(path, 'rb', encoding).read()
  File "/home/ervumlens/Komodo-Edit-9/lib/python/lib/python2.7/codecs.py", line 668, in read
    return self.reader.read(size)
  File "/home/ervumlens/Komodo-Edit-9/lib/python/lib/python2.7/codecs.py", line 474, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte
```

---

Komodo Edit, version 9.2.1, build 15998, platform linux-x86_64. Built on Wed Sep 2 00:18:45 2015.

**Comment by Naatan** [comment]
Please convert your image to UTF8.

I mean, err.. @mitchell-as ? :p CodeIntel should have cancelled out of this the second it saw the language was not supported and/or the file was binary.

**Comment by mitchell-as** [comment]
Codeintel was designed with only text in mind, so the default language and encoding is Text/UTF-8. Loading images does not change it.
