### ISSUE TITLE
Rx Toolkit not working

### ISSUE THREAD

**Issue by asb-capfan** [Komodo/KomodoEdit#609]
I would like to use the Rx Toolkit. However, it always tells me that "The regular expression is empty."
 
I reinstalled Komodo IDE and PDK, by:
* uninstalling Komodo IDE
* uninstalling PDK
* removing %localappdata%\ActiveState\<Komodo + PDK folders here>
* removing %localappdata%\..\Roaming\ActiveState\*
* installing PDK, latest MSI from my ActiveState account page (Komodo-IDE-9.2.1-87651.msi)
* installing Komodo IDE, latest MSI from my ActiveState account page (PDK-9.4.0.298593-windows.msi)
 
When I started the Rx Toolkit for the very first time, Python was configured as language and it seemed to be working (but I don't have Python installed).
However, as I use Perl only, I switched the language. Since then, it always tells me, that the expression would be empty.
 
Please find attached a screenshot.
 
Is there a way to reset the Rx Toolkit?
Do I need to install Python to use the Rx Toolkit? If yes, what version?

**Comment by cgchoffman** [comment]
Hi @asb-capfan.  Can you please provide the following:
- The screenshot you mentioned
- exact reproduction steps including menus used, keybindinds, buttons clicked on, field names filled in
- error logs: Help > Troubleshooting > View Log File

**Comment by asb-capfan** [comment]
Ah yes, the screenshot:
![rx toolkit not working](https://cloud.githubusercontent.com/assets/131959/9915826/82779780-5cb9-11e5-8531-0d05da57594d.png)

Reproduction:
* re-install as described in the initial post
* start Komodo IDE
* press alt to shot the menu bar
* run Tools > Rx Toolkit
* empty regexp field using crtl + a and then backspace
* empty the other fields in the same manner
* switch language to Perl
* enter search text "asd"
* enter expression "as"

Here is the log file:

	[2015-09-16 21:26:07,404] [INFO] Startup: Welcome to Komodo IDE 9.2.1 build 87651 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
	[2015-09-16 21:26:07,404] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Tue Sep 01 17:19:15 2015
	[2015-09-16 21:26:07,989] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
	[2015-09-16 21:26:08,035] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
		@chrome://komodo/content/komodo.js:15:1

	[2015-09-16 21:26:08,499] [ERROR] console-logger: bad script XDR magic number (0) in :0
	Traceback (most recent call last):
	  File "", line 0, in 

	[2015-09-16 21:26:10,033] [WARNING] root: ko.findresults was already loaded, re-creating it.

	[2015-09-16 21:26:11,242] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
	[2015-09-16 21:26:12,572] [INFO] komodospellchecker: Spell checker loaded.
	[2015-09-16 21:26:12,572] [INFO] komodospellchecker: Using dictionary en-US
	[2015-09-16 21:26:19,828] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
	[2015-09-16 21:26:19,829] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
	[2015-09-16 21:26:26,832] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
	[2015-09-16 21:26:26,834] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by asb-capfan** [comment]
When I checked the log file after opening the Rx Toolkit again, it showed new messages:

	[2015-09-16 21:26:07,404] [INFO] Startup: Welcome to Komodo IDE 9.2.1 build 87651 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
	[2015-09-16 21:26:07,404] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Tue Sep 01 17:19:15 2015
	[2015-09-16 21:26:07,989] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
	[2015-09-16 21:26:08,035] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
		@chrome://komodo/content/komodo.js:15:1

	[2015-09-16 21:26:08,499] [ERROR] console-logger: bad script XDR magic number (0) in :0
	Traceback (most recent call last):
	  File "", line 0, in 

	[2015-09-16 21:26:10,033] [WARNING] root: ko.findresults was already loaded, re-creating it.

	[2015-09-16 21:26:11,242] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
	[2015-09-16 21:26:12,572] [INFO] komodospellchecker: Spell checker loaded.
	[2015-09-16 21:26:12,572] [INFO] komodospellchecker: Using dictionary en-US
	[2015-09-16 21:26:19,828] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
	[2015-09-16 21:26:19,829] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
	[2015-09-16 21:26:26,832] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
	[2015-09-16 21:26:26,834] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
	[2015-09-16 21:30:28,236] [ERROR] process: process.py: can't execute None (C:\Windows\system32\cmd.exe; /c ""c:\perl\bin\perl.exe" "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\rxx\rxx_perl.pl"")
	ERROR:xpcom:Unhandled exception calling 'int8 * RunAndNotify(in wstring, in wstring, in wstring, in unicode &, out retval nsISomething);'
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
		return 0, func(*params)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRunService.py", line 1141, in RunAndNotify
		child = runutils.KoRunProcess(command, cwd=cwd, env=envDict)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\runutils.py", line 150, in __init__
		self._process = process.ProcessOpen(cmd, cwd=cwd, env=env)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\process.py", line 319, in __init__
		creationflags=flags)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\subprocess.py", line 711, in __init__
		errread, errwrite)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\process.py", line 139, in _execute_child
		startupinfo)
	WindowsError: [Error 2] The system cannot find the file specified
	ERROR:xpcom:Unhandled exception calling 'int8 * match(in wstring, in nsISomething, in nsISomething);'
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
		return 0, func(*params)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 806, in match
		self._wrapRequest(requestPacket, options)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 793, in _wrapRequest
		self._runRequest(requestPacket)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 754, in _runRequest
		'', '', requestString)
	  File "<XPCOMObject method 'RunAndNotify'>", line 3, in RunAndNotify
	Exception: 2147500037 (NS_ERROR_FAILURE)
	[2015-09-16 21:30:28,246] [ERROR] rxx: 
	-- EXCEPTION START --
	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxHandler.match]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxResults_Update :: line 2095"  data: no]
	+ toString (function) 3 lines
	+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxHandler.match]'
	+ result (number) 2147500037
	+ name (string) 'NS_ERROR_FAILURE'
	+ filename (string) 'chrome://komodo/content/rxx/rxx.js'
	+ lineNumber (number) 2095
	+ columnNumber (number) 0
	+ inner (object) null
	| + data (object) null
	| + stack (string) 'RxxResults_Update@chrome://komodo/content/rxx/rxx.js:2095:0
	OnLoad@chrome://komodo/content/rxx/rxx.js:1063:8
	onload@chrome://komodo/content/rxx/rxx.xul:1:0
	'
	+ location (object) JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxResults_Update :: line 2095
	| + QueryInterface (function) 3 lines
	| + language (number) 2
	| + languageName (string) 'JavaScript'
	| + filename (string) 'chrome://komodo/content/rxx/rxx.js'
	| + name (string) 'RxxResults_Update'
	| + lineNumber (number) 2095
	| + columnNumber (number) 0
	| + sourceLine (string) ''
	| + caller (object) JS frame :: chrome://komodo/content/rxx/rxx.js :: OnLoad :: line 1063
	| + formattedStack (string) 'RxxResults_Update@chrome://komodo/content/rxx/rxx.js:2095:0
	OnLoad@chrome://komodo/content/rxx/rxx.js:1063:8
	onload@chrome://komodo/content/rxx/rxx.xul:1:0
	'
	| + stack
		RxxResults_Update@chrome://komodo/content/rxx/rxx.js:2095:0
		OnLoad@chrome://komodo/content/rxx/rxx.js:1063:8
		onload@chrome://komodo/content/rxx/rxx.xul:1:0
	-- EXCEPTION END --
	ERROR:xpcom:Unhandled exception calling 'int8 * styleRegex(in nsISomething, in nsISomething, in nsISomething);'
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
		return 0, func(*params)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 539, in styleRegex
		self._style("regex", scimoz, resultsManager)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 493, in _style
		language=self.language)
	AttributeError: koRxxResponseHandler instance has no attribute 'language'
	[2015-09-16 21:30:28,362] [ERROR] rxx: 
	-- EXCEPTION START --
	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxResponseHandler.styleRegex]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxRegex_Restyle :: line 1411"  data: no]
	+ toString (function) 3 lines
	+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxResponseHandler.styleRegex]'
	+ result (number) 2147500037
	+ name (string) 'NS_ERROR_FAILURE'
	+ filename (string) 'chrome://komodo/content/rxx/rxx.js'
	+ lineNumber (number) 1411
	+ columnNumber (number) 0
	+ inner (object) null
	| + data (object) null
	| + stack (string) 'RxxRegex_Restyle@chrome://komodo/content/rxx/rxx.js:1411:12
	'
	+ location (object) JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxRegex_Restyle :: line 1411
	| + QueryInterface (function) 3 lines
	| + language (number) 2
	| + languageName (string) 'JavaScript'
	| + filename (string) 'chrome://komodo/content/rxx/rxx.js'
	| + name (string) 'RxxRegex_Restyle'
	| + lineNumber (number) 1411
	| + columnNumber (number) 12
	| + sourceLine (string) ''
	| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
	| + formattedStack (string) 'RxxRegex_Restyle@chrome://komodo/content/rxx/rxx.js:1411:12
	'
	| + stack
		RxxRegex_Restyle@chrome://komodo/content/rxx/rxx.js:1411:12
	-- EXCEPTION END --
	ERROR:xpcom:Unhandled exception calling 'int8 * styleRegex(in nsISomething, in nsISomething, in nsISomething);'
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
		return 0, func(*params)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 539, in styleRegex
		self._style("regex", scimoz, resultsManager)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 493, in _style
		language=self.language)
	AttributeError: koRxxResponseHandler instance has no attribute 'language'
	[2015-09-16 21:30:28,368] [ERROR] rxx: 
	-- EXCEPTION START --
	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxResponseHandler.styleRegex]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxRegex_Restyle :: line 1411"  data: no]
	+ toString (function) 3 lines
	+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxResponseHandler.styleRegex]'
	+ result (number) 2147500037
	+ name (string) 'NS_ERROR_FAILURE'
	+ filename (string) 'chrome://komodo/content/rxx/rxx.js'
	+ lineNumber (number) 1411
	+ columnNumber (number) 0
	+ inner (object) null
	| + data (object) null
	| + stack (string) 'RxxRegex_Restyle@chrome://komodo/content/rxx/rxx.js:1411:12
	'
	+ location (object) JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxRegex_Restyle :: line 1411
	| + QueryInterface (function) 3 lines
	| + language (number) 2
	| + languageName (string) 'JavaScript'
	| + filename (string) 'chrome://komodo/content/rxx/rxx.js'
	| + name (string) 'RxxRegex_Restyle'
	| + lineNumber (number) 1411
	| + columnNumber (number) 12
	| + sourceLine (string) ''
	| + caller (object) native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
	| + formattedStack (string) 'RxxRegex_Restyle@chrome://komodo/content/rxx/rxx.js:1411:12
	'
	| + stack
		RxxRegex_Restyle@chrome://komodo/content/rxx/rxx.js:1411:12
	-- EXCEPTION END --
	[2015-09-16 21:30:28,737] [ERROR] process: process.py: can't execute None (C:\Windows\system32\cmd.exe; /c ""c:\perl\bin\perl.exe" "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\rxx\rxx_perl.pl"")
	ERROR:xpcom:Unhandled exception calling 'int8 * RunAndNotify(in wstring, in wstring, in wstring, in unicode &, out retval nsISomething);'
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
		return 0, func(*params)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRunService.py", line 1141, in RunAndNotify
		child = runutils.KoRunProcess(command, cwd=cwd, env=envDict)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\runutils.py", line 150, in __init__
		self._process = process.ProcessOpen(cmd, cwd=cwd, env=env)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\process.py", line 319, in __init__
		creationflags=flags)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\subprocess.py", line 711, in __init__
		errread, errwrite)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\komodo\process.py", line 139, in _execute_child
		startupinfo)
	WindowsError: [Error 2] The system cannot find the file specified
	ERROR:xpcom:Unhandled exception calling 'int8 * match(in wstring, in nsISomething, in nsISomething);'
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
		return 0, func(*params)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 806, in match
		self._wrapRequest(requestPacket, options)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 793, in _wrapRequest
		self._runRequest(requestPacket)
	  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koRxx.py", line 754, in _runRequest
		'', '', requestString)
	  File "<XPCOMObject method 'RunAndNotify'>", line 3, in RunAndNotify
	Exception: 2147500037 (NS_ERROR_FAILURE)
	[2015-09-16 21:30:28,743] [ERROR] rxx: 
	-- EXCEPTION START --
	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxHandler.match]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxResults_Update :: line 2095"  data: no]
	+ toString (function) 3 lines
	+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIRxxHandler.match]'
	+ result (number) 2147500037
	+ name (string) 'NS_ERROR_FAILURE'
	+ filename (string) 'chrome://komodo/content/rxx/rxx.js'
	+ lineNumber (number) 2095
	+ columnNumber (number) 0
	+ inner (object) null
	| + data (object) null
	| + stack (string) 'RxxResults_Update@chrome://komodo/content/rxx/rxx.js:2095:0
	scheduleDelayedUpdate/gOnModifiedHandlerTimeoutId<@chrome://komodo/content/rxx/rxx.js:671:8
	'
	+ location (object) JS frame :: chrome://komodo/content/rxx/rxx.js :: RxxResults_Update :: line 2095
	| + QueryInterface (function) 3 lines
	| + language (number) 2
	| + languageName (string) 'JavaScript'
	| + filename (string) 'chrome://komodo/content/rxx/rxx.js'
	| + name (string) 'RxxResults_Update'
	| + lineNumber (number) 2095
	| + columnNumber (number) 0
	| + sourceLine (string) ''
	| + caller (object) JS frame :: chrome://komodo/content/rxx/rxx.js :: scheduleDelayedUpdate/gOnModifiedHandlerTimeoutId< :: line 671
	| + formattedStack (string) 'RxxResults_Update@chrome://komodo/content/rxx/rxx.js:2095:0
	scheduleDelayedUpdate/gOnModifiedHandlerTimeoutId<@chrome://komodo/content/rxx/rxx.js:671:8
	'
	| + stack
		RxxResults_Update@chrome://komodo/content/rxx/rxx.js:2095:0
		scheduleDelayedUpdate/gOnModifiedHandlerTimeoutId<@chrome://komodo/content/rxx/rxx.js:671:8
	-- EXCEPTION END --
	[2015-09-16 21:32:24,487] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
	[2015-09-16 21:32:24,487] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by cgchoffman** [comment]
> [2015-09-16 21:30:28,236] [ERROR] process: process.py: can't execute None (C:\Windows\system32\cmd.exe; /c ""c:\perl\bin\perl.exe" "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\rxx\rxx_perl.pl"")

That could explain it.  The quotes on that line look completely broken.  It wouldn't matter if Komodo wasn't installed in a directory that has spaces in it's parent path.

I have no idea how this would have happened though.  I'm using Komodo 9.2.1 as well and there is no issue.

Could you try running the command manually and see what happens?
`C:\Windows\system32\cmd.exe; /c \""c:\perl\bin\perl.exe" "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\rxx\rxx_perl.pl\"\"`

Note that I escaped the first and last quote in the above string.  Might be worth checking if that path to Perl is correct.

- Carey

**Comment by asb-capfan** [comment]
Running the command as written in the log file seems to work:

    C:\Windows\system32\cmd.exe; /c ""c:\perl\bin\perl.exe" "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\support\rxx\rxx_perl.pl""

After entering "as" + Enter, the following is shown:

	{"status":"matchError","exception":"malformed JSON string, neither array, object
	, number, string or atom, at character offset 0 (before \"as\\n\") at C:\\Progra
	m Files (x86)\\ActiveState Komodo IDE 9\\lib\\support\\rxx\\rxx_perl.pl line 17.
	\n"}

I agree that this is a difficult issue when you cannot reproduce it.

Thus, my initial question:
Is there a way to reset the Rx Toolkit?

I assume that the other one ("Do I need to install Python to use the Rx Toolkit? If yes, what version?") can be safely answered with "no".

**Comment by Naatan** [comment]
You could try starting with a clean profile to see if that makes a difference > 

http://beta.docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings

**Comment by cgchoffman** [comment]
> I agree that this is a difficult issue when you cannot reproduce it.
> 
> Thus, my initial question:
> Is there a way to reset the Rx Toolkit?
> 
> I assume that the other one ("Do I need to install Python to use the Rx Toolkit? If yes, what version?") can be safely answered with "no".

Sorry, skipped over those Q's in my head.  Resetting your profile as you've done would reset everything, including the RX tool.  DO try @Naatan's suggestion still as Komodo will import your old profile and could be causing the issue.

No, you don't need to install Python to run the Rx tool.

**Comment by asb-capfan** [comment]
I followed the instructions on http://beta.docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings and created a temporary new profile. However, the Rx Dialog is still stuck. 

I honestly don't want to fully reset Komodo IDE again. I always have to set up my preferences again.

Isn't there anything in the logs that does point you to the error?
Starting komodo.exe -v shows the following:

![06-10-2015 17-09-56 komodo-v](https://cloud.githubusercontent.com/assets/131959/10312858/2ec9c420-6c4d-11e5-91fb-dcb348691402.png)

**Comment by cgchoffman** [comment]
Are those logs from after you've reproduced the issue?  Also, could you attached them as a text file or just paste here?  Images are very limiting.

**Comment by asb-capfan** [comment]
Unfortunately, the verbose log in the console windows could not be copied, as the window was still used for output. That's why I made a screenshot. But I totally agree, it's very limiing.

I have good news for now. It works, the problem does not exist anymore.
As there was messages about plugins and such, I decided to do a new clean installation (again), but this time, I also uninstalled FireFox. Here is some more detail on what I did:

* uninstalling Komodo IDE
* uninstalling PDK
* uninstalling Firefox
* removing %localappdata%\ActiveState<Komodo + PDK folders here>
* removing %localappdata%..\Roaming\ActiveState*
* removing all Firefox localappdata and appdata folders
* removed all orphaned installation folders, if any
* I also found some dubious "virtualstore" folders. No idea where they came from. I removed the folder entirely
* installing PDK, latest MSI from my ActiveState account page
* installing Komodo IDE, latest MSI from my ActiveState account page
* installing Firefox

Now, the Rx Toolkit works again. Event switching the language to Perl worked. Also, I can run external commands again, like a custom command for the PerlTidy source code formatter.

I guess this is the tip that is subsumed under "please reinstall you PC", as I was told by EA suppoer when raising a support issue some time ago.

HTH

**Comment by cgchoffman** [comment]
> Unfortunately, the verbose log in the console windows could not be copied,

This shouldn't prevent you from getting the logs.  Click the Icon in the top left of the Window (should be a Komodo icon) > Edit > Select All then right click to copy to clipboard.  That's a little dependent on your console preferences too...Regardless, you can always copy from the CMD.  It locks the terminal and stops the process so you can copy.  Google might be a better resource for more information on that.
THanks for the info about working around this!
