### ISSUE TITLE
Addons.xpi: Can't drag and drop *.xpi in build 87842

### ISSUE THREAD

**Issue by cgchoffman** [Komodo/KomodoEdit#650]
Komodo IDE, version 9.3.0, build 87842, platform win32-x86.
Built on Wed Sep 30 10:13:17 2015.

Pasting logs below.  One error right off the bat with http inspector.  Then at the bottom is the error when I drop an xpi on KOmodo

```
[2015-10-01 12:12:48,130] [INFO] Startup: Welcome to Komodo IDE 9.3.0 build 8784
2 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2015-10-01 12:12:48,131] [INFO] Startup: C:\Users\careyh\Komodo IDE 9.3.0 night
ly\lib\mozilla\komodo.exe built on Wed Sep 30 10:13:17 2015
1443726769184   addons.xpi      WARN    addMetadata: Add-on httpinspector@Active
State.com is invalid: Error: Invalid addon ID: expected addon ID httpinspector@A
ctiveState.com, found httpinspector@activestate.com in manifest (resource://gre/
modules/addons/XPIProvider.jsm:3167:16) JS Stack trace: addMetadata@XPIProvider.
jsm:3167:17 < XPI_processFileChanges@XPIProvider.jsm:3441:23 < XPI_checkForChang
es@XPIProvider.jsm:3602:34 < XPI_startup@XPIProvider.jsm:2090:25 < callProvider@
AddonManager.jsm:208:12 < _startProvider@AddonManager.jsm:667:5 < AMI_startup@Ad
donManager.jsm:821:9 < AMP_startup@AddonManager.jsm:2399:5 < AMC_observe@addonMa
nager.js:55:7
1443726769216   addons.xpi      WARN    Could not uninstall invalid item from lo
cked install location
[2015-10-01 12:12:50,025] [WARNING] console-logger: mutating the [[Prototype]] o
f an object will cause your code to run very slowly; instead create the object w
ith the correct initial [[Prototype]] value using Object.create (1) in resource:
//gre/modules/Preferences.jsm:381
[2015-10-01 12:12:50,069] [WARNING] console-logger: Ignoring obsolete chrome reg
istration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/careyh/AppDat
a/Local/ActiveState/KomodoIDE/9.3/XRE/extensions/inspector@mozilla.org/chrome.ma
nifest:16
[2015-10-01 12:12:50,084] [WARNING] console-logger: Ignoring obsolete chrome reg
istration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///C:/Users/careyh/A
ppData/Local/ActiveState/KomodoIDE/9.3/XRE/extensions/emmet@chikuyonok.ru.xpi!/c
hrome.manifest:1
[2015-10-01 12:12:50,447] [WARNING] root: ko.logging has been converted to a Com
monJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-10-01 12:12:53,453] [WARNING] console-logger: mutating the [[Prototype]] o
f an object will cause your code to run very slowly; instead create the object w
ith the correct initial [[Prototype]] value using Object.create (1) in file:///C
:/Users/careyh/Komodo%20IDE%209.3.0%20nightly/lib/mozilla/components/koamAddonMa
nager.js:138
[2015-10-01 12:13:39,210] [WARNING] keybindings: [Ctrl+Shift+U] was used for 'cm
d_convertLowerCase', overriding to use 'cmd_scope-sections'
[2015-10-01 12:13:42,180] [DEBUG] editorconfig: Setting editorconfig: {"encoding
Default": "utf-8", "cleanLineEnds": true, "tabWidth": 4, "ensureFinalEOL": true,
 "indentWidth": 4, "useTabs": false, "endOfLine": "LF"}
Failed to load the Python module: 'C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\
mozilla\components\koCVS.py'

Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\python\xpcom\server
\loader.py", line 134, in loadModule
    return self._getCOMModuleForLocation(aLocalFile)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\python\xpcom\server
\loader.py", line 158, in _getCOMModuleForLocation
    py_mod = loader.load_module( module_name_in_sys, stuff )
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\python\lib\ihooks.py", line
 272, in load_module
    m = self.hooks.load_source(name, filename, file)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\python\lib\ihooks.py", line
 170, in load_source
    return imp.load_source(name, filename, file)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\components\koCVS.py
", line 11, in <module>
    import cvslib
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\python\komodo\cvsli
b.py", line 78, in <module>
    parser_re.append(re.compile(r))
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\python\lib\re.py", line 190
, in compile
    return _compile(pattern, flags)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\python\lib\re.py", line 242
, in _compile
    raise error, v # invalid expression
<class 'sre_constants.error'>: nothing to repeat
[2015-10-01 12:13:43,095] [ERROR] koFileStatusService: Unable to load 'cvs' stat
us checker: '@activestate.com/koFileStatusChecker?type=cvs;1'
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\components\koFileSt
atusService.py", line 158, in init
    createInstance(components.interfaces.koIFileStatusChecker)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\python\xpcom\compon
ents.py", line 192, in createInstance
    raise xpcom.COMException(details.errno, "No such component '%s'" % (self.con
tractid,))
Exception: 2147746132 (No such component '@activestate.com/koFileStatusChecker?t
ype=cvs;1')
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2015-10-01 12:13:46,655] [ERROR] SCC: Unable to get cvs scc component
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETU
RNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RET
URNED_FAILURE)"  location: "JS frame :: chrome://komodo/content/scc/scc.js :: Ko
SccGetAvailableSCCComponents :: line 264"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS
_RETURNED_FAILURE) [nsIJSCID.getService]'
+ result (number) 2153185302
+ name (string) 'NS_ERROR_XPC_GS_RETURNED_FAILURE'
+ filename (string) 'chrome://komodo/content/scc/scc.js'
+ lineNumber (number) 264
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'KoSccGetAvailableSCCComponents@chrome://komodo/content/scc/s
cc.js:264:34
peSCC.prototype.supportsCom'...561 chars
+ location (object) JS frame :: chrome://komodo/content/scc/scc.js :: KoSccGetAv
ailableSCCComponents :: line 264
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/scc/scc.js'
| + name (string) 'KoSccGetAvailableSCCComponents'
| + lineNumber (number) 264
| + columnNumber (number) 34
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/project/peSCC.js :: peSC
C.prototype.supportsCommand :: line 155
| + formattedStack (string) 'KoSccGetAvailableSCCComponents@chrome://komodo/cont
ent/scc/scc.js:264:34
peSCC.prototype.supportsCom'...561 chars
| + stack
    KoSccGetAvailableSCCComponents@chrome://komodo/content/scc/scc.js:264:34
    peSCC.prototype.supportsCommand@chrome://komodo/content/project/peSCC.js:155
:33
    projectExtensionManager.prototype.isCommandEnabled@chrome://komodo/content/p
roject/projectExtensionManager.js:272:11
    _command_updateCommand@chrome://komodo/content/library/commands.js:72:22
    command_updateCommandset@chrome://komodo/content/library/commands.js:92:17
    oncommandupdate@chrome://komodo/content/komodo.xul:1:0
    run_delayed_update_commands@chrome://komodo/content/library/performance_twea
ks.js:28:16
-- EXCEPTION END --
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2015-10-01 12:13:47,489] [WARNING] root: ko.findresults was already loaded, re-
creating it.

[2015-10-01 12:13:48,134] [ERROR] console-logger: While trying to require("spell
check/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2015-10-01 12:13:48,161] [ERROR] console-logger: Module `spellcheck/spellcheck`
 is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in
 chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2015-10-01 12:13:48,187] [ERROR] console-logger: require@chrome://komodo/conten
t/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1142:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in

** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2015-10-01 12:13:48,982] [INFO] komodospellchecker: Spell checker loaded.
[2015-10-01 12:13:48,986] [INFO] komodospellchecker: Using dictionary en-US

[2015-10-01 12:13:49,861] [ERROR] koToolbox2: After walking the dir, id(C:\Users
\careyh\AppData\Local\ActiveState\KomodoIDE\9.3\tools) is None
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
[2015-10-01 12:13:50,454] [ERROR] koToolbox2: After walking the dir, id(C:\Progr
amData\ActiveState\KomodoIDE\9.3\tools) is None
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
Exception in thread Index Builder:
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\python\lib\threading.py", l
ine 808, in __bootstrap_inner
    self.run()
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\python\lib\threading.py", l
ine 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\extensions\scope-do
cs@activestate.com\components\koScopeDocs.py", line 143, in _preload
    indexer.build(name=name, path=path)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\extensions\scope-do
cs@activestate.com\components\koScopeDocs.py", line 536, in build
    ''', (str(docId),))
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\extensions\scope-do
cs@activestate.com\components\koScopeDocs.py", line 198, in query
    return self.cursor.execute(query, args)
OperationalError: no such table: entry_search

[2015-10-01 12:13:50,986] [ERROR] koToolbox2: After walking the dir, id(C:\Users
\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\extensions\railstools@activestate.c
om\tools) is None
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
ERROR:xpcom:Unhandled exception calling 'int8 * getStandardToolboxID(out retval
int32);'
TypeError: int() argument must be a string or a number, not 'NoneType'
ERROR:xpcom:Unhandled exception calling 'int8 * initialize(in nsISomething);'
Traceback (most recent call last):
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\python\xpcom\server
\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Users\careyh\Komodo IDE 9.3.0 nightly\lib\mozilla\components\koToolbo
x2HTreeView.py", line 229, in initialize
    self._std_toolbox_id = self.toolbox2Svc.getStandardToolboxID()
  File "<XPCOMObject method 'getStandardToolboxID'>", line 3, in getStandardTool
boxID
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-10-01 12:13:51,516] [ERROR] ko.widgets:
-- EXCEPTION START --
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [k
oIToolbox2HTreeView.initialize]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  loc
ation: "JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: Toolbox2Manag
er.prototype.initialize :: line 71"  data: no]
+ toString (function) 3 lines
+ message (string) 'Component returned failure code: 0x80004005 (NS_ERROR_FAILUR
E) [koIToolbox2HTreeView.initialize]'
+ result (number) 2147500037
+ name (string) 'NS_ERROR_FAILURE'
+ filename (string) 'chrome://komodo/content/toolbox/toolbox2.js'
+ lineNumber (number) 71
+ columnNumber (number) 0
+ inner (object) null
| + data (object) null
| + stack (string) 'Toolbox2Manager.prototype.initialize@chrome://komodo/content
/toolbox/toolbox2.js:71:4
this.onload@ch'...366 chars
+ location (object) JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: T
oolbox2Manager.prototype.initialize :: line 71
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/toolbox/toolbox2.js'
| + name (string) 'Toolbox2Manager.prototype.initialize'
| + lineNumber (number) 71
| + columnNumber (number) 4
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/toolbox/toolbox2.js :: t
his.onload :: line 223
| + formattedStack (string) 'Toolbox2Manager.prototype.initialize@chrome://komod
o/content/toolbox/toolbox2.js:71:4
this.onload@ch'...366 chars
| + stack
    Toolbox2Manager.prototype.initialize@chrome://komodo/content/toolbox/toolbox
2.js:71:4
    this.onload@chrome://komodo/content/toolbox/toolbox2.js:223:4
    window.onload/<@chrome://komodo/content/komodo.js:494:45
    koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.
js:234:16
    WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:14
-- EXCEPTION END --
** [Bugsnag] Notifying https://notify.bugsnag.com of exception
*** Error in logger.exception: ReferenceError: require is not defined
Toolbox2Manager.prototype.initialize@chrome://komodo/content/toolbox/toolbox2.js
:71:4
this.onload@chrome://komodo/content/toolbox/toolbox2.js:223:4
window.onload/<@chrome://komodo/content/komodo.js:494:45
koWidgetManager__widgetLoadCallback@chrome://komodo/content/library/widgets.js:2
34:16
WidgetLoad_onStateChange@chrome://komodo/content/bindings/pane.xml:2443:14

1443726867041   addons.xpi-utils        WARN    XPI Database callback failed: [E
xception... "aUri must be a non-empty string"  nsresult: "0x80070057 (NS_ERROR_I
LLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/AddonManager.jsm :
: AMI_escapeAddonURI :: line 1152"  data: no] Stack trace: AMI_escapeAddonURI()@
resource://gre/modules/AddonManager.jsm:1152 < AM_escapeAddonURI()@resource://gr
e/modules/AddonManager.jsm:2892 < escapeAddonURI()@resource://gre/modules/addons
/XPIProvider.jsm:1244 < UpdateChecker()@resource://gre/modules/addons/XPIProvide
r.jsm:6062 < initLocalInstall_getVisibleAddon()@resource://gre/modules/addons/XP
IProvider.jsm:4912 < makeSafe/<()@resource://gre/modules/addons/XPIProvider.jsm
-> resource://gre/modules/addons/XPIProviderUtils.js:146 < getRepositoryAddon()@
resource://gre/modules/addons/XPIProvider.jsm -> resource://gre/modules/addons/X
PIProviderUtils.js:127 < this.XPIDatabase.getAddon/<()@resource://gre/modules/ad
dons/XPIProvider.jsm -> resource://gre/modules/addons/XPIProviderUtils.js:1071 <
 Handler.prototype.process()@resource://gre/modules/Promise.jsm -> resource://gr
e/modules/Promise-backend.js:865 < this.PromiseWalker.walkerLoop()@resource://gr
e/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:744 < <file:u
nknown>
[2015-10-01 12:15:11,740] [WARNING] console-logger: Key event not available on G
TK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul
:0
[2015-10-01 12:15:20,020] [WARNING] console-logger: Key event not available on G
TK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul
:0
[2015-10-01 12:15:20,085] [WARNING] console-logger: Key event not available on s
ome keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/con
tent/komodo.xul:0
```

**Comment by mitchell-as** [comment]
@cghoffman I cannot reproduce on my nightly Linux box. Does this still happen with the latest nightly on your Windows machine?

**Comment by cgchoffman** [comment]
No, i can't repro any more.  It might have been my corrupted profile causing issues for me.
