### ISSUE TITLE
changing file EOL changes global EOL settings

### ISSUE THREAD

**Issue by babobski** [Komodo/KomodoEdit#717]
if im not mistaking there is a bug in the file preferences, i noticed when i changed the line endings in the file preferences menu the global line endings settings are changed also.

**Comment by Xotic750** [comment]
Not seeing this on v9.2.1.  if I change the current file preference then it changes for the current file but  the global preference does not change. Perhaps a recording of the issue would help, along with the version of Komodo Edit that you are using.

**Comment by babobski** [comment]
Using the latest 9.3 nightly (edit), also tested it on komodo 9.1 but there its working like it should be.
Tried to make a screen capture with camstudio but didn't get it to work

**Comment by babobski** [comment]
got these errors in my log 
<pre>
[2015-10-11 12:14:18,776] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-10-11 12:14:21,729] [ERROR] console-logger: ReferenceError: log is not defined (2) in chrome://komodo/content/pref/project.xul:242
Traceback (most recent call last):
  File "chrome://komodo/content/pref/project.xul", line 242, in 
</pre>

**Comment by babobski** [comment]
Renamed my 9.3 folder to see if starting with a fresh profile resolved the problem, but it didn't

**Comment by Defman21** [comment]
Komodo imports your settings from older profiles (9.2, 9.1, etc.)

**Comment by mitchell-as** [comment]
Sorry, but I'm not seeing this in 9.3 nightly with a clean profile.

**Comment by babobski** [comment]
hmm, strange renamed my user profile this morning at work to fix #705 but having the same problem as at home, changing the file EOL settings changes the global EOL settings. Got almost identical errors in my log 
<pre>
[2015-10-12 16:44:58,834] [WARNING] views: Inconsistent view count in view_opened event
[2015-10-12 16:45:05,453] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-10-12 16:45:20,911] [ERROR] koLintService: unexpected internal error checking 'default.less' with 'Less' linter
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 617, in run
    request.koDoc.new_line_endings)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 538, in _addMixedEOLWarnings
    results.addResult(r)
AttributeError: 'NoneType' object has no attribute 'addResult'
[2015-10-12 16:45:29,513] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-12 16:45:29,513] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-12 16:46:03,394] [ERROR] koLintService: unexpected internal error checking 'default.less' with 'Less' linter
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 617, in run
    request.koDoc.new_line_endings)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\components\koLintService.py", line 538, in _addMixedEOLWarnings
    results.addResult(r)
AttributeError: 'NoneType' object has no attribute 'addResult'
</pre>
Some idea wath i can do some more to debug this problem?

**Comment by Naatan** [comment]
Could you try recreating your project and then seeing if the issue reproduces? From the errors I'm seeing it seems as if your project may have some issues.

**Comment by babobski** [comment]
Created a new test project with one file, but im having the same problem here, noticed when i save my file preferences and drop a file in komodo to open, i get this warning in my error log.
<pre>
[2015-10-12 20:01:58,247] [WARNING] prefs: The '1' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,249] [WARNING] prefs: The 'hasFocus' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,250] [WARNING] prefs: The 'opened_projects_v7' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,250] [WARNING] prefs: The 'current_project' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,255] [WARNING] prefs: The 'topview' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,256] [WARNING] prefs: The 'windowNum' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,256] [WARNING] prefs: The 'restoreOnRestart' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,256] [WARNING] prefs: The 'timestamp' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,257] [WARNING] prefs: The 'history_rctabs' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:01:58,257] [WARNING] prefs: The 'rctabs_list' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
</pre>
When i go to my preferences and there save the EOL settings i get the same error, if drop a file in komodo.
<pre>
[2015-10-12 20:06:24,148] [WARNING] prefs: The '1' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,148] [WARNING] prefs: The 'hasFocus' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,150] [WARNING] prefs: The 'opened_projects_v7' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,150] [WARNING] prefs: The 'current_project' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,154] [WARNING] prefs: The 'topview' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,154] [WARNING] prefs: The 'windowNum' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,155] [WARNING] prefs: The 'restoreOnRestart' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,155] [WARNING] prefs: The 'timestamp' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,157] [WARNING] prefs: The 'history_rctabs' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
[2015-10-12 20:06:24,157] [WARNING] prefs: The 'rctabs_list' preference has changed while the pref window was open. If you get this message, a pref panel is incorrectly modifying prefs and the modified value will be lost.
</pre>

**Comment by babobski** [comment]
updated to the latest nightly, and having the same problem. a other error i have in my log file, posible related:
<pre>
[2015-10-15 15:56:42,707] [ERROR] editorconfig: Invalid filename specified
[2015-10-15 15:56:42,713] [ERROR] editorconfig: Exception while parsing editorconfig
-- EXCEPTION START --
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
+ stack
    viewChanged@chrome://editorconfig/content/editorconfig.js:24:21
-- EXCEPTION END --
</pre>
And i got a new one about projects:
<pre>
[2015-10-15 15:58:12,921] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-10-15 15:58:17,957] [ERROR] project-xul: 
-- EXCEPTION START --
TypeError: project is null
+ stack
    ManagerClass.prototype.moveToProjectDir@chrome://komodo-places/content/places.js:2929:13
    onApplied/<@chrome://komodo/content/pref/project.xul:240:17
    openDialogWrap@chrome://komodo/content/komodo.js:590:19
    peFile_Properties@chrome://komodo/content/project/peFile.js:361:13
    viewManager.prototype.do_cmd_editPrefsCurrent@chrome://komodo/content/views.js:2273:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
    command_doCommand@chrome://komodo/content/library/commands.js:263:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:13
-- EXCEPTION END --
[2015-10-15 15:58:22,918] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-15 15:58:22,918] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-15 15:58:26,342] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-10-15 15:58:29,013] [ERROR] project-xul: 
-- EXCEPTION START --
TypeError: project is null
+ stack
    ManagerClass.prototype.moveToProjectDir@chrome://komodo-places/content/places.js:2929:13
    onApplied/<@chrome://komodo/content/pref/project.xul:240:17
    openDialogWrap@chrome://komodo/content/komodo.js:590:19
    peFile_Properties@chrome://komodo/content/project/peFile.js:361:13
    viewManager.prototype.do_cmd_editPrefsCurrent@chrome://komodo/content/views.js:2273:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
    command_doCommand@chrome://komodo/content/library/commands.js:263:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:13
-- EXCEPTION END --
[2015-10-15 15:58:48,427] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 

[2015-10-15 15:58:53,536] [ERROR] project-xul: 
-- EXCEPTION START --
TypeError: project is null
+ stack
    ManagerClass.prototype.moveToProjectDir@chrome://komodo-places/content/places.js:2929:13
    onApplied/<@chrome://komodo/content/pref/project.xul:240:17
    openDialogWrap@chrome://komodo/content/komodo.js:590:19
    peFile_Properties@chrome://komodo/content/project/peFile.js:361:13
    viewManager.prototype.do_cmd_editPrefsCurrent@chrome://komodo/content/views.js:2273:5
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:9
    command_doCommand@chrome://komodo/content/library/commands.js:263:1
    command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:13
-- EXCEPTION END --
[2015-10-15 15:59:25,798] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 
</pre>

**Comment by Naatan** [comment]
Is this edit or IDE?

**Comment by babobski** [comment]
in edit

**Comment by babobski** [comment]
i think the project is null had something to do with my user profile, experienced some problems with the places wouldn't stop opening projects. When i renamed my 9.3 folder this problem went away.
Just home form work and updated here to the latest nightly. But I'm not seeing the project is null error.
But for the rest I'm getting the same errors as above.
I've got one error line that i didn't see before.
<pre>
[2015-10-15 17:54:33,023] [ERROR] console-logger: TypeError: part is null (2) in chrome://komodo-places/content/project_places_SPV.js:261
Traceback (most recent call last):
  File "chrome://komodo-places/content/project_places_SPV.js", line 261, in 

[2015-10-15 17:54:45,882] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND:  (2) in chrome://komodo/content/pref/koFilteredPrefTree.js:681
Traceback (most recent call last):
  File "chrome://komodo/content/pref/koFilteredPrefTree.js", line 681, in 
</pre>

**Comment by Naatan** [comment]
Could you see if you have the same issues with IDE?

**Comment by babobski** [comment]
just downloaded the trail version, here i also have the same issue when switching my files EOL the one in the prefrerences also changed. also had the same error as #559 at home in the previous nightly, only when opening a specifc project.
In ide i get less errors as in my edit, not seeing any of the errors above

my error log in ide
<pre>
[2015-10-15 18:47:32,000] [INFO] Startup: Welcome to Komodo IDE 9.2.1 build 87651 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2015-10-15 18:47:32,000] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Tue Sep 01 17:19:15 2015
[2015-10-15 18:47:32,891] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-10-15 18:47:32,891] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=no'. (1) in file:///C:/Users/Administrator/AppData/Local/ActiveState/KomodoIDE/9.2/XRE/extensions/inspector@mozilla.org/chrome.manifest:16
[2015-10-15 18:47:32,891] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///C:/Users/Administrator/AppData/Local/ActiveState/KomodoIDE/9.2/XRE/extensions/emmet@chikuyonok.ru.xpi!/chrome.manifest:1
[2015-10-15 18:47:33,062] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-10-15 18:47:34,173] [WARNING] console-logger: Use of Mutation Events is deprecated. Use MutationObserver instead. (1) in chrome://komodo/content/bindings/scrolltabs.xml:777
[2015-10-15 18:47:34,187] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
[2015-10-15 18:47:35,328] [ERROR] console-logger: TypeError: this.tabbox.selectedPanel is null (2) in chrome://komodo/content/bindings/scrolltabs.xml:862
Traceback (most recent call last):
  File "chrome://komodo/content/bindings/scrolltabs.xml", line 862, in 

[2015-10-15 18:47:36,109] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-10-15 18:47:37,750] [INFO] komodospellchecker: Spell checker loaded.
[2015-10-15 18:47:37,750] [INFO] komodospellchecker: Using dictionary en-US
[2015-10-15 18:47:37,861] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.append] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:98
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 98, in 

[2015-10-15 18:49:20,835] [DEBUG] extensions.markdown: onviewchanged: it's a markdown file with no preview
[2015-10-15 18:49:20,835] [DEBUG] extensions.markdown: openPopup
[2015-10-15 18:49:25,756] [DEBUG] extensions.markdown: hidePopup
[2015-10-15 18:50:10,838] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-10-15 18:50:10,884] [DEBUG] extensions.markdown: hidePopup
[2015-10-15 18:50:11,884] [ERROR] koPHPLinter: Error getting phpInfoEx.version.  Is a PHP interpreter defined?
[2015-10-15 18:51:08,684] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-10-15 18:51:08,684] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-10-15 18:51:08,684] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-10-15 18:51:13,420] [WARNING] console-logger: Key event not available on some keyboard layouts: key="b" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-15 18:51:13,434] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-15 18:51:13,434] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-10-15 18:52:12,298] [DEBUG] extensions.markdown: hidePopup
[2015-10-15 18:52:14,500] [DEBUG] extensions.markdown: onviewchanged: it's a markdown file with no preview
[2015-10-15 18:52:14,500] [DEBUG] extensions.markdown: hidePopup
[2015-10-15 18:52:14,500] [DEBUG] extensions.markdown: openPopup
[2015-10-15 18:52:27,627] [DEBUG] extensions.markdown: hidePopup
</pre>

**Comment by Naatan** [comment]
Thanks for checking, that indicates we may have missed a merge or screwed one up. Will dig, thanks!

**Comment by babobski** [comment]
Of course, no problem.
