### ISSUE TITLE
Indicate when automatic push to place is ready (publishing)

### ISSUE THREAD

**Issue by csimpi** [Komodo/KomodoEdit#731]
I developing a local project, and push project files automatically to remote place after save (i checked the option in the publishing setup window). 
I would like to know when the pushing done.

**Comment by Naatan** [comment]
This should be as simple as adding a notify call, so I'll see about doing that for 9.3. If it ends up being more complex I'll have to bump it.

**Comment by Naatan** [comment]
It appears a notification should already be sent for this. Make sure you have "Publishing" enabled under Prefs > Notifications.

**Comment by csimpi** [comment]
Its checked but i dont get notification

**Comment by Naatan** [comment]
Could you explain your workflow, as well as the exact moment that you would like to be notified?

**Comment by csimpi** [comment]
I have to save my work and check my changes to the remote site.
When i modify a source, i have to refresh my browser recursively and check the changes saved or not. Sometimes i cant decide i see the old version or the new saved version, because i cant figure out the automatic remote publish was successfull or not.

Unfortunatelly the auto publishing cant push the file very very frequently, and i dont understand why i cant see my last changes on the website. The auto publishing have to alert me if the push was successsfull or not.

Sometimes after manual Pushing i give a message: There is no changes, but when i start a syncronisation progress, it seems the remote file and the local file different, and i have to relosve diff manually, i have to overwrite the remote file with local file.

There is a lot of problem with auto pushing with me, but i think this is because the internet is poor here. 
The solution is: Komodo have to check after push or pull publishing and compare the remote and local file hash, and notify the user if it was okay or not.

**Comment by Naatan** [comment]
Ok, this is a bit more involved than adding a single notification it seems. We'll have a look into this for Komodo 10: Improve auto-publishing feedback.

**Comment by cgchoffman** [comment]
> There is a lot of problem with auto pushing with me, but i think this is because the internet is poor here. 
> The solution is: Komodo have to check after push or pull publishing and compare the remote and local file hash, and notify the user if it was okay or not.

This should be indicated by the publishing icons on your files.  Those will update to indicate if the file is or is not synced up with the remote.  Are these not working for you?

**Comment by cgchoffman** [comment]
> Those will update to indicate if the file is or is not synced up with the remote. Are these not working for you?

Looks publishing icons aren't working.  They aren't updating:
- Places and tabs never changes state
- Open Files never gets a Publishing icon

@csimpi if that was working, would that be the functionality you're requesting?  These icons on the file would tell you if a file had been synced successfully or not and you would not need to continuously manually check.  I'd like to change the bug title if possible otherwise i'll file a new one.

**Comment by csimpi** [comment]
This should be indicated by the publishing icons on your files. Those will update to indicate if the file is or is not synced up with the remote. Are these not working for you?

No, sometimes the icon indicates the difference, but after i Pushed (ctrl+p,p) the indicate icon hide, but the remote file doesnt change. 
I can upload the file only with the full resync function.

One more thing: If the icon indicates the difference and i Push a file, the icon hide, and if i try to Push again i give a message: There's no differences.

These things happens frequently, next time i will capture a video.

**Comment by csimpi** [comment]
Maybe this helps:

ERROR:xpcom:Unhandled exception calling 'int8 * run();'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\components.py", line 237, in run
    self.result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\extensions\publishing@ActiveState.com\components\koRemoteTransfer.py", line 64, in notifyResult
    self.callback.callback(result, message)
  File "<XPCOMObject method 'callback'>", line 3, in callback
Exception: 2153185313 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)
[2015-10-19 02:56:42,648] [ERROR] console-logger: TypeError: this.tree is null (2) in chrome://publishing/content/publish-dialog.js:546
Traceback (most recent call last):
  File "chrome://publishing/content/publish-dialog.js", line 546, in 

Exception in thread Thread-6379:
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\python\lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\extensions\publishing@ActiveState.com\components\koRemoteTransfer.py", line 408, in run
    str(ex));
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\components.py", line 263, in wrapperFn
    threadMgr.mainThread.dispatch(method, dispatch_flags)
  File "<XPCOMObject method 'dispatch'>", line 3, in dispatch
Exception: 2147500037 (NS_ERROR_FAILURE)

[2015-10-19 03:35:54,138] [ERROR] koFTPConnection: FTP CLOSE ERROR: 421 Idle timeout (600 seconds): closing control connection
[2015-10-19 13:27:49,510] [ERROR] koFTPConnection: FTP CLOSE ERROR: 421 Idle timeout (600 seconds): closing control connection
[2015-10-19 21:40:27,575] [ERROR] koFTPConnection: FTP CLOSE ERROR: 421 Idle timeout (600 seconds): closing control connection
[2015-10-19 22:43:44,605] [ERROR] koFTPConnection: FTP CLOSE ERROR: 421 Idle timeout (600 seconds): closing control connection
[2015-10-20 00:14:04,352] [ERROR] koFTPConnection: FTP CLOSE ERROR: 421 Idle timeout (600 seconds): closing control connection
[2015-10-20 00:41:29,510] [ERROR] koCodeIntel:     INFO: eval 'INPUT' at patient_profile.php#650  <Trigger 'php-complete-array-members' at 24937>
    INFO: _hit_from_citdl:: expr: 'INPUT', scoperef: (<blob 'patient_profile.php'>, [])

**Comment by Naatan** [comment]
Are you running Komodo 9.2.1?

**Comment by csimpi** [comment]
Komodo IDE, version 9.2.1, build 87651, platform win32-x86. Built on Tue Sep 01 17:19:15 2015.

**Comment by Naatan** [comment]
Ok, I think those errors are just reflecting what you said already; an unstable connection. Not a whole lot we can do about that (besides polishing the error messages).

**Comment by csimpi** [comment]
Ok, thx. But! When i try to repush the file, Komodo says There's no changes, this is real bug, you should fix that in the next version. (i think the solution is the force Push function)

**Comment by Naatan** [comment]
Would you mind opening a separate bug for that? We'll keep this one about the UX / user feedback.
