### ISSUE TITLE
Komodo Edit, version 9.3.0, build 16280 - Addons window

### ISSUE THREAD

**Issue by Piniol** [Komodo/KomodoEdit#745]
When selecting from menu Tools->Addons nothing happens, addons window should popup.

**Comment by mitchell-as** [comment]
We've deprecated the old package manager in favor of commando. When you select "Tools > Addons", commando should pop up with the list of installed packages. Is this not the case for you? You should not expect to see a separate window.

**Comment by Piniol** [comment]
Commando does not pop up. Is it possible that it doesnt work because i've disabled some extensions? If yes, how can I enable them now?

**Comment by Naatan** [comment]
Could you share a full error log? Help > Troubleshooting > View Log File.

You can still access the old dialog by executing the following code in the Console (bottom pane):

```
ko.windowManager.openOrFocusDialog("chrome://mozapps/content/extensions/extensions.xul", "Addons:Manager");
```

See if you have anything disabled there that shouldn't be. Note that addon enabling/disabling will disappear in Komodo 9.3.

**Comment by Piniol** [comment]
Log:
```
[2015-10-22 07:59:06,427] [INFO] Startup: Welcome to Komodo Edit 9.3.0 build 16280 (platform win32-x86, running on Windows post2012Server version 6.3.9600)
[2015-10-22 07:59:06,428] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 9 nightly\lib\mozilla\komodo.exe built on Thu Oct 15 10:39:50 2015
[2015-10-22 07:59:22,835] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-10-22 07:59:23,709] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-10-22 07:59:29,164] [ERROR] console-logger: TypeError: redeclaration of const CC (2) in chrome://xtk/content/xtk.js:52
Traceback (most recent call last):
  File "chrome://xtk/content/xtk.js", line 52, in 

[2015-10-22 07:59:32,933] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-10-22 07:59:33,921] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2015-10-22 07:59:48,523] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 07:59:48,523] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 07:59:48,523] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 07:59:48,523] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 07:59:48,523] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 07:59:48,525] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 07:59:48,525] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 07:59:48,525] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 07:59:50,663] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 07:59:50,663] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 07:59:50,663] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 07:59:50,663] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 07:59:50,664] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 07:59:50,664] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 07:59:50,664] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 07:59:50,664] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 07:59:51,707] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 07:59:51,707] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 07:59:51,707] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 07:59:51,707] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 07:59:51,707] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 07:59:51,707] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 07:59:51,709] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 07:59:51,709] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 07:59:51,736] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2015-10-22 07:59:52,980] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 07:59:52,980] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 07:59:52,980] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 07:59:52,980] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 07:59:52,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 07:59:52,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 07:59:52,982] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 07:59:52,983] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 07:59:54,111] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 07:59:54,111] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 07:59:54,111] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 07:59:54,111] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 07:59:54,111] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 07:59:54,111] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 07:59:54,112] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 07:59:54,112] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 07:59:54,552] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 07:59:54,552] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 07:59:54,552] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 07:59:54,552] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 07:59:54,553] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 07:59:54,555] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 07:59:54,555] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 07:59:54,555] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 08:00:03,592] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-10-22 08:00:10,532] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 08:00:10,532] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 08:00:10,532] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 08:00:10,532] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 08:00:10,532] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 08:00:10,532] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 08:00:10,533] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 08:00:10,533] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 08:00:11,132] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209%20nightly/lib/mozilla/components/koamAddonManager.js:138
[2015-10-22 08:01:17,089] [ERROR] console-logger: While trying to require("scope-packages/packages"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-10-22 08:01:17,092] [ERROR] console-logger: Module `scope-packages/packages` is not found at resource://gre/modules/commonjs/scope-packages/packages.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-10-22 08:01:17,094] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
launch_openAddonsMgr@chrome://komodo/content/launch.js:490:12
oncommand@chrome://komodo/content/komodo.xul:1:1
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2015-10-22 08:01:17,095] [ERROR] console-logger: Error: Module `scope-packages/packages` is not found at resource://gre/modules/commonjs/scope-packages/packages.js (2) in chrome://komodo/content/jetpack.js:154
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 154, in 

[2015-10-22 08:01:26,239] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 08:01:26,239] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 08:01:26,239] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 08:01:26,239] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 08:01:26,240] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 08:01:26,240] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 08:01:26,240] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 08:01:26,240] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-10-22 08:01:55,099] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-10-22 08:01:55,101] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

```

Running provided code from console returns:

```
'ko.windowManager.openOrFocusDialog' is not recognized as an internal or external command,
operable program or batch file.

```

When manually  opening commando:

```
[2015-10-22 08:08:11,335] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1465}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1465}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2471
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-10-22 08:08:11,339] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-10-22 08:08:11,365] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1465
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1465, in 

[2015-10-22 08:08:16,250] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-10-22 08:08:16,250] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-10-22 08:08:16,252] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-10-22 08:08:16,252] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-10-22 08:08:16,252] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-10-22 08:08:16,252] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-10-22 08:08:16,253] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-10-22 08:08:16,253] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
```

**Comment by Naatan** [comment]
The fact that "ko.windowManager.openOrFocusDialog" returns an error for you is very indicative, it implies your profile is corrupt. Would you mind trying a clean profile? From a new tab (File > New > New Tab) hit the "Troubleshooting" button (bottom right) and choose "Restart in Safe-Mode". If that works and you do not mind starting from this state again; restart Komodo, go to the Troubleshooting button again and hit "Reset Everything", a dialog will pop up telling you where to find your old settings should you want to access them.

**Comment by Piniol** [comment]
Ok, so I did "Reset Everything" and... nothing. My old preferences are still set as they were befeore restart.

**Comment by Naatan** [comment]
What about restart in safe-mode?

**Comment by Piniol** [comment]
Same, first i tried safe-mode but that did nothing so i tried "reset everything".

**Comment by cgchoffman** [comment]
> Same, first i tried safe-mode but that did nothing so i tried "reset everything".

This is reproducible with Edit for me.  i'll file a separate bug.

**Comment by Naatan** [comment]
Please try the steps here: http://docs.komodoide.com/Troubleshooting/How-do-I-Start-Komodo-with-Default-Settings

**Comment by Piniol** [comment]
That worked.

**Comment by tonyattwood** [comment]
Hi,

I wanted to thank  you for your support and share  with you some interesting  information,  you may find it here <http://expert.seocostaricaexperts.com/e4wfe>

My best to you, tony.attwood@ntlworld.com
