### ISSUE TITLE
CodeIntel doesn't work: list index out of range

### ISSUE THREAD

**Issue by Defman21** [Komodo/KomodoEdit#768]
I did
```bash
export KOMODO_USERDATADIR=/tmp/ko
/path/to/komodo/bin/komodo
```
Then I created a PHP file and Komodo started generating PHP CodeIntel (built-in variables, functions, etc.). In the terminal, I got those errors:
```
udl: failed to compile ptn <[-\w\d._\x80-\xff][:-\w\d._\x80-\xff]*>: failed at offset 22 (w\d._\x80-\xff]*): invalid range in character class
udl: failed to compile ptn <[-\w\d._\x80-\xff][:-\w\d._\x80-\xff]*>: failed at offset 22 (w\d._\x80-\xff]*): invalid range in character class
```
Then I started getting a lot of `List index out of range errors`:
```
[2015-10-24 18:34:46,959] [ERROR] koCodeIntel: list index out of range
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 163, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 147, in _token_at_pos
    token = self.tokens[idx]
IndexError: list index out of range
```
Version: 
```
Komodo IDE, version 9.3.0, build 88074, platform linux-x86_64.
Built on Thu Oct 22 02:24:33 2015.
```
I reproduced it only with a clean profile and not with my regular profile. So now I'm scared to clean the cache of codeintel in my regular profile :(

**Comment by Defman21** [comment]
Okay, seems like it happens in any files that could have a CodeIntel blobs (PHP, Python, Ruby, etc.).

**Comment by Naatan** [comment]
@Defman21 to clarify, was codeintel not working at all or only in certain scenario's? If not at all, were you able to reproduce this with different projects (languages) or was it only with a specific project/language?

**Comment by Defman21** [comment]
It was not working at all. With clean profile in any file, in any project with any language (PHP, Python, Ruby, CSS, JS, etc.)

**Comment by Naatan** [comment]
I'm unable to reproduce that issue. Are you certain you were using a clean profile and you gave codeintel enough time to generate its database?

**Comment by Defman21** [comment]
I was using a clean profile (`export KOMODO_USERDATADIR=/tmp/ko`) and I gave codeintel all the time but I got the error and I wasn't able to get my CodeIntel works. Re-building it didn't help (removing `codeintel` folder from `/tmp/ko/9.3/`)

**Comment by Naatan** [comment]
Ok, let me know if tomorrows nightly works. I'm not able to reproduce your issue.

**Comment by Defman21** [comment]
Okay :)

**Comment by Defman21** [comment]
Don't poke me :P
Will try with the latest nightly.

**Comment by Defman21** [comment]
Got a <s>super-secret build 88107 only for b@d@ss b3ta-testers</s> new nightly and tried to reproduce the issue.
**pystderr.log**: (removed duplicate error messages)
```log
[2015-11-01 19:31:45,275] [INFO] Startup: Welcome to Komodo IDE 9.3.0 build 88107 (platform linux-x86_64, running on Linux 4.2.0-17-generic version #21-Ubuntu SMP Fri Oct 23 19:56:16 UTC 2015)
[2015-11-01 19:31:45,275] [INFO] Startup: /usr/bin/python built on Mon Oct 26 02:21:11 2015
[2015-11-01 19:31:45,373] [WARNING] koEnviron: skipping environment string: '"'><;|&(:'
[2015-11-01 19:31:45,865] [WARNING] koLess: Clearing local and file cache
[2015-11-01 19:31:46,084] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-01 19:31:46,604] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-11-01 19:31:48,567] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2015-11-01 19:31:48,705] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2015-11-01 19:31:49,029] [WARNING] koSkin: Detected GTK theme via libgtk: Arc-Darker
[2015-11-01 19:31:49,145] [WARNING] koLess: Reloading Skin
[2015-11-01 19:31:49,145] [WARNING] koLess: Clearing local and file cache
[2015-11-01 19:31:49,704] [WARNING] koLess: Reloading Skin
[2015-11-01 19:31:52,358] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-11-01 19:31:52,439] [INFO] komodospellchecker: Spell checker loaded.
[2015-11-01 19:31:52,439] [INFO] komodospellchecker: Using dictionary en-US
[2015-11-01 19:31:52,998] [WARNING] console-logger: Unknown property 'paddin-left'.  Declaration dropped. (1) in less://console/content/less/console.less:168
[2015-11-01 19:31:53,133] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-11-01 19:32:02,969] [WARNING] views: Inconsistent view count in view_closed event
[2015-11-01 19:32:03,054] [WARNING] views: Inconsistent view count in view_opened event
[2015-11-01 19:32:21,136] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-01 19:32:36,340] [WARNING] codeintel.manager: File '/usr/share/php/tcpdf/fonts/cid0cs.php' has size greater than 1MB (1583184)
[2015-11-01 19:32:37,068] [WARNING] codeintel.manager: File '/usr/share/php/tcpdf/fonts/cid0ct.php' has size greater than 1MB (1583187)
[2015-11-01 19:32:41,228] [WARNING] codeintel.manager: File '/usr/share/php/tcpdf/fonts/cid0jp.php' has size greater than 1MB (1583178)
[2015-11-01 19:32:45,914] [WARNING] codeintel.manager: File '/usr/share/php/tcpdf/fonts/cid0kr.php' has size greater than 1MB (1583175)
[2015-11-01 19:32:48,641] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-01 19:32:48,646] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-01 19:32:48,647] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-01 19:32:49,414] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-01 19:32:49,473] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-01 19:33:23,817] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/snippet.svg?preset=hud:0
[2015-11-01 19:33:24,829] [ERROR] codeintel.oop.driver: math domain error
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 163, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 145, in _token_at_pos
    for iter_count in range(int(math.ceil(math.log(upper, 2)) + 1)):
ValueError: math domain error
[2015-11-01 19:33:25,650] [ERROR] koCodeIntel: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 163, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 159, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!

[2015-11-01 19:34:44,344] [ERROR] koCodeIntel: list index out of range
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 856, in do_trg_from_pos
    trg = buf.defn_trg_from_pos(pos, lang=None)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 365, in defn_trg_from_pos
    lang=self.lang_from_pos(pos))
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 163, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 147, in _token_at_pos
    token = self.tokens[idx]
IndexError: list index out of range
```

**Comment by Defman21** [comment]
Seems like my super-secret nightly doesn't contain the commit-fix. Will wait for the release :)

**Comment by mitchell-as** [comment]
Yeah, for whatever reason you don't have the latest updates. This should all be fixed at this point.

**Comment by Defman21** [comment]
Well, CodeIntel works fine with the latest release, but there are still some errors in the log related to codeintel.
```
[2015-11-04 17:37:37,122] [INFO] Startup: Welcome to Komodo IDE 9.3.0 build 88117 (platform linux-x86_64, running on Linux 4.2.0-17-generic version #21-Ubuntu SMP Fri Oct 23 19:56:16 UTC 2015)
[2015-11-04 17:37:37,122] [INFO] Startup: /usr/bin/python built on Thu Oct 29 11:07:23 2015
[2015-11-04 17:37:37,133] [WARNING] koEnviron: skipping environment string: '"'><;|&(:'
[2015-11-04 17:37:37,468] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-04 17:37:37,558] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-11-04 17:37:38,434] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/defman/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2015-11-04 17:37:38,488] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2015-11-04 17:37:38,810] [WARNING] koSkin: Detected GTK theme via libgtk: Iris
[2015-11-04 17:37:41,261] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-11-04 17:37:41,262] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-11-04 17:37:41,263] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1150:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2015-11-04 17:37:41,577] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-11-04 17:37:41,657] [INFO] komodospellchecker: Spell checker loaded.
[2015-11-04 17:37:41,658] [INFO] komodospellchecker: Using dictionary en-US
[2015-11-04 17:37:45,313] [WARNING] views: Inconsistent view count in view_closed event
[2015-11-04 17:37:45,398] [WARNING] views: Inconsistent view count in view_opened event
[2015-11-04 17:38:12,184] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-04 17:38:13,851] [ERROR] codeintel.oop.driver: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 165, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 161, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!
[2015-11-04 17:38:13,854] [ERROR] koCodeIntel: style_at_pos binary search sentinel hit: there is likely a logic problem here!
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 165, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 161, in _token_at_pos
    raise CodeIntelError("style_at_pos binary search sentinel hit: "
CodeIntelError: style_at_pos binary search sentinel hit: there is likely a logic problem here!

[2015-11-04 17:38:15,812] [ERROR] codeintel.oop.driver: math domain error
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 165, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 145, in _token_at_pos
    for iter_count in range(int(math.ceil(math.log(upper, 2)) + 1)):
ValueError: math domain error
[2015-11-04 17:38:15,818] [ERROR] koCodeIntel: math domain error
Traceback (most recent call last):
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 564, in run
    handler.handleRequest(request, self)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 622, in handleRequest
    meth(request, driver)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 907, in do_get_scopes
    scopes = self._do_get_scopes_aux(buf, pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/oop/driver.py", line 912, in _do_get_scopes_aux
    scoperef = buf.scoperef_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 303, in scoperef_from_pos
    lang = self.lang_from_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/udl.py", line 217, in lang_from_pos
    style = self.accessor.style_at_pos(pos)
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 165, in style_at_pos
    return self._token_at_pos(pos)["style"]
  File "/home/defman/Komodo-IDE-9/lib/mozilla/python/komodo/codeintel2/accessor.py", line 145, in _token_at_pos
    for iter_count in range(int(math.ceil(math.log(upper, 2)) + 1)):
ValueError: math domain error

[2015-11-04 17:38:22,909] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-04 17:38:22,910] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-04 17:38:22,911] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-04 17:38:23,475] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-04 17:38:23,522] [WARNING] codeintel.php: _handleTraitResolution:: not in a class|trait definition
[2015-11-04 17:38:36,525] [WARNING] notify: Notification panel has already been removed, callback is likely called twice
[2015-11-04 17:38:39,113] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
```
Started with a clean profile.

**Comment by Naatan** [comment]
Does your codeintel work though?

**Comment by Naatan** [comment]
Of course those errors need to be resolved, but they are secondary to your codeintel doing what you expect it to do.

**Comment by Defman21** [comment]
Yep, codeintel works fine. I get all the auto-completions I want.

**Comment by Naatan** [comment]
Alright, good :)

**Comment by Naatan** [comment]
Since we don't know if it's related please file another bug Defman21, thanks! :)
