### ISSUE TITLE
Accessing remote directories fails

### ISSUE THREAD

**Issue by cbroome** [Komodo/KomodoEdit#777]
At a certain point this morning Komodo Edit 9.2 became unresponsive and wouldn't load the directory list for a remote server. I checked the error log and found this: 

    ERROR:xpcom:Unhandled exception calling 'int8 * isContainer(in int32, out retval boolean);'
    Traceback (most recent call last):
      File "/Applications/Komodo Edit 9.app/Contents/Resources/python/xpcom/server/policy.py", line 300, in _CallMethod_
        return 0, func(*params)
      File "/Applications/Komodo Edit 9.app/Contents/Resources/distribution/bundles/places@activestate.com/components/koPlaceTreeView.py", line 1811, in isContainer
        return self._rows[index].isContainer
    IndexError: list index out of range
    [2015-10-30 10:23:54,354] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIPlaceTreeView.isContainer] (2) in chrome://komodo-places/content/places.js:406
    Traceback (most recent call last):
      File "chrome://komodo-places/content/places.js", line 406, in 

I'm going to try and reset the settings (reinstalling the app did nothing). This is all on mac

**Comment by Naatan** [comment]
Thanks for the report, it is very much appreciated. Unfortunately there isn't much we can do unless we have steps to reproduce the problem. If you figure out how to reproduce this issue please report back and I will reopen the ticket. Thank you!
