### ISSUE TITLE
Komodo Go To Anything is not working in Ubuntu 14.04

### ISSUE THREAD

**Issue by sushant1431** [Komodo/KomodoEdit#781]
![error_komodo_goto_anything](https://cloud.githubusercontent.com/assets/9071785/10874851/c27f12d4-8150-11e5-9cf5-38915b8f8fd9.png)

I am not able to use to Go To Anything feature of Komodo Edit, version 9.2.1, build 15998, platform linux-x86_64.Built on Wed Sep 2 00:18:45 2015.

Below is the error log:
[2015-11-02 10:52:45,410] [INFO] Startup: Welcome to Komodo Edit 9.2.1 build 15998 (platform linux-x86_64, running on Linux 3.13.0-66-generic version #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015)
[2015-11-02 10:52:45,411] [INFO] Startup: /usr/bin/python built on Wed Sep 2 00:18:45 2015
[2015-11-02 10:52:45,429] [WARNING] koXMLPrefs: dePickleCache: Can't open file u'/home/inswadhone/Komodo-Edit-9/lib/support/prefs.xmlc'
[2015-11-02 10:52:45,429] [WARNING] koXMLPrefs: the dePickledCache object was None
[2015-11-02 10:52:45,705] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-02 10:52:45,745] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-11-02 10:52:46,267] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-11-02 10:52:46,293] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/inswadhone/Komodo-Edit-9/lib/mozilla/components/koamAddonManager.js:138
[2015-11-02 10:52:46,549] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-02 10:52:46,549] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-02 10:52:46,550] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-02 10:52:46,550] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-02 10:52:46,550] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-02 10:52:46,550] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-02 10:52:46,550] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-02 10:52:46,551] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-02 10:52:46,782] [WARNING] koSkin: Detected GTK theme via libgtk: Ambiance
[2015-11-02 10:52:47,030] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-11-02 10:52:47,416] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-02 10:52:47,417] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-02 10:52:47,417] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-02 10:52:47,417] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-02 10:52:47,417] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-02 10:52:47,417] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-02 10:52:47,417] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-02 10:52:47,418] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-02 10:52:52,273] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-02 10:52:52,802] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2388
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-11-02 10:52:52,828] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-11-02 10:52:52,846] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1359
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1359, in 

[2015-11-02 10:53:34,457] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2388
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-11-02 10:53:34,474] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-11-02 10:53:34,481] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1359
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1359, in 

[2015-11-02 10:53:36,059] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2388
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-11-02 10:53:36,069] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-11-02 10:53:36,074] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1359
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1359, in 

[2015-11-02 10:53:36,448] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2388
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-11-02 10:53:36,460] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-11-02 10:53:36,467] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1359
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1359, in 

[2015-11-02 10:53:37,693] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2388
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-11-02 10:53:37,708] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-11-02 10:53:37,715] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1359
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1359, in 

[2015-11-02 10:56:30,260] [ERROR] ko-fileicons: Exception in timeout for sdk/icons._createPngFromSvg()
-- EXCEPTION START --
Error: path does not exist: /home/inswadhone/.komodoedit/9.2/XRE/icons/fileicons/JSONJSO16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
[2015-11-02 10:56:32,069] [ERROR] ko-fileicons: Exception in timeout for sdk/icons._createPngFromSvg()
-- EXCEPTION START --
Error: path does not exist: /home/inswadhone/.komodoedit/9.2/XRE/icons/fileicons/MarkdownMD16.png.forcedAttrs.svg
+ stack
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:1
    ensureExists@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:54:11
    ensureFile@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:47:3
    remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:174:3
    _createPngFromSvg/img.onload/<@chrome://komodo/content/sdk/icons.js:586:25
    notify@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js:40:9
-- EXCEPTION END --
[2015-11-02 10:56:39,448] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-02 10:56:39,448] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-02 10:56:39,449] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-02 10:56:39,449] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-02 10:56:39,449] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-02 10:56:39,449] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-02 10:56:39,449] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-02 10:56:39,450] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-02 10:56:42,577] [ERROR] commands: An error occurred executing the cmd_showCommando command
-- EXCEPTION START --
[Exception... "[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]'[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js" line: 1359}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263"  data: yes]
+ QueryInterface (function) 3 lines
+ message (string) '[JavaScript Error: "c.getScope(...) is undefined" {file: "chrome://commando/content/sdk/commando.js"'...276 chars
+ result (number) 2153185313
+ name (string) 'NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS'
+ filename (string) 'chrome://komodo/content/library/commands.js'
+ lineNumber (number) 263
+ columnNumber (number) 0
+ location (object) JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 263
| + QueryInterface (function) 3 lines
| + language (number) 2
| + languageName (string) 'JavaScript'
| + filename (string) 'chrome://komodo/content/library/commands.js'
| + name (string) 'command_doCommand'
| + lineNumber (number) 263
| + columnNumber (number) 0
| + sourceLine (string) ''
| + caller (object) JS frame :: chrome://komodo/content/keybindings/keybindings.js :: this.Manager.prototype.evalCommand :: line 2388
| + formattedStack (string) 'command_doCommand@chrome://komodo/content/library/commands.js:263:0
this.Manager.prototype.evalComma'...330 chars
| + inner (object) null
| + data (object) [xpconnect wrapped nsISupports]
| + QueryInterface (function) 3 lines
| + initialize (function) 3 lines
-- EXCEPTION END --
[2015-11-02 10:56:42,589] [ERROR] keybindings: 
-- EXCEPTION START --
2147500037
+ 0 (number) 2147500037
-- EXCEPTION END --
[2015-11-02 10:56:42,594] [ERROR] console-logger: TypeError: c.getScope(...) is undefined (2) in chrome://commando/content/sdk/commando.js:1359
Traceback (most recent call last):
  File "chrome://commando/content/sdk/commando.js", line 1359, in 

[2015-11-02 11:01:30,320] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-02 11:01:30,321] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-02 11:01:30,322] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-02 11:01:30,322] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-02 11:01:30,322] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-02 11:01:30,322] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-02 11:01:30,323] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-02 11:01:30,324] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-02 11:02:08,079] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-02 11:03:00,860] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_change'
[2015-11-02 11:03:00,860] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'spelling_error'
[2015-11-02 11:03:00,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_local_change'
[2015-11-02 11:03:00,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_4'
[2015-11-02 11:03:00,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_5'
[2015-11-02 11:03:00,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_2'
[2015-11-02 11:03:00,861] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_3'
[2015-11-02 11:03:00,862] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'collab_remote_cursor_1'
[2015-11-02 11:03:18,373] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by Defman21** [comment]
Could you try [the latest nightly](http://downloads.activestate.com/Komodo/nightly/komodoedit/latest/Komodo-Edit-9.3.0-16352-linux-x86_64.tar.gz)? IIRC this was fixed.

**Comment by Naatan** [comment]
Did you disable any scopes under Tools > Addons?

**Comment by sushant1431** [comment]
@Naatan , no i haven't disabled scopes, it seems it was disabled by default, but after enabling them, it's working like a charm :). Thanks.

**Comment by sushant1431** [comment]
@Defman21 , Though after enabling scopes, "Go to anything" is working, though still i'll give a try to latest build, may be in this build scopes will be enable by default.

**Comment by Naatan** [comment]
Definitely should not be disabled by default, I can't really think of a way that could have happened. Anyway, glad you got it sorted :)
