### ISSUE TITLE
Komodo IDE 9.3 - 'open documentaton for current language' doesnt work

### ISSUE THREAD

**Issue by earx** [Komodo/KomodoEdit#798]
1. Click button 'open documentaton for current language' on toolbar
2. There is error is shown in Notifications tab:

[Exception... "[JavaScript Error: "commando.isOpen is not a function" {file: "chrome://scope-docs/content/sdk/docs.js" line: 75}]'[JavaScript Error: "commando.isOpen is not a function" {file: "chrome://scope-docs/content/sdk/docs.js" line: 75}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 230"  data: yes]
                                         Wed Nov 04 2015 22:44:42 GMT+0300 (MSK)

Languages: Javascript (node.js) and PHP
build Komodo IDE, version 9.3.0, build 88117, platform linux-x86_64. Built on Thu Oct 
OS: Ubuntu 14.04 x64

**Comment by Naatan** [comment]
That's odd, does Commando work properly for you?

**Comment by earx** [comment]
How do I check it?

**Comment by Defman21** [comment]
Open Commando via Ctrl+Shift+O and change the scopes (top left of the Commando window)

**Comment by earx** [comment]
no, pressing Ctrl+Shift+O have no any effect

**Comment by earx** [comment]
Log file:

[2015-11-04 22:51:37,438] [INFO] Startup: Welcome to Komodo IDE 9.3.0 build 88117 (platform linux-x86_64, running on Linux 3.13.0-66-generic version #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015)
[2015-11-04 22:51:37,438] [INFO] Startup: /usr/bin/python built on Thu Oct 29 11:07:23 2015
[2015-11-04 22:51:37,666] [ERROR] koInitService: Unable to start 'koManifestLoader' service: '@activestate.com/koManifestLoader;1'
Traceback (most recent call last):
  File "/home/evg/Komodo-IDE-9/lib/mozilla/components/koInitService.py", line 331, in loadStartupCategories
    getService(components.interfaces.nsIObserver)
  File "/home/evg/Komodo-IDE-9/lib/mozilla/python/xpcom/components.py", line 195, in getService
    return serviceManager.getServiceByContractID(self.contractid, _get_good_iid(iid))
  File "<XPCOMObject method 'getServiceByContractID'>", line 3, in getServiceByContractID
Exception: 2152857618 (NS_ERROR_FILE_NOT_FOUND)
[2015-11-04 22:51:37,778] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-04 22:51:37,780] [WARNING] console-logger: Ignoring obsolete chrome registration modifier 'xpcnativewrappers=yes'. (1) in jar:file:///home/evg/.komodoide/9.3/XRE/extensions/emmet@chikuyonok.ru.xpi!/chrome.manifest:1
[2015-11-04 22:51:37,782] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChromeRegistry.convertChromeURL] (2) in file:///home/evg/Komodo-IDE-9/lib/mozilla/components/koResolve.js:65
Traceback (most recent call last):
  File "file:///home/evg/Komodo-IDE-9/lib/mozilla/components/koResolve.js", line 65, in 

[2015-11-04 22:51:37,786] [ERROR] console-logger: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIChromeRegistry.convertChromeURL] (2) in file:///home/evg/Komodo-IDE-9/lib/mozilla/components/koResolve.js:65
Traceback (most recent call last):
  File "file:///home/evg/Komodo-IDE-9/lib/mozilla/components/koResolve.js", line 65, in 

[2015-11-04 22:51:37,849] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-11-04 22:51:38,192] [ERROR] console-logger: TypeError: redeclaration of const CC (2) in chrome://xtk/content/xtk.js:22
Traceback (most recent call last):
  File "chrome://xtk/content/xtk.js", line 22, in 

[2015-11-04 22:51:38,523] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-11-04 22:51:40,166] [WARNING] console-logger: Error in parsing value for 'fill'.  Declaration dropped. (1) in file:///home/evg/.komodoide/9.3/XRE/icons/chrome/icomoon/skin/7575bc691457084936805bf832c55834-briefcase3.svg.png.forcedAttrs.svg:0
[2015-11-04 22:51:41,551] [WARNING] console-logger: Error in parsing value for 'left'.  Declaration dropped. (1) in chrome://console/content/views/console.html:0
[2015-11-04 22:51:41,653] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///home/evg/Komodo-IDE-9/lib/mozilla/components/koamAddonManager.js:138
[2015-11-04 22:51:42,078] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-11-04 22:51:42,082] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-11-04 22:51:42,085] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1150:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2015-11-04 22:51:42,174] [INFO] komodospellchecker: Spell checker loaded.
[2015-11-04 22:51:42,174] [INFO] komodospellchecker: Using dictionary en-US
[2015-11-04 22:51:42,189] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-11-04 22:51:42,197] [ERROR] commando-scope-docs-bootstrap: Commando: Exception while registering scope 'Docs'
-- EXCEPTION START --
TypeError: commando.registerScope is not a function
+ stack
    loadIntoWindow@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-docs@activestate.com/bootstrap.js:13:9
    onLoad@resource://gre/modules/addons/XPIProvider.jsm -> file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-docs@activestate.com/bootstrap.js:68:13
    xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:157:5
    onloadDelay/</<@chrome://komodo/content/komodo.js:422:13
-- EXCEPTION END --
[2015-11-04 22:51:42,278] [ERROR] console-logger: While trying to require("commando/commando"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-11-04 22:51:42,281] [ERROR] console-logger: Module `commando/commando` is not found at resource://gre/modules/commonjs/commando/commando.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-11-04 22:51:42,283] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
loadIntoWindow@jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-combined@activestate.com.xpi!/bootstrap.js:9:20
onLoad@jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-combined@activestate.com.xpi!/bootstrap.js:51:13
xtk.domutils.fireEvent@chrome://xtk/content/domutils.js:157:5
onloadDelay/</<@chrome://komodo/content/komodo.js:422:13
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2015-11-04 22:51:42,286] [ERROR] console-logger: Error: Module `commando/commando` is not found at resource://gre/modules/commonjs/commando/commando.js (2) in chrome://komodo/content/jetpack.js:154
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 154, in 

[2015-11-04 22:51:42,289] [ERROR] console-logger: Commando: Exception while registering scope 'Commands' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-commands@activestate.com.xpi!/bootstrap.js:17
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-commands@activestate.com.xpi!/bootstrap.js", line 17, in 

[2015-11-04 22:51:42,292] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-commands@activestate.com.xpi!/bootstrap.js:10
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-commands@activestate.com.xpi!/bootstrap.js", line 10, in 

[2015-11-04 22:51:42,294] [ERROR] console-logger: Commando: Exception while registering scope 'Bookmarks' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-bookmarks@activestate.com.xpi!/bootstrap.js:17
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-bookmarks@activestate.com.xpi!/bootstrap.js", line 17, in 

[2015-11-04 22:51:42,297] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-bookmarks@activestate.com.xpi!/bootstrap.js:10
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-bookmarks@activestate.com.xpi!/bootstrap.js", line 10, in 

[2015-11-04 22:51:42,300] [ERROR] console-logger: Commando: Exception while registering scope 'Shell' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-shell@activestate.com.xpi!/bootstrap.js:17
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-shell@activestate.com.xpi!/bootstrap.js", line 17, in 

[2015-11-04 22:51:42,303] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-shell@activestate.com.xpi!/bootstrap.js:10
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-shell@activestate.com.xpi!/bootstrap.js", line 10, in 

[2015-11-04 22:51:42,312] [ERROR] console-logger: Commando: Exception while registering scope 'Sections' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-sections@activestate.com.xpi!/bootstrap.js:17
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-sections@activestate.com.xpi!/bootstrap.js", line 17, in 

[2015-11-04 22:51:42,315] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-sections@activestate.com.xpi!/bootstrap.js:10
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-sections@activestate.com.xpi!/bootstrap.js", line 10, in 

[2015-11-04 22:51:42,318] [ERROR] console-logger: Commando: Exception while registering scope 'openfiles' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-openfiles@activestate.com.xpi!/bootstrap.js:19
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-openfiles@activestate.com.xpi!/bootstrap.js", line 19, in 

[2015-11-04 22:51:42,321] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-openfiles@activestate.com.xpi!/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-openfiles@activestate.com.xpi!/bootstrap.js", line 12, in 

[2015-11-04 22:51:42,324] [ERROR] console-logger: Commando: Exception while registering scope 'Packages' (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-packages@activestate.com.xpi!/bootstrap.js:19
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-packages@activestate.com.xpi!/bootstrap.js", line 19, in 

[2015-11-04 22:51:42,326] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-packages@activestate.com.xpi!/bootstrap.js:10
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-packages@activestate.com.xpi!/bootstrap.js", line 10, in 

[2015-11-04 22:51:42,329] [ERROR] console-logger: Commando: Exception while registering scope 'Files' (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-files@activestate.com/bootstrap.js:20
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-files@activestate.com/bootstrap.js", line 20, in 

[2015-11-04 22:51:42,332] [ERROR] console-logger: commando.registerScope is not a function (0) in resource://gre/modules/addons/XPIProvider.jsm -> file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-files@activestate.com/bootstrap.js:12
Traceback (most recent call last):
  File "resource://gre/modules/addons/XPIProvider.jsm -> file:///home/evg/Komodo-IDE-9/lib/mozilla/extensions/scope-files@activestate.com/bootstrap.js", line 12, in 

[2015-11-04 22:52:03,773] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-04 22:52:03,774] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-04 22:52:36,031] [WARNING] console-logger: Error in parsing value for 'fill'.  Declaration dropped. (1) in file:///home/evg/.komodoide/9.3/XRE/icons/chrome/icomoon/skin/a727d288722d0e133e38f96b53e7e0b8-file6.svg.png.forcedAttrs.svg:0
[2015-11-04 22:53:38,601] [ERROR] console-logger: TypeError: commando.show is not a function (2) in chrome://scope-packages/content/packages.js:60
Traceback (most recent call last):
  File "chrome://scope-packages/content/packages.js", line 60, in 

[2015-11-04 22:54:52,026] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-04 22:54:52,027] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-04 22:54:54,630] [ERROR] keybindings: FAILURE to find command cmd_scope-files
Traceback from ERROR in 'keybindings' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:337:27
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2507:13
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2704:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2588:5

[2015-11-04 22:54:54,643] [ERROR] keybindings: 
-- EXCEPTION START --
TypeError: command is null
+ stack
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2512:1
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2704:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2588:5
-- EXCEPTION END --
[2015-11-04 22:55:01,310] [WARNING] views: Inconsistent view count in view_closed event
[2015-11-04 22:55:01,539] [WARNING] views: Inconsistent view count in view_opened event
[2015-11-04 22:55:04,731] [ERROR] keybindings: FAILURE to find command cmd_scope-files
Traceback from ERROR in 'keybindings' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:337:27
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2507:13
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2704:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2588:5

[2015-11-04 22:55:04,752] [ERROR] keybindings: 
-- EXCEPTION START --
TypeError: command is null
+ stack
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2512:1
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2704:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2588:5
-- EXCEPTION END --
[2015-11-04 22:56:21,300] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-04 22:56:21,301] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by Defman21** [comment]
Commando is disabled for you as I can see.

**Comment by earx** [comment]
How Do I enable it?

**Comment by Defman21** [comment]
I have no idea how to do it because Add-ons window is hidden in favor of Commando Packages. @Naatan?

**Comment by earx** [comment]
Also, Tools->Addons menu doesnt work (no any action after selecting it). Is it related to this?

**Comment by Defman21** [comment]
Yes, Tools - Addons should open Commando with Packages scope. Try to start Komodo with a clean profile:
```bash
export KOMODO_USERDATADIR=/tmp/komodo
~/Komodo-IDE-9/bin/komodo
```

**Comment by earx** [comment]
min

**Comment by earx** [comment]
yes, it helps

**Comment by earx** [comment]
also, there errors in shell:

LoadPlugin: failed to initialize shared library libXt.so [libXt.so: no such file]
LoadPlugin: failed to initialize shared library libXext.so [libXext.so: no such file]
LoadPlugin: failed to initialize shared library /home/evg/.mozilla/plugins/nppdf.so [/home/evg/.mozilla/plugins/nppdf.so: incorrect class ELF: ELFCLASS32]
LoadPlugin: failed to initialize shared library /usr/lib/mozilla/plugins/nppdf.so [/usr/lib/mozilla/plugins/nppdf.so: incorrect class ELF: ELFCLASS32]

**Comment by Naatan** [comment]
@earx navigate to the "Console pane" (bottom panel) and enter + execute this:

`ko.windowManager.openOrFocusDialog("chrome://mozapps/content/extensions/extensions.xul", "Addons:Manager")`

In the window that pops up uninstall all disabled addons, and enable the ones that cannot be disabled. Then restart Komodo and try again.

**Comment by Naatan** [comment]
Btw you didn't answer my question: did you upgrade from a previous version?

**Comment by earx** [comment]
@Naatan: sorry, missed it.
Yes, I was Ide 9.2

**Comment by earx** [comment]
>navigate to the "Console pane"..
yes, it helps, thank you!

**Comment by earx** [comment]
sorry, another bug here:
when I try to open documentation for second time, i've got error:

[Exception... "[JavaScript Error: "doc is undefined" {file: "chrome://scope-docs/content/sdk/docs.js" line: 78}]'[JavaScript Error: "doc is undefined" {file: "chrome://scope-docs/content/sdk/docs.js" line: 78}]' when calling method: [nsIController::doCommand]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://komodo/content/library/commands.js :: command_doCommand :: line 230"  data: yes]
                                         Wed Nov 04 2015 23:25:06 GMT+0300 (MSK)

**Comment by Naatan** [comment]
Please restart Komodo, reproduce the problem and then share your error log in a new bug report (we don't want to be tracking multiple bugs in one report).

Thanks! :)
