### ISSUE TITLE
Debugger Initialization Error | 9.3 upgraded from 9.2.1

### ISSUE THREAD

**Issue by shawnlaffan** [Komodo/KomodoEdit#867]
I'm getting the "Debugger Initialization Error" when starting a session using Debug -> Run Without Debugging (via control-F7 and menu).  After the first failure the menu option is disabled.  

I don't get the error when calling Debug -> Go/Continue.

This is on Komodo IDE 9.3, upgraded from 9.2.1.

OS is both Windows 7 and Windows 10.  I haven't tested other OSs.

Komodo is set to find a free port and is listening for connections.  (Based on http://code.activestate.com/lists/komodo-beta/4422/ )

The error log is below for a session using a debug session, followed by a non-debug.  The TypeError looks suspicious.  

Regards,
Shawn.

[2015-11-14 17:47:13,789] [INFO] Startup: Welcome to Komodo IDE 9.3.0 build 88117 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2015-11-14 17:47:13,789] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\komodo.exe built on Thu Oct 29 09:49:58 2015
[2015-11-14 17:47:14,523] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-11-14 17:47:14,585] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:15:1

[2015-11-14 17:47:15,147] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-11-14 17:47:15,302] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2015-11-14 17:47:15,739] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20IDE%209/lib/mozilla/components/koamAddonManager.js:138
[2015-11-14 17:47:24,288] [ERROR] console-logger: While trying to require("spellcheck/spellcheck"): (0) in chrome://komodo/content/jetpack.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 156, in 

[2015-11-14 17:47:24,303] [ERROR] console-logger: Module `spellcheck/spellcheck` is not found at resource://gre/modules/commonjs/spellcheck/spellcheck.js (0) in chrome://komodo/content/jetpack.js:157
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 157, in 

[2015-11-14 17:47:24,303] [ERROR] console-logger: require@chrome://komodo/content/jetpack.js:154:20
doUpdateUI/this.spellcheck_timeout<@viewbufferbase:1150:25
 (0) in chrome://komodo/content/jetpack.js:160
Traceback (most recent call last):
  File "chrome://komodo/content/jetpack.js", line 160, in 

[2015-11-14 17:47:25,582] [INFO] komodospellchecker: Spell checker loaded.
[2015-11-14 17:47:25,582] [INFO] komodospellchecker: Using dictionary en-US
[2015-11-14 17:47:25,677] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2015-11-14 17:47:31,760] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-14 17:47:31,760] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2015-11-14 17:47:34,973] [ERROR] console-logger: The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. (0) in file:///c:/users/shawn/appdata/local/temp/tmphq8gl4.html:0
Traceback (most recent call last):
  File "file:///c:/users/shawn/appdata/local/temp/tmphq8gl4.html", line 0, in 

ERROR:xpcom:Unhandled exception calling 'int8 * invoke(in int32);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koInvokeInterpreters.py", line 277, in invoke
    return self._launchForRun()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koInvokeInterpreters.py", line 1297, in _launchForRun
    exe = self.getExecutable()
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\components\koInvokeInterpreters.py", line 1312, in getExecutable
    cwd = os.path.dirname(script)
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\..\python\lib\ntpath.py", line 205, in dirname
    return split(p)[0]
  File "C:\Program Files (x86)\ActiveState Komodo IDE 9\lib\mozilla\..\python\lib\ntpath.py", line 181, in split
    return d + head, tail
TypeError: cannot concatenate 'str' and 'list' objects
[2015-11-14 17:47:38,578] [ERROR] ko.dbg.invocation: There was an unexpected error starting the invocation:[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIInvocation.invoke]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/debugger/debugger.js :: this.invocation.doExecute :: line 2405"  data: no]
Traceback from ERROR in 'ko.dbg.invocation' logger:
    Logger.prototype.error@chrome://komodo/content/sdk/logging.js:337:27
    this.invocation.doExecute@chrome://komodo/content/debugger/debugger.js:2414:13
    ko_dbg_invocation_doStart/onInvocationReady@chrome://komodo/content/debugger/debugger.js:2513:23
    ko_dbg_invocation_getInvocation/onSessionReady@chrome://komodo/content/debugger/debugger.js:2253:13
    ko_dbg_invocation_getInvocation@chrome://komodo/content/debugger/debugger.js:2257:13
    ko_dbg_invocation_doStart/onSessionReady@chrome://komodo/content/debugger/debugger.js:2457:1
    DBG_Manager_newSession/onTabMgrReady@chrome://komodo/content/debugger/debugger.js:395:13
    outputTabManager_getTabMgr@chrome://komodo/content/debugger/debugSessionTab.js:1064:21
    DBG_Manager_newSession@chrome://komodo/content/debugger/debugger.js:401:13
    ko_dbg_invocation_doStart@chrome://komodo/content/debugger/debugger.js:2562:17
    this.invocation.runScript@chrome://komodo/content/debugger/debugger.js:2623:1
    doRun@chrome://komodo/content/debugger/debuggerController.js:226:9
    DebuggerItemsController.prototype.do_cmd_dbgRun@chrome://komodo/content/debugger/debuggerController.js:232:9
    xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:61:9
    command_doCommand@chrome://komodo/content/library/commands.js:230:1
    debugger_doCommand@chrome://komodo/content/debugger/debuggerController.js:31:16
    @chrome://komodo/content/keybindings/keybindings.js line 2533 > eval:1:1
    this.Manager.prototype.evalCommand@chrome://komodo/content/keybindings/keybindings.js:2533:23
    this.Manager.prototype.keypressHandler@chrome://komodo/content/keybindings/keybindings.js:2704:17
    gKeyHandler@chrome://komodo/content/keybindings/keybindings.js:2588:5

[2015-11-14 17:47:52,586] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2015-11-14 17:47:52,586] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by Defman21** [comment]
Duplicate of #835

**Comment by shawnlaffan** [comment]
Thanks @Defman21 .

I should have had another look before logging the bug.
