### ISSUE TITLE
Komodo edit 9 - Problem opening a remote file

### ISSUE THREAD

**Issue by giustonello** [Komodo/KomodoEdit#91]
I can't open a remote file after i restarted komodo 9 (the file was open when i restarted the program and i restarted komodo to try a new skin).

I try to save another file with the same name of the file i can't open and this is the error message.

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1473"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1473"  data: no]

Traceback:
saveAsURI@vieweditor:1473:30
saveAsRemote@vieweditor:1381:19
viewManager.prototype.do_cmd_saveAs_remote@chrome://komodo/content/views.js:1914:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:8
command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:12

Komodo Edit, version 9.0.0, build 15707.
Built on Thu Mar 19 07:01:30 2015.

Thank you for your attention, Giuseppe Tonello

**Comment by Naatan** [comment]
Could you please include the error log for when you try to open the file?

**Comment by giustonello** [comment]
This is the pystderr.log
thank you

[2015-03-31 09:45:01,760] [INFO] Startup: Welcome to Komodo Edit 9.0.0 build 15707 (platform win32-x86, running on Windows 7 version 6.1.7601)
[2015-03-31 09:45:01,762] [INFO] Startup: C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\komodo.exe built on Thu Mar 19 07:01:30 2015
[2015-03-31 09:45:02,311] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in resource://gre/modules/Preferences.jsm:381
[2015-03-31 09:45:02,312] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'component' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:1
[2015-03-31 09:45:02,312] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'contract' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:2
[2015-03-31 09:45:02,313] [WARNING] console-logger: Bootstrapped manifest not allowed to use 'interfaces' directive. (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/extensions/scope-files@activestate.com/components/component.manifest:3
[2015-03-31 09:45:02,374] [WARNING] root: ko.logging has been converted to a CommonJS module; use require("ko/logging") instead (since Komodo 9.0.0a1).
    @chrome://komodo/content/komodo.js:48:1

[2015-03-31 09:45:03,039] [WARNING] console-logger: Unknown property 'border-radius-top-left'.  Declaration dropped. (1) in less://commando/skin/commando.less:19
[2015-03-31 09:45:03,039] [WARNING] console-logger: Unknown property 'border-radius-top-right'.  Declaration dropped. (1) in less://commando/skin/commando.less:20
[2015-03-31 09:45:03,461] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2015-03-31 09:45:04,796] [WARNING] root: ko.findresults was already loaded, re-creating it.

[2015-03-31 09:45:04,844] [DEBUG] places_js: waiting for document complete
[2015-03-31 09:45:06,098] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/components/koamAddonManager.js:138
[2015-03-31 09:45:14,329] [ERROR] console-logger: ReferenceError: nsITreeView is not defined (2) in chrome://komodo/content/dialogs/filebrowser/filebrowseview.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowseview.js", line 156, in 

[2015-03-31 09:45:17,825] [WARNING] koSFTPConnection: do_authenticateWithPassword:: SSHException: Authentication failed.
[2015-03-31 09:45:17,825] [WARNING] koSFTPConnection: SSH error: Invalid username/password
[2015-03-31 09:45:24,345] [ERROR] console-logger: ReferenceError: nsITreeView is not defined (2) in chrome://komodo/content/dialogs/filebrowser/filebrowseview.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowseview.js", line 156, in 

[2015-03-31 09:45:24,346] [ERROR] console-logger: ReferenceError: nsITreeView is not defined (2) in chrome://komodo/content/dialogs/filebrowser/filebrowseview.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowseview.js", line 156, in 

[2015-03-31 09:45:32,088] [ERROR] console-logger: ReferenceError: nsITreeView is not defined (2) in chrome://komodo/content/dialogs/filebrowser/filebrowseview.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowseview.js", line 156, in 

[2015-03-31 09:45:32,091] [ERROR] console-logger: ReferenceError: nsITreeView is not defined (2) in chrome://komodo/content/dialogs/filebrowser/filebrowseview.js:156
Traceback (most recent call last):
  File "chrome://komodo/content/dialogs/filebrowser/filebrowseview.js", line 156, in 

ERROR:xpcom:Unhandled exception calling 'int8 * initWithFile(in nsISomething, in boolean);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\components\koDocument.py", line 217, in initWithFile
    self._setupPrefs()
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\components\koDocument.py", line 320, in _setupPrefs
    encoding_name = self._getEncodingNameForNewFile(language)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\components\koDocument.py", line 281, in _getEncodingNameForNewFile
    return self.prefs.getString('encodingDefault')
  File "<XPCOMObject method 'getString'>", line 3, in getString
Exception: 2147549183 (NS_ERROR_UNEXPECTED)
ERROR:xpcom:Unhandled exception calling 'int8 * createDocumentFromURI(in wstring, out retval nsISomething);'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\python\xpcom\server\policy.py", line 300, in _CallMethod_
    return 0, func(*params)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\components\koDocumentService.py", line 245, in createDocumentFromURI
    return self.createNewDocumentFromURI(uri)
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\components\koDocumentService.py", line 230, in createNewDocumentFromURI
    doc.initWithFile(file,0)
  File "<XPCOMObject method 'initWithFile'>", line 3, in initWithFile
Exception: 2147500037 (NS_ERROR_FAILURE)
[2015-03-31 09:45:37,289] [ERROR] console-logger: NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI] (2) in chrome://komodo/content/views.js:570
Traceback (most recent call last):
  File "chrome://komodo/content/views.js", line 570, in 

[2015-03-31 09:45:43,246] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2015-03-31 09:45:43,246] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0

**Comment by Naatan** [comment]
Thanks, can you please explain how you were opening the file? And what type of remote connection you were using (FTP, SCP, FTPS, ..)

**Comment by giustonello** [comment]
![remoteserver](https://cloud.githubusercontent.com/assets/11717417/6936532/8b4d29e6-d853-11e4-885d-f5752f3fff14.png)

**Comment by Naatan** [comment]
You're saying changing skin is an integral part to reproducing the bug?

**Comment by giustonello** [comment]
Yes i think because it's the only thing I did overtime.

**Comment by giustonello** [comment]
![image2993](https://cloud.githubusercontent.com/assets/11717417/8103055/b52e6f18-1025-11e5-8c97-ffe2648c6066.png)
I try to open an other file and using the "save as" option i put the name of the file i can't open. This is the error that komodo give me.

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1473"  data: no]

Exception: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIDocumentService.createDocumentFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: vieweditor :: saveAsURI :: line 1473"  data: no]

Traceback:
saveAsURI@vieweditor:1473:30
saveAsRemote@vieweditor:1381:19
viewManager.prototype.do_cmd_saveAs_remote@chrome://komodo/content/views.js:1914:4
xtk.Controller.prototype.doCommand@chrome://xtk/content/controller.js:91:8
command_doCommand@chrome://komodo/content/library/commands.js:263:0
command_doCommandAsync/<@chrome://komodo/content/library/commands.js:220:12


Komodo Edit, version 9.1.0, build 15798.
Built on Sat May 30 06:10:24 2015.

I hope this information can help you.
Thanks Giuseppe.
