### ISSUE TITLE
Komodo doesn't allow enter-key input

### ISSUE THREAD

**Issue by krizoek** [Komodo/KomodoEdit#982]
often times inside the komodo editor, i become unable to hit enter; then it works again after restarting komodo

im running 9.3.2 build 16460, platform win32-x86

**Comment by mitchell-as** [comment]
Hi, are there any steps we can follow that would enable us to reproduce your bug? Or is there something you're doing in particular that triggers this inability to press enter? We have very little to go on from your report.

**Comment by krizoek** [comment]
I wish i could say more about it, but it happens when i leave komodo open for some time and go back to it. but i will try to watch more carefully what happens

**Comment by cgchoffman** [comment]
Please look at your error logs (*help > Troubleshooting > view log file* ) next time this happens.

**Comment by krizoek** [comment]
[2016-01-03 22:25:37,391] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/snippet.svg:0
[2016-01-03 22:25:37,696] [WARNING] console-logger: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create (1) in file:///C:/Program%20Files%20(x86)/ActiveState%20Komodo%20Edit%209/lib/mozilla/components/koamAddonManager.js:138
[2016-01-03 22:25:38,664] [INFO] elastic_tabstops: Elastic tabstops loaded.
[2016-01-03 22:25:38,752] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.append] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:98
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 98, in 

[2016-01-03 22:26:01,582] [WARNING] console-logger: Key event not available on some keyboard layouts: key="g" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-01-03 22:26:01,582] [WARNING] console-logger: Key event not available on some keyboard layouts: key="z" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-01-03 22:26:01,584] [WARNING] console-logger: Key event not available on some keyboard layouts: key="c" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-01-03 22:26:01,584] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/komodo.xul:0
[2016-01-03 22:26:01,584] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/komodo.xul:0
[2016-01-03 22:29:30,979] [ERROR] console-logger: bad script XDR magic number (0) in :0
Traceback (most recent call last):
  File "", line 0, in 

[2016-01-03 22:30:45,592] [WARNING] keybindings: [Ctrl+0] was used for 'cmd_goToQuickBookmark_0', overriding to use 'cmd_fontZoomReset'
[2016-01-03 22:30:45,635] [ERROR] KoObserverService: notifyObservers:: topic: 'tabularasa_colors', data: u'global'
Traceback (most recent call last):
  File "C:\Program Files (x86)\ActiveState Komodo Edit 9\lib\mozilla\components\koObserverService.py", line 221, in _notifyObservers
    observer.observe(aSubject, aTopic, someData)
  File "<XPCOMObject method 'observe'>", line 3, in observe
Exception: 2152857601 (NS_ERROR_FILE_UNRECOGNIZED_PATH)
[2016-01-03 22:30:45,663] [ERROR] console-logger: NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.append] (2) in resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:98
Traceback (most recent call last):
  File "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js", line 98, in

maybe it's one of these ones

**Comment by mitchell-as** [comment]
Are you using Komodo's default skin? I see something in your log that may be related to an experimental "tabularasa" skin, which may cause the issue you're experiencing.

**Comment by krizoek** [comment]
i did some experiments with it, but it was set to default now; i'm not sure if i changed it before or after. but i will tell if it happens with the default one. ty :)

**Comment by krizoek** [comment]
It happened again with the default theme, all i did was a backslash to remove one tab-char.

[2016-01-10 19:15:54,177] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'multiple_caret_area'
[2016-01-10 19:15:54,194] [WARNING] koLanguageServiceBase.indenting: Found non-positive guess of 0 (min 1)
[2016-01-10 22:25:28,688] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:28,842] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:29,621] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:29,813] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:31,424] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:31,585] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:32,121] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:32,237] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:38,357] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:38,558] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 

[2016-01-10 22:25:45,561] [WARNING] console-logger: Error in parsing value for 'opacity'.  Declaration dropped. (1) in chrome://komodo/skin/images/toolbox/snippet.svg:0
[2016-01-10 22:25:53,878] [WARNING] koScintillaSchemeService: applyScheme:: no indicator for name 'multiple_caret_area'
[2016-01-10 22:26:24,312] [WARNING] console-logger: Key event not available on some keyboard layouts: key="z" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-01-10 22:26:24,315] [WARNING] console-logger: Key event not available on some keyboard layouts: key="c" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-01-10 22:26:24,315] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-01-10 22:26:24,316] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0

**Comment by mitchell-as** [comment]
@Naatan Any ideas? I cannot tell what the problem might be from this log file.

**Comment by Naatan** [comment]
Do you have any addons or userscripts/macros installed ?

**Comment by krizoek** [comment]
Yes, i have installed tabula rasa - UI skin addon. but its not activated.

i have lots of extra snippets for php, and a few userscripts that i made myself, the commentstorage, TagIndexGenerator and TagNavigate.

Apart from my own, i have one called "movedown" and "moveup". they are for to move lines up or down. i found them somewhere for komodo. the rest is the normal ones that comes with the default komodo installation.

Would you like for me to send a copy of all the snippets, or put online?

https://github.com/krizoek/komodo-comment-storage/blob/master/commentstorage.js

**Comment by krizoek** [comment]
it comes to mind i attempted installing userscripts through the new "go to anything", but it always fail during install. the "auto toggle panes"

**Comment by Naatan** [comment]
Try Help > Troubleshooting > Restart Without Tools and Restart Without Addons

**Comment by rajendrakhabiyagate6** [comment]
[2016-05-13 14:39:17,150] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in 
I face similar problem and below is the last lines of my log file...

[2016-05-13 14:40:35,072] [WARNING] console-logger: Key event not available on GTK2: key="u" modifiers="control,shift" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-05-13 14:40:35,073] [WARNING] console-logger: Key event not available on some keyboard layouts: key="v" modifiers="control,alt" (1) in chrome://komodo/content/tail/tail.xul:0
[2016-05-13 14:40:43,388] [ERROR] console-logger: TypeError: target.dispatchEvent is not a function (2) in chrome://xtk/content/domutils.js:187
Traceback (most recent call last):
  File "chrome://xtk/content/domutils.js", line 187, in

**Comment by Naatan** [comment]
@rajendrakhabiyagate6 please provide context
